OGRE: Ogre::Bullet::DebugDrawer Class Reference
Ogre::Bullet::DebugDrawer Class Reference
Optional Components » Bullet
#include <OgreBullet.h>
Public Member Functions
DebugDrawer (SceneNode *node, btDynamicsWorld *world)
void clear ()
void draw3dText (const btVector3 &location, const char *textString) override
void drawContactPoint (const btVector3 &PointOnB, const btVector3 &normalOnB, btScalar distance, int lifeTime, const btVector3 &color) override
void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &color) override
int getDebugMode () const override
void reportErrorWarning (const char *warningString) override
void setDebugMode (int mode) override
void update ()
Constructor & Destructor Documentation
DebugDrawer()
Ogre::Bullet::DebugDrawer::DebugDrawer (SceneNode * node, btDynamicsWorld * world) inline
References Ogre::MovableObject::setCastShadows().
Member Function Documentation
update()
void Ogre::Bullet::DebugDrawer::update (void) inline
References Ogre::ManualObject::end(), and Ogre::ManualObject::getSections().
drawLine()
void Ogre::Bullet::DebugDrawer::drawLine (const btVector3 & from, const btVector3 & to, const btVector3 & color) override
drawContactPoint()
void Ogre::Bullet::DebugDrawer::drawContactPoint (const btVector3 & PointOnB, const btVector3 & normalOnB, btScalar distance, int lifeTime, const btVector3 & color) inline override
reportErrorWarning()
void Ogre::Bullet::DebugDrawer::reportErrorWarning (const char * warningString) inline override
References Ogre::LogManager::getSingleton(), and Ogre::LogManager::logWarning().
draw3dText()
void Ogre::Bullet::DebugDrawer::draw3dText (const btVector3 & location, const char * textString) inline override
setDebugMode()
void Ogre::Bullet::DebugDrawer::setDebugMode (int mode) inline override
clear()
void Ogre::Bullet::DebugDrawer::clear (void) inline
References Ogre::ManualObject::clear().
getDebugMode()
int Ogre::Bullet::DebugDrawer::getDebugMode () const inline override
The documentation for this class was generated from the following file:
OgreBullet.h