OGRE: Ogre::RTShader::ProgramWriterManager Class Reference
Ogre::RTShader::ProgramWriterManager Class Reference
Optional Components » RTShaderSystem
#include <OgreShaderProgramWriterManager.h>
Public Types
typedef std::map< String, ProgramWriterFactory * > FactoryMap
Public Member Functions
ProgramWriterManager ()
~ProgramWriterManager ()
void addFactory (ProgramWriterFactory *factory)
void addProgramWriter (const String &lang, ProgramWriter *writer)
register and transfer ownership of writer
ProgramWriter * createProgramWriter (const String &language)
ProgramWriter * getProgramWriter (const String &language) const
bool isLanguageSupported (const String &lang)
Returns whether a given high-level language is supported.
void removeFactory (ProgramWriterFactory *factory)
Public Member Functions inherited from Ogre::Singleton< ProgramWriterManager >
Singleton (void)
~Singleton (void)
Static Public Member Functions
static ProgramWriterManager & getSingleton ()
Override standard Singleton retrieval.
static ProgramWriterManager * getSingletonPtr ()
Get the singleton instance.
Static Public Member Functions inherited from Ogre::Singleton< ProgramWriterManager >
static ProgramWriterManager & getSingleton (void)
Get the singleton instance.
static ProgramWriterManager * getSingletonPtr (void)
Get the singleton instance.
Member Typedef Documentation
FactoryMap
typedef std::map<String, ProgramWriterFactory*> Ogre::RTShader::ProgramWriterManager::FactoryMap
Constructor & Destructor Documentation
ProgramWriterManager()
Ogre::RTShader::ProgramWriterManager::ProgramWriterManager ()
~ProgramWriterManager()
Ogre::RTShader::ProgramWriterManager::~ProgramWriterManager ()
Member Function Documentation
addProgramWriter()
void Ogre::RTShader::ProgramWriterManager::addProgramWriter (const String & lang, ProgramWriter * writer)
register and transfer ownership of writer
isLanguageSupported()
bool Ogre::RTShader::ProgramWriterManager::isLanguageSupported (const String & lang)
Returns whether a given high-level language is supported.
addFactory()
void Ogre::RTShader::ProgramWriterManager::addFactory (ProgramWriterFactory * factory) inline
Deprecated:
References Ogre::RTShader::ProgramWriterFactory::create(), and Ogre::RTShader::ProgramWriterFactory::getTargetLanguage().
removeFactory()
void Ogre::RTShader::ProgramWriterManager::removeFactory (ProgramWriterFactory * factory) inline
Deprecated:
References Ogre::RTShader::ProgramWriterFactory::getTargetLanguage().
createProgramWriter()
ProgramWriter* Ogre::RTShader::ProgramWriterManager::createProgramWriter (const String & language)
Deprecated:
getProgramWriter()
ProgramWriter* Ogre::RTShader::ProgramWriterManager::getProgramWriter (const String & language) const inline
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
getSingleton()
static ProgramWriterManager& Ogre::RTShader::ProgramWriterManager::getSingleton () static
Override standard Singleton retrieval.
Remarks
Why do we do this? Well, it's because the Singleton implementation is in a .h file, which means it gets compiled into anybody who includes it. This is needed for the Singleton template to work, but we actually only want it compiled into the implementation of the class based on the Singleton, not all of them. If we don't change this, we get link errors when trying to use the Singleton-based class from an outside dll.
This method just delegates to the template version anyway, but the implementation stays in this single compilation unit, preventing link errors.
getSingletonPtr()
static ProgramWriterManager* Ogre::RTShader::ProgramWriterManager::getSingletonPtr () static
Get the singleton instance.
The documentation for this class was generated from the following file:
OgreShaderProgramWriterManager.h