#!/bin/sh

# Check for proper versions of autotools
# We require:
#  - autoconf 2.50+
#  - automake 1.6+
#  - libtool 1.4+

# Deal with some gentoo-specific issues
export WANT_AUTOMAKE='1.7'
export WANT_AUTOCONF='2.5'

## Using prereq in autoconf rather than here, mostly for the debian systems at
## this point
if test -z "`autoconf --version 2>&1|head -n 1|egrep '2.[56]'`"; then
	echo "Autoconf 2.50 or above is required. Aborting build...";
    exit 1;
fi

if test -z "`automake --version 2>&1|head -n 1|egrep '1.([6-9]|[1-9][0-9])'`"; then
	echo "Automake 1.6 or above is required. Aborting build...";
	exit 1;
fi

if test 140 -gt "`libtool --version|head -n 1|awk '{print $4;}'|sed "s/\.//g"`"; then 
	echo "Libtool 1.4 or above is required. Aborting build...";
	exit 1;
fi

# clean up files which cause confusion when switch versions of auto*
rm -rf autom4te.cache

# Fire up autotools
libtoolize --force --copy && aclocal -I Scripts/m4 $ACLOCAL_FLAGS && autoheader && automake --include-deps --add-missing --foreign --copy && autoconf 
