OGRE: Ogre::RTShader::SampleTextureAtom Class Reference
Ogre::RTShader::SampleTextureAtom Class Reference
Optional Components » RTShaderSystem
shorthand for "dst = texture(sampler, uv);" instead of using FFP_SampleTexture
#include <OgreShaderFunctionAtom.h>
Public Types
typedef std::vector< Operand > OperandVector
Public Member Functions
SampleTextureAtom (int groupOrder)
SampleTextureAtom (const In &sampler, const In &texcoord, const Out &dst, int groupOrder)
const String & getFunctionAtomType ()
const String & getFunctionName () const
Return the function name.
int getGroupExecutionOrder () const
Get the group execution order of this function atom.
int getInternalExecutionOrder () const
Get an internal execution order within a group of this function atom.
OperandVector & getOperandList ()
Get a list of parameters this function invocation will use in the function call as arguments.
const String & getReturnType () const
Return the return type.
bool operator!= (const FunctionInvocation &rhs) const
Determines if the current object is not equal to the compared one.
bool operator< (const FunctionInvocation &rhs) const
Determines if the current object is less than the compared one.
bool operator== (const FunctionInvocation &rhs) const
Determines if the current object is equal to the compared one.
void pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask=Operand::OPM_ALL, int indirectionLevel=0)
Push a new operand (on the end) to the function.
void setOperands (const OperandVector &ops)
void writeSourceCode (std::ostream &os, const String &targetLanguage) const
Static Public Attributes
static String Type
Detailed Description
shorthand for "dst = texture(sampler, uv);" instead of using FFP_SampleTexture
Member Typedef Documentation
OperandVector
typedef std::vector<Operand> Ogre::RTShader::FunctionInvocation::OperandVector inherited
Constructor & Destructor Documentation
SampleTextureAtom() [1/2]
Ogre::RTShader::SampleTextureAtom::SampleTextureAtom (int groupOrder) inline explicit
SampleTextureAtom() [2/2]
Ogre::RTShader::SampleTextureAtom::SampleTextureAtom (const In & sampler, const In & texcoord, const Out & dst, int groupOrder)
Member Function Documentation
writeSourceCode()
void Ogre::RTShader::SampleTextureAtom::writeSourceCode (std::ostream & os, const String & targetLanguage) const virtual
See also
FunctionAtom::writeSourceCode
Reimplemented from Ogre::RTShader::FunctionInvocation.
getFunctionAtomType()
const String& Ogre::RTShader::SampleTextureAtom::getFunctionAtomType () inline virtual
See also
FunctionAtom::getFunctionAtomType
Reimplemented from Ogre::RTShader::FunctionInvocation.
getOperandList()
OperandVector& Ogre::RTShader::FunctionInvocation::getOperandList () inline inherited
Get a list of parameters this function invocation will use in the function call as arguments.
References Ogre::RTShader::Operand::OPM_ALL.
pushOperand()
void Ogre::RTShader::FunctionInvocation::pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask = Operand::OPM_ALL, int indirectionLevel = 0) inherited
Push a new operand (on the end) to the function.
Parameters
parameter A function parameter.
opSemantic The in/out semantic of the parameter.
opMask The field mask of the parameter.
indirectionLevel The level of nesting inside brackets
setOperands()
void Ogre::RTShader::FunctionInvocation::setOperands (const OperandVector & ops) inherited
getFunctionName()
const String& Ogre::RTShader::FunctionInvocation::getFunctionName () const inline inherited
Return the function name.
getReturnType()
const String& Ogre::RTShader::FunctionInvocation::getReturnType () const inline inherited
Return the return type.
References Ogre::operator!=(), Ogre::operator<(), and Ogre::operator==().
operator==()
bool Ogre::RTShader::FunctionInvocation::operator== (const FunctionInvocation & rhs) const inherited
Determines if the current object is equal to the compared one.
operator!=()
bool Ogre::RTShader::FunctionInvocation::operator!= (const FunctionInvocation & rhs) const inherited
Determines if the current object is not equal to the compared one.
operator<()
bool Ogre::RTShader::FunctionInvocation::operator< (const FunctionInvocation & rhs) const inherited
Determines if the current object is less than the compared one.
getGroupExecutionOrder()
int Ogre::RTShader::FunctionAtom::getGroupExecutionOrder () const inherited
Get the group execution order of this function atom.
getInternalExecutionOrder()
int Ogre::RTShader::FunctionAtom::getInternalExecutionOrder () const inline inherited
Get an internal execution order within a group of this function atom.
Member Data Documentation
Type
String Ogre::RTShader::SampleTextureAtom::Type static
The documentation for this class was generated from the following file:
OgreShaderFunctionAtom.h