OGRE: Ogre::VectorBase< dims, T > Struct Template Reference
Ogre::VectorBase< dims, T > Struct Template Reference
Core » Math
helper class to implement legacy API. Notably x, y, z access
#include <OgreVector.h>
Public Member Functions
VectorBase ()
VectorBase (T _x, T _y)
VectorBase (T _x, T _y, T _z)
VectorBase (T _x, T _y, T _z, T _w)
T * ptr ()
const T * ptr () const
Public Attributes
T data [dims]
Detailed Description
template<int dims, typename T>
struct Ogre::VectorBase< dims, T >
helper class to implement legacy API. Notably x, y, z access
Constructor & Destructor Documentation
VectorBase() [1/4]
template<int dims, typename T> Ogre::VectorBase< dims, T >::VectorBase () inline
VectorBase() [2/4]
template<int dims, typename T> Ogre::VectorBase< dims, T >::VectorBase (T _x, T _y) inline
VectorBase() [3/4]
template<int dims, typename T> Ogre::VectorBase< dims, T >::VectorBase (T _x, T _y, T _z) inline
VectorBase() [4/4]
template<int dims, typename T> Ogre::VectorBase< dims, T >::VectorBase (T _x, T _y, T _z, T _w) inline
Member Function Documentation
ptr() [1/2]
template<int dims, typename T> T* Ogre::VectorBase< dims, T >::ptr () inline
Referenced by Ogre::Vector< 3, Real >::dotProduct(), Ogre::Vector< 3, Real >::isNaN(), Ogre::Vector< 3, Real >::makeCeil(), Ogre::Vector< 3, Real >::makeFloor(), Ogre::Vector< 3, Real >::normalise(), Ogre::Vector< 3, Real >::operator*=(), Ogre::Vector< 3, Real >::operator+=(), Ogre::Vector< 3, Real >::operator-=(), Ogre::Vector< 3, Real >::operator/=(), Ogre::Vector< 3, Real >::operator<(), Ogre::Vector< 3, Real >::operator==(), Ogre::Vector< 3, Real >::operator>(), Ogre::Vector< 3, Real >::operator[](), Ogre::Vector< 3, Real >::positionEquals(), Ogre::RTShader::UniformParameter::setGpuParameter(), Ogre::Vector< 3, Real >::Vector(), Ogre::Vector< 3, Real >::xy(), and Ogre::Vector< 3, Real >::xyz().
ptr() [2/2]
template<int dims, typename T> const T* Ogre::VectorBase< dims, T >::ptr () const inline
Member Data Documentation
data
template<int dims, typename T> T Ogre::VectorBase< dims, T >::data[dims]
Referenced by Ogre::VectorBase< dims, int >::ptr(), and Ogre::VectorBase< dims, int >::VectorBase().
The documentation for this struct was generated from the following file:
OgreVector.h