// This file has been auto-generated by clone_datablock.py
// Please DO NOT manually edit this file. Any subsequent invocation of clone_datablock.py will overwrite your modifications.

/*
-----------------------------------------------------------------------------
This source file is part of OGRE
    (Object-oriented Graphics Rendering Engine)
For the latest info, see http://www.ogre3d.org/

Copyright (c) 2000-2014 Torus Knot Software Ltd

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-----------------------------------------------------------------------------
*/

namespace Ogre
{
    //-----------------------------------------------------------------------------------
    void HlmsPbsDatablock::cloneImpl( HlmsDatablock *datablock ) const
    {
        HlmsPbsDatablock *datablockImpl = static_cast<HlmsPbsDatablock*>( datablock );

        datablockImpl->mFresnelTypeSizeBytes = mFresnelTypeSizeBytes;
        datablockImpl->mTwoSided = mTwoSided;
        datablockImpl->mUseAlphaFromTextures = mUseAlphaFromTextures;
        datablockImpl->mWorkflow = mWorkflow;
        datablockImpl->mReceiveShadows = mReceiveShadows;
        datablockImpl->mTransparencyMode = mTransparencyMode;
        datablockImpl->mkDr = mkDr;
        datablockImpl->mkDg = mkDg;
        datablockImpl->mkDb = mkDb;
        datablockImpl->_padding0 = _padding0;
        datablockImpl->mkSr = mkSr;
        datablockImpl->mkSg = mkSg;
        datablockImpl->mkSb = mkSb;
        datablockImpl->mRoughness = mRoughness;
        datablockImpl->mFresnelR = mFresnelR;
        datablockImpl->mFresnelG = mFresnelG;
        datablockImpl->mFresnelB = mFresnelB;
        datablockImpl->mTransparencyValue = mTransparencyValue;
        datablockImpl->mNormalMapWeight = mNormalMapWeight;
        datablockImpl->mCubemapProbe = mCubemapProbe;
        datablockImpl->mBrdf = mBrdf;

        for( size_t i=0; i<mBakedTextures.size(); ++i )
        {
            datablockImpl->mBakedTextures.push_back( mBakedTextures[i] );
        }

        for( size_t i=0; i<3; ++i )
        {
            datablockImpl->mEmissive[i] = mEmissive[i];
        }

        for( size_t i=0; i<3; ++i )
        {
            for( size_t j=0; j<4; ++j )
            {
                datablockImpl->mUserValue[i][j] = mUserValue[i][j];
            }
        }

        for( size_t i=0; i<4; ++i )
        {
            datablockImpl->mBlendModes[i] = mBlendModes[i];
        }

        for( size_t i=0; i<4; ++i )
        {
            datablockImpl->mBgDiffuse[i] = mBgDiffuse[i];
        }

        for( size_t i=0; i<4; ++i )
        {
            datablockImpl->mDetailNormalWeight[i] = mDetailNormalWeight[i];
        }

        for( size_t i=0; i<4; ++i )
        {
            datablockImpl->mDetailWeight[i] = mDetailWeight[i];
        }

        for( size_t i=0; i<4; ++i )
        {
            for( size_t j=0; j<4; ++j )
            {
                datablockImpl->mDetailsOffsetScale[i][j] = mDetailsOffsetScale[i][j];
            }
        }

        for( size_t i=0; i<14; ++i )
        {
            datablockImpl->mUvSource[i] = mUvSource[i];
        }

        for( size_t i=0; i<15; ++i )
        {
            datablockImpl->mTexIndices[i] = mTexIndices[i];
        }

        for( size_t i=0; i<15; ++i )
        {
            datablockImpl->mTexToBakedTextureIdx[i] = mTexToBakedTextureIdx[i];
        }

        for( size_t i=0; i<15; ++i )
        {
            datablockImpl->mSamplerblocks[i] = mSamplerblocks[i];
            if( datablockImpl->mSamplerblocks[i] )
                mCreator->getHlmsManager()->addReference( datablockImpl->mSamplerblocks[i] );
        }
    }
}
