OGRE: Ogre::RotationAffector Class Reference
Ogre::RotationAffector Class Reference
Plugins » ParticleFX
This plugin subclass of ParticleAffector allows you to alter the rotation of particles.
#include <OgreRotationAffector.h>
Classes
class CmdRotationRangeEnd
Command object for particle emitter - see ParamCommand.
class CmdRotationRangeStart
Command object for particle emitter - see ParamCommand.
class CmdRotationSpeedRangeEnd
Command object for particle emitter - see ParamCommand.
class CmdRotationSpeedRangeStart
Command object for particle emitter - see ParamCommand.
Public Member Functions
RotationAffector (ParticleSystem *psys)
Default constructor.
void _affectParticles (ParticleSystem *pSystem, Real timeElapsed)
See ParticleAffector.
void _initParticle (Particle *pParticle)
See ParticleAffector.
void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
const Radian & getRotationRangeEnd (void) const
Gets the maximum rotation of particles to be emitted.
const Radian & getRotationRangeStart (void) const
Gets the minimum rotation of particles to be emitted.
const Radian & getRotationSpeedRangeEnd (void) const
Gets the maximum rotation speed of particles to be emitted.
const Radian & getRotationSpeedRangeStart (void) const
Gets the minimum rotation speed of particles to be emitted.
const String & getType (void) const
Returns the name of the type of affector.
bool setParameter (const String &name, const String &value)
Generic parameter setting method.
void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setRotationRangeEnd (const Radian &angle)
Sets the maximum rotation angle of particles to be emitted.
void setRotationRangeStart (const Radian &angle)
Sets the minimum rotation angle of particles to be emitted.
void setRotationSpeedRangeEnd (const Radian &angle)
Sets the maximum rotation speed of particles to be emitted.
void setRotationSpeedRangeStart (const Radian &angle)
Sets the minimum rotation speed of particles to be emitted.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Static Public Attributes
static CmdRotationRangeEnd msRotationRangeEndCmd
static CmdRotationRangeStart msRotationRangeStartCmd
static CmdRotationSpeedRangeEnd msRotationSpeedRangeEndCmd
static CmdRotationSpeedRangeStart msRotationSpeedRangeStartCmd
Detailed Description
This plugin subclass of ParticleAffector allows you to alter the rotation of particles.
Remarks
This class supplies the ParticleAffector implementation required to make the particle expand or contract in mid-flight.
Constructor & Destructor Documentation
RotationAffector()
Ogre::RotationAffector::RotationAffector (ParticleSystem * psys)
Default constructor.
Member Function Documentation
_initParticle()
void Ogre::RotationAffector::_initParticle (Particle * pParticle) virtual
See ParticleAffector.
Reimplemented from Ogre::ParticleAffector.
_affectParticles()
void Ogre::RotationAffector::_affectParticles (ParticleSystem * pSystem, Real timeElapsed) virtual
See ParticleAffector.
Implements Ogre::ParticleAffector.
setRotationSpeedRangeStart()
void Ogre::RotationAffector::setRotationSpeedRangeStart (const Radian & angle)
Sets the minimum rotation speed of particles to be emitted.
setRotationSpeedRangeEnd()
void Ogre::RotationAffector::setRotationSpeedRangeEnd (const Radian & angle)
Sets the maximum rotation speed of particles to be emitted.
getRotationSpeedRangeStart()
const Radian& Ogre::RotationAffector::getRotationSpeedRangeStart (void) const
Gets the minimum rotation speed of particles to be emitted.
getRotationSpeedRangeEnd()
const Radian& Ogre::RotationAffector::getRotationSpeedRangeEnd (void) const
Gets the maximum rotation speed of particles to be emitted.
setRotationRangeStart()
void Ogre::RotationAffector::setRotationRangeStart (const Radian & angle)
Sets the minimum rotation angle of particles to be emitted.
setRotationRangeEnd()
void Ogre::RotationAffector::setRotationRangeEnd (const Radian & angle)
Sets the maximum rotation angle of particles to be emitted.
getRotationRangeStart()
const Radian& Ogre::RotationAffector::getRotationRangeStart (void) const
Gets the minimum rotation of particles to be emitted.
getRotationRangeEnd()
const Radian& Ogre::RotationAffector::getRotationRangeEnd (void) const
Gets the maximum rotation of particles to be emitted.
getType()
const String& Ogre::ParticleAffector::getType (void) const inline inherited
Returns the name of the type of affector.
Remarks
This property is useful for determining the type of affector procedurally so another can be created.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
setParameter()
bool Ogre::StringInterface::setParameter (const String & name, const String & value) inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
getParameter()
String Ogre::StringInterface::getParameter (const String & name) const inline inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
copyParametersTo()
void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
msRotationSpeedRangeStartCmd
CmdRotationSpeedRangeStart Ogre::RotationAffector::msRotationSpeedRangeStartCmd static
msRotationSpeedRangeEndCmd
CmdRotationSpeedRangeEnd Ogre::RotationAffector::msRotationSpeedRangeEndCmd static
msRotationRangeStartCmd
CmdRotationRangeStart Ogre::RotationAffector::msRotationRangeStartCmd static
msRotationRangeEndCmd
CmdRotationRangeEnd Ogre::RotationAffector::msRotationRangeEndCmd static
The documentation for this class was generated from the following file:
OgreRotationAffector.h