OGRE: Ogre::Compositor Class Reference
Ogre::Compositor Class Reference
Core » Effects
Class representing a Compositor object.
#include <OgreCompositor.h>
Public Types
enum LoadingFlags {
LF_DEFAULT = 0, LF_INCLUDE_NON_RELOADABLE = 1, LF_ONLY_UNREFERENCED = 2, LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3,
LF_PRESERVE_STATE = 4
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
typedef VectorIterator< Techniques > TechniqueIterator
typedef vector< CompositionTechnique * >::type Techniques
Data types for internal lists.
Public Member Functions
Compositor (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual=false, ManualResourceLoader *loader=0)
~Compositor ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
void _fireUnloadingComplete (void)
Firing of unloading complete event.
void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
CompositionTechnique * createTechnique ()
Create a new technique, and return a pointer to it.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual LoadingState getLoadingState () const
Returns the current loading state.
virtual const String & getName (void) const
Gets resource name.
size_t getNumSupportedTechniques ()
Get the number of supported techniques.
size_t getNumTechniques ()
Get the number of techniques.
const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
RenderTarget * getRenderTarget (const String &name)
Get the render target for a given render texture name.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
CompositionTechnique * getSupportedTechnique (size_t idx)
Get a supported technique.
CompositionTechnique * getSupportedTechnique (const String &schemeName=BLANKSTRING)
Get a pointer to a supported technique for a given scheme.
TechniqueIterator getSupportedTechniqueIterator (void)
Gets an iterator over all the Techniques which are supported by the current card.
CompositionTechnique * getTechnique (size_t idx)
Get a technique.
TechniqueIterator getTechniqueIterator (void)
Get an iterator over the Techniques in this compositor.
TexturePtr getTextureInstance (const String &name, size_t mrtIndex)
Get the instance of a global texture.
const String & getTextureInstanceName (const String &name, size_t mrtIndex)
Get the instance name for a global texture.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
void removeAllTechniques ()
Remove all techniques.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
void removeTechnique (size_t idx)
Remove a technique.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
bool setParameter (const String &name, const String &value)
Generic parameter setting method.
void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
OGRE_AUTO_MUTEX
Detailed Description
Class representing a Compositor object.
Compositors provide the means to flexibly "composite" the final rendering result from multiple scene renders and intermediate operations like rendering fullscreen quads. This makes it possible to apply postfilter effects, HDRI postprocessing, and shadow effects to a Viewport.
Member Typedef Documentation
Techniques
typedef vector<CompositionTechnique *>::type Ogre::Compositor::Techniques
Data types for internal lists.
TechniqueIterator
typedef VectorIterator<Techniques> Ogre::Compositor::TechniqueIterator
Member Enumeration Documentation
LoadingState
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
LoadingFlags
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object. Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
Constructor & Destructor Documentation
Compositor()
Ogre::Compositor::Compositor (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual = false, ManualResourceLoader * loader = 0)
~Compositor()
Ogre::Compositor::~Compositor ()
Member Function Documentation
createTechnique()
CompositionTechnique* Ogre::Compositor::createTechnique ()
Create a new technique, and return a pointer to it.
removeTechnique()
void Ogre::Compositor::removeTechnique (size_t idx)
Remove a technique.
It will also be destroyed.
getTechnique()
CompositionTechnique* Ogre::Compositor::getTechnique (size_t idx)
Get a technique.
getNumTechniques()
size_t Ogre::Compositor::getNumTechniques ()
Get the number of techniques.
removeAllTechniques()
void Ogre::Compositor::removeAllTechniques ()
Remove all techniques.
getTechniqueIterator()
TechniqueIterator Ogre::Compositor::getTechniqueIterator (void)
Get an iterator over the Techniques in this compositor.
getSupportedTechnique() [1/2]
CompositionTechnique* Ogre::Compositor::getSupportedTechnique (size_t idx)
Get a supported technique.
Remarks
The supported technique list is only available after this compositor has been compiled, which typically happens on loading it. Therefore, if this method returns an empty list, try calling Compositor::load.
getNumSupportedTechniques()
size_t Ogre::Compositor::getNumSupportedTechniques ()
Get the number of supported techniques.
Remarks
The supported technique list is only available after this compositor has been compiled, which typically happens on loading it. Therefore, if this method returns an empty list, try calling Compositor::load.
getSupportedTechniqueIterator()
TechniqueIterator Ogre::Compositor::getSupportedTechniqueIterator (void)
Gets an iterator over all the Techniques which are supported by the current card.
Remarks
The supported technique list is only available after this compositor has been compiled, which typically happens on loading it. Therefore, if this method returns an empty list, try calling Compositor::load.
getSupportedTechnique() [2/2]
CompositionTechnique* Ogre::Compositor::getSupportedTechnique (const String & schemeName = BLANKSTRING)
Get a pointer to a supported technique for a given scheme.
Remarks
If there is no specific supported technique with this scheme name, then the first supported technique with no specific scheme will be returned.
Parameters
schemeName The scheme name you are looking for. Blank means to look for techniques with no scheme associated
getTextureInstanceName()
const String& Ogre::Compositor::getTextureInstanceName (const String & name, size_t mrtIndex)
Get the instance name for a global texture.
Parameters
name The name of the texture in the original compositor definition
mrtIndex If name identifies a MRT, which texture attachment to retrieve
Returns
The instance name for the texture, corresponds to a real texture
getTextureInstance()
TexturePtr Ogre::Compositor::getTextureInstance (const String & name, size_t mrtIndex)
Get the instance of a global texture.
Parameters
name The name of the texture in the original compositor definition
mrtIndex If name identifies a MRT, which texture attachment to retrieve
Returns
The texture pointer, corresponds to a real texture
getRenderTarget()
RenderTarget* Ogre::Compositor::getRenderTarget (const String & name)
Get the render target for a given render texture name.
Remarks
You can use this to add listeners etc, but do not use it to update the targets manually or any other modifications, the compositor instance is in charge of this.
prepare()
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
load()
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
reload()
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
isReloadable()
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isManuallyLoaded()
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
setManuallyLoaded()
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
Deprecated:
do not use
unload()
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getSize()
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
touch()
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
getName()
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::SkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName(), and OgreBites::TrayManager::resourceLoadStarted().
getHandle()
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::SkeletonInstance.
isPrepared()
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::load().
isLoaded()
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
setToLoaded()
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
Deprecated:
do not use
References Ogre::AtomicScalar< T >::store().
isLoading()
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
getLoadingState()
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
isBackgroundLoaded()
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setBackgroundLoaded()
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
See also
Resource::isBackgroundLoaded. Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
escalateLoading()
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
addListener()
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
removeListener()
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getGroup()
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::SkeletonInstance.
changeGroupOwnership()
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
getCreator()
ResourceManager* Ogre::Resource::getCreator (void) inline inherited
Gets the manager which created this resource.
getOrigin()
const String& Ogre::Resource::getOrigin (void) const inline inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
_notifyOrigin()
void Ogre::Resource::_notifyOrigin (const String & origin) inline inherited
Notify this resource of it's origin.
getStateCount()
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
_dirtyState()
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
_fireLoadingComplete()
void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_firePreparingComplete()
void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_fireUnloadingComplete()
void Ogre::Resource::_fireUnloadingComplete (void) inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
setParameter()
bool Ogre::StringInterface::setParameter (const String & name, const String & value) inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
getParameter()
String Ogre::StringInterface::getParameter (const String & name) const inline inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
copyParametersTo()
void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
OGRE_AUTO_MUTEX
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreCompositor.h