OGRE: Ogre::VertexAnimationTrack Class Reference
Ogre::VertexAnimationTrack Class Reference
Core » Animation
Specialised AnimationTrack for dealing with changing vertex position information.
#include <OgreAnimationTrack.h>
Public Types
enum TargetMode { TM_SOFTWARE, TM_HARDWARE }
The target animation mode.
Public Member Functions
VertexAnimationTrack (Animation *parent, unsigned short handle, VertexAnimationType animType)
Constructor.
VertexAnimationTrack (Animation *parent, unsigned short handle, VertexAnimationType animType, VertexData *targetData, TargetMode target=TM_SOFTWARE)
Constructor, associates with target VertexData and temp buffer (for software)
void _applyBaseKeyFrame (const KeyFrame *base)
Internal method to re-base the keyframes relative to a given keyframe.
virtual void _buildKeyFrameIndexMap (const vector< Real >::type &keyFrameTimes)
Internal method to build keyframe time index map to translate global lower bound index to local lower bound index.
VertexAnimationTrack * _clone (Animation *newParent) const
Clone this track (internal use only)
virtual void _collectKeyFrameTimes (vector< Real >::type &keyFrameTimes)
Internal method to collect keyframe times, in unique, ordered format.
virtual void _keyFrameDataChanged (void) const
Internal method used to tell the track that keyframe data has been changed, which may cause it to rebuild some internal data.
virtual void apply (const TimeIndex &timeIndex, Real weight=1.0, Real scale=1.0f)
Applies an animation track to the designated target.
virtual void applyToVertexData (VertexData *data, const TimeIndex &timeIndex, Real weight=1.0, const PoseList *poseList=0)
As the 'apply' method but applies to specified VertexData instead of associated data.
virtual KeyFrame * createKeyFrame (Real timePos)
Creates a new KeyFrame and adds it to this animation at the given time index.
virtual VertexMorphKeyFrame * createVertexMorphKeyFrame (Real timePos)
Creates a new morph KeyFrame and adds it to this animation at the given time index.
virtual VertexPoseKeyFrame * createVertexPoseKeyFrame (Real timePos)
Creates the single pose KeyFrame and adds it to this animation.
VertexAnimationType getAnimationType (void) const
Get the type of vertex animation we're performing.
VertexData * getAssociatedVertexData (void) const
Gets the associated VertexData which this track will update.
unsigned short getHandle (void) const
Get the handle associated with this track.
virtual void getInterpolatedKeyFrame (const TimeIndex &timeIndex, KeyFrame *kf) const
Gets a KeyFrame object which contains the interpolated transforms at the time index specified.
virtual KeyFrame * getKeyFrame (unsigned short index) const
Returns the KeyFrame at the specified index.
virtual Real getKeyFramesAtTime (const TimeIndex &timeIndex, KeyFrame **keyFrame1, KeyFrame **keyFrame2, unsigned short *firstKeyIndex=0) const
Gets the 2 KeyFrame objects which are active at the time given, and the blend value between them.
virtual unsigned short getNumKeyFrames (void) const
Returns the number of keyframes in this animation.
Animation * getParent () const
Returns the parent Animation object for this track.
TargetMode getTargetMode (void) const
Get the target mode.
bool getVertexAnimationIncludesNormals () const
Whether the vertex animation (if present) includes normals.
VertexMorphKeyFrame * getVertexMorphKeyFrame (unsigned short index) const
Returns the morph KeyFrame at the specified index.
VertexPoseKeyFrame * getVertexPoseKeyFrame (unsigned short index) const
Returns the pose KeyFrame at the specified index.
virtual bool hasNonZeroKeyFrames (void) const
Method to determine if this track has any KeyFrames which are doing anything useful - can be used to determine if this track can be optimised out.
virtual void optimise (void)
Optimise the current track by removing any duplicate keyframes.
virtual void removeAllKeyFrames (void)
Removes all the KeyFrames from this track.
virtual void removeKeyFrame (unsigned short index)
Removes a KeyFrame by it's index.
void setAssociatedVertexData (VertexData *data)
Sets the associated VertexData which this track will update.
virtual void setListener (Listener *l)
Set a listener for this track.
void setTargetMode (TargetMode m)
Set the target mode.
Detailed Description
Specialised AnimationTrack for dealing with changing vertex position information.
See also
VertexAnimationType
Member Enumeration Documentation
TargetMode
enum Ogre::VertexAnimationTrack::TargetMode
The target animation mode.
Enumerator
TM_SOFTWARE
Interpolate vertex positions in software.
TM_HARDWARE
Bind keyframe 1 to position, and keyframe 2 to a texture coordinate for interpolation in hardware.
Constructor & Destructor Documentation
VertexAnimationTrack() [1/2]
Ogre::VertexAnimationTrack::VertexAnimationTrack (Animation * parent, unsigned short handle, VertexAnimationType animType)
Constructor.
VertexAnimationTrack() [2/2]
Ogre::VertexAnimationTrack::VertexAnimationTrack (Animation * parent, unsigned short handle, VertexAnimationType animType, VertexData * targetData, TargetMode target = TM_SOFTWARE)
Constructor, associates with target VertexData and temp buffer (for software)
Member Function Documentation
getAnimationType()
VertexAnimationType Ogre::VertexAnimationTrack::getAnimationType (void) const inline
Get the type of vertex animation we're performing.
Referenced by Ogre::Lod0Stripifier::~Lod0Stripifier().
getVertexAnimationIncludesNormals()
bool Ogre::VertexAnimationTrack::getVertexAnimationIncludesNormals () const
Whether the vertex animation (if present) includes normals.
createVertexMorphKeyFrame()
virtual VertexMorphKeyFrame* Ogre::VertexAnimationTrack::createVertexMorphKeyFrame (Real timePos) virtual
Creates a new morph KeyFrame and adds it to this animation at the given time index.
Remarks
It is better to create KeyFrames in time order. Creating them out of order can result in expensive reordering processing. Note that a KeyFrame at time index 0.0 is always created for you, so you don't need to create this one, just access it using getKeyFrame(0);
Parameters
timePos The time from which this KeyFrame will apply.
createVertexPoseKeyFrame()
virtual VertexPoseKeyFrame* Ogre::VertexAnimationTrack::createVertexPoseKeyFrame (Real timePos) virtual
Creates the single pose KeyFrame and adds it to this animation.
getInterpolatedKeyFrame()
virtual void Ogre::VertexAnimationTrack::getInterpolatedKeyFrame (const TimeIndex & timeIndex, KeyFrame * kf) const virtual
Gets a KeyFrame object which contains the interpolated transforms at the time index specified.
Remarks
The KeyFrame objects held by this class are transformation snapshots at discrete points in time. Normally however, you want to interpolate between these keyframes to produce smooth movement, and this method allows you to do this easily. In animation terminology this is called 'tweening'.
Parameters
timeIndex The time (in relation to the whole animation sequence)
kf Keyframe object to store results
Implements Ogre::AnimationTrack.
apply()
virtual void Ogre::VertexAnimationTrack::apply (const TimeIndex & timeIndex, Real weight = 1.0, Real scale = 1.0f) virtual
Applies an animation track to the designated target.
Parameters
timeIndex The time position in the animation to apply.
weight The influence to give to this track, 1.0 for full influence, less to blend with other animations.
scale The scale to apply to translations and scalings, useful for adapting an animation to a different size target.
Implements Ogre::AnimationTrack.
applyToVertexData()
virtual void Ogre::VertexAnimationTrack::applyToVertexData (VertexData * data, const TimeIndex & timeIndex, Real weight = 1.0, const PoseList * poseList = 0) virtual
As the 'apply' method but applies to specified VertexData instead of associated data.
getVertexMorphKeyFrame()
VertexMorphKeyFrame* Ogre::VertexAnimationTrack::getVertexMorphKeyFrame (unsigned short index) const
Returns the morph KeyFrame at the specified index.
Referenced by Ogre::Lod0Stripifier::~Lod0Stripifier().
getVertexPoseKeyFrame()
VertexPoseKeyFrame* Ogre::VertexAnimationTrack::getVertexPoseKeyFrame (unsigned short index) const
Returns the pose KeyFrame at the specified index.
setAssociatedVertexData()
void Ogre::VertexAnimationTrack::setAssociatedVertexData (VertexData * data) inline
Sets the associated VertexData which this track will update.
getAssociatedVertexData()
VertexData* Ogre::VertexAnimationTrack::getAssociatedVertexData (void) const inline
Gets the associated VertexData which this track will update.
setTargetMode()
void Ogre::VertexAnimationTrack::setTargetMode (TargetMode m) inline
Set the target mode.
getTargetMode()
TargetMode Ogre::VertexAnimationTrack::getTargetMode (void) const inline
Get the target mode.
hasNonZeroKeyFrames()
virtual bool Ogre::VertexAnimationTrack::hasNonZeroKeyFrames (void) const virtual
Method to determine if this track has any KeyFrames which are doing anything useful - can be used to determine if this track can be optimised out.
Reimplemented from Ogre::AnimationTrack.
optimise()
virtual void Ogre::VertexAnimationTrack::optimise (void) virtual
Optimise the current track by removing any duplicate keyframes.
Reimplemented from Ogre::AnimationTrack.
_clone()
VertexAnimationTrack* Ogre::VertexAnimationTrack::_clone (Animation * newParent) const
Clone this track (internal use only)
_applyBaseKeyFrame()
void Ogre::VertexAnimationTrack::_applyBaseKeyFrame (const KeyFrame * base) virtual
Internal method to re-base the keyframes relative to a given keyframe.
Reimplemented from Ogre::AnimationTrack.
getHandle()
unsigned short Ogre::AnimationTrack::getHandle (void) const inline inherited
Get the handle associated with this track.
Referenced by Ogre::Lod0Stripifier::StripLod0Vertices().
getNumKeyFrames()
virtual unsigned short Ogre::AnimationTrack::getNumKeyFrames (void) const virtual inherited
Returns the number of keyframes in this animation.
Referenced by Ogre::Lod0Stripifier::~Lod0Stripifier().
getKeyFrame()
virtual KeyFrame* Ogre::AnimationTrack::getKeyFrame (unsigned short index) const virtual inherited
Returns the KeyFrame at the specified index.
getKeyFramesAtTime()
virtual Real Ogre::AnimationTrack::getKeyFramesAtTime (const TimeIndex & timeIndex, KeyFrame ** keyFrame1, KeyFrame ** keyFrame2, unsigned short * firstKeyIndex = 0) const virtual inherited
Gets the 2 KeyFrame objects which are active at the time given, and the blend value between them.
Remarks
At any point in time in an animation, there are either 1 or 2 keyframes which are 'active', 1 if the time index is exactly on a keyframe, 2 at all other times i.e. the keyframe before and the keyframe after.
This method returns those keyframes given a time index, and also returns a parametric value indicating the value of 't' representing where the time index falls between them. E.g. if it returns 0, the time index is exactly on keyFrame1, if it returns 0.5 it is half way between keyFrame1 and keyFrame2 etc.
Parameters
timeIndex The time index.
keyFrame1 Pointer to a KeyFrame pointer which will receive the pointer to the keyframe just before or at this time index.
keyFrame2 Pointer to a KeyFrame pointer which will receive the pointer to the keyframe just after this time index.
firstKeyIndex Pointer to an unsigned short which, if supplied, will receive the index of the 'from' keyframe in case the caller needs it.
Returns
Parametric value indicating how far along the gap between the 2 keyframes the timeIndex value is, e.g. 0.0 for exactly at 1, 0.25 for a quarter etc. By definition the range of this value is: 0.0 <= returnValue < 1.0 .
createKeyFrame()
virtual KeyFrame* Ogre::AnimationTrack::createKeyFrame (Real timePos) virtual inherited
Creates a new KeyFrame and adds it to this animation at the given time index.
Remarks
It is better to create KeyFrames in time order. Creating them out of order can result in expensive reordering processing. Note that a KeyFrame at time index 0.0 is always created for you, so you don't need to create this one, just access it using getKeyFrame(0);
Parameters
timePos The time from which this KeyFrame will apply.
removeKeyFrame()
virtual void Ogre::AnimationTrack::removeKeyFrame (unsigned short index) virtual inherited
Removes a KeyFrame by it's index.
removeAllKeyFrames()
virtual void Ogre::AnimationTrack::removeAllKeyFrames (void) virtual inherited
Removes all the KeyFrames from this track.
_keyFrameDataChanged()
virtual void Ogre::AnimationTrack::_keyFrameDataChanged (void) const inline virtual inherited
Internal method used to tell the track that keyframe data has been changed, which may cause it to rebuild some internal data.
Reimplemented in Ogre::NodeAnimationTrack.
_collectKeyFrameTimes()
virtual void Ogre::AnimationTrack::_collectKeyFrameTimes (vector< Real >::type & keyFrameTimes) virtual inherited
Internal method to collect keyframe times, in unique, ordered format.
_buildKeyFrameIndexMap()
virtual void Ogre::AnimationTrack::_buildKeyFrameIndexMap (const vector< Real >::type & keyFrameTimes) virtual inherited
Internal method to build keyframe time index map to translate global lower bound index to local lower bound index.
setListener()
virtual void Ogre::AnimationTrack::setListener (Listener * l) inline virtual inherited
Set a listener for this track.
getParent()
Animation* Ogre::AnimationTrack::getParent () const inline inherited
Returns the parent Animation object for this track.
The documentation for this class was generated from the following file:
OgreAnimationTrack.h