OGRE: Ogre::RTShader::GLSLESProgramProcessor Class Reference
Ogre::RTShader::GLSLESProgramProcessor Class Reference
Optional Components » RTShaderSystem
GLSL ES Language program processor class.
#include <OgreShaderGLSLESProgramProcessor.h>
Public Member Functions
GLSLESProgramProcessor ()
Class constructor.
virtual ~GLSLESProgramProcessor ()
Class destructor.
virtual const String & getTargetLanguage () const
Return the target language of this processor.
virtual bool postCreateGpuPrograms (ProgramSet *programSet)
virtual bool preCreateGpuPrograms (ProgramSet *programSet)
Detailed Description
GLSL ES Language program processor class.
Constructor & Destructor Documentation
GLSLESProgramProcessor()
Ogre::RTShader::GLSLESProgramProcessor::GLSLESProgramProcessor ()
Class constructor.
~GLSLESProgramProcessor()
virtual Ogre::RTShader::GLSLESProgramProcessor::~GLSLESProgramProcessor () virtual
Class destructor.
Member Function Documentation
getTargetLanguage()
virtual const String& Ogre::RTShader::GLSLESProgramProcessor::getTargetLanguage () const inline virtual
Return the target language of this processor.
Implements Ogre::RTShader::ProgramProcessor.
References postCreateGpuPrograms(), and preCreateGpuPrograms().
preCreateGpuPrograms()
virtual bool Ogre::RTShader::GLSLESProgramProcessor::preCreateGpuPrograms (ProgramSet * programSet) virtual
See also
ProgramProcessor::preCreateGpuPrograms
Implements Ogre::RTShader::ProgramProcessor.
Referenced by getTargetLanguage().
postCreateGpuPrograms()
virtual bool Ogre::RTShader::GLSLESProgramProcessor::postCreateGpuPrograms (ProgramSet * programSet) virtual
See also
ProgramProcessor::postCreateGpuPrograms
Implements Ogre::RTShader::ProgramProcessor.
Referenced by getTargetLanguage().
The documentation for this class was generated from the following file:
OgreShaderGLSLESProgramProcessor.h