OGRE: Ogre::ColourFaderAffector Class Reference
Ogre::ColourFaderAffector Class Reference
Plugins » ParticleFX
This plugin subclass of ParticleAffector allows you to alter the colour of particles.
#include <OgreColourFaderAffector.h>
Classes
class CmdAlphaAdjust
Command object for alpha adjust (see ParamCommand).
class CmdBlueAdjust
Command object for blue adjust (see ParamCommand).
class CmdGreenAdjust
Command object for green adjust (see ParamCommand).
class CmdRedAdjust
Command object for red adjust (see ParamCommand).
Public Member Functions
ColourFaderAffector (ParticleSystem *psys)
Default constructor.
void _affectParticles (ParticleSystem *pSystem, Real timeElapsed)
See ParticleAffector.
virtual void _initParticle (Particle *pParticle)
Method called to allow the affector to initialize all newly created particles in the system.
void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
float getAlphaAdjust (void) const
Gets the alpha adjustment to be made per second to particles.
float getBlueAdjust (void) const
Gets the blue adjustment to be made per second to particles.
float getGreenAdjust (void) const
Gets the green adjustment to be made per second to particles.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
float getRedAdjust (void) const
Gets the red adjustment to be made per second to particles.
const String & getType (void) const
Returns the name of the type of affector.
void setAdjust (float red, float green, float blue, float alpha=0.0)
Sets the colour adjustment to be made per second to particles.
void setAlphaAdjust (float alpha)
Sets the alpha adjustment to be made per second to particles.
void setBlueAdjust (float blue)
Sets the blue adjustment to be made per second to particles.
void setGreenAdjust (float green)
Sets the green adjustment to be made per second to particles.
bool setParameter (const String &name, const String &value)
Generic parameter setting method.
void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setRedAdjust (float red)
Sets the red adjustment to be made per second to particles.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Static Public Attributes
static CmdAlphaAdjust msAlphaCmd
static CmdBlueAdjust msBlueCmd
static CmdGreenAdjust msGreenCmd
static CmdRedAdjust msRedCmd
Detailed Description
This plugin subclass of ParticleAffector allows you to alter the colour of particles.
Remarks
This class supplies the ParticleAffector implementation required to modify the colour of particle in mid-flight.
Constructor & Destructor Documentation
ColourFaderAffector()
Ogre::ColourFaderAffector::ColourFaderAffector (ParticleSystem * psys)
Default constructor.
Member Function Documentation
_affectParticles()
void Ogre::ColourFaderAffector::_affectParticles (ParticleSystem * pSystem, Real timeElapsed) virtual
See ParticleAffector.
Implements Ogre::ParticleAffector.
setAdjust()
void Ogre::ColourFaderAffector::setAdjust (float red, float green, float blue, float alpha = 0.0)
Sets the colour adjustment to be made per second to particles.
Parameters
red,green,blue,alpha Sets the adjustment to be made to each of the colour components per second. These values will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
setRedAdjust()
void Ogre::ColourFaderAffector::setRedAdjust (float red)
Sets the red adjustment to be made per second to particles.
Parameters
red The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
getRedAdjust()
float Ogre::ColourFaderAffector::getRedAdjust (void) const
Gets the red adjustment to be made per second to particles.
setGreenAdjust()
void Ogre::ColourFaderAffector::setGreenAdjust (float green)
Sets the green adjustment to be made per second to particles.
Parameters
green The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
getGreenAdjust()
float Ogre::ColourFaderAffector::getGreenAdjust (void) const
Gets the green adjustment to be made per second to particles.
setBlueAdjust()
void Ogre::ColourFaderAffector::setBlueAdjust (float blue)
Sets the blue adjustment to be made per second to particles.
Parameters
blue The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
getBlueAdjust()
float Ogre::ColourFaderAffector::getBlueAdjust (void) const
Gets the blue adjustment to be made per second to particles.
setAlphaAdjust()
void Ogre::ColourFaderAffector::setAlphaAdjust (float alpha)
Sets the alpha adjustment to be made per second to particles.
Parameters
alpha The adjustment to be made to the colour component per second. This value will be added to the colour of all particles every second, scaled over each frame for a smooth adjustment.
getAlphaAdjust()
float Ogre::ColourFaderAffector::getAlphaAdjust (void) const
Gets the alpha adjustment to be made per second to particles.
_initParticle()
virtual void Ogre::ParticleAffector::_initParticle (Particle * pParticle) inline virtual inherited
Method called to allow the affector to initialize all newly created particles in the system.
Remarks
This is where the affector gets the chance to initialize it's effects to the particles of a system. The affector is expected to initialize some or all of the particles in the system passed to it, depending on the affector's approach.
Parameters
pParticle Pointer to a Particle to initialize.
Reimplemented in Ogre::RotationAffector, and Ogre::ColourImageAffector.
getType()
const String& Ogre::ParticleAffector::getType (void) const inline inherited
Returns the name of the type of affector.
Remarks
This property is useful for determining the type of affector procedurally so another can be created.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
setParameter()
bool Ogre::StringInterface::setParameter (const String & name, const String & value) inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
getParameter()
String Ogre::StringInterface::getParameter (const String & name) const inline inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
copyParametersTo()
void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
msRedCmd
CmdRedAdjust Ogre::ColourFaderAffector::msRedCmd static
msGreenCmd
CmdGreenAdjust Ogre::ColourFaderAffector::msGreenCmd static
msBlueCmd
CmdBlueAdjust Ogre::ColourFaderAffector::msBlueCmd static
msAlphaCmd
CmdAlphaAdjust Ogre::ColourFaderAffector::msAlphaCmd static
The documentation for this class was generated from the following file:
OgreColourFaderAffector.h