OGRE: Ogre::DefaultHardwareBufferManagerBase Class Reference
Ogre::DefaultHardwareBufferManagerBase Class Reference
Core » RenderSystem
Specialisation of HardwareBufferManagerBase to emulate hardware buffers.
#include <OgreDefaultHardwareBufferManager.h>
Public Types
enum BufferLicenseType { BLT_MANUAL_RELEASE, BLT_AUTOMATIC_RELEASE }
Public Member Functions
DefaultHardwareBufferManagerBase ()
~DefaultHardwareBufferManagerBase ()
virtual void _forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr &sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _forceReleaseBufferCopies (HardwareVertexBuffer *sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _freeUnusedBufferCopies (void)
Free all unused vertex buffer copies.
void _notifyCounterBufferDestroyed (HardwareCounterBuffer *buf)
Notification that at hardware counter buffer has been destroyed.
void _notifyIndexBufferDestroyed (HardwareIndexBuffer *buf)
Notification that a hardware index buffer has been destroyed.
void _notifyUniformBufferDestroyed (HardwareUniformBuffer *buf)
Notification that at hardware uniform buffer has been destroyed.
void _notifyVertexBufferDestroyed (HardwareVertexBuffer *buf)
Notification that a hardware vertex buffer has been destroyed.
virtual void _releaseBufferCopies (bool forceFreeUnused=false)
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
virtual HardwareVertexBufferSharedPtr allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee *licensee, bool copyData=false)
Allocates a copy of a given vertex buffer.
HardwareCounterBufferSharedPtr createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage=HardwareBuffer::HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE, bool useShadowBuffer=false, const String &name="")
Create a hardware counter buffer.
HardwareIndexBufferSharedPtr createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Create a hardware index buffer.
RenderToVertexBufferSharedPtr createRenderToVertexBuffer ()
Create a hardware vertex buffer.
HardwareUniformBufferSharedPtr createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage=HardwareBuffer::HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE, bool useShadowBuffer=false, const String &name="")
Create a hardware uniform buffer.
HardwareVertexBufferSharedPtr createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Creates a vertex buffer.
virtual VertexBufferBinding * createVertexBufferBinding (void)
Creates a new VertexBufferBinding.
virtual VertexDeclaration * createVertexDeclaration (void)
Creates a new vertex declaration.
virtual void destroyVertexBufferBinding (VertexBufferBinding *binding)
Destroys a VertexBufferBinding.
virtual void destroyVertexDeclaration (VertexDeclaration *decl)
Destroys a vertex declaration.
virtual void registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, const HardwareVertexBufferSharedPtr &copy)
Registers a vertex buffer as a copy of another.
virtual void releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Manually release a vertex buffer copy for others to subsequently use.
virtual void touchVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Tell engine that the vertex buffer copy intent to reuse.
Detailed Description
Specialisation of HardwareBufferManagerBase to emulate hardware buffers.
Remarks
You might want to instantiate this class if you want to utilise classes like MeshSerializer without having initialised the rendering system (which is required to create a 'real' hardware buffer manager).
Member Enumeration Documentation
BufferLicenseType
enum Ogre::HardwareBufferManagerBase::BufferLicenseType inherited
Enumerator
BLT_MANUAL_RELEASE
Licensee will only release buffer when it says so.
BLT_AUTOMATIC_RELEASE
Licensee can have license revoked.
Constructor & Destructor Documentation
DefaultHardwareBufferManagerBase()
Ogre::DefaultHardwareBufferManagerBase::DefaultHardwareBufferManagerBase ()
~DefaultHardwareBufferManagerBase()
Ogre::DefaultHardwareBufferManagerBase::~DefaultHardwareBufferManagerBase ()
Member Function Documentation
createVertexBuffer()
HardwareVertexBufferSharedPtr Ogre::DefaultHardwareBufferManagerBase::createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Creates a vertex buffer.
Implements Ogre::HardwareBufferManagerBase.
createIndexBuffer()
HardwareIndexBufferSharedPtr Ogre::DefaultHardwareBufferManagerBase::createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Create a hardware index buffer.
Implements Ogre::HardwareBufferManagerBase.
createRenderToVertexBuffer()
RenderToVertexBufferSharedPtr Ogre::DefaultHardwareBufferManagerBase::createRenderToVertexBuffer () virtual
Create a hardware vertex buffer.
Implements Ogre::HardwareBufferManagerBase.
createUniformBuffer()
HardwareUniformBufferSharedPtr Ogre::DefaultHardwareBufferManagerBase::createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage = HardwareBuffer::HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE, bool useShadowBuffer = false, const String & name = "") virtual
Create a hardware uniform buffer.
Implements Ogre::HardwareBufferManagerBase.
createCounterBuffer()
HardwareCounterBufferSharedPtr Ogre::DefaultHardwareBufferManagerBase::createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage = HardwareBuffer::HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE, bool useShadowBuffer = false, const String & name = "") virtual
Create a hardware counter buffer.
Implements Ogre::HardwareBufferManagerBase.
createVertexDeclaration()
virtual VertexDeclaration* Ogre::HardwareBufferManagerBase::createVertexDeclaration (void) virtual inherited
Creates a new vertex declaration.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::createVertexDeclaration().
destroyVertexDeclaration()
virtual void Ogre::HardwareBufferManagerBase::destroyVertexDeclaration (VertexDeclaration * decl) virtual inherited
Destroys a vertex declaration.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::destroyVertexDeclaration().
createVertexBufferBinding()
virtual VertexBufferBinding* Ogre::HardwareBufferManagerBase::createVertexBufferBinding (void) virtual inherited
Creates a new VertexBufferBinding.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::createVertexBufferBinding().
destroyVertexBufferBinding()
virtual void Ogre::HardwareBufferManagerBase::destroyVertexBufferBinding (VertexBufferBinding * binding) virtual inherited
Destroys a VertexBufferBinding.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::destroyVertexBufferBinding().
registerVertexBufferSourceAndCopy()
virtual void Ogre::HardwareBufferManagerBase::registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, const HardwareVertexBufferSharedPtr & copy) virtual inherited
Registers a vertex buffer as a copy of another.
Remarks
This is useful for registering an existing buffer as a temporary buffer which can be allocated just like a copy.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::registerVertexBufferSourceAndCopy().
allocateVertexBufferCopy()
virtual HardwareVertexBufferSharedPtr Ogre::HardwareBufferManagerBase::allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee * licensee, bool copyData = false) virtual inherited
Allocates a copy of a given vertex buffer.
Remarks
This method allocates a temporary copy of an existing vertex buffer. This buffer is subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction.
Parameters
sourceBuffer The source buffer to use as a copy.
licenseType The type of license required on this buffer - automatic release causes this class to release licenses every frame so that they can be reallocated anew.
licensee Pointer back to the class requesting the copy, which must implement HardwareBufferLicense in order to be notified when the license expires.
copyData If true, the current data is copied as well as the structure of the buffer/
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::allocateVertexBufferCopy().
releaseVertexBufferCopy()
virtual void Ogre::HardwareBufferManagerBase::releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Manually release a vertex buffer copy for others to subsequently use.
Remarks
Only required if the original call to allocateVertexBufferCopy included a licenseType of BLT_MANUAL_RELEASE.
Parameters
bufferCopy The buffer copy. The caller is expected to delete or at least no longer use this reference, since another user may well begin to modify the contents of the buffer.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::releaseVertexBufferCopy().
touchVertexBufferCopy()
virtual void Ogre::HardwareBufferManagerBase::touchVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Tell engine that the vertex buffer copy intent to reuse.
Remarks
Ogre internal keep an expired delay counter of BLT_AUTOMATIC_RELEASE buffers, when the counter count down to zero, it'll release for other purposes later. But you can use this function to reset the counter to the internal configured value, keep the buffer not get released for some frames.
Parameters
bufferCopy The buffer copy. The caller is expected to keep this buffer copy for use.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::touchVertexBufferCopy().
_freeUnusedBufferCopies()
virtual void Ogre::HardwareBufferManagerBase::_freeUnusedBufferCopies (void) virtual inherited
Free all unused vertex buffer copies.
Remarks
This method free all temporary vertex buffers that not in used. In normally, temporary vertex buffers are subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction. But in some cases you want to free them to save hardware memory (e.g. application was runs in a long time, you might free temporary buffers periodically to avoid memory overload).
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_freeUnusedBufferCopies().
_releaseBufferCopies()
virtual void Ogre::HardwareBufferManagerBase::_releaseBufferCopies (bool forceFreeUnused = false) virtual inherited
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
Parameters
forceFreeUnused If true, free all unused temporary buffers. If false, auto detect and free all unused temporary buffers based on temporary buffers utilization.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_releaseBufferCopies().
_forceReleaseBufferCopies() [1/2]
virtual void Ogre::HardwareBufferManagerBase::_forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr & sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a shared pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::HardwareBufferManager.
Referenced by Ogre::HardwareBufferManager::_forceReleaseBufferCopies().
_forceReleaseBufferCopies() [2/2]
virtual void Ogre::HardwareBufferManagerBase::_forceReleaseBufferCopies (HardwareVertexBuffer * sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::HardwareBufferManager.
_notifyVertexBufferDestroyed()
void Ogre::HardwareBufferManagerBase::_notifyVertexBufferDestroyed (HardwareVertexBuffer * buf) inherited
Notification that a hardware vertex buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyVertexBufferDestroyed().
_notifyIndexBufferDestroyed()
void Ogre::HardwareBufferManagerBase::_notifyIndexBufferDestroyed (HardwareIndexBuffer * buf) inherited
Notification that a hardware index buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyIndexBufferDestroyed().
_notifyUniformBufferDestroyed()
void Ogre::HardwareBufferManagerBase::_notifyUniformBufferDestroyed (HardwareUniformBuffer * buf) inherited
Notification that at hardware uniform buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyUniformBufferDestroyed().
_notifyCounterBufferDestroyed()
void Ogre::HardwareBufferManagerBase::_notifyCounterBufferDestroyed (HardwareCounterBuffer * buf) inherited
Notification that at hardware counter buffer has been destroyed.
Referenced by Ogre::HardwareBufferManager::_notifyConterBufferDestroyed().
The documentation for this class was generated from the following file:
OgreDefaultHardwareBufferManager.h