OGRE: Ogre::SubEntity Class Reference
Ogre::SubEntity Class Reference
Core » Scene
Utility class which defines the sub-parts of an Entity.
#include <OgreSubEntity.h>
Public Types
typedef SharedPtr< RenderSystemData > RenderSystemDataPtr
Public Member Functions
bool _getBuffersMarkedForAnimation (void) const
Are buffers already marked as vertex animated?
VertexData * _getHardwareVertexAnimVertexData (void)
Advanced method to get the hardware morph vertex information.
TempBlendedBufferInfo * _getSkelAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software skeletal animation.
VertexData * _getSkelAnimVertexData (void)
Advanced method to get the temporarily blended vertex information for entities which are software skinned.
VertexData * _getSoftwareVertexAnimVertexData (void)
Advanced method to get the temporarily blended software morph vertex information.
TempBlendedBufferInfo * _getVertexAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software morph animation.
void _invalidateCameraCache ()
Invalidate the camera distance cache.
void _markBuffersUnusedForAnimation (void)
Mark all vertex data as so far unanimated.
void _markBuffersUsedForAnimation (void)
Mark all vertex data as animated.
void _restoreBuffersForUnusedAnimation (bool hardwareAnimation)
Internal method to copy original vertex data to the morph structures should there be no active animation in use.
void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Overridden from Renderable to provide some custom behaviour.
bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
size_t getIndexDataEndIndex () const
Returns the current value of the start index used for drawing.
size_t getIndexDataStartIndex () const
Returns the current value of the start index used for drawing.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
const MaterialPtr & getMaterial (void) const
Overridden - see Renderable.
const String & getMaterialName () const
Gets the name of the Material in use by this instance.
unsigned short getNumWorldTransforms (void) const
Overridden - see Renderable.
Entity * getParent (void) const
Accessor to get parent Entity.
bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void getRenderOperation (RenderOperation &op)
Overridden - see Renderable.
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
ushort getRenderQueuePriority (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
const RenderSystemDataPtr & getRenderSystemData () const
Gets RenderSystem private data.
Real getSquaredViewDepth (const Camera *cam) const
Overridden, see Renderable.
SubMesh * getSubMesh (void)
Accessor method to read mesh data.
Technique * getTechnique (void) const
Overridden - see Renderable.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
VertexData * getVertexDataForBinding (void)
Retrieve the VertexData which should be used for GPU binding.
void getWorldTransforms (Matrix4 *xform) const
Overridden - see Renderable.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool isRenderQueueGroupSet (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
bool isRenderQueuePrioritySet (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
bool isVisible (void) const
Returns whether or not this SubEntity is supposed to be visible.
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void resetIndexDataStartEndIndex ()
Reset the custom start/end index to the default values.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setIndexDataEndIndex (size_t end_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
void setIndexDataStartIndex (size_t start_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
void setMaterial (const MaterialPtr &material)
Sets the name of the Material to be used.
void setMaterialName (const String &name, const String &groupName=ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME)
Sets the name of the Material to be used.
void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this SubEntity will be rendered through.
void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
Sets the render queue group and group priority this SubEntity will be rendered through.
void setRenderSystemData (RenderSystemDataPtr val) const
Sets RenderSystem private data.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
void setUserAny (const Any &anything)
void setVisible (bool visible)
Tells this SubEntity whether to be visible or not.
Friends
class Entity
class SceneManager
Detailed Description
Utility class which defines the sub-parts of an Entity.
Remarks
Just as meshes are split into submeshes, an Entity is made up of potentially multiple SubMeshes. These are mainly here to provide the link between the Material which the SubEntity uses (which may be the default Material for the SubMesh or may have been changed for this object) and the SubMesh data.
The SubEntity also allows the application some flexibility in the material properties for this section of a particular instance of this Mesh, e.g. tinting the windows on a car model.
SubEntity instances are never created manually. They are created at the same time as their parent Entity by the SceneManager method createEntity.
Member Typedef Documentation
RenderSystemDataPtr
typedef SharedPtr<RenderSystemData> Ogre::Renderable::RenderSystemDataPtr inherited
Member Function Documentation
getMaterialName()
const String& Ogre::SubEntity::getMaterialName () const
Gets the name of the Material in use by this instance.
setMaterialName()
void Ogre::SubEntity::setMaterialName (const String & name, const String & groupName = ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME)
Sets the name of the Material to be used.
Remarks
By default a SubEntity uses the default Material that the SubMesh uses. This call can alter that so that the Material is different for this instance.
setMaterial()
void Ogre::SubEntity::setMaterial (const MaterialPtr & material)
Sets the name of the Material to be used.
Remarks
By default a SubEntity uses the default Material that the SubMesh uses. This call can alter that so that the Material is different for this instance.
setVisible()
void Ogre::SubEntity::setVisible (bool visible)
Tells this SubEntity whether to be visible or not.
isVisible()
bool Ogre::SubEntity::isVisible (void) const
Returns whether or not this SubEntity is supposed to be visible.
setRenderQueueGroup()
void Ogre::SubEntity::setRenderQueueGroup (uint8 queueID)
Sets the render queue group this SubEntity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, the SubEntity will use either the Entity's queue or it will use the default (RenderQueue::getDefaultQueueGroup).
See Entity::setRenderQueueGroup for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
setRenderQueueGroupAndPriority()
void Ogre::SubEntity::setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
Sets the render queue group and group priority this SubEntity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. Within a single render group there another type of grouping called priority which allows further control. If you do not call this method, all Entity objects default to the default queue and priority (RenderQueue::getDefaultQueueGroup, RenderQueue::getDefaultRenderablePriority).
See Entity::setRenderQueueGroupAndPriority for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
priority The priority within a group to use.
getRenderQueueGroup()
uint8 Ogre::SubEntity::getRenderQueueGroup (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
getRenderQueuePriority()
ushort Ogre::SubEntity::getRenderQueuePriority (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
isRenderQueueGroupSet()
bool Ogre::SubEntity::isRenderQueueGroupSet (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
isRenderQueuePrioritySet()
bool Ogre::SubEntity::isRenderQueuePrioritySet (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
getSubMesh()
SubMesh* Ogre::SubEntity::getSubMesh (void)
Accessor method to read mesh data.
getParent()
Entity* Ogre::SubEntity::getParent (void) const inline
Accessor to get parent Entity.
getMaterial()
const MaterialPtr& Ogre::SubEntity::getMaterial (void) const virtual
Overridden - see Renderable.
Implements Ogre::Renderable.
getTechnique()
Technique* Ogre::SubEntity::getTechnique (void) const virtual
Overridden - see Renderable.
Reimplemented from Ogre::Renderable.
getRenderOperation()
void Ogre::SubEntity::getRenderOperation (RenderOperation & op) virtual
Overridden - see Renderable.
Implements Ogre::Renderable.
setIndexDataStartIndex()
void Ogre::SubEntity::setIndexDataStartIndex (size_t start_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
Default value is zero so that the entire index buffer is used when drawing. Valid values are zero to getIndexDataEndIndex()
getIndexDataStartIndex()
size_t Ogre::SubEntity::getIndexDataStartIndex () const
Returns the current value of the start index used for drawing.
See also
setIndexDataStartIndex
setIndexDataEndIndex()
void Ogre::SubEntity::setIndexDataEndIndex (size_t end_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
Default value is SubMesh::indexData::indexCount so that the entire index buffer is used when drawing. Valid values are mStartIndex to SubMesh::indexData::indexCount
getIndexDataEndIndex()
size_t Ogre::SubEntity::getIndexDataEndIndex () const
Returns the current value of the start index used for drawing.
resetIndexDataStartEndIndex()
void Ogre::SubEntity::resetIndexDataStartEndIndex ()
Reset the custom start/end index to the default values.
getWorldTransforms()
void Ogre::SubEntity::getWorldTransforms (Matrix4 * xform) const virtual
Overridden - see Renderable.
Implements Ogre::Renderable.
getNumWorldTransforms()
unsigned short Ogre::SubEntity::getNumWorldTransforms (void) const virtual
Overridden - see Renderable.
Reimplemented from Ogre::Renderable.
getSquaredViewDepth()
Real Ogre::SubEntity::getSquaredViewDepth (const Camera * cam) const virtual
Overridden, see Renderable.
Implements Ogre::Renderable.
getLights()
const LightList& Ogre::SubEntity::getLights (void) const virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
getCastsShadows()
bool Ogre::SubEntity::getCastsShadows (void) const virtual
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented from Ogre::Renderable.
_getSkelAnimVertexData()
VertexData* Ogre::SubEntity::_getSkelAnimVertexData (void)
Advanced method to get the temporarily blended vertex information for entities which are software skinned.
Remarks
Internal engine will eliminate software animation if possible, this information is unreliable unless added request for software animation via Entity::addSoftwareAnimationRequest.
Note
The positions/normals of the returned vertex data is in object space.
_getSoftwareVertexAnimVertexData()
VertexData* Ogre::SubEntity::_getSoftwareVertexAnimVertexData (void)
Advanced method to get the temporarily blended software morph vertex information.
Remarks
Internal engine will eliminate software animation if possible, this information is unreliable unless added request for software animation via Entity::addSoftwareAnimationRequest.
Note
The positions/normals of the returned vertex data is in object space.
_getHardwareVertexAnimVertexData()
VertexData* Ogre::SubEntity::_getHardwareVertexAnimVertexData (void)
Advanced method to get the hardware morph vertex information.
Note
The positions/normals of the returned vertex data is in object space.
_getSkelAnimTempBufferInfo()
TempBlendedBufferInfo* Ogre::SubEntity::_getSkelAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software skeletal animation.
_getVertexAnimTempBufferInfo()
TempBlendedBufferInfo* Ogre::SubEntity::_getVertexAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software morph animation.
getVertexDataForBinding()
VertexData* Ogre::SubEntity::getVertexDataForBinding (void)
Retrieve the VertexData which should be used for GPU binding.
_markBuffersUnusedForAnimation()
void Ogre::SubEntity::_markBuffersUnusedForAnimation (void)
Mark all vertex data as so far unanimated.
_markBuffersUsedForAnimation()
void Ogre::SubEntity::_markBuffersUsedForAnimation (void)
Mark all vertex data as animated.
_getBuffersMarkedForAnimation()
bool Ogre::SubEntity::_getBuffersMarkedForAnimation (void) const inline
Are buffers already marked as vertex animated?
_restoreBuffersForUnusedAnimation()
void Ogre::SubEntity::_restoreBuffersForUnusedAnimation (bool hardwareAnimation)
Internal method to copy original vertex data to the morph structures should there be no active animation in use.
_updateCustomGpuParameter()
void Ogre::SubEntity::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const virtual
Overridden from Renderable to provide some custom behaviour.
Reimplemented from Ogre::Renderable.
_invalidateCameraCache()
void Ogre::SubEntity::_invalidateCameraCache () inline
Invalidate the camera distance cache.
preRender()
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::BillboardChain.
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
getCustomParameter()
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
setPolygonModeOverrideable()
void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
getPolygonModeOverrideable()
bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Referenced by Ogre::BorderRenderable::getPolygonModeOverrideable().
setUserAny()
void Ogre::Renderable::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserAny()
const Any& Ogre::Renderable::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserObjectBindings() [1/2]
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/2]
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getRenderSystemData()
const RenderSystemDataPtr& Ogre::Renderable::getRenderSystemData () const inline inherited
Gets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
setRenderSystemData()
void Ogre::Renderable::setRenderSystemData (RenderSystemDataPtr val) const inline inherited
Sets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
Friends And Related Function Documentation
Entity
friend class Entity friend
SceneManager
friend class SceneManager friend
The documentation for this class was generated from the following file:
OgreSubEntity.h