OGRE: Ogre::Lod0Stripifier Class Reference
Ogre::Lod0Stripifier Class Reference
#include <OgreLod0Stripifier.h>
Classes
struct RemapInfo
Public Member Functions
Lod0Stripifier ()
~Lod0Stripifier ()
bool StripLod0Vertices (const MeshPtr &mesh, bool stableVertexOrder=false)
Constructor & Destructor Documentation
Lod0Stripifier()
Ogre::Lod0Stripifier::Lod0Stripifier () inline
~Lod0Stripifier()
Ogre::Lod0Stripifier::~Lod0Stripifier () inline
References Ogre::Pose::addVertex(), Ogre::Pose::clearVertices(), Ogre::HardwareBufferManager::createIndexBuffer(), Ogre::HardwareBufferManager::createVertexBuffer(), Ogre::VertexAnimationTrack::getAnimationType(), Ogre::VertexBufferBinding::getBindings(), Ogre::Pose::getIncludesNormals(), Ogre::HardwareIndexBuffer::getIndexSize(), Ogre::Pose::getNormals(), Ogre::AnimationTrack::getNumKeyFrames(), Ogre::Mesh::getNumLodLevels(), Ogre::Mesh::getNumSubMeshes(), Ogre::HardwareVertexBuffer::getNumVertices(), Ogre::HardwareBufferManager::getSingleton(), Ogre::Mesh::getSubMesh(), Ogre::HardwareIndexBuffer::getType(), Ogre::HardwareBuffer::getUsage(), Ogre::VertexMorphKeyFrame::getVertexBuffer(), Ogre::VertexAnimationTrack::getVertexMorphKeyFrame(), Ogre::Pose::getVertexOffsets(), Ogre::HardwareVertexBuffer::getVertexSize(), Ogre::VertexData::hardwareShadowVolWBuffer, Ogre::HardwareBuffer::hasShadowBuffer(), Ogre::HardwareBuffer::HBL_DISCARD, Ogre::HardwareBuffer::HBL_READ_ONLY, Ogre::VertexData::hwAnimationDataList, Ogre::VertexData::hwAnimDataItemsUsed, Ogre::IndexData::indexBuffer, Ogre::IndexData::indexCount, Ogre::Lod0Stripifier::RemapInfo::indexMap, Ogre::IndexData::indexStart, Ogre::HardwareIndexBuffer::IT_16BIT, Ogre::HardwareIndexBuffer::IT_32BIT, Ogre::HardwareBuffer::lock(), Ogre::Lod0Stripifier::RemapInfo::markUsedIndices(), Ogre::Lod0Stripifier::RemapInfo::minimalIndexType(), Ogre::SubMesh::mLodFaceList, Ogre::Lod0Stripifier::RemapInfo::nothingToStrip(), Ogre::VertexBufferBinding::setBinding(), Ogre::VertexMorphKeyFrame::setVertexBuffer(), Ogre::Mesh::sharedVertexData, Ogre::HardwareBuffer::unlock(), Ogre::Lod0Stripifier::RemapInfo::UnusedIdx, Ogre::Lod0Stripifier::RemapInfo::usedCount, Ogre::SubMesh::useSharedVertices, Ogre::VAT_MORPH, Ogre::VertexData::vertexBufferBinding, Ogre::VertexData::vertexCount, Ogre::SubMesh::vertexData, Ogre::VertexBoneAssignment_s::vertexIndex, and Ogre::VertexData::vertexStart.
Member Function Documentation
StripLod0Vertices()
bool Ogre::Lod0Stripifier::StripLod0Vertices (const MeshPtr & mesh, bool stableVertexOrder = false) inline
References Ogre::Mesh::_setLodInfo(), Ogre::Mesh::_setLodUsage(), Ogre::Mesh::buildEdgeList(), Ogre::Mesh::freeEdgeList(), Ogre::SharedPtr< T >::get(), Ogre::Mesh::getAnimation(), Ogre::AnimationTrack::getHandle(), Ogre::Mesh::getLodLevel(), Ogre::MapIteratorWrapper< T, IteratorType >::getNext(), Ogre::Mesh::getNumAnimations(), Ogre::Mesh::getNumLodLevels(), Ogre::Mesh::getNumSubMeshes(), Ogre::Mesh::getPoseList(), Ogre::Mesh::getSubMesh(), Ogre::Pose::getTarget(), Ogre::Animation::getVertexTrackIterator(), Ogre::Mesh::hasManualLodLevel(), Ogre::IteratorWrapper< T, IteratorType, ValType >::hasMoreElements(), Ogre::SubMesh::indexData, Ogre::Mesh::isEdgeListBuilt(), Ogre::SubMesh::mLodFaceList, OGRE_DELETE, Ogre::Mesh::sharedVertexData, Ogre::SubMesh::useSharedVertices, and Ogre::SubMesh::vertexData.
The documentation for this class was generated from the following file:
OgreLod0Stripifier.h