OGRE: Ogre::GLArbGpuProgram Class Reference
Ogre::GLArbGpuProgram Class Reference
Specialisation of the GL low-level program for ARB programs.
#include <OgreGLGpuProgram.h>
Public Types
enum LoadingFlags {
LF_DEFAULT = 0, LF_INCLUDE_NON_RELOADABLE = 1, LF_ONLY_UNREFERENCED = 2, LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE = 3,
LF_PRESERVE_STATE = 4
}
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
Public Member Functions
GLArbGpuProgram (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual=false, ManualResourceLoader *loader=0)
virtual ~GLArbGpuProgram ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
void _fireUnloadingComplete (void)
Firing of unloading complete event.
virtual GpuProgram * _getBindingDelegate (void)
Returns the GpuProgram which should be bound to the pipeline.
void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
void bindProgram (void)
Execute the binding functions for this program.
void bindProgramParameters (GpuProgramParametersSharedPtr params, uint16 mask)
Execute the param binding functions for this program.
void bindProgramPassIterationParameters (GpuProgramParametersSharedPtr params)
Bind just the pass iteration parameters.
virtual size_t calculateSize (void) const
Calculate the size of a resource; this will only be called after 'load'.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual GpuProgramParametersSharedPtr createParameters (void)
Creates a new parameters object compatible with this program definition.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
virtual Vector3 getComputeGroupDimensions (void) const
Returns the number of process groups dispatched by this compute program.
virtual const GpuNamedConstants & getConstantDefinitions () const
Get the full list of named constants.
ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr getDefaultParameters (void)
Get a reference to the default parameters which are to be used for all uses of this program.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual const String & getLanguage (void) const
Returns a string that specifies the language of the gpu programs as specified in a material script.
virtual LoadingState getLoadingState () const
Returns the current loading state.
const String & getManualNamedConstantsFile () const
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual const String & getName (void) const
Gets resource name.
virtual ushort getNumberOfPosesIncluded (void) const
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual bool getPassFogStates (void) const
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
virtual bool getPassSurfaceAndLightStates (void) const
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
virtual bool getPassTransformStates (void) const
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
GLenum getProgramType (void) const
Get the GL type for the program.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
const String & getSource (void) const
Gets the assembler source for this program.
const String & getSourceFile (void) const
Gets the name of the file used as source for this program.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
const String & getSyntaxCode (void) const
Gets the syntax code for this program e.g.
GpuProgramType getType (void) const
Get the program type.
virtual bool hasCompileError (void) const
Did this program encounter a compile error when loading?
virtual bool hasDefaultParameters (void) const
Returns true if default parameters have been set up.
virtual bool isAdjacencyInfoRequired (void) const
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool isAttributeValid (VertexElementSemantic semantic, uint index)
Test whether attribute index for a given semantic is valid.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isMorphAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform morph animation.
virtual bool isPoseAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform pose animation.
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual bool isSkeletalAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform skeletal animation.
virtual bool isSupported (void) const
Returns whether this program can be supported on the current renderer and hardware.
virtual bool isVertexTextureFetchRequired (void) const
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (LoadingFlags flags=LF_DEFAULT)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void resetCompileError (void)
Reset a compile error if it occurred, allowing the load to be retried.
virtual void setAdjacencyInfoRequired (bool r)
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
virtual void setComputeGroupDimensions (Vector3 dimensions)
Sets the number of process groups dispatched by this compute program.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
void setManualNamedConstants (const GpuNamedConstants &namedConstants)
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
void setManualNamedConstantsFile (const String &paramDefFile)
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual void setMorphAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform morph animation.
bool setParameter (const String &name, const String &value)
Generic parameter setting method.
void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPoseAnimationIncluded (ushort poseCount)
Sets whether a vertex program includes the required instructions to perform pose animation.
virtual void setSkeletalAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform skeletal animation.
void setSource (const String &source)
Sets the source assembly for this program from an in-memory string.
void setSourceFile (const String &filename)
Sets the filename of the source assembly for this program.
void setSyntaxCode (const String &syntax)
Sets the syntax code for this program e.g.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
void setType (GpuProgramType t)
Set the program type (only valid before load)
virtual void setVertexTextureFetchRequired (bool r)
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
void unbindProgram (void)
Execute the unbinding functions for this program.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
static const String getProgramTypeName (GpuProgramType programType)
Public Attributes
OGRE_AUTO_MUTEX
Detailed Description
Specialisation of the GL low-level program for ARB programs.
Member Enumeration Documentation
LoadingState
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
LoadingFlags
enum Ogre::Resource::LoadingFlags inherited
Enum that allow to choose subset of unloaded/reloaded resources and to adjust reloading behavior.
Enumerator
LF_DEFAULT
Only reloadable resources are processed, reload restores initial state.
LF_INCLUDE_NON_RELOADABLE
Process non-reloadable resources too.
LF_ONLY_UNREFERENCED
Process only resources which are not referenced by any other object. Usefull to reduce resource consumption.
LF_ONLY_UNREFERENCED_INCLUDE_NON_RELOADABLE
Combination of LF_ONLY_UNREFERENCED and LF_INCLUDE_NON_RELOADABLE.
LF_PRESERVE_STATE
Preserve some states during reloading, for example stencil shadows prepareness for Meshes.
Constructor & Destructor Documentation
GLArbGpuProgram()
Ogre::GLArbGpuProgram::GLArbGpuProgram (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual = false, ManualResourceLoader * loader = 0)
~GLArbGpuProgram()
virtual Ogre::GLArbGpuProgram::~GLArbGpuProgram () virtual
Member Function Documentation
bindProgram()
void Ogre::GLArbGpuProgram::bindProgram (void) virtual
Execute the binding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
unbindProgram()
void Ogre::GLArbGpuProgram::unbindProgram (void) virtual
Execute the unbinding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
bindProgramParameters()
void Ogre::GLArbGpuProgram::bindProgramParameters (GpuProgramParametersSharedPtr params, uint16 mask) virtual
Execute the param binding functions for this program.
Reimplemented from Ogre::GLGpuProgram.
bindProgramPassIterationParameters()
void Ogre::GLArbGpuProgram::bindProgramPassIterationParameters (GpuProgramParametersSharedPtr params) virtual
Bind just the pass iteration parameters.
Reimplemented from Ogre::GLGpuProgram.
getProgramType()
GLenum Ogre::GLArbGpuProgram::getProgramType (void) const
Get the GL type for the program.
calculateSize()
virtual size_t Ogre::GLGpuProgram::calculateSize (void) const virtual inherited
Calculate the size of a resource; this will only be called after 'load'.
Reimplemented from Ogre::GpuProgram.
isAttributeValid()
virtual bool Ogre::GLGpuProgram::isAttributeValid (VertexElementSemantic semantic, uint index) virtual inherited
Test whether attribute index for a given semantic is valid.
Reimplemented in Ogre::GLSL::GLSLGpuProgram.
getProgramTypeName()
static const String Ogre::GpuProgram::getProgramTypeName (GpuProgramType programType) static inherited
setSourceFile()
void Ogre::GpuProgram::setSourceFile (const String & filename) inherited
Sets the filename of the source assembly for this program.
Remarks
Setting this will have no effect until you (re)load the program.
setSource()
void Ogre::GpuProgram::setSource (const String & source) inherited
Sets the source assembly for this program from an in-memory string.
Remarks
Setting this will have no effect until you (re)load the program.
getSyntaxCode()
const String& Ogre::GpuProgram::getSyntaxCode (void) const inline inherited
Gets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
setSyntaxCode()
void Ogre::GpuProgram::setSyntaxCode (const String & syntax) inherited
Sets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
getSourceFile()
const String& Ogre::GpuProgram::getSourceFile (void) const inline inherited
Gets the name of the file used as source for this program.
getSource()
const String& Ogre::GpuProgram::getSource (void) const inline inherited
Gets the assembler source for this program.
setType()
void Ogre::GpuProgram::setType (GpuProgramType t) inherited
Set the program type (only valid before load)
getType()
GpuProgramType Ogre::GpuProgram::getType (void) const inline inherited
Get the program type.
_getBindingDelegate()
virtual GpuProgram* Ogre::GpuProgram::_getBindingDelegate (void) inline virtual inherited
Returns the GpuProgram which should be bound to the pipeline.
Remarks
This method is simply to allow some subclasses of GpuProgram to delegate the program which is bound to the pipeline to a delegate, if required.
Reimplemented in Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, Ogre::HighLevelGpuProgram, Ogre::GLSLShader, and Ogre::GLSLESProgram.
isSupported()
virtual bool Ogre::GpuProgram::isSupported (void) const virtual inherited
Returns whether this program can be supported on the current renderer and hardware.
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
createParameters()
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::createParameters (void) virtual inherited
Creates a new parameters object compatible with this program definition.
Remarks
It is recommended that you use this method of creating parameters objects rather than going direct to GpuProgramManager, because this method will populate any implementation-specific extras (like named parameters) where they are appropriate.
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, Ogre::HighLevelGpuProgram, Ogre::GLSLESProgram, and Ogre::GLSLShader.
setSkeletalAnimationIncluded()
virtual void Ogre::GpuProgram::setSkeletalAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
isSkeletalAnimationIncluded()
virtual bool Ogre::GpuProgram::isSkeletalAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this returns true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
setMorphAnimationIncluded()
virtual void Ogre::GpuProgram::setMorphAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
setPoseAnimationIncluded()
virtual void Ogre::GpuProgram::setPoseAnimationIncluded (ushort poseCount) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Parameters
poseCount The number of simultaneous poses the program can blend
isMorphAnimationIncluded()
virtual bool Ogre::GpuProgram::isMorphAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this returns true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
isPoseAnimationIncluded()
virtual bool Ogre::GpuProgram::isPoseAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this returns true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
getNumberOfPosesIncluded()
virtual ushort Ogre::GpuProgram::getNumberOfPosesIncluded (void) const inline virtual inherited
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setVertexTextureFetchRequired()
virtual void Ogre::GpuProgram::setVertexTextureFetchRequired (bool r) inline virtual inherited
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
isVertexTextureFetchRequired()
virtual bool Ogre::GpuProgram::isVertexTextureFetchRequired (void) const inline virtual inherited
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
setAdjacencyInfoRequired()
virtual void Ogre::GpuProgram::setAdjacencyInfoRequired (bool r) inline virtual inherited
Sets whether this geometry program requires adjacency information from the input primitives.
isAdjacencyInfoRequired()
virtual bool Ogre::GpuProgram::isAdjacencyInfoRequired (void) const inline virtual inherited
Returns whether this geometry program requires adjacency information from the input primitives.
setComputeGroupDimensions()
virtual void Ogre::GpuProgram::setComputeGroupDimensions (Vector3 dimensions) inline virtual inherited
Sets the number of process groups dispatched by this compute program.
getComputeGroupDimensions()
virtual Vector3 Ogre::GpuProgram::getComputeGroupDimensions (void) const inline virtual inherited
Returns the number of process groups dispatched by this compute program.
getDefaultParameters()
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::getDefaultParameters (void) virtual inherited
Get a reference to the default parameters which are to be used for all uses of this program.
Remarks
A program can be set up with a list of default parameters, which can save time when using a program many times in a material with roughly the same settings. By retrieving the default parameters and populating it with the most used options, any new parameter objects created from this program afterwards will automatically include the default parameters; thus users of the program need only change the parameters which are unique to their own usage of the program.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
hasDefaultParameters()
virtual bool Ogre::GpuProgram::hasDefaultParameters (void) const inline virtual inherited
Returns true if default parameters have been set up.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
References Ogre::SharedPtr< T >::get().
getPassSurfaceAndLightStates()
virtual bool Ogre::GpuProgram::getPassSurfaceAndLightStates (void) const inline virtual inherited
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
Remarks
Most vertex programs do not need this material information, however GLSL shaders can refer to this material and lighting state so enable this option
Reimplemented in Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLShaderCommon.
getPassFogStates()
virtual bool Ogre::GpuProgram::getPassFogStates (void) const inline virtual inherited
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
Remarks
On DirectX, shader model 2 and earlier continues to have fixed-function fog applied to it, so fog state is still passed (you should disable fog on the pass if you want to perform fog in the shader). In OpenGL it is also common to be able to access the fixed-function fog state inside the shader.
Reimplemented in Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLShaderCommon.
getPassTransformStates()
virtual bool Ogre::GpuProgram::getPassTransformStates (void) const inline virtual inherited
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
Remarks
Most vertex programs do not need fixed-function transform information, however GLSL shaders can refer to this state so enable this option
Reimplemented in Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLShaderCommon.
getLanguage()
virtual const String& Ogre::GpuProgram::getLanguage (void) const virtual inherited
Returns a string that specifies the language of the gpu programs as specified in a material script.
ie: asm, cg, hlsl, glsl
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::CgProgram, Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLESProgram, Ogre::GLSLShader, Ogre::GLSL::GLSLProgram, and Ogre::GLSLESCgProgram.
hasCompileError()
virtual bool Ogre::GpuProgram::hasCompileError (void) const inline virtual inherited
Did this program encounter a compile error when loading?
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
resetCompileError()
virtual void Ogre::GpuProgram::resetCompileError (void) inline virtual inherited
Reset a compile error if it occurred, allowing the load to be retried.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
setManualNamedConstants()
void Ogre::GpuProgram::setManualNamedConstants (const GpuNamedConstants & namedConstants) inherited
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source.
See also
setManualNamedConstantsFile
setManualNamedConstantsFile()
void Ogre::GpuProgram::setManualNamedConstantsFile (const String & paramDefFile) inherited
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source. This method will make a low-level program search in the resource group of the program for the named file from which to load parameter names from. The file must be in the format produced by GpuNamedConstants::save.
getManualNamedConstantsFile()
const String& Ogre::GpuProgram::getManualNamedConstantsFile () const inline inherited
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
getConstantDefinitions()
virtual const GpuNamedConstants& Ogre::GpuProgram::getConstantDefinitions () const inline virtual inherited
Get the full list of named constants.
Note
Only available if this parameters object has named parameters, which means either a high-level program which loads them, or a low-level program which has them specified manually.
Reimplemented in Ogre::HighLevelGpuProgram.
References Ogre::SharedPtr< T >::get().
prepare()
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
load()
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
reload()
virtual void Ogre::Resource::reload (LoadingFlags flags = LF_DEFAULT) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::Mesh, and Ogre::UnifiedHighLevelGpuProgram.
isReloadable()
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isManuallyLoaded()
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
setManuallyLoaded()
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
Deprecated:
do not use
unload()
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getSize()
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
touch()
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, Ogre::CgProgram, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
getName()
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::SkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName(), and OgreBites::TrayManager::resourceLoadStarted().
getHandle()
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::SkeletonInstance.
isPrepared()
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::load().
isLoaded()
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
setToLoaded()
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
Deprecated:
do not use
References Ogre::AtomicScalar< T >::store().
isLoading()
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
getLoadingState()
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::load().
isBackgroundLoaded()
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setBackgroundLoaded()
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
See also
Resource::isBackgroundLoaded. Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
escalateLoading()
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
addListener()
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
removeListener()
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getGroup()
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::SkeletonInstance.
changeGroupOwnership()
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
getCreator()
ResourceManager* Ogre::Resource::getCreator (void) inline inherited
Gets the manager which created this resource.
getOrigin()
const String& Ogre::Resource::getOrigin (void) const inline inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
_notifyOrigin()
void Ogre::Resource::_notifyOrigin (const String & origin) inline inherited
Notify this resource of it's origin.
getStateCount()
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
_dirtyState()
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
_fireLoadingComplete()
void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_firePreparingComplete()
void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_fireUnloadingComplete()
void Ogre::Resource::_fireUnloadingComplete (void) inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
setParameter()
bool Ogre::StringInterface::setParameter (const String & name, const String & value) inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
getParameter()
String Ogre::StringInterface::getParameter (const String & name) const inline inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
copyParametersTo()
void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
OGRE_AUTO_MUTEX
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreGLGpuProgram.h