OGRE: Ogre::D3D11HardwareUniformBuffer Class Reference
Ogre::D3D11HardwareUniformBuffer Class Reference
Specialisation of HardwareBuffer for D3D11.
#include <OgreD3D11HardwareUniformBuffer.h>
Public Types
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum UploadOptions { HBU_DEFAULT = 0x0000, HBU_ON_DEMAND = 0x0001 }
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = HBU_STATIC | HBU_WRITE_ONLY, HBU_DYNAMIC_WRITE_ONLY = HBU_DYNAMIC | HBU_WRITE_ONLY, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = HBU_DYNAMIC_WRITE_ONLY | HBU_DISCARDABLE
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
D3D11HardwareUniformBuffer (HardwareBufferManagerBase *mgr, size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String &name, D3D11Device &device)
~D3D11HardwareUniformBuffer ()
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
ID3D11Buffer * getD3DConstantBuffer (void) const
Get the D3D-specific vertex buffer.
HardwareBufferManagerBase * getManager () const
Return the manager of this buffer, if any.
const String & getName () const
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
void * lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the buffer for (potentially) reading / writing.
void * lock (LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
void readData (size_t offset, size_t length, void *pDest)
Reads data from the buffer and places it in the memory pointed to by pDest.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
void unlock (void)
Releases the lock on this buffer.
void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Detailed Description
Specialisation of HardwareBuffer for D3D11.
Member Enumeration Documentation
Usage
enum Ogre::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
This is the least optimal buffer setting.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
However, you may read from it’s shadow buffer if you set one up
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY This is the optimal buffer usage setting.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE This means that you expect to replace the entire contents of the buffer on an extremely regular basis, most likely every frame.
By selecting this option, you free the system up from having to be concerned about losing the existing contents of the buffer at any time, because if it does lose them, you will be replacing them next frame anyway. On some platforms this can make a significant performance difference, so you should try to use this whenever you have a buffer you need to update regularly. Note that if you create a buffer this way, you should use the HBL_DISCARD flag when locking the contents of it for writing.
LockOptions
enum Ogre::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
This kind of lock allows reading and writing from the buffer - it’s also the least optimal because basically you’re telling the card you could be doing anything at all. If you’re not using a shadow buffer, it requires the buffer to be transferred from the card and back again. If you’re using a shadow buffer the effect is minimal.
HBL_DISCARD
Discards the entire buffer while locking.
This means you are happy for the card to discard the entire current contents of the buffer. Implicitly this means you are not going to read the data - it also means that the card can avoid any stalls if the buffer is currently being rendered from, because it will actually give you an entirely different one. Use this wherever possible when you are locking a buffer which was not created with a shadow buffer. If you are using a shadow buffer it matters less, although with a shadow buffer it’s preferable to lock the entire buffer at once, because that allows the shadow buffer to use HBL_DISCARD when it uploads the updated contents to the real buffer. Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
This is only useful on buffers with no shadow buffer.
HBL_WRITE_ONLY
Lock the buffer for writing only.
UploadOptions
enum Ogre::HardwareBuffer::UploadOptions inherited
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
Deprecated:
do not use
Enumerator
HBU_DEFAULT
HBU_ON_DEMAND
Constructor & Destructor Documentation
D3D11HardwareUniformBuffer()
Ogre::D3D11HardwareUniformBuffer::D3D11HardwareUniformBuffer (HardwareBufferManagerBase * mgr, size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String & name, D3D11Device & device)
~D3D11HardwareUniformBuffer()
Ogre::D3D11HardwareUniformBuffer::~D3D11HardwareUniformBuffer ()
Member Function Documentation
lock() [1/2]
void* Ogre::D3D11HardwareUniformBuffer::lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) virtual
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
uploadOpt
Returns
Pointer to the locked memory
Reimplemented from Ogre::HardwareBuffer.
unlock()
void Ogre::D3D11HardwareUniformBuffer::unlock (void) virtual
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented from Ogre::HardwareBuffer.
readData()
void Ogre::D3D11HardwareUniformBuffer::readData (size_t offset, size_t length, void * pDest) virtual
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implements Ogre::HardwareBuffer.
writeData()
void Ogre::D3D11HardwareUniformBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implements Ogre::HardwareBuffer.
copyData() [1/2]
void Ogre::D3D11HardwareUniformBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) virtual
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented from Ogre::HardwareBuffer.
isLocked()
bool Ogre::D3D11HardwareUniformBuffer::isLocked (void) const
getD3DConstantBuffer()
ID3D11Buffer* Ogre::D3D11HardwareUniformBuffer::getD3DConstantBuffer (void) const
Get the D3D-specific vertex buffer.
lock() [2/2]
void* Ogre::HardwareBuffer::lock (LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) inline inherited
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
copyData() [2/2]
virtual void Ogre::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References Ogre::HardwareBuffer::getSizeInBytes().
_updateFromShadow()
virtual void Ogre::HardwareBuffer::_updateFromShadow (void) inline virtual inherited
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::D3D11HardwareBuffer, Ogre::GLES2HardwareVertexBuffer, Ogre::GLES2HardwareIndexBuffer, Ogre::GL3PlusHardwareVertexBuffer, Ogre::GL3PlusHardwareIndexBuffer, Ogre::GLHardwareVertexBuffer, and Ogre::GLHardwareIndexBuffer.
getSizeInBytes()
size_t Ogre::HardwareBuffer::getSizeInBytes (void) const inline inherited
Returns the size of this buffer in bytes.
Referenced by Ogre::HardwareBuffer::copyData().
getUsage()
Usage Ogre::HardwareBuffer::getUsage (void) const inline inherited
Returns the Usage flags with which this buffer was created.
Referenced by Ogre::Lod0Stripifier::~Lod0Stripifier().
isSystemMemory()
bool Ogre::HardwareBuffer::isSystemMemory (void) const inline inherited
Returns whether this buffer is held in system memory.
hasShadowBuffer()
bool Ogre::HardwareBuffer::hasShadowBuffer (void) const inline inherited
Returns whether this buffer has a system memory shadow for quicker reading.
Referenced by Ogre::Lod0Stripifier::~Lod0Stripifier().
suppressHardwareUpdate()
void Ogre::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline inherited
Pass true to suppress hardware upload of shadow buffer changes.
The documentation for this class was generated from the following file:
OgreD3D11HardwareUniformBuffer.h