OGRE: Ogre::BillboardChain Class Reference
Ogre::BillboardChain Class Reference
Core » Effects
Allows the rendering of a chain of connected billboards.
#include <OgreBillboardChain.h>
Classes
class Element
Contains the data of an element of the BillboardChain.
Public Types
typedef vector< Element >::type ElementList
typedef SharedPtr< RenderSystemData > RenderSystemDataPtr
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
enum TexCoordDirection { TCD_U, TCD_V }
The direction in which texture coordinates from elements of the chain are used.
Public Member Functions
BillboardChain (const String &name, size_t maxElements=20, size_t numberOfChains=1, bool useTextureCoords=true, bool useColours=true, bool dynamic=true)
Constructor (don't use directly, use factory)
virtual ~BillboardChain ()
Destructor.
MovableObjectFactory * _getCreator (void) const
Get the creator of this object, if any (internal use only)
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager (void) const
Get the manager of this object, if any (internal use only)
virtual const Matrix4 & _getParentNodeFullTransform (void) const
Return the full transformation of the parent sceneNode or the attachingPoint node.
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
Internal method called to notify the object that it has been attached to a node.
virtual void _notifyCreator (MovableObjectFactory *fact)
Notify the object of it's creator (internal use only)
virtual void _notifyCurrentCamera (Camera *cam)
Internal method to notify the object of the camera to be used for the next rendering operation.
virtual void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyMoved (void)
Internal method called to notify the object that it has been moved.
virtual void _releaseManualHardwareResources ()
Notifies the movable object that hardware resources were lost.
virtual void _restoreManualHardwareResources ()
Notifies the movable object that hardware resources should be restored.
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
void _updateRenderQueue (RenderQueue *)
Internal method by which the movable object must add Renderable subclass instances to the rendering queue.
virtual void addChainElement (size_t chainIndex, const Element &billboardChainElement)
Add an element to the 'head' of a chain.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
virtual void clearAllChains (void)
Remove all elements from all chains (but leave the chains themselves intact).
virtual void clearChain (size_t chainIndex)
Remove all elements of a given chain (but leave the chain intact).
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
void detachFromParent (void)
Detaches an object from a parent SceneNode or TagPoint, if attached.
const StringVector & getAnimableValueNames (void) const
Gets a list of animable value names for this object.
const AxisAlignedBox & getBoundingBox (void) const
Retrieves the local axis-aligned bounding box for this object.
Real getBoundingRadius (void) const
Retrieves the radius of the origin-centered bounding sphere for this object.
bool getCastShadows (void) const
Returns whether shadow casting is enabled for this object.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
virtual const Element & getChainElement (size_t chainIndex, size_t elementIndex) const
Get the detail of a chain element.
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
Overridden member from ShadowCaster.
virtual bool getDynamic (void) const
Gets whether or not the buffers created for this object are suitable for dynamic alteration.
EdgeData * getEdgeList (void)
Returns details of the edges which might be used to determine a silhouette.
const AxisAlignedBox & getLightCapBounds (void) const
Overridden member from ShadowCaster.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
Listener * getListener (void) const
Gets the current listener for this object.
const MaterialPtr & getMaterial (void) const
Retrieves a weak reference to the material this renderable object uses.
virtual const String & getMaterialName (void) const
Get the material name in use.
virtual size_t getMaxChainElements (void) const
Get the maximum number of chain elements per chain.
const String & getMovableType (void) const
Returns the type name of this object.
const String & getName (void) const
Returns the name of this object.
virtual size_t getNumberOfChains (void) const
Get the number of chain segments (this class can render multiple chains at once using the same material).
virtual size_t getNumChainElements (size_t chainIndex) const
Returns the number of chain elements.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
virtual const Real * getOtherTextureCoordRange (void) const
Get the range of the texture coordinates generated across the width of the chain elements.
Node * getParentNode (void) const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode (void) const
Returns the scene node to which this object is attached.
Real getPointExtrusionDistance (const Light *l) const
Get the distance to extrude for a point/spot light.
bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
uint32 getQueryFlags (void) const
Returns the query flags relevant for this object.
bool getReceivesShadows ()
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
Real getRenderingDistance (void) const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
void getRenderOperation (RenderOperation &)
Gets the render operation required to send this object to the frame buffer.
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity.
const RenderSystemDataPtr & getRenderSystemData () const
Gets RenderSystem private data.
ShadowRenderableListIterator getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light *light, HardwareIndexBufferSharedPtr *indexBuffer, size_t *indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags=0)
Define a default implementation of method from ShadowCaster which implements no shadows.
Real getSquaredViewDepth (const Camera *cam) const
Returns the camera-relative squared depth of this renderable.
virtual Technique * getTechnique (void) const
Retrieves a pointer to the Material Technique this renderable object uses.
virtual TexCoordDirection getTextureCoordDirection (void)
Gets the direction in which texture coords specified on each element are deemed to run.
virtual uint32 getTypeFlags (void) const
Get the 'type flags' for this MovableObject.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
const Any & getUserAny (void) const
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
virtual bool getUseTextureCoords (void) const
Gets whether texture coordinate information should be included in the final buffers generated.
virtual bool getUseVertexColours (void) const
Gets whether vertex colour information should be included in the final buffers generated.
uint32 getVisibilityFlags (void) const
Returns the visibility flags relevant for this object.
bool getVisible (void) const
Gets this object whether to be visible or not, if it has a renderable component.
virtual const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const
Retrieves the axis-aligned bounding box for this object in world coordinates.
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
Retrieves the worldspace bounding sphere for this object.
void getWorldTransforms (Matrix4 *) const
Gets the world transform matrix / matrices for this renderable object.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasEdgeList (void)
Returns whether the object has a valid edge list.
bool isAttached (void) const
Returns true if this object is attached to a SceneNode or TagPoint.
bool isDebugDisplayEnabled (void) const
Gets whether debug display of this object is enabled.
virtual bool isInScene (void) const
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
bool isParentTagPoint () const
Gets whether the parent node is a TagPoint (or a SceneNode)
virtual bool isVisible (void) const
Returns whether or not this object is supposed to be visible or not.
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
const LightList & queryLights (void) const
Gets a list of lights, ordered relative to how close they are to this movable object.
virtual void removeChainElement (size_t chainIndex)
Remove an element from the 'tail' of a chain.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDebugDisplayEnabled (bool enabled)
Sets whether or not the debug display of this object is enabled.
virtual void setDynamic (bool dyn)
Sets whether or not the buffers created for this object are suitable for dynamic alteration.
void setFaceCamera (bool faceCamera, const Vector3 &normalVector=Vector3::UNIT_X)
Sets whether the billboard should always be facing the camera or a custom direction set by each point element.
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
virtual void setMaterialName (const String &name, const String &groupName=ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME)
Set the material name to use for rendering.
virtual void setMaxChainElements (size_t maxElements)
Set the maximum number of chain elements per chain.
virtual void setNumberOfChains (size_t numChains)
Set the number of chain segments (this class can render multiple chains at once using the same material).
virtual void setOtherTextureCoordRange (Real start, Real end)
Set the range of the texture coordinates generated across the width of the chain elements.
void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
Sets the render queue group and group priority this entity will be rendered through.
void setRenderSystemData (RenderSystemDataPtr val) const
Sets RenderSystem private data.
virtual void setTextureCoordDirection (TexCoordDirection dir)
Sets the direction in which texture coords specified on each element are deemed to run along the length of the chain.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
void setUserAny (const Any &anything)
void setUserAny (const Any &anything)
virtual void setUseTextureCoords (bool use)
Sets whether texture coordinate information should be included in the final buffers generated.
virtual void setUseVertexColours (bool use)
Sets whether vertex colour information should be included in the final buffers generated.
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
virtual void updateChainElement (size_t chainIndex, size_t elementIndex, const Element &billboardChainElement)
Update the details of an existing chain element.
void visitRenderables (Renderable::Visitor *visitor, bool debugRenderables=false)
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Static Public Member Functions
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
Common implementation of releasing shadow renderables.
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Utility method for extruding vertices based on a light.
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
Detailed Description
Allows the rendering of a chain of connected billboards.
Remarks
A billboard chain operates much like a traditional billboard, i.e. its segments always face the camera; the difference being that instead of a set of disconnected quads, the elements in this class are connected together in a chain which must always stay in a continuous strip. This kind of effect is useful for creating effects such as trails, beams, lightning effects, etc.
A single instance of this class can actually render multiple separate chain segments in a single render operation, provided they all use the same material. To clarify the terminology: a 'segment' is a separate sub-part of the chain with its own start and end (called the 'head' and the 'tail'). An 'element' is a single position / colour / texcoord entry in a segment. You can add items to the head of a chain, and remove them from the tail, very efficiently. Each segment has a max size, and if adding an element to the segment would exceed this size, the tail element is automatically removed and re-used as the new item on the head.
This class has no auto-updating features to do things like alter the colour of the elements or to automatically add / remove elements over time - you have to do all this yourself as a user of the class. Subclasses can however be used to provide this kind of behaviour automatically.
See also
RibbonTrail
Member Typedef Documentation
ElementList
typedef vector<Element>::type Ogre::BillboardChain::ElementList
ShadowRenderableList
typedef vector<ShadowRenderable*>::type Ogre::ShadowCaster::ShadowRenderableList inherited
ShadowRenderableListIterator
typedef VectorIterator<ShadowRenderableList> Ogre::ShadowCaster::ShadowRenderableListIterator inherited
RenderSystemDataPtr
typedef SharedPtr<RenderSystemData> Ogre::Renderable::RenderSystemDataPtr inherited
Member Enumeration Documentation
TexCoordDirection
enum Ogre::BillboardChain::TexCoordDirection
The direction in which texture coordinates from elements of the chain are used.
Enumerator
TCD_U
Tex coord in elements is treated as the 'u' texture coordinate.
TCD_V
Tex coord in elements is treated as the 'v' texture coordinate.
Constructor & Destructor Documentation
BillboardChain()
Ogre::BillboardChain::BillboardChain (const String & name, size_t maxElements = 20, size_t numberOfChains = 1, bool useTextureCoords = true, bool useColours = true, bool dynamic = true)
Constructor (don't use directly, use factory)
Parameters
name The name to give this object
maxElements The maximum number of elements per chain
numberOfChains The number of separate chain segments contained in this object
useTextureCoords If true, use texture coordinates from the chain elements
useColours If true, use vertex colours from the chain elements
dynamic If true, buffers are created with the intention of being updated
~BillboardChain()
virtual Ogre::BillboardChain::~BillboardChain () virtual
Destructor.
Member Function Documentation
setMaxChainElements()
virtual void Ogre::BillboardChain::setMaxChainElements (size_t maxElements) virtual
Set the maximum number of chain elements per chain.
Reimplemented in Ogre::RibbonTrail.
getMaxChainElements()
virtual size_t Ogre::BillboardChain::getMaxChainElements (void) const inline virtual
Get the maximum number of chain elements per chain.
setNumberOfChains()
virtual void Ogre::BillboardChain::setNumberOfChains (size_t numChains) virtual
Set the number of chain segments (this class can render multiple chains at once using the same material).
Reimplemented in Ogre::RibbonTrail.
getNumberOfChains()
virtual size_t Ogre::BillboardChain::getNumberOfChains (void) const inline virtual
Get the number of chain segments (this class can render multiple chains at once using the same material).
setUseTextureCoords()
virtual void Ogre::BillboardChain::setUseTextureCoords (bool use) virtual
Sets whether texture coordinate information should be included in the final buffers generated.
Note
You must use either texture coordinates or vertex colour since the vertices have no normals and without one of these there is no source of colour for the vertices.
getUseTextureCoords()
virtual bool Ogre::BillboardChain::getUseTextureCoords (void) const inline virtual
Gets whether texture coordinate information should be included in the final buffers generated.
setTextureCoordDirection()
virtual void Ogre::BillboardChain::setTextureCoordDirection (TexCoordDirection dir) virtual
Sets the direction in which texture coords specified on each element are deemed to run along the length of the chain.
Parameters
dir The direction, default is TCD_U.
getTextureCoordDirection()
virtual TexCoordDirection Ogre::BillboardChain::getTextureCoordDirection (void) inline virtual
Gets the direction in which texture coords specified on each element are deemed to run.
setOtherTextureCoordRange()
virtual void Ogre::BillboardChain::setOtherTextureCoordRange (Real start, Real end) virtual
Set the range of the texture coordinates generated across the width of the chain elements.
Parameters
start Start coordinate, default 0.0
end End coordinate, default 1.0
getOtherTextureCoordRange()
virtual const Real* Ogre::BillboardChain::getOtherTextureCoordRange (void) const inline virtual
Get the range of the texture coordinates generated across the width of the chain elements.
setUseVertexColours()
virtual void Ogre::BillboardChain::setUseVertexColours (bool use) virtual
Sets whether vertex colour information should be included in the final buffers generated.
Note
You must use either texture coordinates or vertex colour since the vertices have no normals and without one of these there is no source of colour for the vertices.
getUseVertexColours()
virtual bool Ogre::BillboardChain::getUseVertexColours (void) const inline virtual
Gets whether vertex colour information should be included in the final buffers generated.
setDynamic()
virtual void Ogre::BillboardChain::setDynamic (bool dyn) virtual
Sets whether or not the buffers created for this object are suitable for dynamic alteration.
getDynamic()
virtual bool Ogre::BillboardChain::getDynamic (void) const inline virtual
Gets whether or not the buffers created for this object are suitable for dynamic alteration.
References Ogre::Vector3::UNIT_X.
addChainElement()
virtual void Ogre::BillboardChain::addChainElement (size_t chainIndex, const Element & billboardChainElement) virtual
Add an element to the 'head' of a chain.
Remarks
If this causes the number of elements to exceed the maximum elements per chain, the last element in the chain (the 'tail') will be removed to allow the additional element to be added.
Parameters
chainIndex The index of the chain
billboardChainElement The details to add
removeChainElement()
virtual void Ogre::BillboardChain::removeChainElement (size_t chainIndex) virtual
Remove an element from the 'tail' of a chain.
Parameters
chainIndex The index of the chain
updateChainElement()
virtual void Ogre::BillboardChain::updateChainElement (size_t chainIndex, size_t elementIndex, const Element & billboardChainElement) virtual
Update the details of an existing chain element.
Parameters
chainIndex The index of the chain
elementIndex The element index within the chain, measured from the 'head' of the chain
billboardChainElement The details to set
getChainElement()
virtual const Element& Ogre::BillboardChain::getChainElement (size_t chainIndex, size_t elementIndex) const virtual
Get the detail of a chain element.
Parameters
chainIndex The index of the chain
elementIndex The element index within the chain, measured from the 'head' of the chain
getNumChainElements()
virtual size_t Ogre::BillboardChain::getNumChainElements (size_t chainIndex) const virtual
Returns the number of chain elements.
clearChain()
virtual void Ogre::BillboardChain::clearChain (size_t chainIndex) virtual
Remove all elements of a given chain (but leave the chain intact).
Reimplemented in Ogre::RibbonTrail.
clearAllChains()
virtual void Ogre::BillboardChain::clearAllChains (void) virtual
Remove all elements from all chains (but leave the chains themselves intact).
setFaceCamera()
void Ogre::BillboardChain::setFaceCamera (bool faceCamera, const Vector3 & normalVector = Vector3::UNIT_X)
Sets whether the billboard should always be facing the camera or a custom direction set by each point element.
Remarks
Billboards facing the camera are useful for smoke trails, light beams, etc by simulating a cylinder. However, because of this property, wide trails can cause several artefacts unless the head is properly covered. Therefore, non-camera-facing billboards are much more convenient for leaving big trails of movement from thin objects, for example a sword swing as seen in many fighting games.
Parameters
faceCamera True to be always facing the camera (Default value: True)
normalVector Only used when faceCamera == false. Must be a non-zero vector. This vector is the "point of reference" for each point orientation. For example, if normalVector is Vector3::UNIT_Z, and the point's orientation is an identity matrix, the segment corresponding to that point will be facing towards UNIT_Z This vector is internally normalized.
getMaterialName()
virtual const String& Ogre::BillboardChain::getMaterialName (void) const inline virtual
Get the material name in use.
References Ogre::ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME.
setMaterialName()
virtual void Ogre::BillboardChain::setMaterialName (const String & name, const String & groupName = ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME) virtual
Set the material name to use for rendering.
getSquaredViewDepth()
Real Ogre::BillboardChain::getSquaredViewDepth (const Camera * cam) const virtual
Returns the camera-relative squared depth of this renderable.
Remarks
Used to sort transparent objects. Squared depth is used rather than actual depth to avoid having to perform a square root on the result.
Implements Ogre::Renderable.
getBoundingRadius()
Real Ogre::BillboardChain::getBoundingRadius (void) const virtual
Retrieves the radius of the origin-centered bounding sphere for this object.
Implements Ogre::MovableObject.
getBoundingBox()
const AxisAlignedBox& Ogre::BillboardChain::getBoundingBox (void) const virtual
Retrieves the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
Implements Ogre::MovableObject.
getMaterial()
const MaterialPtr& Ogre::BillboardChain::getMaterial (void) const virtual
Retrieves a weak reference to the material this renderable object uses.
Remarks
Note that the Renderable also has the option to override the getTechnique method to specify a particular Technique to use instead of the best one available.
Implements Ogre::Renderable.
getMovableType()
const String& Ogre::BillboardChain::getMovableType (void) const virtual
Returns the type name of this object.
Implements Ogre::MovableObject.
Reimplemented in Ogre::RibbonTrail.
_updateRenderQueue()
void Ogre::BillboardChain::_updateRenderQueue (RenderQueue * queue) virtual
Internal method by which the movable object must add Renderable subclass instances to the rendering queue.
Remarks
The engine will call this method when this object is to be rendered. The object must then create one or more Renderable subclass instances which it places on the passed in Queue for rendering.
Implements Ogre::MovableObject.
getRenderOperation()
void Ogre::BillboardChain::getRenderOperation (RenderOperation & op) virtual
Gets the render operation required to send this object to the frame buffer.
Implements Ogre::Renderable.
preRender()
virtual bool Ogre::BillboardChain::preRender (SceneManager * sm, RenderSystem * rsys) virtual
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented from Ogre::Renderable.
getWorldTransforms()
void Ogre::BillboardChain::getWorldTransforms (Matrix4 * xform) const virtual
Gets the world transform matrix / matrices for this renderable object.
Remarks
If the object has any derived transforms, these are expected to be up to date as long as all the SceneNode structures have been updated before this is called.
This method will populate transform with 1 matrix if it does not use vertex blending. If it does use vertex blending it will fill the passed in pointer with an array of matrices, the length being the value returned from getNumWorldTransforms.
Note
Internal Ogre never supports non-affine matrix for world transform matrix/matrices, the behavior is undefined if returns non-affine matrix here.
See also
Matrix4::isAffine.
Implements Ogre::Renderable.
getLights()
const LightList& Ogre::BillboardChain::getLights (void) const virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
visitRenderables()
void Ogre::BillboardChain::visitRenderables (Renderable::Visitor * visitor, bool debugRenderables = false) virtual
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Parameters
visitor Pointer to a class implementing the Renderable::Visitor interface which will be called back for each Renderable which will be queued. Bear in mind that the state of the Renderable instances may not be finalised depending on when you call this.
debugRenderables If false, only regular renderables will be visited (those for normal display). If true, debug renderables will be included too.
Implements Ogre::MovableObject.
_notifyCreator()
virtual void Ogre::MovableObject::_notifyCreator (MovableObjectFactory * fact) inline virtual inherited
Notify the object of it's creator (internal use only)
_getCreator()
MovableObjectFactory* Ogre::MovableObject::_getCreator (void) const inline inherited
Get the creator of this object, if any (internal use only)
_notifyManager()
virtual void Ogre::MovableObject::_notifyManager (SceneManager * man) inline virtual inherited
Notify the object of it's manager (internal use only)
_getManager()
SceneManager* Ogre::MovableObject::_getManager (void) const inline inherited
Get the manager of this object, if any (internal use only)
_releaseManualHardwareResources()
virtual void Ogre::MovableObject::_releaseManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources were lost.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::BillboardSet, Ogre::StaticGeometry::Region, Ogre::Entity, and Ogre::ManualObject.
_restoreManualHardwareResources()
virtual void Ogre::MovableObject::_restoreManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources should be restored.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::StaticGeometry::Region, and Ogre::Entity.
getName()
const String& Ogre::MovableObject::getName (void) const inline inherited
Returns the name of this object.
getParentNode()
Node* Ogre::MovableObject::getParentNode (void) const inline inherited
Returns the node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. Both are Node subclasses so this method will return either.
getParentSceneNode()
SceneNode* Ogre::MovableObject::getParentSceneNode (void) const inherited
Returns the scene node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. This method will return the scene node of the parent entity if the latter is true.
isParentTagPoint()
bool Ogre::MovableObject::isParentTagPoint () const inline inherited
Gets whether the parent node is a TagPoint (or a SceneNode)
_notifyAttached()
virtual void Ogre::MovableObject::_notifyAttached (Node * parent, bool isTagPoint = false) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::Entity, Ogre::ParticleSystem, Ogre::Light, Ogre::PortalBase, and Ogre::InstancedEntity.
Referenced by Ogre::PortalBase::_notifyAttached().
isAttached()
bool Ogre::MovableObject::isAttached (void) const inline inherited
Returns true if this object is attached to a SceneNode or TagPoint.
detachFromParent()
void Ogre::MovableObject::detachFromParent (void) inherited
Detaches an object from a parent SceneNode or TagPoint, if attached.
isInScene()
virtual bool Ogre::MovableObject::isInScene (void) const virtual inherited
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
Reimplemented in Ogre::InstancedEntity.
_notifyMoved()
virtual void Ogre::MovableObject::_notifyMoved (void) virtual inherited
Internal method called to notify the object that it has been moved.
Reimplemented in Ogre::Light, Ogre::PortalBase, Ogre::InstancedEntity, and Ogre::PCZLight.
_notifyCurrentCamera()
virtual void Ogre::MovableObject::_notifyCurrentCamera (Camera * cam) virtual inherited
Internal method to notify the object of the camera to be used for the next rendering operation.
Remarks
Certain objects may want to do specific processing based on the camera position. This method notifies them in case they wish to do this.
Reimplemented in Ogre::BillboardSet, Ogre::Frustum, Ogre::InstancedGeometry::BatchInstance, Ogre::StaticGeometry::Region, Ogre::Entity, Ogre::ParticleSystem, Ogre::InstanceBatch, Ogre::SimpleRenderable, and Ogre::MovablePlane.
getWorldBoundingBox()
virtual const AxisAlignedBox& Ogre::MovableObject::getWorldBoundingBox (bool derive = false) const virtual inherited
Retrieves the axis-aligned bounding box for this object in world coordinates.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
getWorldBoundingSphere()
virtual const Sphere& Ogre::MovableObject::getWorldBoundingSphere (bool derive = false) const virtual inherited
Retrieves the worldspace bounding sphere for this object.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
setVisible()
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
Referenced by Ogre::Light::setVisible().
getVisible()
bool Ogre::MovableObject::getVisible (void) const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
isVisible()
virtual bool Ogre::MovableObject::isVisible (void) const virtual inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account both upper rendering distance and visible flag.
Reimplemented in Ogre::InstancedGeometry::BatchInstance, and Ogre::StaticGeometry::Region.
Referenced by Ogre::Frustum::isCustomProjectionMatrixEnabled().
setRenderingDistance()
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Note
Camera::setUseRenderingDistance() needs to be called for this parameter to be used.
Parameters
dist Distance beyond which the object will not be rendered (the default is 0, which means objects are always rendered).
getRenderingDistance()
Real Ogre::MovableObject::getRenderingDistance (void) const inline inherited
Gets the distance at which batches are no longer rendered.
setRenderingMinPixelSize()
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
getRenderingMinPixelSize()
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
setUserAny() [1/2]
void Ogre::MovableObject::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this MovableObject. This can be a pointer back to one of your own classes for instance.
getUserAny() [1/2]
const Any& Ogre::MovableObject::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
getUserObjectBindings() [1/4]
UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/4]
const UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
setRenderQueueGroup()
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
setRenderQueueGroupAndPriority()
virtual void Ogre::MovableObject::setRenderQueueGroupAndPriority (uint8 queueID, ushort priority) virtual inherited
Sets the render queue group and group priority this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. Within a single render group there another type of grouping called priority which allows further control. If you do not call this method, all Entity objects default to the default queue and priority (RenderQueue::getDefaultQueueGroup, RenderQueue::getDefaultRenderablePriority), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
priority The priority within a group to use.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
getRenderQueueGroup()
uint8 Ogre::MovableObject::getRenderQueueGroup (void) const inline inherited
Gets the queue group for this entity.
See also
setRenderQueueGroup
_getParentNodeFullTransform()
virtual const Matrix4& Ogre::MovableObject::_getParentNodeFullTransform (void) const virtual inherited
Return the full transformation of the parent sceneNode or the attachingPoint node.
Reimplemented in Ogre::InstancedEntity.
setQueryFlags()
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
addQueryFlags()
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
removeQueryFlags()
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
getQueryFlags()
uint32 Ogre::MovableObject::getQueryFlags (void) const inline inherited
Returns the query flags relevant for this object.
setDefaultQueryFlags()
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
getDefaultQueryFlags()
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
setVisibilityFlags()
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags which when 'and'ed with the SceneManager's visibility mask can also make an object invisible.
addVisibilityFlags()
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
removeVisibilityFlags()
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
getVisibilityFlags()
uint32 Ogre::MovableObject::getVisibilityFlags (void) const inline inherited
Returns the visibility flags relevant for this object.
setDefaultVisibilityFlags()
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
getDefaultVisibilityFlags()
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
setListener()
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
getListener()
Listener* Ogre::MovableObject::getListener (void) const inline inherited
Gets the current listener for this object.
queryLights()
const LightList& Ogre::MovableObject::queryLights (void) const inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
By default, this method gives the listener a chance to populate light list first, if there is no listener or Listener::objectQueryLights returns NULL, it'll query the light list from parent entity if it is present, or returns SceneNode::findLights if it has parent scene node, otherwise it just returns an empty list.
The object internally caches the light list, so it will recalculate it only when object is moved, or lights that affect the frustum have been changed (
See also
SceneManager::_getLightsDirtyCounter), but if listener exists, it will be called each time, so the listener should implement their own cache mechanism to optimise performance.
This method can be useful when implementing Renderable::getLights in case the renderable is a part of the movable.
Returns
The list of lights use to lighting this object.
getLightMask()
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
setLightMask()
void Ogre::MovableObject::setLightMask (uint32 lightMask) inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
_getLightList()
LightList* Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
getEdgeList()
EdgeData* Ogre::MovableObject::getEdgeList (void) inline virtual inherited
Returns details of the edges which might be used to determine a silhouette.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
hasEdgeList()
bool Ogre::MovableObject::hasEdgeList (void) inline virtual inherited
Returns whether the object has a valid edge list.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
getShadowVolumeRenderableIterator()
ShadowRenderableListIterator Ogre::MovableObject::getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light * light, HardwareIndexBufferSharedPtr * indexBuffer, size_t * indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags = 0) virtual inherited
Define a default implementation of method from ShadowCaster which implements no shadows.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
getLightCapBounds()
const AxisAlignedBox& Ogre::MovableObject::getLightCapBounds (void) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
getDarkCapBounds()
const AxisAlignedBox& Ogre::MovableObject::getDarkCapBounds (const Light & light, Real dirLightExtrusionDist) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
setCastShadows()
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
getCastShadows()
bool Ogre::MovableObject::getCastShadows (void) const inline virtual inherited
Returns whether shadow casting is enabled for this object.
Implements Ogre::ShadowCaster.
getReceivesShadows()
bool Ogre::MovableObject::getReceivesShadows () inherited
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
getPointExtrusionDistance()
Real Ogre::MovableObject::getPointExtrusionDistance (const Light * l) const virtual inherited
Get the distance to extrude for a point/spot light.
Implements Ogre::ShadowCaster.
getTypeFlags()
virtual uint32 Ogre::MovableObject::getTypeFlags (void) const virtual inherited
Get the 'type flags' for this MovableObject.
Remarks
A type flag identifies the type of the MovableObject as a bitpattern. This is used for categorical inclusion / exclusion in SceneQuery objects. By default, this method returns all ones for objects not created by a MovableObjectFactory (hence always including them); otherwise it returns the value assigned to the MovableObjectFactory. Custom objects which don't use MovableObjectFactory will need to override this if they want to be included in queries.
Reimplemented in Ogre::BillboardSet, Ogre::Entity, Ogre::ParticleSystem, Ogre::Frustum, Ogre::StaticGeometry::Region, and Ogre::Light.
setDebugDisplayEnabled()
void Ogre::MovableObject::setDebugDisplayEnabled (bool enabled) inline inherited
Sets whether or not the debug display of this object is enabled.
Remarks
Some objects aren't visible themselves but it can be useful to display a debug representation of them. Or, objects may have an additional debug display on top of their regular display. This option enables / disables that debug display. Objects that are not visible never display debug geometry regardless of this setting.
isDebugDisplayEnabled()
bool Ogre::MovableObject::isDebugDisplayEnabled (void) const inline inherited
Gets whether debug display of this object is enabled.
clearShadowRenderableList()
static void Ogre::ShadowCaster::clearShadowRenderableList (ShadowRenderableList & shadowRenderables) static inherited
Common implementation of releasing shadow renderables.
extrudeVertices()
static void Ogre::ShadowCaster::extrudeVertices (const HardwareVertexBufferSharedPtr & vertexBuffer, size_t originalVertexCount, const Vector4 & lightPos, Real extrudeDist) static inherited
Utility method for extruding vertices based on a light.
Remarks
Unfortunately, because D3D cannot handle homogeneous (4D) position coordinates in the fixed-function pipeline (GL can, but we have to be cross-API), when we extrude in software we cannot extrude to infinity the way we do in the vertex program (by setting w to 0.0f). Therefore we extrude by a fixed distance, which may cause some problems with larger scenes. Luckily better hardware (ie vertex programs) can fix this.
Parameters
vertexBuffer The vertex buffer containing ONLY xyz position values, which must be originalVertexCount * 2 * 3 floats long.
originalVertexCount The count of the original number of vertices, i.e. the number in the mesh, not counting the doubling which has already been done (by VertexData::prepareForShadowVolume) to provide the extruded area of the buffer.
lightPos 4D light position in object space, when w=0.0f this represents a directional light.
extrudeDist The distance to extrude.
getAnimableValueNames()
const StringVector& Ogre::AnimableObject::getAnimableValueNames (void) const inline inherited
Gets a list of animable value names for this object.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
createAnimableValue()
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
getTechnique()
virtual Technique* Ogre::Renderable::getTechnique (void) const inline virtual inherited
Retrieves a pointer to the Material Technique this renderable object uses.
Remarks
This is to allow Renderables to use a chosen Technique if they wish, otherwise they will use the best Technique available for the Material they are using.
Reimplemented in Ogre::InstanceBatch, Ogre::InstancedGeometry::GeometryBucket, Ogre::StaticGeometry::GeometryBucket, and Ogre::SubEntity.
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
getNumWorldTransforms()
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::BorderRenderable, Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, Ogre::BaseInstanceBatchVTF, Ogre::InstanceBatchHW, and Ogre::InstanceBatchShader.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
getCastsShadows()
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, and Ogre::StaticGeometry::GeometryBucket.
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
getCustomParameter()
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
_updateCustomGpuParameter()
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
setPolygonModeOverrideable()
void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
getPolygonModeOverrideable()
bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Referenced by Ogre::BorderRenderable::getPolygonModeOverrideable().
setUserAny() [2/2]
void Ogre::Renderable::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserAny() [2/2]
const Any& Ogre::Renderable::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserObjectBindings() [3/4]
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [4/4]
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getRenderSystemData()
const RenderSystemDataPtr& Ogre::Renderable::getRenderSystemData () const inline inherited
Gets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
setRenderSystemData()
void Ogre::Renderable::setRenderSystemData (RenderSystemDataPtr val) const inline inherited
Sets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
The documentation for this class was generated from the following file:
OgreBillboardChain.h