OGRE: Ogre::BillboardSet Class Reference
Ogre::BillboardSet Class Reference
Core » Effects
A collection of billboards (faces which are always facing the given direction) with the same (default) dimensions, material and which are fairly close proximity to each other.
#include <OgreBillboardSet.h>
Public Types
typedef SharedPtr< RenderSystemData > RenderSystemDataPtr
typedef vector< ShadowRenderable * >::type ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Public Member Functions
BillboardSet (const String &name, unsigned int poolSize=20, bool externalDataSource=false)
Usual constructor - this is called by the SceneManager.
virtual ~BillboardSet ()
MovableObjectFactory * _getCreator (void) const
Get the creator of this object, if any (internal use only)
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager (void) const
Get the manager of this object, if any (internal use only)
virtual const Matrix4 & _getParentNodeFullTransform (void) const
Return the full transformation of the parent sceneNode or the attachingPoint node.
virtual SortMode _getSortMode (void) const
Gets the sort mode of this billboard set.
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
Internal method called to notify the object that it has been attached to a node.
virtual void _notifyBillboardResized (void)
Internal callback used by Billboards to notify their parent that they have been resized.
virtual void _notifyBillboardRotated (void)
Internal callback used by Billboards to notify their parent that they have been rotated.
virtual void _notifyCreator (MovableObjectFactory *fact)
Notify the object of it's creator (internal use only)
virtual void _notifyCurrentCamera (Camera *cam)
Overridden from MovableObject.
virtual void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyMoved (void)
Internal method called to notify the object that it has been moved.
void _releaseManualHardwareResources ()
Notifies the movable object that hardware resources were lost.
virtual void _restoreManualHardwareResources ()
Notifies the movable object that hardware resources should be restored.
virtual void _sortBillboards (Camera *cam)
Sort the billboard set.
virtual void _updateBounds (void)
Update the bounds of the billboardset.
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
virtual void _updateRenderQueue (RenderQueue *queue)
Overridden from MovableObject.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
void beginBillboards (size_t numBillboards=0)
Begin injection of billboard data; applicable when constructing the BillboardSet for external data use.
virtual void clear ()
Empties this set of all billboards.
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
Billboard * createBillboard (const Vector3 &position, const ColourValue &colour=ColourValue::White)
Creates a new billboard and adds it to this set.
Billboard * createBillboard (Real x, Real y, Real z, const ColourValue &colour=ColourValue::White)
Creates a new billboard and adds it to this set.
void detachFromParent (void)
Detaches an object from a parent SceneNode or TagPoint, if attached.
void endBillboards (void)
Finish defining billboards.
const StringVector & getAnimableValueNames (void) const
Gets a list of animable value names for this object.
virtual bool getAutoextend (void) const
Returns true if the billboard pool automatically extends.
bool getAutoUpdate (void) const
Return the auto update state of this billboard set.
virtual Billboard * getBillboard (unsigned int index) const
Returns a pointer to the billboard at the supplied index.
virtual BillboardOrigin getBillboardOrigin (void) const
Gets the point which acts as the origin point for all billboards in this set.
virtual BillboardRotationType getBillboardRotationType (void) const
Sets billboard rotation type.
bool getBillboardsInWorldSpace ()
Gets whether billboards are treated as being in world space.
virtual BillboardType getBillboardType (void) const
Returns the billboard type in use.
virtual const AxisAlignedBox & getBoundingBox (void) const
Overridden from MovableObject.
virtual Real getBoundingRadius (void) const
Overridden from MovableObject.
bool getCastShadows (void) const
Returns whether shadow casting is enabled for this object.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
virtual const Vector3 & getCommonDirection (void) const
Gets the common direction for all billboards (BBT_ORIENTED_COMMON)
virtual const Vector3 & getCommonUpVector (void) const
Gets the common up-vector for all billboards (BBT_PERPENDICULAR_SELF and BBT_PERPENDICULAR_COMMON)
virtual bool getCullIndividually (void) const
Returns whether or not billboards in this are tested individually for culling.
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
Overridden member from ShadowCaster.
virtual Real getDefaultHeight (void) const
See setDefaultDimensions - this gets 1 component individually.
virtual Real getDefaultWidth (void) const
See setDefaultDimensions - this gets 1 component individually.
EdgeData * getEdgeList (void)
Returns details of the edges which might be used to determine a silhouette.
const AxisAlignedBox & getLightCapBounds (void) const
Overridden member from ShadowCaster.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
Listener * getListener (void) const
Gets the current listener for this object.
virtual const MaterialPtr & getMaterial (void) const
Overridden from MovableObject.
virtual const String & getMaterialName (void) const
Sets the name of the material to be used for this billboard set.
virtual const String & getMovableType (void) const
Overridden from MovableObject.
const String & getName (void) const
Returns the name of this object.
virtual int getNumBillboards (void) const
Returns the number of active billboards which currently make up this set.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
Node * getParentNode (void) const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode (void) const
Returns the scene node to which this object is attached.
Real getPointExtrusionDistance (const Light *l) const
Get the distance to extrude for a point/spot light.
bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
virtual unsigned int getPoolSize (void) const
Returns the current size of the billboard pool.
uint32 getQueryFlags (void) const
Returns the query flags relevant for this object.
bool getReceivesShadows ()
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
Real getRenderingDistance (void) const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void getRenderOperation (RenderOperation &op)
Overridden from MovableObject.
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity.
const RenderSystemDataPtr & getRenderSystemData () const
Gets RenderSystem private data.
ShadowRenderableListIterator getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light *light, HardwareIndexBufferSharedPtr *indexBuffer, size_t *indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags=0)
Define a default implementation of method from ShadowCaster which implements no shadows.
virtual bool getSortingEnabled (void) const
Returns true if sorting of billboards is enabled based on their distance from the camera.
Real getSquaredViewDepth (const Camera *cam) const
Overridden, see Renderable.
virtual Technique * getTechnique (void) const
Retrieves a pointer to the Material Technique this renderable object uses.
virtual Ogre::FloatRect const * getTextureCoords (uint16 *oNumCoords)
getTextureCoords() returns the current texture coordinate rects in effect.
uint32 getTypeFlags (void) const
Override to return specific type flag.
virtual bool getUseAccurateFacing (void) const
Gets whether or not billboards use an 'accurate' facing model based on the vector from each billboard to the camera, rather than an optimised version using just the camera direction.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
const Any & getUserAny (void) const
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
uint32 getVisibilityFlags (void) const
Returns the visibility flags relevant for this object.
bool getVisible (void) const
Gets this object whether to be visible or not, if it has a renderable component.
virtual const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const
Retrieves the axis-aligned bounding box for this object in world coordinates.
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
Retrieves the worldspace bounding sphere for this object.
virtual void getWorldTransforms (Matrix4 *xform) const
Overridden from MovableObject.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasEdgeList (void)
Returns whether the object has a valid edge list.
void injectBillboard (const Billboard &bb)
Define a billboard.
bool isAttached (void) const
Returns true if this object is attached to a SceneNode or TagPoint.
bool isDebugDisplayEnabled (void) const
Gets whether debug display of this object is enabled.
virtual bool isInScene (void) const
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
bool isParentTagPoint () const
Gets whether the parent node is a TagPoint (or a SceneNode)
virtual bool isPointRenderingEnabled (void) const
Returns whether point rendering is enabled.
virtual bool isVisible (void) const
Returns whether or not this object is supposed to be visible or not.
void notifyBillboardDataChanged (void)
When billboard set is not auto updating its GPU buffer, the user is responsible to inform it about any billboard changes in order to reflect them at the rendering stage.
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
const LightList & queryLights (void) const
Gets a list of lights, ordered relative to how close they are to this movable object.
virtual void removeBillboard (unsigned int index)
Removes the billboard at the supplied index.
virtual void removeBillboard (Billboard *pBill)
Removes a billboard from the set.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
virtual void setAutoextend (bool autoextend)
Tells the set whether to allow automatic extension of the pool of billboards.
void setAutoUpdate (bool autoUpdate)
Set the auto update state of this billboard set.
virtual void setBillboardOrigin (BillboardOrigin origin)
Sets the point which acts as the origin point for all billboards in this set.
virtual void setBillboardRotationType (BillboardRotationType rotationType)
Sets billboard rotation type.
virtual void setBillboardsInWorldSpace (bool ws)
Sets whether billboards should be treated as being in world space.
virtual void setBillboardType (BillboardType bbt)
Sets the type of billboard to render.
void setBounds (const AxisAlignedBox &box, Real radius)
Set the bounds of the BillboardSet.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
virtual void setCommonDirection (const Vector3 &vec)
Use this to specify the common direction given to billboards of type BBT_ORIENTED_COMMON or BBT_PERPENDICULAR_COMMON.
virtual void setCommonUpVector (const Vector3 &vec)
Use this to specify the common up-vector given to billboards of type BBT_PERPENDICULAR_SELF or BBT_PERPENDICULAR_COMMON.
virtual void setCullIndividually (bool cullIndividual)
Sets whether culling tests billboards in this individually as well as in a group.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDebugDisplayEnabled (bool enabled)
Sets whether or not the debug display of this object is enabled.
virtual void setDefaultDimensions (Real width, Real height)
Sets the default dimensions of the billboards in this set.
virtual void setDefaultHeight (Real height)
See setDefaultDimensions - this sets 1 component individually.
virtual void setDefaultWidth (Real width)
See setDefaultDimensions - this sets 1 component individually.
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
virtual void setMaterial (const MaterialPtr &material)
Sets the name of the material to be used for this billboard set.
virtual void setMaterialName (const String &name, const String &groupName=ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME)
Sets the name of the material to be used for this billboard set.
virtual void setPointRenderingEnabled (bool enabled)
Set whether or not the BillboardSet will use point rendering rather than manually generated quads.
void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
virtual void setPoolSize (size_t size)
Adjusts the size of the pool of billboards available in this set.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
Sets the render queue group and group priority this entity will be rendered through.
void setRenderSystemData (RenderSystemDataPtr val) const
Sets RenderSystem private data.
virtual void setSortingEnabled (bool sortenable)
Enables sorting for this BillboardSet.
virtual void setTextureCoords (Ogre::FloatRect const *coords, uint16 numCoords)
BillboardSet can use custom texture coordinates for various billboards.
virtual void setTextureStacksAndSlices (uchar stacks, uchar slices)
setTextureStacksAndSlices() will generate texture coordinate rects as if the texture for the billboard set contained 'stacks' rows of 'slices' images each, all equal size.
virtual void setUseAccurateFacing (bool acc)
Sets whether or not billboards should use an 'accurate' facing model based on the vector from each billboard to the camera, rather than an optimised version using just the camera direction.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
void setUserAny (const Any &anything)
void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
void visitRenderables (Renderable::Visitor *visitor, bool debugRenderables=false)
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Static Public Member Functions
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
Common implementation of releasing shadow renderables.
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Utility method for extruding vertices based on a light.
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
Detailed Description
A collection of billboards (faces which are always facing the given direction) with the same (default) dimensions, material and which are fairly close proximity to each other.
Remarks
Billboards are rectangles made up of 2 tris which are always facing the given direction. They are typically used for special effects like particles. This class collects together a set of billboards with the same (default) dimensions, material and relative locality in order to process them more efficiently. The entire set of billboards will be culled as a whole (by default, although this can be changed if you want a large set of billboards which are spread out and you want them culled individually), individual Billboards have locations which are relative to the set (which itself derives it's position from the SceneNode it is attached to since it is a MoveableObject), they will be rendered as a single rendering operation, and some calculations will be sped up by the fact that they use the same dimensions so some workings can be reused.
A BillboardSet can be created using the SceneManager::createBillboardSet method. They can also be used internally by other classes to create effects.
Note
Billboard bounds are only automatically calculated when you create them. If you modify the position of a billboard you may need to call _updateBounds if the billboard moves outside the original bounds. Similarly, the bounds do no shrink when you remove a billboard, if you want them to call _updateBounds, but note this requires a potentially expensive examination of every billboard in the set.
Member Typedef Documentation
ShadowRenderableList
typedef vector<ShadowRenderable*>::type Ogre::ShadowCaster::ShadowRenderableList inherited
ShadowRenderableListIterator
typedef VectorIterator<ShadowRenderableList> Ogre::ShadowCaster::ShadowRenderableListIterator inherited
RenderSystemDataPtr
typedef SharedPtr<RenderSystemData> Ogre::Renderable::RenderSystemDataPtr inherited
Constructor & Destructor Documentation
BillboardSet()
Ogre::BillboardSet::BillboardSet (const String & name, unsigned int poolSize = 20, bool externalDataSource = false)
Usual constructor - this is called by the SceneManager.
Parameters
name The name to give the billboard set (must be unique)
poolSize The initial size of the billboard pool. Estimate of the number of billboards which will be required, and pass it using this parameter. The set will preallocate this number to avoid memory fragmentation. The default behaviour once this pool has run out is to double it.
externalDataSource If true, the source of data for drawing the billboards will not be the internal billboard list, but external data. When driving the billboard from external data, you must call _notifyCurrentCamera to reorient the billboards, setPoolSize to set the maximum billboards you want to use, beginBillboards to start the update, and injectBillboard per billboard, followed by endBillboards.
See also
BillboardSet::setAutoextend
~BillboardSet()
virtual Ogre::BillboardSet::~BillboardSet () virtual
Member Function Documentation
createBillboard() [1/2]
Billboard* Ogre::BillboardSet::createBillboard (const Vector3 & position, const ColourValue & colour = ColourValue::White)
Creates a new billboard and adds it to this set.
Remarks
Behaviour once the billboard pool has been exhausted depends on the BillboardSet::setAutoextend option.
Parameters
position The position of the new billboard realtive to the certer of the set
colour Optional base colour of the billboard.
Returns
On success, a pointer to a newly created Billboard is returned.
On failure (i.e. no more space and can't autoextend), NULL is returned.
See also
BillboardSet::setAutoextend
createBillboard() [2/2]
Billboard* Ogre::BillboardSet::createBillboard (Real x, Real y, Real z, const ColourValue & colour = ColourValue::White)
Creates a new billboard and adds it to this set.
Remarks
Behaviour once the billboard pool has been exhausted depends on the BillboardSet::setAutoextend option.
Parameters
x The x position of the new billboard relative to the center of the set
y The y position of the new billboard relative to the center of the set
z The z position of the new billboard relative to the center of the set
colour Optional base colour of the billboard.
Returns
On success, a pointer to a newly created Billboard is returned.
On failure (i.e. no more space and can't autoextend), NULL is returned.
See also
BillboardSet::setAutoextend
getNumBillboards()
virtual int Ogre::BillboardSet::getNumBillboards (void) const virtual
Returns the number of active billboards which currently make up this set.
setAutoextend()
virtual void Ogre::BillboardSet::setAutoextend (bool autoextend) virtual
Tells the set whether to allow automatic extension of the pool of billboards.
Remarks
A BillboardSet stores a pool of pre-constructed billboards which are used as needed when a new billboard is requested. This allows applications to create / remove billboards efficiently without incurring construction / destruction costs (a must for sets with lots of billboards like particle effects). This method allows you to configure the behaviour when a new billboard is requested but the billboard pool has been exhausted.
The default behaviour is to allow the pool to extend (typically this allocates double the current pool of billboards when the pool is expended), equivalent to calling this method with autoExtend = true. If you set the parameter to false however, any attempt to create a new billboard when the pool has expired will simply fail silently, returning a null pointer.
Parameters
autoextend true to double the pool every time it runs out, false to fail silently.
getAutoextend()
virtual bool Ogre::BillboardSet::getAutoextend (void) const virtual
Returns true if the billboard pool automatically extends.
See also
BillboardSet::setAutoextend
setSortingEnabled()
virtual void Ogre::BillboardSet::setSortingEnabled (bool sortenable) virtual
Enables sorting for this BillboardSet.
(default: off)
Parameters
sortenable true to sort the billboards according to their distance to the camera
getSortingEnabled()
virtual bool Ogre::BillboardSet::getSortingEnabled (void) const virtual
Returns true if sorting of billboards is enabled based on their distance from the camera.
See also
BillboardSet::setSortingEnabled
setPoolSize()
virtual void Ogre::BillboardSet::setPoolSize (size_t size) virtual
Adjusts the size of the pool of billboards available in this set.
Remarks
See the BillboardSet::setAutoextend method for full details of the billboard pool. This method adjusts the preallocated size of the pool. If you try to reduce the size of the pool, the set has the option of ignoring you if too many billboards are already in use. Bear in mind that calling this method will incur significant construction / destruction calls so should be avoided in time-critical code. The same goes for auto-extension, try to avoid it by estimating the pool size correctly up-front.
Parameters
size The new size for the pool.
getPoolSize()
virtual unsigned int Ogre::BillboardSet::getPoolSize (void) const virtual
Returns the current size of the billboard pool.
Returns
The current size of the billboard pool.
See also
BillboardSet::setAutoextend
clear()
virtual void Ogre::BillboardSet::clear () virtual
Empties this set of all billboards.
getBillboard()
virtual Billboard* Ogre::BillboardSet::getBillboard (unsigned int index) const virtual
Returns a pointer to the billboard at the supplied index.
Note
This method requires linear time since the billboard list is a linked list.
Parameters
index The index of the billboard that is requested.
Returns
On success, a valid pointer to the requested billboard is returned.
On failure, NULL is returned.
removeBillboard() [1/2]
virtual void Ogre::BillboardSet::removeBillboard (unsigned int index) virtual
Removes the billboard at the supplied index.
Note
This method requires linear time since the billboard list is a linked list.
removeBillboard() [2/2]
virtual void Ogre::BillboardSet::removeBillboard (Billboard * pBill) virtual
Removes a billboard from the set.
Note
This version is more efficient than removing by index.
setBillboardOrigin()
virtual void Ogre::BillboardSet::setBillboardOrigin (BillboardOrigin origin) virtual
Sets the point which acts as the origin point for all billboards in this set.
Remarks
This setting controls the fine tuning of where a billboard appears in relation to it's position. It could be that a billboard's position represents it's center (e.g. for fireballs), it could mean the center of the bottom edge (e.g. a tree which is positioned on the ground), the top-left corner (e.g. a cursor).
The default setting is BBO_CENTER.
Parameters
origin A member of the BillboardOrigin enum specifying the origin for all the billboards in this set.
Referenced by Ogre::BillboardParticleRenderer::setBillboardOrigin().
getBillboardOrigin()
virtual BillboardOrigin Ogre::BillboardSet::getBillboardOrigin (void) const virtual
Gets the point which acts as the origin point for all billboards in this set.
Returns
A member of the BillboardOrigin enum specifying the origin for all the billboards in this set.
Referenced by Ogre::BillboardParticleRenderer::getBillboardOrigin().
setBillboardRotationType()
virtual void Ogre::BillboardSet::setBillboardRotationType (BillboardRotationType rotationType) virtual
Sets billboard rotation type.
Remarks
This setting controls the billboard rotation type, you can deciding rotate the billboard's vertices around their facing direction or rotate the billboard's texture coordinates.
The default settings is BBR_TEXCOORD.
Parameters
rotationType A member of the BillboardRotationType enum specifying the rotation type for all the billboards in this set.
getBillboardRotationType()
virtual BillboardRotationType Ogre::BillboardSet::getBillboardRotationType (void) const virtual
Sets billboard rotation type.
Returns
A member of the BillboardRotationType enum specifying the rotation type for all the billboards in this set.
setDefaultDimensions()
virtual void Ogre::BillboardSet::setDefaultDimensions (Real width, Real height) virtual
Sets the default dimensions of the billboards in this set.
Remarks
All billboards in a set are created with these default dimensions. The set will render most efficiently if all the billboards in the set are the default size. It is possible to alter the size of individual billboards at the expense of extra calculation. See the Billboard class for more info.
Parameters
width The new default width for the billboards in this set.
height The new default height for the billboards in this set.
setDefaultWidth()
virtual void Ogre::BillboardSet::setDefaultWidth (Real width) virtual
See setDefaultDimensions - this sets 1 component individually.
getDefaultWidth()
virtual Real Ogre::BillboardSet::getDefaultWidth (void) const virtual
See setDefaultDimensions - this gets 1 component individually.
setDefaultHeight()
virtual void Ogre::BillboardSet::setDefaultHeight (Real height) virtual
See setDefaultDimensions - this sets 1 component individually.
getDefaultHeight()
virtual Real Ogre::BillboardSet::getDefaultHeight (void) const virtual
See setDefaultDimensions - this gets 1 component individually.
setMaterialName()
virtual void Ogre::BillboardSet::setMaterialName (const String & name, const String & groupName = ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME) virtual
Sets the name of the material to be used for this billboard set.
Parameters
name The new name of the material to use for this set.
getMaterialName()
virtual const String& Ogre::BillboardSet::getMaterialName (void) const virtual
Sets the name of the material to be used for this billboard set.
Returns
The name of the material that is used for this set.
_notifyCurrentCamera()
virtual void Ogre::BillboardSet::_notifyCurrentCamera (Camera * cam) virtual
Overridden from MovableObject.
See also
MovableObject
Reimplemented from Ogre::MovableObject.
beginBillboards()
void Ogre::BillboardSet::beginBillboards (size_t numBillboards = 0)
Begin injection of billboard data; applicable when constructing the BillboardSet for external data use.
Parameters
numBillboards If you know the number of billboards you will be issuing, state it here to make the update more efficient.
injectBillboard()
void Ogre::BillboardSet::injectBillboard (const Billboard & bb)
Define a billboard.
endBillboards()
void Ogre::BillboardSet::endBillboards (void)
Finish defining billboards.
setBounds()
void Ogre::BillboardSet::setBounds (const AxisAlignedBox & box, Real radius)
Set the bounds of the BillboardSet.
Remarks
You may need to call this if you're injecting billboards manually, and you're relying on the BillboardSet to determine culling.
getBoundingBox()
virtual const AxisAlignedBox& Ogre::BillboardSet::getBoundingBox (void) const virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::MovableObject.
getBoundingRadius()
virtual Real Ogre::BillboardSet::getBoundingRadius (void) const virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::MovableObject.
_updateRenderQueue()
virtual void Ogre::BillboardSet::_updateRenderQueue (RenderQueue * queue) virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::MovableObject.
getMaterial()
virtual const MaterialPtr& Ogre::BillboardSet::getMaterial (void) const virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::Renderable.
setMaterial()
virtual void Ogre::BillboardSet::setMaterial (const MaterialPtr & material) virtual
Sets the name of the material to be used for this billboard set.
Parameters
material The new material to use for this set.
getRenderOperation()
virtual void Ogre::BillboardSet::getRenderOperation (RenderOperation & op) virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::Renderable.
getWorldTransforms()
virtual void Ogre::BillboardSet::getWorldTransforms (Matrix4 * xform) const virtual
Overridden from MovableObject.
See also
MovableObject
Implements Ogre::Renderable.
_notifyBillboardResized()
virtual void Ogre::BillboardSet::_notifyBillboardResized (void) virtual
Internal callback used by Billboards to notify their parent that they have been resized.
_notifyBillboardRotated()
virtual void Ogre::BillboardSet::_notifyBillboardRotated (void) virtual
Internal callback used by Billboards to notify their parent that they have been rotated.
getCullIndividually()
virtual bool Ogre::BillboardSet::getCullIndividually (void) const virtual
Returns whether or not billboards in this are tested individually for culling.
setCullIndividually()
virtual void Ogre::BillboardSet::setCullIndividually (bool cullIndividual) virtual
Sets whether culling tests billboards in this individually as well as in a group.
Remarks
Billboard sets are always culled as a whole group, based on a bounding box which encloses all billboards in the set. For fairly localised sets, this is enough. However, you can optionally tell the set to also cull individual billboards in the set, i.e. to test each individual billboard before rendering. The default is not to do this.
This is useful when you have a large, fairly distributed set of billboards, like maybe trees on a landscape. You probably still want to group them into more than one set (maybe one set per section of landscape), which will be culled coarsely, but you also want to cull the billboards individually because they are spread out. Whilst you could have lots of single-tree sets which are culled separately, this would be inefficient to render because each tree would be issued as it's own rendering operation.
By calling this method with a parameter of true, you can have large billboard sets which are spaced out and so get the benefit of batch rendering and coarse culling, but also have fine-grained culling so unnecessary rendering is avoided.
Parameters
cullIndividual If true, each billboard is tested before being sent to the pipeline as well as the whole set having to pass the coarse group bounding test.
setBillboardType()
virtual void Ogre::BillboardSet::setBillboardType (BillboardType bbt) virtual
Sets the type of billboard to render.
Remarks
The default sort of billboard (BBT_POINT), always has both x and y axes parallel to the camera's local axes. This is fine for 'point' style billboards (e.g. flares, smoke, anything which is symmetrical about a central point) but does not look good for billboards which have an orientation (e.g. an elongated raindrop). In this case, the oriented billboards are more suitable (BBT_ORIENTED_COMMON or BBT_ORIENTED_SELF) since they retain an independent Y axis and only the X axis is generated, perpendicular to both the local Y and the camera Z.
In some case you might want the billboard has fixed Z axis and doesn't need to face to camera (e.g. an aureola around the player and parallel to the ground). You can use BBT_PERPENDICULAR_SELF which the billboard plane perpendicular to the billboard own direction. Or BBT_PERPENDICULAR_COMMON which the billboard plane perpendicular to the common direction.
Note
BBT_PERPENDICULAR_SELF and BBT_PERPENDICULAR_COMMON can't guarantee counterclockwise, you might use double-side material (cull_hardware node) to ensure no billboard are culled.
Parameters
bbt The type of billboard to render
getBillboardType()
virtual BillboardType Ogre::BillboardSet::getBillboardType (void) const virtual
Returns the billboard type in use.
setCommonDirection()
virtual void Ogre::BillboardSet::setCommonDirection (const Vector3 & vec) virtual
Use this to specify the common direction given to billboards of type BBT_ORIENTED_COMMON or BBT_PERPENDICULAR_COMMON.
Remarks
Use BBT_ORIENTED_COMMON when you want oriented billboards but you know they are always going to be oriented the same way (e.g. rain in calm weather). It is faster for the system to calculate the billboard vertices if they have a common direction.
The common direction also use in BBT_PERPENDICULAR_COMMON, in this case the common direction treat as Z axis, and an additional common up-vector was use to determine billboard X and Y axis.
See also
setCommonUpVector
Parameters
vec The direction for all billboards.
Note
The direction are use as is, never normalised in internal, user are supposed to normalise it himself.
getCommonDirection()
virtual const Vector3& Ogre::BillboardSet::getCommonDirection (void) const virtual
Gets the common direction for all billboards (BBT_ORIENTED_COMMON)
setCommonUpVector()
virtual void Ogre::BillboardSet::setCommonUpVector (const Vector3 & vec) virtual
Use this to specify the common up-vector given to billboards of type BBT_PERPENDICULAR_SELF or BBT_PERPENDICULAR_COMMON.
Remarks
Use BBT_PERPENDICULAR_SELF or BBT_PERPENDICULAR_COMMON when you want oriented billboards perpendicular to specify direction vector (or, Z axis), and doesn't face to camera. In this case, we need an additional up-vector to determine the billboard X and Y axis. The generated billboard plane and X-axis guarantee perpendicular to specify direction.
See also
setCommonDirection
The specify direction is billboard own direction when billboard type is BBT_PERPENDICULAR_SELF, and it's shared common direction when billboard type is BBT_PERPENDICULAR_COMMON.
Parameters
vec The up-vector for all billboards.
Note
The up-vector are use as is, never normalised in internal, user are supposed to normalise it himself.
getCommonUpVector()
virtual const Vector3& Ogre::BillboardSet::getCommonUpVector (void) const virtual
Gets the common up-vector for all billboards (BBT_PERPENDICULAR_SELF and BBT_PERPENDICULAR_COMMON)
setUseAccurateFacing()
virtual void Ogre::BillboardSet::setUseAccurateFacing (bool acc) inline virtual
Sets whether or not billboards should use an 'accurate' facing model based on the vector from each billboard to the camera, rather than an optimised version using just the camera direction.
Remarks
By default, the axes for all billboards are calculated using the camera's view direction, not the vector from the camera position to the billboard. The former is faster, and most of the time the difference is not noticeable. However for some purposes (e.g. very large, static billboards) the changing billboard orientation when rotating the camera can be off putting, therefore you can enable this option to use a more expensive, but more accurate version.
Parameters
acc True to use the slower but more accurate model. Default is false.
getUseAccurateFacing()
virtual bool Ogre::BillboardSet::getUseAccurateFacing (void) const inline virtual
Gets whether or not billboards use an 'accurate' facing model based on the vector from each billboard to the camera, rather than an optimised version using just the camera direction.
getMovableType()
virtual const String& Ogre::BillboardSet::getMovableType (void) const virtual
Overridden from MovableObject.
Implements Ogre::MovableObject.
getSquaredViewDepth()
Real Ogre::BillboardSet::getSquaredViewDepth (const Camera * cam) const virtual
Overridden, see Renderable.
Implements Ogre::Renderable.
_updateBounds()
virtual void Ogre::BillboardSet::_updateBounds (void) virtual
Update the bounds of the billboardset.
getLights()
const LightList& Ogre::BillboardSet::getLights (void) const virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
visitRenderables()
void Ogre::BillboardSet::visitRenderables (Renderable::Visitor * visitor, bool debugRenderables = false) virtual
Method to allow a caller to abstractly iterate over the Renderable instances that this MovableObject will add to the render queue when asked, if any.
Parameters
visitor Pointer to a class implementing the Renderable::Visitor interface which will be called back for each Renderable which will be queued. Bear in mind that the state of the Renderable instances may not be finalised depending on when you call this.
debugRenderables If false, only regular renderables will be visited (those for normal display). If true, debug renderables will be included too.
Implements Ogre::MovableObject.
_sortBillboards()
virtual void Ogre::BillboardSet::_sortBillboards (Camera * cam) virtual
Sort the billboard set.
Only called when enabled via setSortingEnabled
_getSortMode()
virtual SortMode Ogre::BillboardSet::_getSortMode (void) const virtual
Gets the sort mode of this billboard set.
setBillboardsInWorldSpace()
virtual void Ogre::BillboardSet::setBillboardsInWorldSpace (bool ws) inline virtual
Sets whether billboards should be treated as being in world space.
Remarks
This is most useful when you are driving the billboard set from an external data source.
getBillboardsInWorldSpace()
bool Ogre::BillboardSet::getBillboardsInWorldSpace () inline
Gets whether billboards are treated as being in world space.
setTextureCoords()
virtual void Ogre::BillboardSet::setTextureCoords (Ogre::FloatRect const * coords, uint16 numCoords) virtual
BillboardSet can use custom texture coordinates for various billboards.
This is useful for selecting one of many particle images out of a tiled texture sheet, or doing flipbook animation within a single texture.
The generic functionality is setTextureCoords(), which will copy the texture coordinate rects you supply into internal storage for the billboard set. If your texture sheet is a square grid, you can also use setTextureStacksAndSlices() for more convenience, which will construct the set of texture coordinates for you.
When a Billboard is created, it can be assigned a texture coordinate set from within the sets you specify (that set can also be re-specified later). When drawn, the billboard will use those texture coordinates, rather than the full 0-1 range.
Parameters
coords is a vector of texture coordinates (in UV space) to choose from for each billboard created in the set.
numCoords is how many such coordinate rectangles there are to choose from.
Remarks
Set 'coords' to 0 and/or 'numCoords' to 0 to reset the texture coord rects to the initial set of a single rectangle spanning 0 through 1 in both U and V (i e, the entire texture).
See also
BillboardSet::setTextureStacksAndSlices() Billboard::setTexcoordIndex()
setTextureStacksAndSlices()
virtual void Ogre::BillboardSet::setTextureStacksAndSlices (uchar stacks, uchar slices) virtual
setTextureStacksAndSlices() will generate texture coordinate rects as if the texture for the billboard set contained 'stacks' rows of 'slices' images each, all equal size.
Thus, if the texture size is 512x512 and 'stacks' is 4 and 'slices' is 8, each sub-rectangle of the texture would be 128 texels tall and 64 texels wide.
Remarks
This function is short-hand for creating a regular set and calling setTextureCoords() yourself. The numbering used for Billboard::setTexcoordIndex() counts first across, then down, so top-left is 0, the one to the right of that is 1, and the lower-right is stacks*slices-1.
See also
BillboardSet::setTextureCoords()
getTextureCoords()
virtual Ogre::FloatRect const* Ogre::BillboardSet::getTextureCoords (uint16 * oNumCoords) virtual
getTextureCoords() returns the current texture coordinate rects in effect.
By default, there is only one texture coordinate rect in the set, spanning the entire texture from 0 through 1 in each direction.
See also
BillboardSet::setTextureCoords()
setPointRenderingEnabled()
virtual void Ogre::BillboardSet::setPointRenderingEnabled (bool enabled) virtual
Set whether or not the BillboardSet will use point rendering rather than manually generated quads.
Remarks
By default a billboardset is rendered by generating geometry for a textured quad in memory, taking into account the size and orientation settings, and uploading it to the video card. The alternative is to use hardware point rendering, which means that only one position needs to be sent per billboard rather than 4 and the hardware sorts out how this is rendered based on the render state.
Using point rendering is faster than generating quads manually, but is more restrictive. The following restrictions apply:
Only the BBT_POINT type is supported
Size and appearance of each billboard is controlled by the material (Pass::setPointSize, Pass::setPointSizeAttenuation, Pass::setPointSpritesEnabled)
Per-billboard size is not supported (stems from the above)
Per-billboard rotation is not supported, this can only be controlled through texture unit rotation
Only BBO_CENTER origin is supported
Per-billboard texture coordinates are not supported
You will almost certainly want to enable in your material pass both point attenuation and point sprites if you use this option.
Parameters
enabled True to enable point rendering, false otherwise
isPointRenderingEnabled()
virtual bool Ogre::BillboardSet::isPointRenderingEnabled (void) const inline virtual
Returns whether point rendering is enabled.
getTypeFlags()
uint32 Ogre::BillboardSet::getTypeFlags (void) const virtual
Override to return specific type flag.
Reimplemented from Ogre::MovableObject.
setAutoUpdate()
void Ogre::BillboardSet::setAutoUpdate (bool autoUpdate)
Set the auto update state of this billboard set.
Remarks
This methods controls the updating policy of the vertex buffer. By default auto update is true so the vertex buffer is being update every time this billboard set is about to be rendered. This behavior best fit when the billboards of this set changes frequently. When using static or semi-static billboards, it is recommended to set auto update to false. In that case one should call notifyBillboardDataChanged method to reflect changes made to the billboards data.
getAutoUpdate()
bool Ogre::BillboardSet::getAutoUpdate (void) const inline
Return the auto update state of this billboard set.
notifyBillboardDataChanged()
void Ogre::BillboardSet::notifyBillboardDataChanged (void) inline
When billboard set is not auto updating its GPU buffer, the user is responsible to inform it about any billboard changes in order to reflect them at the rendering stage.
Calling this method will cause GPU buffers update in the next render queue update.
_releaseManualHardwareResources()
void Ogre::BillboardSet::_releaseManualHardwareResources () inline virtual
Notifies the movable object that hardware resources were lost.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented from Ogre::MovableObject.
_notifyCreator()
virtual void Ogre::MovableObject::_notifyCreator (MovableObjectFactory * fact) inline virtual inherited
Notify the object of it's creator (internal use only)
_getCreator()
MovableObjectFactory* Ogre::MovableObject::_getCreator (void) const inline inherited
Get the creator of this object, if any (internal use only)
_notifyManager()
virtual void Ogre::MovableObject::_notifyManager (SceneManager * man) inline virtual inherited
Notify the object of it's manager (internal use only)
_getManager()
SceneManager* Ogre::MovableObject::_getManager (void) const inline inherited
Get the manager of this object, if any (internal use only)
_restoreManualHardwareResources()
virtual void Ogre::MovableObject::_restoreManualHardwareResources () inline virtual inherited
Notifies the movable object that hardware resources should be restored.
Remarks
Called automatically by RenderSystem if hardware resources were lost and can not be restored using some internal mechanism. Among affected resources are nested shadow renderables, ManualObjects, etc.
Reimplemented in Ogre::StaticGeometry::Region, and Ogre::Entity.
getName()
const String& Ogre::MovableObject::getName (void) const inline inherited
Returns the name of this object.
getParentNode()
Node* Ogre::MovableObject::getParentNode (void) const inline inherited
Returns the node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. Both are Node subclasses so this method will return either.
getParentSceneNode()
SceneNode* Ogre::MovableObject::getParentSceneNode (void) const inherited
Returns the scene node to which this object is attached.
Remarks
A MovableObject may be attached to either a SceneNode or to a TagPoint, the latter case if it's attached to a bone on an animated entity. This method will return the scene node of the parent entity if the latter is true.
isParentTagPoint()
bool Ogre::MovableObject::isParentTagPoint () const inline inherited
Gets whether the parent node is a TagPoint (or a SceneNode)
_notifyAttached()
virtual void Ogre::MovableObject::_notifyAttached (Node * parent, bool isTagPoint = false) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::Entity, Ogre::ParticleSystem, Ogre::Light, Ogre::PortalBase, and Ogre::InstancedEntity.
Referenced by Ogre::PortalBase::_notifyAttached().
isAttached()
bool Ogre::MovableObject::isAttached (void) const inline inherited
Returns true if this object is attached to a SceneNode or TagPoint.
detachFromParent()
void Ogre::MovableObject::detachFromParent (void) inherited
Detaches an object from a parent SceneNode or TagPoint, if attached.
isInScene()
virtual bool Ogre::MovableObject::isInScene (void) const virtual inherited
Returns true if this object is attached to a SceneNode or TagPoint, and this SceneNode / TagPoint is currently in an active part of the scene graph.
Reimplemented in Ogre::InstancedEntity.
_notifyMoved()
virtual void Ogre::MovableObject::_notifyMoved (void) virtual inherited
Internal method called to notify the object that it has been moved.
Reimplemented in Ogre::Light, Ogre::PortalBase, Ogre::InstancedEntity, and Ogre::PCZLight.
getWorldBoundingBox()
virtual const AxisAlignedBox& Ogre::MovableObject::getWorldBoundingBox (bool derive = false) const virtual inherited
Retrieves the axis-aligned bounding box for this object in world coordinates.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
getWorldBoundingSphere()
virtual const Sphere& Ogre::MovableObject::getWorldBoundingSphere (bool derive = false) const virtual inherited
Retrieves the worldspace bounding sphere for this object.
Reimplemented in Ogre::Entity, and Ogre::PortalBase.
setVisible()
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
Referenced by Ogre::Light::setVisible().
getVisible()
bool Ogre::MovableObject::getVisible (void) const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
isVisible()
virtual bool Ogre::MovableObject::isVisible (void) const virtual inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account both upper rendering distance and visible flag.
Reimplemented in Ogre::InstancedGeometry::BatchInstance, and Ogre::StaticGeometry::Region.
Referenced by Ogre::Frustum::isCustomProjectionMatrixEnabled().
setRenderingDistance()
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Note
Camera::setUseRenderingDistance() needs to be called for this parameter to be used.
Parameters
dist Distance beyond which the object will not be rendered (the default is 0, which means objects are always rendered).
getRenderingDistance()
Real Ogre::MovableObject::getRenderingDistance (void) const inline inherited
Gets the distance at which batches are no longer rendered.
setRenderingMinPixelSize()
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
getRenderingMinPixelSize()
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
setUserAny() [1/2]
void Ogre::MovableObject::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this MovableObject. This can be a pointer back to one of your own classes for instance.
getUserAny() [1/2]
const Any& Ogre::MovableObject::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
getUserObjectBindings() [1/4]
UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/4]
const UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
setRenderQueueGroup()
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
setRenderQueueGroupAndPriority()
virtual void Ogre::MovableObject::setRenderQueueGroupAndPriority (uint8 queueID, ushort priority) virtual inherited
Sets the render queue group and group priority this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. Within a single render group there another type of grouping called priority which allows further control. If you do not call this method, all Entity objects default to the default queue and priority (RenderQueue::getDefaultQueueGroup, RenderQueue::getDefaultRenderablePriority), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
priority The priority within a group to use.
Reimplemented in Ogre::ParticleSystem, and Ogre::Entity.
getRenderQueueGroup()
uint8 Ogre::MovableObject::getRenderQueueGroup (void) const inline inherited
Gets the queue group for this entity.
See also
setRenderQueueGroup
_getParentNodeFullTransform()
virtual const Matrix4& Ogre::MovableObject::_getParentNodeFullTransform (void) const virtual inherited
Return the full transformation of the parent sceneNode or the attachingPoint node.
Reimplemented in Ogre::InstancedEntity.
setQueryFlags()
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
addQueryFlags()
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
removeQueryFlags()
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
getQueryFlags()
uint32 Ogre::MovableObject::getQueryFlags (void) const inline inherited
Returns the query flags relevant for this object.
setDefaultQueryFlags()
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
getDefaultQueryFlags()
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
setVisibilityFlags()
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags which when 'and'ed with the SceneManager's visibility mask can also make an object invisible.
addVisibilityFlags()
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
removeVisibilityFlags()
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
getVisibilityFlags()
uint32 Ogre::MovableObject::getVisibilityFlags (void) const inline inherited
Returns the visibility flags relevant for this object.
setDefaultVisibilityFlags()
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
getDefaultVisibilityFlags()
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
setListener()
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
getListener()
Listener* Ogre::MovableObject::getListener (void) const inline inherited
Gets the current listener for this object.
queryLights()
const LightList& Ogre::MovableObject::queryLights (void) const inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
By default, this method gives the listener a chance to populate light list first, if there is no listener or Listener::objectQueryLights returns NULL, it'll query the light list from parent entity if it is present, or returns SceneNode::findLights if it has parent scene node, otherwise it just returns an empty list.
The object internally caches the light list, so it will recalculate it only when object is moved, or lights that affect the frustum have been changed (
See also
SceneManager::_getLightsDirtyCounter), but if listener exists, it will be called each time, so the listener should implement their own cache mechanism to optimise performance.
This method can be useful when implementing Renderable::getLights in case the renderable is a part of the movable.
Returns
The list of lights use to lighting this object.
getLightMask()
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
setLightMask()
void Ogre::MovableObject::setLightMask (uint32 lightMask) inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
_getLightList()
LightList* Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
getEdgeList()
EdgeData* Ogre::MovableObject::getEdgeList (void) inline virtual inherited
Returns details of the edges which might be used to determine a silhouette.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
hasEdgeList()
bool Ogre::MovableObject::hasEdgeList (void) inline virtual inherited
Returns whether the object has a valid edge list.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
getShadowVolumeRenderableIterator()
ShadowRenderableListIterator Ogre::MovableObject::getShadowVolumeRenderableIterator (ShadowTechnique shadowTechnique, const Light * light, HardwareIndexBufferSharedPtr * indexBuffer, size_t * indexBufferUsedSize, bool extrudeVertices, Real extrusionDist, unsigned long flags = 0) virtual inherited
Define a default implementation of method from ShadowCaster which implements no shadows.
Implements Ogre::ShadowCaster.
Reimplemented in Ogre::StaticGeometry::Region.
getLightCapBounds()
const AxisAlignedBox& Ogre::MovableObject::getLightCapBounds (void) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
getDarkCapBounds()
const AxisAlignedBox& Ogre::MovableObject::getDarkCapBounds (const Light & light, Real dirLightExtrusionDist) const virtual inherited
Overridden member from ShadowCaster.
Implements Ogre::ShadowCaster.
setCastShadows()
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
getCastShadows()
bool Ogre::MovableObject::getCastShadows (void) const inline virtual inherited
Returns whether shadow casting is enabled for this object.
Implements Ogre::ShadowCaster.
getReceivesShadows()
bool Ogre::MovableObject::getReceivesShadows () inherited
Returns whether the Material of any Renderable that this MovableObject will add to the render queue will receive shadows.
getPointExtrusionDistance()
Real Ogre::MovableObject::getPointExtrusionDistance (const Light * l) const virtual inherited
Get the distance to extrude for a point/spot light.
Implements Ogre::ShadowCaster.
setDebugDisplayEnabled()
void Ogre::MovableObject::setDebugDisplayEnabled (bool enabled) inline inherited
Sets whether or not the debug display of this object is enabled.
Remarks
Some objects aren't visible themselves but it can be useful to display a debug representation of them. Or, objects may have an additional debug display on top of their regular display. This option enables / disables that debug display. Objects that are not visible never display debug geometry regardless of this setting.
isDebugDisplayEnabled()
bool Ogre::MovableObject::isDebugDisplayEnabled (void) const inline inherited
Gets whether debug display of this object is enabled.
clearShadowRenderableList()
static void Ogre::ShadowCaster::clearShadowRenderableList (ShadowRenderableList & shadowRenderables) static inherited
Common implementation of releasing shadow renderables.
extrudeVertices()
static void Ogre::ShadowCaster::extrudeVertices (const HardwareVertexBufferSharedPtr & vertexBuffer, size_t originalVertexCount, const Vector4 & lightPos, Real extrudeDist) static inherited
Utility method for extruding vertices based on a light.
Remarks
Unfortunately, because D3D cannot handle homogeneous (4D) position coordinates in the fixed-function pipeline (GL can, but we have to be cross-API), when we extrude in software we cannot extrude to infinity the way we do in the vertex program (by setting w to 0.0f). Therefore we extrude by a fixed distance, which may cause some problems with larger scenes. Luckily better hardware (ie vertex programs) can fix this.
Parameters
vertexBuffer The vertex buffer containing ONLY xyz position values, which must be originalVertexCount * 2 * 3 floats long.
originalVertexCount The count of the original number of vertices, i.e. the number in the mesh, not counting the doubling which has already been done (by VertexData::prepareForShadowVolume) to provide the extruded area of the buffer.
lightPos 4D light position in object space, when w=0.0f this represents a directional light.
extrudeDist The distance to extrude.
getAnimableValueNames()
const StringVector& Ogre::AnimableObject::getAnimableValueNames (void) const inline inherited
Gets a list of animable value names for this object.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
createAnimableValue()
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
getTechnique()
virtual Technique* Ogre::Renderable::getTechnique (void) const inline virtual inherited
Retrieves a pointer to the Material Technique this renderable object uses.
Remarks
This is to allow Renderables to use a chosen Technique if they wish, otherwise they will use the best Technique available for the Material they are using.
Reimplemented in Ogre::InstanceBatch, Ogre::InstancedGeometry::GeometryBucket, Ogre::StaticGeometry::GeometryBucket, and Ogre::SubEntity.
preRender()
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::BillboardChain.
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
getNumWorldTransforms()
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::BorderRenderable, Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, Ogre::BaseInstanceBatchVTF, Ogre::InstanceBatchHW, and Ogre::InstanceBatchShader.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
getCastsShadows()
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, and Ogre::StaticGeometry::GeometryBucket.
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
getCustomParameter()
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
_updateCustomGpuParameter()
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
setPolygonModeOverrideable()
void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
getPolygonModeOverrideable()
bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Referenced by Ogre::BorderRenderable::getPolygonModeOverrideable().
setUserAny() [2/2]
void Ogre::Renderable::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserAny() [2/2]
const Any& Ogre::Renderable::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserObjectBindings() [3/4]
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [4/4]
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getRenderSystemData()
const RenderSystemDataPtr& Ogre::Renderable::getRenderSystemData () const inline inherited
Gets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
setRenderSystemData()
void Ogre::Renderable::setRenderSystemData (RenderSystemDataPtr val) const inline inherited
Sets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
The documentation for this class was generated from the following file:
OgreBillboardSet.h