OGRE: Ogre::GL3PlusFBOMultiRenderTarget Class Reference
Ogre::GL3PlusFBOMultiRenderTarget Class Reference
MultiRenderTarget for OpenGL.
#include <OgreGL3PlusFBOMultiRenderTarget.h>
Public Types
typedef vector< RenderTexture * >::type BoundSufaceList
enum FrameBuffer { FB_FRONT, FB_BACK, FB_AUTO }
enum StatFlags {
SF_NONE = 0, SF_FPS = 1, SF_AVG_FPS = 2, SF_BEST_FPS = 4,
SF_WORST_FPS = 8, SF_TRIANGLE_COUNT = 16, SF_ALL = 0xFFFF
}
Public Member Functions
GL3PlusFBOMultiRenderTarget (GL3PlusFBOManager *manager, const String &name)
~GL3PlusFBOMultiRenderTarget ()
virtual void _beginUpdate ()
Method for manual management of rendering : fires 'preRenderTargetUpdate' and initialises statistics etc.
virtual void _detachDepthBuffer ()
Detaches DepthBuffer without notifying it from the detach.
virtual void _endUpdate ()
Method for manual management of rendering - finishes statistics calculation and fires 'postRenderTargetUpdate'.
virtual Impl * _getImpl ()
Get rendersystem specific interface for this RenderTarget.
virtual void _notifyCameraRemoved (const Camera *cam)
Utility method to notify a render target that a camera has been removed, incase it was referring to it as a viewer.
virtual void _updateAutoUpdatedViewports (bool updateStatistics=true)
Method for manual management of rendering - renders only viewports that are auto updated.
virtual void _updateViewport (int zorder, bool updateStatistics=true)
Method for manual management of rendering - renders the given viewport (even if it is not autoupdated)
virtual void _updateViewport (Viewport *viewport, bool updateStatistics=true)
Method for manual management of rendering - renders the given viewport (even if it is not autoupdated)
virtual void addListener (RenderTargetListener *listener)
Add a listener to this RenderTarget which will be called back before & after rendering.
virtual Viewport * addViewport (Camera *cam, int ZOrder=0, float left=0.0f, float top=0.0f, float width=1.0f, float height=1.0f)
Adds a viewport to the rendering target.
virtual bool attachDepthBuffer (DepthBuffer *depthBuffer)
Override so we can attach the depth buffer to the FBO.
virtual void bindSurface (size_t attachment, RenderTexture *target)
Bind a surface to a certain attachment point.
virtual void copyContentsToMemory (const Box &src, const PixelBox &dst, FrameBuffer buffer=FB_AUTO)
Error throwing implementation, it's not possible to write a MultiRenderTarget to disk.
void copyContentsToMemory (const PixelBox &dst, FrameBuffer buffer=FB_AUTO)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
virtual void detachDepthBuffer ()
virtual float getAverageFPS () const
virtual size_t getBatchCount (void) const
virtual float getBestFPS () const
virtual float getBestFrameTime () const
RenderTexture * getBoundSurface (size_t index)
Get a pointer to a bound surface.
const BoundSufaceList & getBoundSurfaceList () const
Get a list of the surfaces which have been bound.
virtual uint32 getColourDepth (void) const
virtual void getCustomAttribute (const String &name, void *pData)
Gets a custom (maybe platform-specific) attribute.
DepthBuffer * getDepthBuffer () const
uint16 getDepthBufferPool () const
virtual uint getFSAA () const
Indicates whether multisampling is performed on rendering and at what level.
virtual const String & getFSAAHint () const
Gets the FSAA hint (.
virtual uint32 getHeight (void) const
virtual float getLastFPS () const
virtual void getMetrics (unsigned int &width, unsigned int &height, unsigned int &colourDepth)
Retrieve information about the render target.
virtual const String & getName (void) const
Retrieve target's name.
virtual unsigned short getNumViewports (void) const
Returns the number of viewports attached to this target.
virtual uchar getPriority () const
Gets the priority of a render target.
virtual void getStatistics (float &lastFPS, float &avgFPS, float &bestFPS, float &worstFPS) const
Retieves details of current rendering performance.
const FrameStats & getStatistics (void) const
Retieves details of current rendering performance.
virtual size_t getTriangleCount (void) const
virtual Viewport * getViewport (unsigned short index)
Retrieves a pointer to the viewport with the given index.
virtual Viewport * getViewportByZOrder (int ZOrder)
Retrieves a pointer to the viewport with the given Z-order.
virtual uint32 getWidth (void) const
virtual float getWorstFPS () const
virtual float getWorstFrameTime () const
virtual bool hasViewportWithZOrder (int ZOrder)
Returns true if and only if a viewport exists at the given Z-order.
virtual void insertListener (RenderTargetListener *listener, const unsigned int pos=0)
same as addListener, but force the position in the vector, so we can control the call order
virtual bool isActive () const
Used to retrieve or set the active state of the render target.
virtual bool isAutoUpdated (void) const
Gets whether this target is automatically updated if Ogre's rendering loop or Root::_updateAllRenderTargets is being used.
virtual bool isHardwareGammaEnabled () const
Indicates whether on rendering, linear colour space is converted to sRGB gamma colour space.
virtual bool isPrimary (void) const
Indicates whether this target is the primary window.
virtual bool isStereoEnabled (void) const
Indicates whether stereo is currently enabled for this target.
virtual void removeAllListeners (void)
Removes all listeners from this instance.
virtual void removeAllViewports (void)
Removes all viewports on this target.
virtual void removeListener (RenderTargetListener *listener)
Removes a RenderTargetListener previously registered using addListener.
virtual void removeViewport (int ZOrder)
Removes a viewport at a given Z-order.
bool requiresTextureFlipping () const
void resetStatistics (void)
Resets saved frame-rate statistices.
virtual void setActive (bool state)
Used to set the active state of the render target.
virtual void setAutoUpdated (bool autoupdate)
Sets whether this target should be automatically updated if Ogre's rendering loop or Root::_updateAllRenderTargets is being used.
void setDepthBufferPool (uint16 poolId)
Sets the pool ID this RenderTarget should query from.
virtual void setFSAA (uint fsaa, const String &fsaaHint)
Set the level of multisample AA to be used if hardware support it.
virtual void setPriority (uchar priority)
Sets the priority of this render target in relation to the others.
PixelFormat suggestPixelFormat () const
Irrelevant implementation since cannot copy.
virtual void swapBuffers ()
Swaps the frame buffers to display the next frame.
virtual void unbindSurface (size_t attachment)
Unbind attachment.
virtual void update (bool swapBuffers=true)
Tells the target to update it's contents.
void writeContentsToFile (const String &filename)
Writes the current contents of the render target to the named file.
virtual String writeContentsToTimestampedFile (const String &filenamePrefix, const String &filenameSuffix)
Writes the current contents of the render target to the (PREFIX)(time-stamp)(SUFFIX) file.
Detailed Description
MultiRenderTarget for OpenGL.
Member Typedef Documentation
BoundSufaceList
typedef vector<RenderTexture*>::type Ogre::MultiRenderTarget::BoundSufaceList inherited
Member Enumeration Documentation
StatFlags
enum Ogre::RenderTarget::StatFlags inherited
Enumerator
SF_NONE
SF_FPS
SF_AVG_FPS
SF_BEST_FPS
SF_WORST_FPS
SF_TRIANGLE_COUNT
SF_ALL
FrameBuffer
enum Ogre::RenderTarget::FrameBuffer inherited
Enumerator
FB_FRONT
FB_BACK
FB_AUTO
Constructor & Destructor Documentation
GL3PlusFBOMultiRenderTarget()
Ogre::GL3PlusFBOMultiRenderTarget::GL3PlusFBOMultiRenderTarget (GL3PlusFBOManager * manager, const String & name)
~GL3PlusFBOMultiRenderTarget()
Ogre::GL3PlusFBOMultiRenderTarget::~GL3PlusFBOMultiRenderTarget ()
Member Function Documentation
getCustomAttribute()
virtual void Ogre::GL3PlusFBOMultiRenderTarget::getCustomAttribute (const String & name, void * pData) virtual
Gets a custom (maybe platform-specific) attribute.
Remarks
This is a nasty way of satisfying any API's need to see platform-specific details. It horrid, but D3D needs this kind of info. At least it's abstracted.
Parameters
name The name of the attribute.
pData Pointer to memory of the right kind of structure to receive the info.
Reimplemented from Ogre::RenderTarget.
requiresTextureFlipping()
bool Ogre::GL3PlusFBOMultiRenderTarget::requiresTextureFlipping () const inline virtual
Implements Ogre::RenderTarget.
attachDepthBuffer()
virtual bool Ogre::GL3PlusFBOMultiRenderTarget::attachDepthBuffer (DepthBuffer * depthBuffer) virtual
Override so we can attach the depth buffer to the FBO.
Reimplemented from Ogre::RenderTarget.
detachDepthBuffer()
virtual void Ogre::GL3PlusFBOMultiRenderTarget::detachDepthBuffer () virtual
Reimplemented from Ogre::RenderTarget.
_detachDepthBuffer()
virtual void Ogre::GL3PlusFBOMultiRenderTarget::_detachDepthBuffer () virtual
Detaches DepthBuffer without notifying it from the detach.
Useful when called from the DepthBuffer while it iterates through attached RenderTargets (
See also
DepthBuffer::_setPoolId())
Reimplemented from Ogre::RenderTarget.
bindSurface()
virtual void Ogre::MultiRenderTarget::bindSurface (size_t attachment, RenderTexture * target) inline virtual inherited
Bind a surface to a certain attachment point.
Parameters
attachment 0 .. mCapabilities->getNumMultiRenderTargets()-1
target RenderTexture to bind.
It does not bind the surface and fails with an exception (ERR_INVALIDPARAMS) if:
Not all bound surfaces have the same size
Not all bound surfaces have the same internal format
unbindSurface()
virtual void Ogre::MultiRenderTarget::unbindSurface (size_t attachment) inline virtual inherited
Unbind attachment.
References Ogre::RenderTarget::copyContentsToMemory().
copyContentsToMemory() [1/2]
virtual void Ogre::MultiRenderTarget::copyContentsToMemory (const Box & src, const PixelBox & dst, FrameBuffer buffer = FB_AUTO) virtual inherited
Error throwing implementation, it's not possible to write a MultiRenderTarget to disk.
Implements Ogre::RenderTarget.
copyContentsToMemory() [2/2]
void Ogre::RenderTarget::copyContentsToMemory (const PixelBox & dst, FrameBuffer buffer = FB_AUTO) inline inherited
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Deprecated:
This function is deprecated as behavior for dst.size < RenderTarget.size was inconsistent in previous versions of Ogre.
Sometimes the whole rect was used as a source, sometimes the rect with the size equal to the size of destination rect but located in the top left corner of the render target, sometimes the destination rect itself. Use the overload with explicitly specified source and destination boxes instead.
References Ogre::RenderTarget::copyContentsToMemory().
Referenced by Ogre::RenderTarget::copyContentsToMemory().
suggestPixelFormat()
PixelFormat Ogre::MultiRenderTarget::suggestPixelFormat () const inline virtual inherited
Irrelevant implementation since cannot copy.
Reimplemented from Ogre::RenderTarget.
References Ogre::PF_UNKNOWN.
getBoundSurfaceList()
const BoundSufaceList& Ogre::MultiRenderTarget::getBoundSurfaceList () const inline inherited
Get a list of the surfaces which have been bound.
getBoundSurface()
RenderTexture* Ogre::MultiRenderTarget::getBoundSurface (size_t index) inline inherited
Get a pointer to a bound surface.
getName()
virtual const String& Ogre::RenderTarget::getName (void) const virtual inherited
Retrieve target's name.
getMetrics()
virtual void Ogre::RenderTarget::getMetrics (unsigned int & width, unsigned int & height, unsigned int & colourDepth) virtual inherited
Retrieve information about the render target.
Referenced by Ogre::RenderWindow::isActive().
getWidth()
virtual uint32 Ogre::RenderTarget::getWidth (void) const virtual inherited
getHeight()
virtual uint32 Ogre::RenderTarget::getHeight (void) const virtual inherited
getColourDepth()
virtual uint32 Ogre::RenderTarget::getColourDepth (void) const virtual inherited
setDepthBufferPool()
void Ogre::RenderTarget::setDepthBufferPool (uint16 poolId) inherited
Sets the pool ID this RenderTarget should query from.
Default value is POOL_DEFAULT. Set to POOL_NO_DEPTH to avoid using a DepthBuffer (or manually controlling it)
See also
DepthBuffer
Remarks
Changing the pool Id will cause the current depth buffer to be detached unless the old id and the new one are the same
getDepthBufferPool()
uint16 Ogre::RenderTarget::getDepthBufferPool () const inherited
getDepthBuffer()
DepthBuffer* Ogre::RenderTarget::getDepthBuffer () const inherited
update()
virtual void Ogre::RenderTarget::update (bool swapBuffers = true) virtual inherited
Tells the target to update it's contents.
Remarks
If OGRE is not running in an automatic rendering loop (started using Root::startRendering), the user of the library is responsible for asking each render target to refresh. This is the method used to do this. It automatically re-renders the contents of the target using whatever cameras have been pointed at it (using Camera::setRenderTarget).
This allows OGRE to be used in multi-windowed utilities and for contents to be refreshed only when required, rather than constantly as with the automatic rendering loop.
Parameters
swapBuffers For targets that support double-buffering, if set to true, the target will immediately swap it's buffers after update. Otherwise, the buffers are not swapped, and you have to call swapBuffers yourself sometime later. You might want to do this on some rendersystems which pause for queued rendering commands to complete before accepting swap buffers calls - so you could do other CPU tasks whilst the queued commands complete. Or, you might do this if you want custom control over your windows, such as for externally created windows.
Reimplemented in Ogre::D3D9RenderTexture, and Ogre::D3D9MultiRenderTarget.
swapBuffers()
virtual void Ogre::RenderTarget::swapBuffers () inline virtual inherited
Swaps the frame buffers to display the next frame.
Remarks
For targets that are double-buffered so that no 'in-progress' versions of the scene are displayed during rendering. Once rendering has completed (to an off-screen version of the window) the buffers are swapped to display the new frame.
Reimplemented in Ogre::D3D9RenderTexture, Ogre::D3D11RenderWindowSwapChainBased, Ogre::NaClWindow, Ogre::D3D9RenderWindow, Ogre::GLFBORenderTexture, Ogre::GL3PlusFBORenderTexture, and Ogre::GLES2FBORenderTexture.
addViewport()
virtual Viewport* Ogre::RenderTarget::addViewport (Camera * cam, int ZOrder = 0, float left = 0.0f, float top = 0.0f, float width = 1.0f, float height = 1.0f) virtual inherited
Adds a viewport to the rendering target.
Remarks
A viewport is the rectangle into which rendering output is sent. This method adds a viewport to the render target, rendering from the supplied camera. The rest of the parameters are only required if you wish to add more than one viewport to a single rendering target. Note that size information passed to this method is passed as a parametric, i.e. it is relative rather than absolute. This is to allow viewports to automatically resize along with the target.
Parameters
cam The camera from which the viewport contents will be rendered (mandatory)
ZOrder The relative order of the viewport with others on the target (allows overlapping viewports i.e. picture-in-picture). Higher Z-orders are on top of lower ones. The actual number is irrelevant, only the relative Z-order matters (you can leave gaps in the numbering)
left The relative position of the left of the viewport on the target, as a value between 0 and 1.
top The relative position of the top of the viewport on the target, as a value between 0 and 1.
width The relative width of the viewport on the target, as a value between 0 and 1.
height The relative height of the viewport on the target, as a value between 0 and 1.
getNumViewports()
virtual unsigned short Ogre::RenderTarget::getNumViewports (void) const virtual inherited
Returns the number of viewports attached to this target.
getViewport()
virtual Viewport* Ogre::RenderTarget::getViewport (unsigned short index) virtual inherited
Retrieves a pointer to the viewport with the given index.
getViewportByZOrder()
virtual Viewport* Ogre::RenderTarget::getViewportByZOrder (int ZOrder) virtual inherited
Retrieves a pointer to the viewport with the given Z-order.
Remarks
throws if not found.
hasViewportWithZOrder()
virtual bool Ogre::RenderTarget::hasViewportWithZOrder (int ZOrder) virtual inherited
Returns true if and only if a viewport exists at the given Z-order.
removeViewport()
virtual void Ogre::RenderTarget::removeViewport (int ZOrder) virtual inherited
Removes a viewport at a given Z-order.
removeAllViewports()
virtual void Ogre::RenderTarget::removeAllViewports (void) virtual inherited
Removes all viewports on this target.
getStatistics() [1/2]
virtual void Ogre::RenderTarget::getStatistics (float & lastFPS, float & avgFPS, float & bestFPS, float & worstFPS) const virtual inherited
Retieves details of current rendering performance.
Remarks
If the user application wishes to do it's own performance display, or use performance for some other means, this method allows it to retrieve the statistics.
Parameters
lastFPS Pointer to a float to receive the number of frames per second (FPS) based on the last frame rendered.
avgFPS Pointer to a float to receive the FPS rating based on an average of all the frames rendered since rendering began (the call to Root::startRendering).
bestFPS Pointer to a float to receive the best FPS rating that has been achieved since rendering began.
worstFPS Pointer to a float to receive the worst FPS rating seen so far.
Deprecated:
use getStatistics()
getStatistics() [2/2]
const FrameStats& Ogre::RenderTarget::getStatistics (void) const inline inherited
Retieves details of current rendering performance.
getLastFPS()
virtual float Ogre::RenderTarget::getLastFPS () const virtual inherited
Deprecated:
use getStatistics()
getAverageFPS()
virtual float Ogre::RenderTarget::getAverageFPS () const virtual inherited
Deprecated:
use getStatistics()
getBestFPS()
virtual float Ogre::RenderTarget::getBestFPS () const virtual inherited
Deprecated:
use getStatistics()
getWorstFPS()
virtual float Ogre::RenderTarget::getWorstFPS () const virtual inherited
Deprecated:
use getStatistics()
getBestFrameTime()
virtual float Ogre::RenderTarget::getBestFrameTime () const virtual inherited
Deprecated:
use getStatistics()
getWorstFrameTime()
virtual float Ogre::RenderTarget::getWorstFrameTime () const virtual inherited
Deprecated:
use getStatistics()
resetStatistics()
void Ogre::RenderTarget::resetStatistics (void) inherited
Resets saved frame-rate statistices.
addListener()
virtual void Ogre::RenderTarget::addListener (RenderTargetListener * listener) virtual inherited
Add a listener to this RenderTarget which will be called back before & after rendering.
Remarks
If you want notifications before and after a target is updated by the system, use this method to register your own custom RenderTargetListener class. This is useful for potentially adding your own manual rendering commands before and after the 'normal' system rendering.
NB this should not be used for frame-based scene updates, use Root::addFrameListener for that.
insertListener()
virtual void Ogre::RenderTarget::insertListener (RenderTargetListener * listener, const unsigned int pos = 0) virtual inherited
same as addListener, but force the position in the vector, so we can control the call order
removeListener()
virtual void Ogre::RenderTarget::removeListener (RenderTargetListener * listener) virtual inherited
Removes a RenderTargetListener previously registered using addListener.
removeAllListeners()
virtual void Ogre::RenderTarget::removeAllListeners (void) virtual inherited
Removes all listeners from this instance.
setPriority()
virtual void Ogre::RenderTarget::setPriority (uchar priority) inline virtual inherited
Sets the priority of this render target in relation to the others.
Remarks
This can be used in order to schedule render target updates. Lower priorities will be rendered first. Note that the priority must be set at the time the render target is attached to the render system, changes afterwards will not affect the ordering.
getPriority()
virtual uchar Ogre::RenderTarget::getPriority () const inline virtual inherited
Gets the priority of a render target.
isActive()
virtual bool Ogre::RenderTarget::isActive () const virtual inherited
Used to retrieve or set the active state of the render target.
Reimplemented in Ogre::RenderWindow, and Ogre::D3D9RenderWindow.
setActive()
virtual void Ogre::RenderTarget::setActive (bool state) virtual inherited
Used to set the active state of the render target.
setAutoUpdated()
virtual void Ogre::RenderTarget::setAutoUpdated (bool autoupdate) virtual inherited
Sets whether this target should be automatically updated if Ogre's rendering loop or Root::_updateAllRenderTargets is being used.
Remarks
By default, if you use Ogre's own rendering loop (Root::startRendering) or call Root::_updateAllRenderTargets, all render targets are updated automatically. This method allows you to control that behaviour, if for example you have a render target which you only want to update periodically.
Parameters
autoupdate If true, the render target is updated during the automatic render loop or when Root::_updateAllRenderTargets is called. If false, the target is only updated when its update() method is called explicitly.
isAutoUpdated()
virtual bool Ogre::RenderTarget::isAutoUpdated (void) const virtual inherited
Gets whether this target is automatically updated if Ogre's rendering loop or Root::_updateAllRenderTargets is being used.
writeContentsToFile()
void Ogre::RenderTarget::writeContentsToFile (const String & filename) inherited
Writes the current contents of the render target to the named file.
writeContentsToTimestampedFile()
virtual String Ogre::RenderTarget::writeContentsToTimestampedFile (const String & filenamePrefix, const String & filenameSuffix) virtual inherited
Writes the current contents of the render target to the (PREFIX)(time-stamp)(SUFFIX) file.
Returns
the name of the file used.
getTriangleCount()
virtual size_t Ogre::RenderTarget::getTriangleCount (void) const virtual inherited
Deprecated:
use getStatistics()
getBatchCount()
virtual size_t Ogre::RenderTarget::getBatchCount (void) const virtual inherited
Deprecated:
use getStatistics()
_notifyCameraRemoved()
virtual void Ogre::RenderTarget::_notifyCameraRemoved (const Camera * cam) virtual inherited
Utility method to notify a render target that a camera has been removed, incase it was referring to it as a viewer.
isPrimary()
virtual bool Ogre::RenderTarget::isPrimary (void) const virtual inherited
Indicates whether this target is the primary window.
The primary window is special in that it is destroyed when ogre is shut down, and cannot be destroyed directly. This is the case because it holds the context for vertex, index buffers and textures.
Reimplemented in Ogre::RenderWindow.
isStereoEnabled()
virtual bool Ogre::RenderTarget::isStereoEnabled (void) const virtual inherited
Indicates whether stereo is currently enabled for this target.
Default is false.
isHardwareGammaEnabled()
virtual bool Ogre::RenderTarget::isHardwareGammaEnabled () const inline virtual inherited
Indicates whether on rendering, linear colour space is converted to sRGB gamma colour space.
This is the exact opposite conversion of what is indicated by Texture::isHardwareGammaEnabled, and can only be enabled on creation of the render target. For render windows, it's enabled through the 'gamma' creation misc parameter. For textures, it is enabled through the hwGamma parameter to the create call.
getFSAA()
virtual uint Ogre::RenderTarget::getFSAA () const inline virtual inherited
Indicates whether multisampling is performed on rendering and at what level.
getFSAAHint()
virtual const String& Ogre::RenderTarget::getFSAAHint () const inline virtual inherited
Gets the FSAA hint (.
See also
Root::createRenderWindow)
setFSAA()
virtual void Ogre::RenderTarget::setFSAA (uint fsaa, const String & fsaaHint) inline virtual inherited
Set the level of multisample AA to be used if hardware support it.
This option will be ignored if the hardware does not support it or setting can not be changed on the fly on per-target level.
Parameters
fsaa The number of samples
fsaaHint Any hinting text (
See also
Root::createRenderWindow)
Reimplemented in Ogre::D3D11RenderWindowSwapChainBased, and Ogre::D3D11RenderWindowBase.
_getImpl()
virtual Impl* Ogre::RenderTarget::_getImpl () virtual inherited
Get rendersystem specific interface for this RenderTarget.
This is used by the RenderSystem to (un)bind this target, and to get specific information like surfaces and framebuffer objects.
_beginUpdate()
virtual void Ogre::RenderTarget::_beginUpdate () virtual inherited
Method for manual management of rendering : fires 'preRenderTargetUpdate' and initialises statistics etc.
Remarks
_beginUpdate resets statistics and fires 'preRenderTargetUpdate'.
_updateViewport renders the given viewport (even if it is not autoupdated), fires preViewportUpdate and postViewportUpdate and manages statistics.
_updateAutoUpdatedViewports renders only viewports that are auto updated, fires preViewportUpdate and postViewportUpdate and manages statistics.
_endUpdate() ends statistics calculation and fires postRenderTargetUpdate.
you can use it like this for example :
    renderTarget->_beginUpdate();
    renderTarget->_updateViewport(1); // which is not auto updated
    renderTarget->_updateViewport(2); // which is not auto updated
    renderTarget->_updateAutoUpdatedViewports();
    renderTarget->_endUpdate();
    renderTarget->swapBuffers();
Please note that in that case, the zorder may not work as you expect, since you are responsible for calling _updateViewport in the correct order.
Reimplemented in Ogre::D3D9RenderWindow.
_updateViewport() [1/2]
virtual void Ogre::RenderTarget::_updateViewport (int zorder, bool updateStatistics = true) virtual inherited
Method for manual management of rendering - renders the given viewport (even if it is not autoupdated)
Remarks
This also fires preViewportUpdate and postViewportUpdate, and manages statistics. You should call it between _beginUpdate() and _endUpdate().
See also
_beginUpdate for more details.
Parameters
zorder The zorder of the viewport to update.
updateStatistics Whether you want to update statistics or not.
_updateViewport() [2/2]
virtual void Ogre::RenderTarget::_updateViewport (Viewport * viewport, bool updateStatistics = true) virtual inherited
Method for manual management of rendering - renders the given viewport (even if it is not autoupdated)
Remarks
This also fires preViewportUpdate and postViewportUpdate, and manages statistics if needed. You should call it between _beginUpdate() and _endUpdate().
See also
_beginUpdate for more details.
Parameters
viewport The viewport you want to update, it must be bound to the rendertarget.
updateStatistics Whether you want to update statistics or not.
Reimplemented in Ogre::D3D9RenderWindow.
_updateAutoUpdatedViewports()
virtual void Ogre::RenderTarget::_updateAutoUpdatedViewports (bool updateStatistics = true) virtual inherited
Method for manual management of rendering - renders only viewports that are auto updated.
Remarks
This also fires preViewportUpdate and postViewportUpdate, and manages statistics. You should call it between _beginUpdate() and _endUpdate(). See _beginUpdate for more details.
Parameters
updateStatistics Whether you want to update statistics or not.
See also
_beginUpdate()
_endUpdate()
virtual void Ogre::RenderTarget::_endUpdate () virtual inherited
Method for manual management of rendering - finishes statistics calculation and fires 'postRenderTargetUpdate'.
Remarks
You should call it after a _beginUpdate
See also
_beginUpdate for more details.
Reimplemented in Ogre::D3D9RenderWindow.
The documentation for this class was generated from the following file:
OgreGL3PlusFBOMultiRenderTarget.h