OGRE: Ogre::LinearForceAffector Class Reference
Ogre::LinearForceAffector Class Reference
Plugins » ParticleFX
This class defines a ParticleAffector which applies a linear force to particles in a system.
#include <OgreLinearForceAffector.h>
Classes
class CmdForceApp
Command object for force application (see ParamCommand).
class CmdForceVector
Command object for force vector (see ParamCommand).
Public Types
enum ForceApplication { FA_AVERAGE, FA_ADD }
Choice of how to apply the force vector to particles.
Public Member Functions
LinearForceAffector (ParticleSystem *psys)
Default constructor.
void _affectParticles (ParticleSystem *pSystem, Real timeElapsed)
See ParticleAffector.
virtual void _initParticle (Particle *pParticle)
Method called to allow the affector to initialize all newly created particles in the system.
void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
ForceApplication getForceApplication (void) const
Retrieves how the force vector is applied to a particle.
Vector3 getForceVector (void) const
Gets the force vector to apply to the particles in a system.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
const String & getType (void) const
Returns the name of the type of affector.
void setForceApplication (ForceApplication fa)
Sets how the force vector is applied to a particle.
void setForceVector (const Vector3 &force)
Sets the force vector to apply to the particles in a system.
bool setParameter (const String &name, const String &value)
Generic parameter setting method.
void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Static Public Attributes
static CmdForceApp msForceAppCmd
static CmdForceVector msForceVectorCmd
Command objects.
Detailed Description
This class defines a ParticleAffector which applies a linear force to particles in a system.
Remarks
This affector (see ParticleAffector) applies a linear force, such as gravity, to a particle system. This force can be applied in 2 ways: by taking the average of the particle's current momentum and the force vector, or by adding the force vector to the current particle's momentum.
The former approach is self-stabilising i.e. once a particle's momentum is equal to the force vector, no further change is made to it's momentum. It also results in a non-linear acceleration of particles. The latter approach is simpler and applies a constant acceleration to particles. However, it is not self-stabilising and can lead to perpetually increasing particle velocities. You choose the approach by calling the setForceApplication method.
Member Enumeration Documentation
ForceApplication
enum Ogre::LinearForceAffector::ForceApplication
Choice of how to apply the force vector to particles.
Enumerator
FA_AVERAGE
Take the average of the force vector and the particle momentum.
FA_ADD
Add the force vector to the particle momentum.
Constructor & Destructor Documentation
LinearForceAffector()
Ogre::LinearForceAffector::LinearForceAffector (ParticleSystem * psys)
Default constructor.
Member Function Documentation
_affectParticles()
void Ogre::LinearForceAffector::_affectParticles (ParticleSystem * pSystem, Real timeElapsed) virtual
See ParticleAffector.
Implements Ogre::ParticleAffector.
setForceVector()
void Ogre::LinearForceAffector::setForceVector (const Vector3 & force)
Sets the force vector to apply to the particles in a system.
getForceVector()
Vector3 Ogre::LinearForceAffector::getForceVector (void) const
Gets the force vector to apply to the particles in a system.
setForceApplication()
void Ogre::LinearForceAffector::setForceApplication (ForceApplication fa)
Sets how the force vector is applied to a particle.
Remarks
The default is FA_ADD.
Parameters
fa A member of the ForceApplication enum.
getForceApplication()
ForceApplication Ogre::LinearForceAffector::getForceApplication (void) const
Retrieves how the force vector is applied to a particle.
Returns
A member of the ForceApplication enum.
_initParticle()
virtual void Ogre::ParticleAffector::_initParticle (Particle * pParticle) inline virtual inherited
Method called to allow the affector to initialize all newly created particles in the system.
Remarks
This is where the affector gets the chance to initialize it's effects to the particles of a system. The affector is expected to initialize some or all of the particles in the system passed to it, depending on the affector's approach.
Parameters
pParticle Pointer to a Particle to initialize.
Reimplemented in Ogre::RotationAffector, and Ogre::ColourImageAffector.
getType()
const String& Ogre::ParticleAffector::getType (void) const inline inherited
Returns the name of the type of affector.
Remarks
This property is useful for determining the type of affector procedurally so another can be created.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
setParameter()
bool Ogre::StringInterface::setParameter (const String & name, const String & value) inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
getParameter()
String Ogre::StringInterface::getParameter (const String & name) const inline inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
copyParametersTo()
void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
Member Data Documentation
msForceVectorCmd
CmdForceVector Ogre::LinearForceAffector::msForceVectorCmd static
Command objects.
msForceAppCmd
CmdForceApp Ogre::LinearForceAffector::msForceAppCmd static
The documentation for this class was generated from the following file:
OgreLinearForceAffector.h