OGRE: Ogre::ShadowRenderable Class Reference
Ogre::ShadowRenderable Class Reference abstract
Core » Scene
Class which represents the renderable aspects of a set of shadow volume faces.
#include <OgreShadowCaster.h>
Public Types
typedef SharedPtr< RenderSystemData > RenderSystemDataPtr
Public Member Functions
ShadowRenderable ()
Used only if isLightCapSeparate == true.
virtual ~ShadowRenderable ()
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
ShadowRenderable * getLightCapRenderable (void)
Get the light cap version of this renderable.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
const MaterialPtr & getMaterial (void) const
Retrieves a weak reference to the material this renderable object uses.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void getRenderOperation (RenderOperation &op)
Gets the render operation required to send this object to the frame buffer.
RenderOperation * getRenderOperationForUpdate (void)
Get the internal render operation for set up.
const RenderSystemDataPtr & getRenderSystemData () const
Gets RenderSystem private data.
Real getSquaredViewDepth (const Camera *) const
Returns the camera-relative squared depth of this renderable.
virtual Technique * getTechnique (void) const
Retrieves a pointer to the Material Technique this renderable object uses.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
void getWorldTransforms (Matrix4 *xform) const =0
Gets the world transform matrix / matrices for this renderable object.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool isLightCapSeparate (void) const
Does this renderable require a separate light cap?
virtual bool isVisible (void) const
Should this ShadowRenderable be treated as visible?
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
virtual void rebindIndexBuffer (const HardwareIndexBufferSharedPtr &indexBuffer)=0
This function informs the shadow renderable that the global index buffer from the SceneManager has been updated.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setMaterial (const MaterialPtr &mat)
Set the material to be used by the shadow, should be set by the caller before adding to a render queue.
void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setRenderSystemData (RenderSystemDataPtr val) const
Sets RenderSystem private data.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
void setUserAny (const Any &anything)
Detailed Description
Class which represents the renderable aspects of a set of shadow volume faces.
Remarks
Note that for casters comprised of more than one set of vertex buffers (e.g. SubMeshes each using their own geometry), it will take more than one ShadowRenderable to render the shadow volume. Therefore for shadow caster geometry, it is best to stick to one set of vertex buffers (not necessarily one buffer, but the positions for the entire geometry should come from one buffer if possible)
Member Typedef Documentation
RenderSystemDataPtr
typedef SharedPtr<RenderSystemData> Ogre::Renderable::RenderSystemDataPtr inherited
Constructor & Destructor Documentation
ShadowRenderable()
Ogre::ShadowRenderable::ShadowRenderable () inline
Used only if isLightCapSeparate == true.
~ShadowRenderable()
virtual Ogre::ShadowRenderable::~ShadowRenderable () inline virtual
Member Function Documentation
setMaterial()
void Ogre::ShadowRenderable::setMaterial (const MaterialPtr & mat) inline
Set the material to be used by the shadow, should be set by the caller before adding to a render queue.
getMaterial()
const MaterialPtr& Ogre::ShadowRenderable::getMaterial (void) const inline virtual
Retrieves a weak reference to the material this renderable object uses.
Remarks
Note that the Renderable also has the option to override the getTechnique method to specify a particular Technique to use instead of the best one available.
Implements Ogre::Renderable.
getRenderOperation()
void Ogre::ShadowRenderable::getRenderOperation (RenderOperation & op) inline virtual
Gets the render operation required to send this object to the frame buffer.
Implements Ogre::Renderable.
getRenderOperationForUpdate()
RenderOperation* Ogre::ShadowRenderable::getRenderOperationForUpdate (void) inline
Get the internal render operation for set up.
getWorldTransforms()
void Ogre::ShadowRenderable::getWorldTransforms (Matrix4 * xform) const pure virtual
Gets the world transform matrix / matrices for this renderable object.
Remarks
If the object has any derived transforms, these are expected to be up to date as long as all the SceneNode structures have been updated before this is called.
This method will populate transform with 1 matrix if it does not use vertex blending. If it does use vertex blending it will fill the passed in pointer with an array of matrices, the length being the value returned from getNumWorldTransforms.
Note
Internal Ogre never supports non-affine matrix for world transform matrix/matrices, the behavior is undefined if returns non-affine matrix here.
See also
Matrix4::isAffine.
Implements Ogre::Renderable.
Implemented in Ogre::ManualObject::ManualObjectSectionShadowRenderable.
getSquaredViewDepth()
Real Ogre::ShadowRenderable::getSquaredViewDepth (const Camera *) const inline virtual
Returns the camera-relative squared depth of this renderable.
Remarks
Used to sort transparent objects. Squared depth is used rather than actual depth to avoid having to perform a square root on the result.
Implements Ogre::Renderable.
getLights()
const LightList& Ogre::ShadowRenderable::getLights (void) const virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
isLightCapSeparate()
bool Ogre::ShadowRenderable::isLightCapSeparate (void) const inline
Does this renderable require a separate light cap?
Remarks
If possible, the light cap (when required) should be contained in the usual geometry of the shadow renderable. However, if for some reason the normal depth function (less than) could cause artefacts, then a separate light cap with a depth function of 'always fail' can be used instead. The primary example of this is when there are floating point inaccuracies caused by calculating the shadow geometry separately from the real geometry.
getLightCapRenderable()
ShadowRenderable* Ogre::ShadowRenderable::getLightCapRenderable (void) inline
Get the light cap version of this renderable.
isVisible()
virtual bool Ogre::ShadowRenderable::isVisible (void) const inline virtual
Should this ShadowRenderable be treated as visible?
rebindIndexBuffer()
virtual void Ogre::ShadowRenderable::rebindIndexBuffer (const HardwareIndexBufferSharedPtr & indexBuffer) pure virtual
This function informs the shadow renderable that the global index buffer from the SceneManager has been updated.
As all shadow use this buffer their pointer must be updated as well.
Parameters
indexBuffer Pointer to the new index buffer.
Implemented in Ogre::ManualObject::ManualObjectSectionShadowRenderable.
getTechnique()
virtual Technique* Ogre::Renderable::getTechnique (void) const inline virtual inherited
Retrieves a pointer to the Material Technique this renderable object uses.
Remarks
This is to allow Renderables to use a chosen Technique if they wish, otherwise they will use the best Technique available for the Material they are using.
Reimplemented in Ogre::InstanceBatch, Ogre::InstancedGeometry::GeometryBucket, Ogre::StaticGeometry::GeometryBucket, and Ogre::SubEntity.
preRender()
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::BillboardChain.
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
getNumWorldTransforms()
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::BorderRenderable, Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, Ogre::BaseInstanceBatchVTF, Ogre::InstanceBatchHW, and Ogre::InstanceBatchShader.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
getCastsShadows()
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::SubEntity, Ogre::InstancedGeometry::GeometryBucket, and Ogre::StaticGeometry::GeometryBucket.
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
getCustomParameter()
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
_updateCustomGpuParameter()
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
setPolygonModeOverrideable()
void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
getPolygonModeOverrideable()
bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Referenced by Ogre::BorderRenderable::getPolygonModeOverrideable().
setUserAny()
void Ogre::Renderable::setUserAny (const Any & anything) inline inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserAny()
const Any& Ogre::Renderable::getUserAny (void) const inline inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::InstanceBatch::getRenderOperation().
getUserObjectBindings() [1/2]
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/2]
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getRenderSystemData()
const RenderSystemDataPtr& Ogre::Renderable::getRenderSystemData () const inline inherited
Gets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
setRenderSystemData()
void Ogre::Renderable::setRenderSystemData (RenderSystemDataPtr val) const inline inherited
Sets RenderSystem private data.
Remarks
This should only be used by a RenderSystem
The documentation for this class was generated from the following file:
OgreShadowCaster.h