OGRE: General
General
Core
Classes
struct Ogre::_ConfigOption
Packages the details of a configuration option.
class Ogre::AbstractNode
class Ogre::AnimationControllerFunction
Predefined controller function for dealing with animation.
class Ogre::Any
Variant type that can hold Any other type.
class Ogre::AnyNumeric
Specialised Any class which has built in arithmetic operators, but can hold only types which support operator +,-,* and / .
class Ogre::AtomAbstractNode
This is an abstract node which cannot be broken down further.
class Ogre::AtomicObject< T >
class Ogre::AtomicScalar< T >
struct Ogre::Box
Structure used to define a box in a 3-D integer space.
class Ogre::BuiltinScriptTranslatorManager
This class manages the builtin translators.
class Ogre::Codec
Abstract class that defines a 'codec'.
class Ogre::ColourValue
Class representing colour.
class Ogre::CompositionPassTranslator
class Ogre::CompositionTargetPassTranslator
class Ogre::CompositionTechniqueTranslator
class Ogre::CompositorTranslator
class Ogre::ComPtr< T >
struct Ogre::ConcreteNode
class Ogre::ConfigDialog
Defines the behaviour of an automatic renderer configuration dialog.
class Ogre::ConfigFile
Class for quickly loading settings from a text file.
class Ogre::Controller< T >
Instances of this class 'control' the value of another object in the system.
class Ogre::ControllerFunction< T >
Subclasses of this class are responsible for performing a function on an input value for a Controller.
class Ogre::ControllerManager
Class for managing Controller instances.
class Ogre::ControllerValue< T >
Can either be used as an input or output value.
class Ogre::CreateCompositorScriptCompilerEvent
class Ogre::CreateGpuProgramScriptCompilerEvent
class Ogre::CreateGpuSharedParametersScriptCompilerEvent
class Ogre::CreateHighLevelGpuProgramScriptCompilerEvent
class Ogre::CreateMaterialScriptCompilerEvent
class Ogre::CreateParticleSystemScriptCompilerEvent
class Ogre::DefaultWorkQueueBase
Base for a general purpose request / response style background work queue.
class Ogre::DynLib
Resource holding data about a dynamic library.
class Ogre::DynLibManager
Manager for Dynamic-loading Libraries.
class Ogre::ErrorDialog
Class for displaying the error dialog if Ogre fails badly.
class Ogre::Exception
When thrown, provides information about an error that has occurred inside the engine.
class Ogre::ExceptionFactory
Class implementing dispatch methods in order to construct by-value exceptions of a derived type based just on an exception code.
class Ogre::FactoryObj< T >
Abstract factory class.
class Ogre::FileNotFoundException
class Ogre::FloatGpuParameterControllerValue
Predefined controller value for setting a single floating- point value in a constant parameter of a vertex or fragment program.
struct Ogre::FrameEvent
Struct containing information about a frame event.
class Ogre::FrameListener
A interface class defining a listener which can be used to receive notifications of frame events.
class Ogre::FrameTimeControllerValue
Predefined controller value for getting the latest frame time.
class Ogre::GpuProgramTranslator
class Ogre::HashedVector< T >
A hashed vector.
class Ogre::ImportAbstractNode
This abstract node represents an import statement.
class Ogre::InternalErrorException
class Ogre::InvalidCallException
class Ogre::InvalidParametersException
class Ogre::InvalidStateException
class Ogre::IOException
class Ogre::ItemIdentityException
class Ogre::LinearControllerFunction
Predefined controller function based on linear function interpolation.
class Ogre::Log
class Ogre::LogListener
class Ogre::LogManager
The log manager handles the creation and retrieval of logs for the application.
class Ogre::MaterialTranslator
class Ogre::NameGenerator
Utility class to generate a sequentially numbered series of names.
class Ogre::NoAddRefRelease< T >
class Ogre::ObjectAbstractNode
This specific abstract node represents a script object.
class Ogre::ParamCommand
Abstract class which is command object which gets/sets parameters.
class Ogre::ParamDictionary
Class to hold a dictionary of parameters for a single class.
class Ogre::ParameterDef
Definition of a parameter supported by a StringInterface class, for introspection.
class Ogre::ParticleAffectorTranslator
class Ogre::ParticleEmitterTranslator
class Ogre::ParticleSystemTranslator
class Ogre::PassthroughControllerFunction
Predefined controller function which just passes through the original source directly to dest.
class Ogre::PassTranslator
class Ogre::PlatformInformation
Class which provides the run-time platform information Ogre runs on.
class Ogre::Plugin
Class defining a generic OGRE plugin.
class Ogre::PreApplyTextureAliasesScriptCompilerEvent
class Ogre::ProcessNameExclusionScriptCompilerEvent
class Ogre::ProcessResourceNameScriptCompilerEvent
class Ogre::Profile
An individual profile that will be processed by the Profiler.
struct Ogre::ProfileFrame
Represents the total timing information of a profile since profiles can be called more than once each frame.
struct Ogre::ProfileHistory
Represents a history of each profile during the duration of the app.
class Ogre::ProfileInstance
Represents an individual profile call.
class Ogre::Profiler
The profiler allows you to measure the performance of your code.
class Ogre::ProfileSessionListener
ProfileSessionListener should be used to visualize profile results.
class Ogre::PropertyAbstractNode
This abstract node represents a script property.
class Ogre::RadixSort< TContainer, TContainerValueType, TCompValueType >
Class for performing a radix sort (fast comparison-less sort based on byte value) on various standard STL containers.
class Ogre::RenderingAPIException
struct Ogre::RenderWindowDescription
Render window creation parameters.
class Ogre::Root
The root class of the Ogre system.
class Ogre::RuntimeAssertionException
class Ogre::ScaleControllerFunction
Predefined controller function which simply scales an input to an output value.
class Ogre::ScriptCompiler
This is the main class for the compiler.
class Ogre::ScriptCompilerEvent
This struct is a base class for events which can be thrown by the compilers and caught by subscribers.
class Ogre::ScriptCompilerListener
This is a listener for the compiler.
class Ogre::ScriptCompilerManager
Manages threaded compilation of scripts.
class Ogre::ScriptLexer
class Ogre::ScriptLoader
Abstract class defining the interface used by classes which wish to perform script loading to define instances of whatever they manage.
class Ogre::ScriptParser
struct Ogre::ScriptToken
This struct represents a token, which is an ID'd lexeme from the parsing input stream.
class Ogre::ScriptTranslator
This class translates script AST (abstract syntax tree) into Ogre resources.
class Ogre::ScriptTranslatorManager
The ScriptTranslatorManager manages the lifetime and access to script translators.
class Ogre::Serializer
Generic class for serialising data to / from binary stream-based files.
class Ogre::SharedParamsTranslator
class Ogre::SharedPtr< T >
Reference-counted shared pointer, used for objects where implicit destruction is required.
struct Ogre::SharedPtrInfo
class Ogre::SharedPtrInfoDelete< T >
class Ogre::SharedPtrInfoDeleteT< T >
class Ogre::SharedPtrInfoFree< T >
struct Ogre::SharedPtrInfoNone
class Ogre::Singleton< T >
Template class for creating single-instance global classes.
class Ogre::StringConverter
Class for converting the core Ogre data types to/from Strings.
class Ogre::StringInterface
Class defining the common interface which classes can use to present a reflection-style, self-defining parameter set to callers.
class Ogre::StringUtil
Utility class for manipulating Strings.
class Ogre::TechniqueTranslator
class Ogre::TexCoordModifierControllerValue
Predefined controller value for getting / setting a texture coordinate modifications (scales and translates).
class Ogre::TextureFrameControllerValue
Predefined controller value for getting / setting the frame number of a texture layer.
class Ogre::TextureSourceTranslator
class Ogre::TextureUnitTranslator
class Ogre::Timer
Timer class.
struct Ogre::TRect< T >
class Ogre::UnimplementedException
Template struct which creates a distinct type for each exception code.
class Ogre::VariableAccessAbstractNode
This abstract node represents a variable assignment.
class Ogre::WaveformControllerFunction
Predefined controller function based on a waveform.
class Ogre::WorkQueue
Interface to a general purpose request / response style background work queue.
Macros
#define OGRE_EXCEPT(code, desc, src) Ogre::ExceptionFactory::throwException(code, desc, src, __FILE__, __LINE__)
#define OGRE_EXCEPT_EX(code, num, desc, src) Ogre::ExceptionFactory::throwExceptionEx(code, num, desc, src, __FILE__, __LINE__)
#define OGRE_LOG_THRESHOLD 4
Typedefs
typedef stdext::hash_compare< _StringBase, std::less< _StringBase > > Ogre::_StringHash
typedef uint32 Ogre::ABGR
typedef list< AbstractNodePtr >::type Ogre::AbstractNodeList
typedef SharedPtr< AbstractNodeList > Ogre::AbstractNodeListPtr
typedef SharedPtr< AbstractNode > Ogre::AbstractNodePtr
typedef map< String, String >::type Ogre::AliasTextureNamePairList
Alias / Texture name pair (first = alias, second = texture name)
typedef uint32 Ogre::ARGB
typedef uint32 Ogre::BGRA
typedef map< String, String >::type Ogre::BinaryOptionList
typedef list< ConcreteNodePtr >::type Ogre::ConcreteNodeList
typedef SharedPtr< ConcreteNodeList > Ogre::ConcreteNodeListPtr
typedef SharedPtr< ConcreteNode > Ogre::ConcreteNodePtr
typedef struct Ogre::_ConfigOption Ogre::ConfigOption
Packages the details of a configuration option.
typedef map< String, ConfigOption >::type Ogre::ConfigOptionMap
typedef SharedPtr< ControllerFunction< Real > > Ogre::ControllerFunctionRealPtr
typedef SharedPtr< ControllerValue< Real > > Ogre::ControllerValueRealPtr
typedef TRect< float > Ogre::FloatRect
Structure used to define a rectangle in a 2-D floating point space.
typedef HashedVector< Light * > Ogre::LightList
typedef map< String, String >::type Ogre::NameValuePairList
Name / value parameter pair (first = name, second = value)
typedef map< String, ParamCommand *>::type Ogre::ParamCommandMap
typedef map< String, ParamDictionary >::type Ogre::ParamDictionaryMap
typedef vector< ParameterDef >::type Ogre::ParameterList
typedef TRect< Real > Ogre::RealRect
Structure used to define a rectangle in a 2-D floating point space, subject to double / single floating point settings.
typedef TRect< long > Ogre::Rect
Structure used to define a rectangle in a 2-D integer space.
typedef vector< RenderSystem * >::type Ogre::RenderSystemList
typedef vector< RenderWindowDescription >::type Ogre::RenderWindowDescriptionList
Render window creation parameters container.
typedef vector< RenderWindow * >::type Ogre::RenderWindowList
Render window container.
typedef uint32 Ogre::RGBA
typedef vector< ScriptTokenPtr >::type Ogre::ScriptTokenList
typedef SharedPtr< ScriptTokenList > Ogre::ScriptTokenListPtr
typedef SharedPtr< ScriptToken > Ogre::ScriptTokenPtr
typedef vector< String >::type Ogre::StringVector
typedef SharedPtr< StringVector > Ogre::StringVectorPtr
typedef int Ogre::TrackVertexColourType
An enumeration describing which material properties should track the vertex colours.
typedef map< String, bool >::type Ogre::UnaryOptionList
Enumerations
enum {
Ogre::TID_LBRACKET = 0, Ogre::TID_RBRACKET, Ogre::TID_COLON, Ogre::TID_VARIABLE,
Ogre::TID_WORD, Ogre::TID_QUOTE, Ogre::TID_NEWLINE, Ogre::TID_UNKNOWN,
Ogre::TID_END
}
These codes represent token IDs which are numerical translations of specific lexemes.
enum {
Ogre::ID_MATERIAL = 3, Ogre::ID_VERTEX_PROGRAM, Ogre::ID_GEOMETRY_PROGRAM, Ogre::ID_FRAGMENT_PROGRAM,
Ogre::ID_TECHNIQUE, Ogre::ID_PASS, Ogre::ID_TEXTURE_UNIT, Ogre::ID_VERTEX_PROGRAM_REF,
Ogre::ID_GEOMETRY_PROGRAM_REF, Ogre::ID_FRAGMENT_PROGRAM_REF, Ogre::ID_SHADOW_CASTER_VERTEX_PROGRAM_REF, Ogre::ID_SHADOW_CASTER_FRAGMENT_PROGRAM_REF,
Ogre::ID_SHADOW_RECEIVER_VERTEX_PROGRAM_REF, Ogre::ID_SHADOW_RECEIVER_FRAGMENT_PROGRAM_REF, Ogre::ID_SHADOW_CASTER_MATERIAL, Ogre::ID_SHADOW_RECEIVER_MATERIAL,
Ogre::ID_LOD_VALUES, Ogre::ID_LOD_STRATEGY, Ogre::ID_LOD_DISTANCES, Ogre::ID_RECEIVE_SHADOWS,
Ogre::ID_TRANSPARENCY_CASTS_SHADOWS, Ogre::ID_SET_TEXTURE_ALIAS, Ogre::ID_SOURCE, Ogre::ID_SYNTAX,
Ogre::ID_DEFAULT_PARAMS, Ogre::ID_PARAM_INDEXED, Ogre::ID_PARAM_NAMED, Ogre::ID_PARAM_INDEXED_AUTO,
Ogre::ID_PARAM_NAMED_AUTO, Ogre::ID_SCHEME, Ogre::ID_LOD_INDEX, Ogre::ID_GPU_VENDOR_RULE,
Ogre::ID_GPU_DEVICE_RULE, Ogre::ID_INCLUDE, Ogre::ID_EXCLUDE, Ogre::ID_AMBIENT,
Ogre::ID_DIFFUSE, Ogre::ID_SPECULAR, Ogre::ID_EMISSIVE, Ogre::ID_VERTEXCOLOUR,
Ogre::ID_SCENE_BLEND, Ogre::ID_COLOUR_BLEND, Ogre::ID_ONE, Ogre::ID_ZERO,
Ogre::ID_DEST_COLOUR, Ogre::ID_SRC_COLOUR, Ogre::ID_ONE_MINUS_DEST_COLOUR, Ogre::ID_ONE_MINUS_SRC_COLOUR,
Ogre::ID_DEST_ALPHA, Ogre::ID_SRC_ALPHA, Ogre::ID_ONE_MINUS_DEST_ALPHA, Ogre::ID_ONE_MINUS_SRC_ALPHA,
Ogre::ID_SEPARATE_SCENE_BLEND, Ogre::ID_SCENE_BLEND_OP, Ogre::ID_REVERSE_SUBTRACT, Ogre::ID_MIN,
Ogre::ID_MAX, Ogre::ID_SEPARATE_SCENE_BLEND_OP, Ogre::ID_DEPTH_CHECK, Ogre::ID_DEPTH_WRITE,
Ogre::ID_DEPTH_FUNC, Ogre::ID_DEPTH_BIAS, Ogre::ID_ITERATION_DEPTH_BIAS, Ogre::ID_ALWAYS_FAIL,
Ogre::ID_ALWAYS_PASS, Ogre::ID_LESS_EQUAL, Ogre::ID_LESS, Ogre::ID_EQUAL,
Ogre::ID_NOT_EQUAL, Ogre::ID_GREATER_EQUAL, Ogre::ID_GREATER, Ogre::ID_ALPHA_REJECTION,
Ogre::ID_ALPHA_TO_COVERAGE, Ogre::ID_LIGHT_SCISSOR, Ogre::ID_LIGHT_CLIP_PLANES, Ogre::ID_TRANSPARENT_SORTING,
Ogre::ID_ILLUMINATION_STAGE, Ogre::ID_DECAL, Ogre::ID_CULL_HARDWARE, Ogre::ID_CLOCKWISE,
Ogre::ID_ANTICLOCKWISE, Ogre::ID_CULL_SOFTWARE, Ogre::ID_BACK, Ogre::ID_FRONT,
Ogre::ID_NORMALISE_NORMALS, Ogre::ID_LIGHTING, Ogre::ID_SHADING, Ogre::ID_FLAT,
Ogre::ID_GOURAUD, Ogre::ID_PHONG, Ogre::ID_POLYGON_MODE, Ogre::ID_SOLID,
Ogre::ID_WIREFRAME, Ogre::ID_POINTS, Ogre::ID_POLYGON_MODE_OVERRIDEABLE, Ogre::ID_FOG_OVERRIDE,
Ogre::ID_NONE, Ogre::ID_LINEAR, Ogre::ID_EXP, Ogre::ID_EXP2,
Ogre::ID_COLOUR_WRITE, Ogre::ID_MAX_LIGHTS, Ogre::ID_START_LIGHT, Ogre::ID_ITERATION,
Ogre::ID_ONCE, Ogre::ID_ONCE_PER_LIGHT, Ogre::ID_PER_LIGHT, Ogre::ID_PER_N_LIGHTS,
Ogre::ID_POINT, Ogre::ID_SPOT, Ogre::ID_DIRECTIONAL, Ogre::ID_LIGHT_MASK,
Ogre::ID_POINT_SIZE, Ogre::ID_POINT_SPRITES, Ogre::ID_POINT_SIZE_ATTENUATION, Ogre::ID_POINT_SIZE_MIN,
Ogre::ID_POINT_SIZE_MAX, Ogre::ID_TEXTURE_ALIAS, Ogre::ID_TEXTURE, Ogre::ID_1D,
Ogre::ID_2D, Ogre::ID_3D, Ogre::ID_CUBIC, Ogre::ID_2DARRAY,
Ogre::ID_UNLIMITED, Ogre::ID_ALPHA, Ogre::ID_GAMMA, Ogre::ID_ANIM_TEXTURE,
Ogre::ID_CUBIC_TEXTURE, Ogre::ID_SEPARATE_UV, Ogre::ID_COMBINED_UVW, Ogre::ID_TEX_COORD_SET,
Ogre::ID_TEX_ADDRESS_MODE, Ogre::ID_WRAP, Ogre::ID_CLAMP, Ogre::ID_BORDER,
Ogre::ID_MIRROR, Ogre::ID_TEX_BORDER_COLOUR, Ogre::ID_FILTERING, Ogre::ID_BILINEAR,
Ogre::ID_TRILINEAR, Ogre::ID_ANISOTROPIC, Ogre::ID_CMPTEST, Ogre::ID_ON,
Ogre::ID_OFF, Ogre::ID_CMPFUNC, Ogre::ID_MAX_ANISOTROPY, Ogre::ID_MIPMAP_BIAS,
Ogre::ID_COLOUR_OP, Ogre::ID_REPLACE, Ogre::ID_ADD, Ogre::ID_MODULATE,
Ogre::ID_ALPHA_BLEND, Ogre::ID_COLOUR_OP_EX, Ogre::ID_SOURCE1, Ogre::ID_SOURCE2,
Ogre::ID_MODULATE_X2, Ogre::ID_MODULATE_X4, Ogre::ID_ADD_SIGNED, Ogre::ID_ADD_SMOOTH,
Ogre::ID_SUBTRACT, Ogre::ID_BLEND_DIFFUSE_COLOUR, Ogre::ID_BLEND_DIFFUSE_ALPHA, Ogre::ID_BLEND_TEXTURE_ALPHA,
Ogre::ID_BLEND_CURRENT_ALPHA, Ogre::ID_BLEND_MANUAL, Ogre::ID_DOT_PRODUCT, Ogre::ID_SRC_CURRENT,
Ogre::ID_SRC_TEXTURE, Ogre::ID_SRC_DIFFUSE, Ogre::ID_SRC_SPECULAR, Ogre::ID_SRC_MANUAL,
Ogre::ID_COLOUR_OP_MULTIPASS_FALLBACK, Ogre::ID_ALPHA_OP_EX, Ogre::ID_ENV_MAP, Ogre::ID_SPHERICAL,
Ogre::ID_PLANAR, Ogre::ID_CUBIC_REFLECTION, Ogre::ID_CUBIC_NORMAL, Ogre::ID_SCROLL,
Ogre::ID_SCROLL_ANIM, Ogre::ID_ROTATE, Ogre::ID_ROTATE_ANIM, Ogre::ID_SCALE,
Ogre::ID_WAVE_XFORM, Ogre::ID_SCROLL_X, Ogre::ID_SCROLL_Y, Ogre::ID_SCALE_X,
Ogre::ID_SCALE_Y, Ogre::ID_SINE, Ogre::ID_TRIANGLE, Ogre::ID_SQUARE,
Ogre::ID_SAWTOOTH, Ogre::ID_INVERSE_SAWTOOTH, Ogre::ID_TRANSFORM, Ogre::ID_BINDING_TYPE,
Ogre::ID_VERTEX, Ogre::ID_FRAGMENT, Ogre::ID_CONTENT_TYPE, Ogre::ID_NAMED,
Ogre::ID_SHADOW, Ogre::ID_TEXTURE_SOURCE, Ogre::ID_SHARED_PARAMS, Ogre::ID_SHARED_PARAM_NAMED,
Ogre::ID_SHARED_PARAMS_REF, Ogre::ID_PARTICLE_SYSTEM, Ogre::ID_EMITTER, Ogre::ID_AFFECTOR,
Ogre::ID_COMPOSITOR, Ogre::ID_TARGET, Ogre::ID_TARGET_OUTPUT, Ogre::ID_INPUT,
Ogre::ID_PREVIOUS, Ogre::ID_TARGET_WIDTH, Ogre::ID_TARGET_HEIGHT, Ogre::ID_TARGET_WIDTH_SCALED,
Ogre::ID_TARGET_HEIGHT_SCALED, Ogre::ID_COMPOSITOR_LOGIC, Ogre::ID_TEXTURE_REF, Ogre::ID_SCOPE_LOCAL,
Ogre::ID_SCOPE_CHAIN, Ogre::ID_SCOPE_GLOBAL, Ogre::ID_POOLED, Ogre::ID_NO_FSAA,
Ogre::ID_DEPTH_POOL, Ogre::ID_ONLY_INITIAL, Ogre::ID_VISIBILITY_MASK, Ogre::ID_LOD_BIAS,
Ogre::ID_MATERIAL_SCHEME, Ogre::ID_SHADOWS_ENABLED, Ogre::ID_CLEAR, Ogre::ID_STENCIL,
Ogre::ID_RENDER_SCENE, Ogre::ID_RENDER_QUAD, Ogre::ID_IDENTIFIER, Ogre::ID_FIRST_RENDER_QUEUE,
Ogre::ID_LAST_RENDER_QUEUE, Ogre::ID_QUAD_NORMALS, Ogre::ID_CAMERA_FAR_CORNERS_VIEW_SPACE, Ogre::ID_CAMERA_FAR_CORNERS_WORLD_SPACE,
Ogre::ID_BUFFERS, Ogre::ID_COLOUR, Ogre::ID_DEPTH, Ogre::ID_COLOUR_VALUE,
Ogre::ID_DEPTH_VALUE, Ogre::ID_STENCIL_VALUE, Ogre::ID_CHECK, Ogre::ID_COMP_FUNC,
Ogre::ID_REF_VALUE, Ogre::ID_MASK, Ogre::ID_FAIL_OP, Ogre::ID_KEEP,
Ogre::ID_INCREMENT, Ogre::ID_DECREMENT, Ogre::ID_INCREMENT_WRAP, Ogre::ID_DECREMENT_WRAP,
Ogre::ID_INVERT, Ogre::ID_DEPTH_FAIL_OP, Ogre::ID_PASS_OP, Ogre::ID_TWO_SIDED,
Ogre::ID_READ_BACK_AS_TEXTURE, Ogre::ID_RT_SHADER_SYSTEM, Ogre::ID_TESSELLATION_HULL_PROGRAM, Ogre::ID_TESSELLATION_DOMAIN_PROGRAM,
Ogre::ID_COMPUTE_PROGRAM, Ogre::ID_TESSELLATION_HULL_PROGRAM_REF, Ogre::ID_TESSELLATION_DOMAIN_PROGRAM_REF, Ogre::ID_COMPUTE_PROGRAM_REF,
Ogre::ID_GEOMETRY, Ogre::ID_TESSELLATION_HULL, Ogre::ID_TESSELLATION_DOMAIN, Ogre::ID_COMPUTE,
Ogre::ID_SUBROUTINE, Ogre::ID_END_BUILTIN_IDS
}
This enum defines the integer ids for keywords this compiler handles.
enum Ogre::AbstractNodeType {
Ogre::ANT_UNKNOWN, Ogre::ANT_ATOM, Ogre::ANT_OBJECT, Ogre::ANT_PROPERTY,
Ogre::ANT_IMPORT, Ogre::ANT_VARIABLE_SET, Ogre::ANT_VARIABLE_ACCESS
}
This enum holds the types of the possible abstract nodes.
enum Ogre::ClipResult { Ogre::CLIPPED_NONE = 0, Ogre::CLIPPED_SOME = 1, Ogre::CLIPPED_ALL = 2 }
Generic result of clipping.
enum Ogre::ColourBufferType { Ogre::CBT_BACK = 0x0, Ogre::CBT_BACK_LEFT, Ogre::CBT_BACK_RIGHT }
Defines the colour buffer types.
enum Ogre::CompareFunction {
Ogre::CMPF_ALWAYS_FAIL, Ogre::CMPF_ALWAYS_PASS, Ogre::CMPF_LESS, Ogre::CMPF_LESS_EQUAL,
Ogre::CMPF_EQUAL, Ogre::CMPF_NOT_EQUAL, Ogre::CMPF_GREATER_EQUAL, Ogre::CMPF_GREATER
}
Comparison functions used for the depth/stencil buffer operations and others.
enum Ogre::ConcreteNodeType {
Ogre::CNT_VARIABLE, Ogre::CNT_VARIABLE_ASSIGN, Ogre::CNT_WORD, Ogre::CNT_IMPORT,
Ogre::CNT_QUOTE, Ogre::CNT_LBRACE, Ogre::CNT_RBRACE, Ogre::CNT_COLON
}
These enums hold the types of the concrete parsed nodes.
enum Ogre::CullingMode { Ogre::CULL_NONE = 1, Ogre::CULL_CLOCKWISE = 2, Ogre::CULL_ANTICLOCKWISE = 3 }
Hardware culling modes based on vertex winding.
enum Ogre::FilterOptions { Ogre::FO_NONE, Ogre::FO_POINT, Ogre::FO_LINEAR, Ogre::FO_ANISOTROPIC }
Filtering options for textures / mipmaps.
enum Ogre::FilterType { Ogre::FT_MIN, Ogre::FT_MAG, Ogre::FT_MIP }
enum Ogre::FogMode { Ogre::FOG_NONE, Ogre::FOG_EXP, Ogre::FOG_EXP2, Ogre::FOG_LINEAR }
Fog modes.
enum Ogre::FrameBufferType { Ogre::FBT_COLOUR = 0x1, Ogre::FBT_DEPTH = 0x2, Ogre::FBT_STENCIL = 0x4 }
Defines the frame buffer types.
enum Ogre::InstanceManagerFlags {
Ogre::IM_USE16BIT = 0x0001, Ogre::IM_VTFBESTFIT = 0x0002, Ogre::IM_VTFBONEMATRIXLOOKUP = 0x0004, Ogre::IM_USEBONEDUALQUATERNIONS = 0x0008,
Ogre::IM_USEONEWEIGHT = 0x0010, Ogre::IM_FORCEONEWEIGHT = 0x0020, Ogre::IM_USEALL = IM_USE16BIT|IM_VTFBESTFIT|IM_USEONEWEIGHT
}
Flags for the Instance Manager when calculating ideal number of instances per batch.
enum Ogre::LoggingLevel { Ogre::LL_LOW = 1, Ogre::LL_NORMAL = 2, Ogre::LL_BOREME = 3 }
The level of detail to which the log will go into.
enum Ogre::LogMessageLevel { Ogre::LML_TRIVIAL = 1, Ogre::LML_NORMAL = 2, Ogre::LML_WARNING = 3, Ogre::LML_CRITICAL = 4 }
The importance of a logged message.
enum Ogre::ManualCullingMode { Ogre::MANUAL_CULL_NONE = 1, Ogre::MANUAL_CULL_BACK = 2, Ogre::MANUAL_CULL_FRONT = 3 }
Manual culling modes based on vertex normals.
enum Ogre::ParameterType {
Ogre::PT_BOOL, Ogre::PT_REAL, Ogre::PT_INT, Ogre::PT_UNSIGNED_INT,
Ogre::PT_SHORT, Ogre::PT_UNSIGNED_SHORT, Ogre::PT_LONG, Ogre::PT_UNSIGNED_LONG,
Ogre::PT_STRING, Ogre::PT_VECTOR3, Ogre::PT_MATRIX3, Ogre::PT_MATRIX4,
Ogre::PT_QUATERNION, Ogre::PT_COLOURVALUE
}
List of parameter types available.
enum Ogre::PolygonMode { Ogre::PM_POINTS = 1, Ogre::PM_WIREFRAME = 2, Ogre::PM_SOLID = 3 }
The polygon mode to use when rasterising.
enum Ogre::ProfileGroupMask {
Ogre::OGREPROF_USER_DEFAULT = 0x00000001, Ogre::OGREPROF_ALL = 0xFF000000, Ogre::OGREPROF_GENERAL = 0x80000000, Ogre::OGREPROF_CULLING = 0x40000000,
Ogre::OGREPROF_RENDERING = 0x20000000
}
List of reserved profiling masks.
enum Ogre::ShadeOptions { Ogre::SO_FLAT, Ogre::SO_GOURAUD, Ogre::SO_PHONG }
Light shading modes.
enum Ogre::ShadowTechnique {
Ogre::SHADOWTYPE_NONE = 0x00, Ogre::SHADOWDETAILTYPE_ADDITIVE = 0x01, Ogre::SHADOWDETAILTYPE_MODULATIVE = 0x02, Ogre::SHADOWDETAILTYPE_INTEGRATED = 0x04,
Ogre::SHADOWDETAILTYPE_STENCIL = 0x10, Ogre::SHADOWDETAILTYPE_TEXTURE = 0x20, Ogre::SHADOWTYPE_STENCIL_MODULATIVE = SHADOWDETAILTYPE_STENCIL | SHADOWDETAILTYPE_MODULATIVE, Ogre::SHADOWTYPE_STENCIL_ADDITIVE = SHADOWDETAILTYPE_STENCIL | SHADOWDETAILTYPE_ADDITIVE,
Ogre::SHADOWTYPE_TEXTURE_MODULATIVE = SHADOWDETAILTYPE_TEXTURE | SHADOWDETAILTYPE_MODULATIVE, Ogre::SHADOWTYPE_TEXTURE_ADDITIVE = SHADOWDETAILTYPE_TEXTURE | SHADOWDETAILTYPE_ADDITIVE, Ogre::SHADOWTYPE_TEXTURE_ADDITIVE_INTEGRATED = SHADOWTYPE_TEXTURE_ADDITIVE | SHADOWDETAILTYPE_INTEGRATED, Ogre::SHADOWTYPE_TEXTURE_MODULATIVE_INTEGRATED = SHADOWTYPE_TEXTURE_MODULATIVE | SHADOWDETAILTYPE_INTEGRATED
}
An enumeration of broad shadow techniques.
enum Ogre::SharedPtrFreeMethod { Ogre::SPFM_DELETE, Ogre::SPFM_DELETE_T, Ogre::SPFM_FREE, Ogre::SPFM_NONE }
The method to use to free memory on destruction.
enum Ogre::SortMode { Ogre::SM_DIRECTION, Ogre::SM_DISTANCE }
Sort mode for billboard-set and particle-system.
enum Ogre::StereoModeType { Ogre::SMT_NONE = 0x0, Ogre::SMT_FRAME_SEQUENTIAL }
Defines the stereo mode types.
enum Ogre::TextureFilterOptions { Ogre::TFO_NONE, Ogre::TFO_BILINEAR, Ogre::TFO_TRILINEAR, Ogre::TFO_ANISOTROPIC }
High-level filtering options providing shortcuts to settings the minification, magnification and mip filters.
enum Ogre::TrackVertexColourEnum {
Ogre::TVC_NONE = 0x0, Ogre::TVC_AMBIENT = 0x1, Ogre::TVC_DIFFUSE = 0x2, Ogre::TVC_SPECULAR = 0x4,
Ogre::TVC_EMISSIVE = 0x8
}
enum Ogre::WaveformType {
Ogre::WFT_SINE, Ogre::WFT_TRIANGLE, Ogre::WFT_SQUARE, Ogre::WFT_SAWTOOTH,
Ogre::WFT_INVERSE_SAWTOOTH, Ogre::WFT_PWM
}
Enumerates the wave types usable with the Ogre engine.
Functions
template<typename ValueType >
ValueType Ogre::any_cast (const Any &operand)
template<typename ValueType >
ValueType * Ogre::any_cast (Any *operand)
template<typename ValueType >
const ValueType * Ogre::any_cast (const Any *operand)
template<class T , class U >
SharedPtr< T > Ogre::dynamic_pointer_cast (const SharedPtr< U > &r)
uint32 Ogre::FastHash (const char *data, size_t len, uint32 hashSoFar=0)
Fast general hashing algorithm.
int _OgreExport Ogre::findCommandLineOpts (int numargs, char **argv, UnaryOptionList &unaryOptList, BinaryOptionList &binOptList)
Locate command-line options of the unary form '-blah' and of the binary form '-blah foo', passing back the index of the next non-option.
template<typename T >
uint32 Ogre::HashCombine (uint32 hashSoFar, const T &data)
Combine hashes with same style as boost::hash_combine.
template<class T >
bool Ogre::operator!= (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<class T , class U >
bool Ogre::operator!= (SharedPtr< T > const &a, SharedPtr< U > const &b)
template<class T >
bool Ogre::operator< (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<class T , class U >
bool Ogre::operator< (SharedPtr< T > const &a, SharedPtr< U > const &b)
template<typename T >
std::ostream & Ogre::operator<< (std::ostream &o, const TRect< T > &r)
template<class T >
bool Ogre::operator<= (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<class T >
bool Ogre::operator== (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<class T , class U >
bool Ogre::operator== (SharedPtr< T > const &a, SharedPtr< U > const &b)
template<class T >
bool Ogre::operator> (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<class T >
bool Ogre::operator>= (const ComPtr< T > &a, const ComPtr< T > &b) ASSUME_NOEXCEPT
template<>
void Ogre::StringConverter::parse (const String &str, ColourValue &v)
template<>
void Ogre::StringConverter::parse (const String &str, Quaternion &v)
template<>
void Ogre::StringConverter::parse (const String &str, Matrix4 &v)
template<>
void Ogre::StringConverter::parse (const String &str, Matrix3 &v)
template<>
void Ogre::StringConverter::parse (const String &str, Vector4 &v)
template<>
void Ogre::StringConverter::parse (const String &str, Vector3 &v)
template<>
void Ogre::StringConverter::parse (const String &str, Vector2 &v)
template<>
void Ogre::StringConverter::parse (const String &str, size_t &v)
template<>
void Ogre::StringConverter::parse (const String &str, long &v)
template<>
void Ogre::StringConverter::parse (const String &str, bool &v)
template<>
void Ogre::StringConverter::parse (const String &str, int &v)
template<>
void Ogre::StringConverter::parse (const String &str, Real &v)
template<class T , class U >
SharedPtr< T > Ogre::static_pointer_cast (const SharedPtr< U > &r)
template<class T >
void Ogre::swap (ComPtr< T > &a, ComPtr< T > &b)
Variables
const String Ogre::BLANKSTRING
Constant blank string, useful for returning by ref where local does not exist.
Detailed Description
Macro Definition Documentation
OGRE_EXCEPT
#define OGRE_EXCEPT (code, desc, src) Ogre::ExceptionFactory::throwException(code, desc, src, __FILE__, __LINE__)
Referenced by Ogre::any_cast(), Ogre::AnimableValue::applyDeltaValue(), Ogre::AnimableObject::createAnimableValue(), Ogre::AnimableObject::getAnimableValueNames(), Ogre::Renderable::getCustomParameter(), Ogre::InstanceManager::getInstanceBatchIterator(), Ogre::HardwareBuffer::lock(), Ogre::Codec::registerCodec(), Ogre::GLNativeSupport::setConfigOption(), Ogre::PortalBase::setDirection(), Ogre::AnimableValue::setValue(), and Ogre::PropertySet::setValue().
OGRE_EXCEPT_EX
#define OGRE_EXCEPT_EX (code, num, desc, src) Ogre::ExceptionFactory::throwExceptionEx(code, num, desc, src, __FILE__, __LINE__)
Deprecated:
do not use
Referenced by Ogre::D3D11Texture::HasAutoMipMapGenerationEnabled().
OGRE_LOG_THRESHOLD
#define OGRE_LOG_THRESHOLD 4
Typedef Documentation
RGBA
typedef uint32 Ogre::RGBA
ARGB
typedef uint32 Ogre::ARGB
ABGR
typedef uint32 Ogre::ABGR
BGRA
typedef uint32 Ogre::BGRA
TrackVertexColourType
typedef int Ogre::TrackVertexColourType
An enumeration describing which material properties should track the vertex colours.
LightList
typedef HashedVector<Light*> Ogre::LightList
UnaryOptionList
typedef map<String, bool>::type Ogre::UnaryOptionList
BinaryOptionList
typedef map<String, String>::type Ogre::BinaryOptionList
NameValuePairList
typedef map<String, String>::type Ogre::NameValuePairList
Name / value parameter pair (first = name, second = value)
AliasTextureNamePairList
typedef map<String, String>::type Ogre::AliasTextureNamePairList
Alias / Texture name pair (first = alias, second = texture name)
FloatRect
typedef TRect<float> Ogre::FloatRect
Structure used to define a rectangle in a 2-D floating point space.
RealRect
typedef TRect<Real> Ogre::RealRect
Structure used to define a rectangle in a 2-D floating point space, subject to double / single floating point settings.
Rect
typedef TRect< long > Ogre::Rect
Structure used to define a rectangle in a 2-D integer space.
RenderWindowDescriptionList
typedef vector<RenderWindowDescription>::type Ogre::RenderWindowDescriptionList
Render window creation parameters container.
RenderWindowList
typedef vector<RenderWindow*>::type Ogre::RenderWindowList
Render window container.
ConfigOption
typedef struct Ogre::_ConfigOption Ogre::ConfigOption
Packages the details of a configuration option.
Remarks
Used for RenderSystem::getConfigOptions. If immutable is true, this option must be disabled for modifying.
ConfigOptionMap
typedef map< String, ConfigOption >::type Ogre::ConfigOptionMap
ControllerValueRealPtr
typedef SharedPtr< ControllerValue<Real> > Ogre::ControllerValueRealPtr
ControllerFunctionRealPtr
typedef SharedPtr< ControllerFunction<Real> > Ogre::ControllerFunctionRealPtr
RenderSystemList
typedef vector<RenderSystem*>::type Ogre::RenderSystemList
ConcreteNodePtr
typedef SharedPtr<ConcreteNode> Ogre::ConcreteNodePtr
ConcreteNodeList
typedef list<ConcreteNodePtr>::type Ogre::ConcreteNodeList
ConcreteNodeListPtr
typedef SharedPtr<ConcreteNodeList> Ogre::ConcreteNodeListPtr
AbstractNodePtr
typedef SharedPtr<AbstractNode> Ogre::AbstractNodePtr
AbstractNodeList
typedef list<AbstractNodePtr>::type Ogre::AbstractNodeList
AbstractNodeListPtr
typedef SharedPtr<AbstractNodeList> Ogre::AbstractNodeListPtr
ScriptTokenPtr
typedef SharedPtr<ScriptToken> Ogre::ScriptTokenPtr
ScriptTokenList
typedef vector<ScriptTokenPtr>::type Ogre::ScriptTokenList
ScriptTokenListPtr
typedef SharedPtr<ScriptTokenList> Ogre::ScriptTokenListPtr
_StringHash
typedef stdext::hash_compare< _StringBase, std::less< _StringBase > > Ogre::_StringHash
ParameterList
typedef vector<ParameterDef>::type Ogre::ParameterList
ParamCommandMap
typedef map<String, ParamCommand* >::type Ogre::ParamCommandMap
ParamDictionaryMap
typedef map<String, ParamDictionary>::type Ogre::ParamDictionaryMap
StringVector
typedef vector<String>::type Ogre::StringVector
StringVectorPtr
typedef SharedPtr<StringVector> Ogre::StringVectorPtr
Enumeration Type Documentation
CompareFunction
enum Ogre::CompareFunction
Comparison functions used for the depth/stencil buffer operations and others.
Enumerator
CMPF_ALWAYS_FAIL
CMPF_ALWAYS_PASS
CMPF_LESS
CMPF_LESS_EQUAL
CMPF_EQUAL
CMPF_NOT_EQUAL
CMPF_GREATER_EQUAL
CMPF_GREATER
TextureFilterOptions
enum Ogre::TextureFilterOptions
High-level filtering options providing shortcuts to settings the minification, magnification and mip filters.
Enumerator
TFO_NONE
Equal to: min=FO_POINT, mag=FO_POINT, mip=FO_NONE.
TFO_BILINEAR
Equal to: min=FO_LINEAR, mag=FO_LINEAR, mip=FO_POINT.
TFO_TRILINEAR
Equal to: min=FO_LINEAR, mag=FO_LINEAR, mip=FO_LINEAR.
TFO_ANISOTROPIC
Equal to: min=FO_ANISOTROPIC, max=FO_ANISOTROPIC, mip=FO_LINEAR.
FilterType
enum Ogre::FilterType
Enumerator
FT_MIN
The filter used when shrinking a texture.
FT_MAG
The filter used when magnifying a texture.
FT_MIP
The filter used when determining the mipmap.
FilterOptions
enum Ogre::FilterOptions
Filtering options for textures / mipmaps.
Enumerator
FO_NONE
No filtering, used for FT_MIP to turn off mipmapping.
FO_POINT
Use the closest pixel.
FO_LINEAR
Average of a 2x2 pixel area, denotes bilinear for MIN and MAG, trilinear for MIP.
FO_ANISOTROPIC
Similar to FO_LINEAR, but compensates for the angle of the texture plane.
ShadeOptions
enum Ogre::ShadeOptions
Light shading modes.
Enumerator
SO_FLAT
SO_GOURAUD
SO_PHONG
FogMode
enum Ogre::FogMode
Fog modes.
Enumerator
FOG_NONE
No fog. Duh.
FOG_EXP
Fog density increases exponentially from the camera (fog = 1/e^(distance * density))
FOG_EXP2
Fog density increases at the square of FOG_EXP, i.e. even quicker (fog = 1/e^(distance * density)^2)
FOG_LINEAR
Fog density increases linearly between the start and end distances.
CullingMode
enum Ogre::CullingMode
Hardware culling modes based on vertex winding.
This setting applies to how the hardware API culls triangles it is sent.
Enumerator
CULL_NONE
Hardware never culls triangles and renders everything it receives.
CULL_CLOCKWISE
Hardware culls triangles whose vertices are listed clockwise in the view (default).
CULL_ANTICLOCKWISE
Hardware culls triangles whose vertices are listed anticlockwise in the view.
ManualCullingMode
enum Ogre::ManualCullingMode
Manual culling modes based on vertex normals.
This setting applies to how the software culls triangles before sending them to the hardware API. This culling mode is used by scene managers which choose to implement it - normally those which deal with large amounts of fixed world geometry which is often planar (software culling movable variable geometry is expensive).
Enumerator
MANUAL_CULL_NONE
No culling so everything is sent to the hardware.
MANUAL_CULL_BACK
Cull triangles whose normal is pointing away from the camera (default).
MANUAL_CULL_FRONT
Cull triangles whose normal is pointing towards the camera.
WaveformType
enum Ogre::WaveformType
Enumerates the wave types usable with the Ogre engine.
Enumerator
WFT_SINE
Standard sine wave which smoothly changes from low to high and back again.
WFT_TRIANGLE
An angular wave with a constant increase / decrease speed with pointed peaks.
WFT_SQUARE
Half of the time is spent at the min, half at the max with instant transition between.
WFT_SAWTOOTH
Gradual steady increase from min to max over the period with an instant return to min at the end.
WFT_INVERSE_SAWTOOTH
Gradual steady decrease from max to min over the period, with an instant return to max at the end.
WFT_PWM
Pulse Width Modulation.
Works like WFT_SQUARE, except the high to low transition is controlled by duty cycle. With a duty cycle of 50% (0.5) will give the same output as WFT_SQUARE.
PolygonMode
enum Ogre::PolygonMode
The polygon mode to use when rasterising.
Enumerator
PM_POINTS
Only points are rendered.
PM_WIREFRAME
Wireframe models are rendered.
PM_SOLID
Solid polygons are rendered.
ShadowTechnique
enum Ogre::ShadowTechnique
An enumeration of broad shadow techniques.
Enumerator
SHADOWTYPE_NONE
No shadows.
SHADOWDETAILTYPE_ADDITIVE
Mask for additive shadows (not for direct use, use SHADOWTYPE_ enum instead)
SHADOWDETAILTYPE_MODULATIVE
Mask for modulative shadows (not for direct use, use SHADOWTYPE_ enum instead)
SHADOWDETAILTYPE_INTEGRATED
Mask for integrated shadows (not for direct use, use SHADOWTYPE_ enum instead)
SHADOWDETAILTYPE_STENCIL
Mask for stencil shadows (not for direct use, use SHADOWTYPE_ enum instead)
SHADOWDETAILTYPE_TEXTURE
Mask for texture shadows (not for direct use, use SHADOWTYPE_ enum instead)
SHADOWTYPE_STENCIL_MODULATIVE
Stencil shadow technique which renders all shadow volumes as a modulation after all the non-transparent areas have been rendered.
This technique is considerably less fillrate intensive than the additive stencil shadow approach when there are multiple lights, but is not an accurate model.
SHADOWTYPE_STENCIL_ADDITIVE
Stencil shadow technique which renders each light as a separate additive pass to the scene.
This technique can be very fillrate intensive because it requires at least 2 passes of the entire scene, more if there are multiple lights. However, it is a more accurate model than the modulative stencil approach and this is especially apparent when using coloured lights or bump mapping.
SHADOWTYPE_TEXTURE_MODULATIVE
Texture-based shadow technique which involves a monochrome render-to-texture of the shadow caster and a projection of that texture onto the shadow receivers as a modulative pass.
SHADOWTYPE_TEXTURE_ADDITIVE
Texture-based shadow technique which involves a render-to-texture of the shadow caster and a projection of that texture onto the shadow receivers, built up per light as additive passes.
This technique can be very fillrate intensive because it requires numLights + 2 passes of the entire scene. However, it is a more accurate model than the modulative approach and this is especially apparent when using coloured lights or bump mapping.
SHADOWTYPE_TEXTURE_ADDITIVE_INTEGRATED
Texture-based shadow technique which involves a render-to-texture of the shadow caster and a projection of that texture on to the shadow receivers, with the usage of those shadow textures completely controlled by the materials of the receivers.
This technique is easily the most flexible of all techniques because the material author is in complete control over how the shadows are combined with regular rendering. It can perform shadows as accurately as SHADOWTYPE_TEXTURE_ADDITIVE but more efficiently because it requires less passes. However it also requires more expertise to use, and in almost all cases, shader capable hardware to really use to the full.
Note
The 'additive' part of this mode means that the colour of the rendered shadow texture is by default plain black. It does not mean it does the adding on your receivers automatically though, how you use that result is up to you.
SHADOWTYPE_TEXTURE_MODULATIVE_INTEGRATED
Texture-based shadow technique which involves a render-to-texture of the shadow caster and a projection of that texture on to the shadow receivers, with the usage of those shadow textures completely controlled by the materials of the receivers.
This technique is easily the most flexible of all techniques because the material author is in complete control over how the shadows are combined with regular rendering. It can perform shadows as accurately as SHADOWTYPE_TEXTURE_ADDITIVE but more efficiently because it requires less passes. However it also requires more expertise to use, and in almost all cases, shader capable hardware to really use to the full.
Note
The 'modulative' part of this mode means that the colour of the rendered shadow texture is by default the 'shadow colour'. It does not mean it modulates on your receivers automatically though, how you use that result is up to you.
TrackVertexColourEnum
enum Ogre::TrackVertexColourEnum
Enumerator
TVC_NONE
TVC_AMBIENT
TVC_DIFFUSE
TVC_SPECULAR
TVC_EMISSIVE
SortMode
enum Ogre::SortMode
Sort mode for billboard-set and particle-system.
Enumerator
SM_DIRECTION
Sort by direction of the camera.
SM_DISTANCE
Sort by distance from the camera.
FrameBufferType
enum Ogre::FrameBufferType
Defines the frame buffer types.
Enumerator
FBT_COLOUR
FBT_DEPTH
FBT_STENCIL
ColourBufferType
enum Ogre::ColourBufferType
Defines the colour buffer types.
Enumerator
CBT_BACK
CBT_BACK_LEFT
CBT_BACK_RIGHT
StereoModeType
enum Ogre::StereoModeType
Defines the stereo mode types.
Enumerator
SMT_NONE
SMT_FRAME_SEQUENTIAL
InstanceManagerFlags
enum Ogre::InstanceManagerFlags
Flags for the Instance Manager when calculating ideal number of instances per batch.
Enumerator
IM_USE16BIT
Forces an amount of instances per batch low enough so that vertices * numInst < 65535 since usually improves performance.
In HW instanced techniques, this flag is ignored
IM_VTFBESTFIT
The num.
of instances is adjusted so that as few pixels as possible are wasted in the vertex texture
IM_VTFBONEMATRIXLOOKUP
Use a limited number of skeleton animations shared among all instances.
Update only that limited amount of animations in the vertex texture.
IM_USEBONEDUALQUATERNIONS
IM_USEONEWEIGHT
Use one weight per vertex when recommended (i.e.
VTF).
IM_FORCEONEWEIGHT
All techniques are forced to one weight per vertex.
IM_USEALL
ClipResult
enum Ogre::ClipResult
Generic result of clipping.
Enumerator
CLIPPED_NONE
Nothing was clipped.
CLIPPED_SOME
Partially clipped.
CLIPPED_ALL
Everything was clipped away.
LoggingLevel
enum Ogre::LoggingLevel
The level of detail to which the log will go into.
Enumerator
LL_LOW
LL_NORMAL
LL_BOREME
LogMessageLevel
enum Ogre::LogMessageLevel
The importance of a logged message.
Enumerator
LML_TRIVIAL
LML_NORMAL
LML_WARNING
LML_CRITICAL
ProfileGroupMask
enum Ogre::ProfileGroupMask
List of reserved profiling masks.
Enumerator
OGREPROF_USER_DEFAULT
User default profile.
OGREPROF_ALL
All in-built Ogre profiling will match this mask.
OGREPROF_GENERAL
General processing.
OGREPROF_CULLING
Culling.
OGREPROF_RENDERING
Rendering.
ConcreteNodeType
enum Ogre::ConcreteNodeType
These enums hold the types of the concrete parsed nodes.
Enumerator
CNT_VARIABLE
CNT_VARIABLE_ASSIGN
CNT_WORD
CNT_IMPORT
CNT_QUOTE
CNT_LBRACE
CNT_RBRACE
CNT_COLON
AbstractNodeType
enum Ogre::AbstractNodeType
This enum holds the types of the possible abstract nodes.
Enumerator
ANT_UNKNOWN
ANT_ATOM
ANT_OBJECT
ANT_PROPERTY
ANT_IMPORT
ANT_VARIABLE_SET
ANT_VARIABLE_ACCESS
anonymous enum
anonymous enum
This enum defines the integer ids for keywords this compiler handles.
Enumerator
ID_MATERIAL
ID_VERTEX_PROGRAM
ID_GEOMETRY_PROGRAM
ID_FRAGMENT_PROGRAM
ID_TECHNIQUE
ID_PASS
ID_TEXTURE_UNIT
ID_VERTEX_PROGRAM_REF
ID_GEOMETRY_PROGRAM_REF
ID_FRAGMENT_PROGRAM_REF
ID_SHADOW_CASTER_VERTEX_PROGRAM_REF
ID_SHADOW_CASTER_FRAGMENT_PROGRAM_REF
ID_SHADOW_RECEIVER_VERTEX_PROGRAM_REF
ID_SHADOW_RECEIVER_FRAGMENT_PROGRAM_REF
ID_SHADOW_CASTER_MATERIAL
ID_SHADOW_RECEIVER_MATERIAL
ID_LOD_VALUES
ID_LOD_STRATEGY
ID_LOD_DISTANCES
ID_RECEIVE_SHADOWS
ID_TRANSPARENCY_CASTS_SHADOWS
ID_SET_TEXTURE_ALIAS
ID_SOURCE
ID_SYNTAX
ID_DEFAULT_PARAMS
ID_PARAM_INDEXED
ID_PARAM_NAMED
ID_PARAM_INDEXED_AUTO
ID_PARAM_NAMED_AUTO
ID_SCHEME
ID_LOD_INDEX
ID_GPU_VENDOR_RULE
ID_GPU_DEVICE_RULE
ID_INCLUDE
ID_EXCLUDE
ID_AMBIENT
ID_DIFFUSE
ID_SPECULAR
ID_EMISSIVE
ID_VERTEXCOLOUR
ID_SCENE_BLEND
ID_COLOUR_BLEND
ID_ONE
ID_ZERO
ID_DEST_COLOUR
ID_SRC_COLOUR
ID_ONE_MINUS_DEST_COLOUR
ID_ONE_MINUS_SRC_COLOUR
ID_DEST_ALPHA
ID_SRC_ALPHA
ID_ONE_MINUS_DEST_ALPHA
ID_ONE_MINUS_SRC_ALPHA
ID_SEPARATE_SCENE_BLEND
ID_SCENE_BLEND_OP
ID_REVERSE_SUBTRACT
ID_MIN
ID_MAX
ID_SEPARATE_SCENE_BLEND_OP
ID_DEPTH_CHECK
ID_DEPTH_WRITE
ID_DEPTH_FUNC
ID_DEPTH_BIAS
ID_ITERATION_DEPTH_BIAS
ID_ALWAYS_FAIL
ID_ALWAYS_PASS
ID_LESS_EQUAL
ID_LESS
ID_EQUAL
ID_NOT_EQUAL
ID_GREATER_EQUAL
ID_GREATER
ID_ALPHA_REJECTION
ID_ALPHA_TO_COVERAGE
ID_LIGHT_SCISSOR
ID_LIGHT_CLIP_PLANES
ID_TRANSPARENT_SORTING
ID_ILLUMINATION_STAGE
ID_DECAL
ID_CULL_HARDWARE
ID_CLOCKWISE
ID_ANTICLOCKWISE
ID_CULL_SOFTWARE
ID_BACK
ID_FRONT
ID_NORMALISE_NORMALS
ID_LIGHTING
ID_SHADING
ID_FLAT
ID_GOURAUD
ID_PHONG
ID_POLYGON_MODE
ID_SOLID
ID_WIREFRAME
ID_POINTS
ID_POLYGON_MODE_OVERRIDEABLE
ID_FOG_OVERRIDE
ID_NONE
ID_LINEAR
ID_EXP
ID_EXP2
ID_COLOUR_WRITE
ID_MAX_LIGHTS
ID_START_LIGHT
ID_ITERATION
ID_ONCE
ID_ONCE_PER_LIGHT
ID_PER_LIGHT
ID_PER_N_LIGHTS
ID_POINT
ID_SPOT
ID_DIRECTIONAL
ID_LIGHT_MASK
ID_POINT_SIZE
ID_POINT_SPRITES
ID_POINT_SIZE_ATTENUATION
ID_POINT_SIZE_MIN
ID_POINT_SIZE_MAX
ID_TEXTURE_ALIAS
ID_TEXTURE
ID_1D
ID_2D
ID_3D
ID_CUBIC
ID_2DARRAY
ID_UNLIMITED
ID_ALPHA
ID_GAMMA
ID_ANIM_TEXTURE
ID_CUBIC_TEXTURE
ID_SEPARATE_UV
ID_COMBINED_UVW
ID_TEX_COORD_SET
ID_TEX_ADDRESS_MODE
ID_WRAP
ID_CLAMP
ID_BORDER
ID_MIRROR
ID_TEX_BORDER_COLOUR
ID_FILTERING
ID_BILINEAR
ID_TRILINEAR
ID_ANISOTROPIC
ID_CMPTEST
ID_ON
ID_OFF
ID_CMPFUNC
ID_MAX_ANISOTROPY
ID_MIPMAP_BIAS
ID_COLOUR_OP
ID_REPLACE
ID_ADD
ID_MODULATE
ID_ALPHA_BLEND
ID_COLOUR_OP_EX
ID_SOURCE1
ID_SOURCE2
ID_MODULATE_X2
ID_MODULATE_X4
ID_ADD_SIGNED
ID_ADD_SMOOTH
ID_SUBTRACT
ID_BLEND_DIFFUSE_COLOUR
ID_BLEND_DIFFUSE_ALPHA
ID_BLEND_TEXTURE_ALPHA
ID_BLEND_CURRENT_ALPHA
ID_BLEND_MANUAL
ID_DOT_PRODUCT
ID_SRC_CURRENT
ID_SRC_TEXTURE
ID_SRC_DIFFUSE
ID_SRC_SPECULAR
ID_SRC_MANUAL
ID_COLOUR_OP_MULTIPASS_FALLBACK
ID_ALPHA_OP_EX
ID_ENV_MAP
ID_SPHERICAL
ID_PLANAR
ID_CUBIC_REFLECTION
ID_CUBIC_NORMAL
ID_SCROLL
ID_SCROLL_ANIM
ID_ROTATE
ID_ROTATE_ANIM
ID_SCALE
ID_WAVE_XFORM
ID_SCROLL_X
ID_SCROLL_Y
ID_SCALE_X
ID_SCALE_Y
ID_SINE
ID_TRIANGLE
ID_SQUARE
ID_SAWTOOTH
ID_INVERSE_SAWTOOTH
ID_TRANSFORM
ID_BINDING_TYPE
ID_VERTEX
ID_FRAGMENT
ID_CONTENT_TYPE
ID_NAMED
ID_SHADOW
ID_TEXTURE_SOURCE
ID_SHARED_PARAMS
ID_SHARED_PARAM_NAMED
ID_SHARED_PARAMS_REF
ID_PARTICLE_SYSTEM
ID_EMITTER
ID_AFFECTOR
ID_COMPOSITOR
ID_TARGET
ID_TARGET_OUTPUT
ID_INPUT
ID_PREVIOUS
ID_TARGET_WIDTH
ID_TARGET_HEIGHT
ID_TARGET_WIDTH_SCALED
ID_TARGET_HEIGHT_SCALED
ID_COMPOSITOR_LOGIC
ID_TEXTURE_REF
ID_SCOPE_LOCAL
ID_SCOPE_CHAIN
ID_SCOPE_GLOBAL
ID_POOLED
ID_NO_FSAA
ID_DEPTH_POOL
ID_ONLY_INITIAL
ID_VISIBILITY_MASK
ID_LOD_BIAS
ID_MATERIAL_SCHEME
ID_SHADOWS_ENABLED
ID_CLEAR
ID_STENCIL
ID_RENDER_SCENE
ID_RENDER_QUAD
ID_IDENTIFIER
ID_FIRST_RENDER_QUEUE
ID_LAST_RENDER_QUEUE
ID_QUAD_NORMALS
ID_CAMERA_FAR_CORNERS_VIEW_SPACE
ID_CAMERA_FAR_CORNERS_WORLD_SPACE
ID_BUFFERS
ID_COLOUR
ID_DEPTH
ID_COLOUR_VALUE
ID_DEPTH_VALUE
ID_STENCIL_VALUE
ID_CHECK
ID_COMP_FUNC
ID_REF_VALUE
ID_MASK
ID_FAIL_OP
ID_KEEP
ID_INCREMENT
ID_DECREMENT
ID_INCREMENT_WRAP
ID_DECREMENT_WRAP
ID_INVERT
ID_DEPTH_FAIL_OP
ID_PASS_OP
ID_TWO_SIDED
ID_READ_BACK_AS_TEXTURE
ID_RT_SHADER_SYSTEM
ID_TESSELLATION_HULL_PROGRAM
Suport for shader model 5.0.
ID_TESSELLATION_DOMAIN_PROGRAM
ID_COMPUTE_PROGRAM
ID_TESSELLATION_HULL_PROGRAM_REF
ID_TESSELLATION_DOMAIN_PROGRAM_REF
ID_COMPUTE_PROGRAM_REF
ID_GEOMETRY
ID_TESSELLATION_HULL
ID_TESSELLATION_DOMAIN
ID_COMPUTE
ID_SUBROUTINE
ID_END_BUILTIN_IDS
anonymous enum
anonymous enum
These codes represent token IDs which are numerical translations of specific lexemes.
Specific compilers using the lexer can register their own token IDs which are given precedence over these built-in ones.
Enumerator
TID_LBRACKET
TID_RBRACKET
TID_COLON
TID_VARIABLE
TID_WORD
TID_QUOTE
TID_NEWLINE
TID_UNKNOWN
TID_END
SharedPtrFreeMethod
enum Ogre::SharedPtrFreeMethod
The method to use to free memory on destruction.
Enumerator
SPFM_DELETE
Use OGRE_DELETE to free the memory.
SPFM_DELETE_T
Use OGRE_DELETE_T to free (only MEMCATEGORY_GENERAL supported)
SPFM_FREE
Use OGRE_FREE to free (only MEMCATEGORY_GENERAL supported)
SPFM_NONE
Don`t free resource at all, lifetime controlled externally.
ParameterType
enum Ogre::ParameterType
List of parameter types available.
Enumerator
PT_BOOL
PT_REAL
PT_INT
PT_UNSIGNED_INT
PT_SHORT
PT_UNSIGNED_SHORT
PT_LONG
PT_UNSIGNED_LONG
PT_STRING
PT_VECTOR3
PT_MATRIX3
PT_MATRIX4
PT_QUATERNION
PT_COLOURVALUE
Function Documentation
any_cast() [1/3]
template<typename ValueType > ValueType* Ogre::any_cast (Any * operand)
References Ogre::Any::type().
any_cast() [2/3]
template<typename ValueType > const ValueType* Ogre::any_cast (const Any * operand)
References Ogre::Any::any_cast.
any_cast() [3/3]
template<typename ValueType > ValueType Ogre::any_cast (const Any & operand)
References Ogre::Any::any_cast, Ogre::Exception::ERR_INVALIDPARAMS, OGRE_EXCEPT, and Ogre::Any::type().
FastHash()
uint32 Ogre::FastHash (const char * data, size_t len, uint32 hashSoFar = 0) inline
Fast general hashing algorithm.
Referenced by Ogre::HashCombine().
HashCombine()
template<typename T > uint32 Ogre::HashCombine (uint32 hashSoFar, const T & data)
Combine hashes with same style as boost::hash_combine.
References Ogre::FastHash().
operator<<()
template<typename T > std::ostream& Ogre::operator<< (std::ostream & o, const TRect< T > & r)
References Ogre::TRect< T >::left.
Referenced by Ogre::Camera::Listener::cameraDestroyed(), Ogre::PagedWorld::getPageProvider(), Ogre::PagedWorldSection::getPageProvider(), Ogre::Terrain::isDerivedDataUpdateInProgress(), Ogre::Polygon::operator!=(), Ogre::ConvexBody::operator!=(), Ogre::Plane::operator!=(), and Ogre::ResourceBackgroundQueue::Listener::~Listener().
findCommandLineOpts()
int _OgreExport Ogre::findCommandLineOpts (int numargs, char ** argv, UnaryOptionList & unaryOptList, BinaryOptionList & binOptList)
Locate command-line options of the unary form '-blah' and of the binary form '-blah foo', passing back the index of the next non-option.
Parameters
numargs,argv The standard parameters passed to the main method
unaryOptList Map of unary options (i.e. those that do not require a parameter). Should be pre-populated with, for example '-e' in the key and false in the value. Options which are found will be set to true on return.
binOptList Map of binary options (i.e. those that require a parameter e.g. '-e afile.txt'). Should be pre-populated with, for example '-e' and the default setting. Options which are found will have the value updated.
Referenced by Ogre::Box::getDepth().
static_pointer_cast()
template<class T , class U > SharedPtr<T> Ogre::static_pointer_cast (const SharedPtr< U > & r) inline
Referenced by Ogre::SharedPtr< Skeleton >::staticCast().
dynamic_pointer_cast()
template<class T , class U > SharedPtr<T> Ogre::dynamic_pointer_cast (const SharedPtr< U > & r) inline
Referenced by Ogre::SharedPtr< Skeleton >::dynamicCast().
operator==() [1/2]
template<class T , class U > bool Ogre::operator== (SharedPtr< T > const & a, SharedPtr< U > const & b) inline
References Ogre::SharedPtr< T >::get().
operator!=() [1/2]
template<class T , class U > bool Ogre::operator!= (SharedPtr< T > const & a, SharedPtr< U > const & b) inline
References Ogre::SharedPtr< T >::get().
operator<() [1/2]
template<class T , class U > bool Ogre::operator< (SharedPtr< T > const & a, SharedPtr< U > const & b) inline
Referenced by Ogre::RTShader::FunctionInvocation::getReturnType().
swap()
template<class T > void Ogre::swap (ComPtr< T > & a, ComPtr< T > & b)
References Ogre::ComPtr< T >::Swap().
Referenced by Ogre::SharedPtr< Skeleton >::operator=(), Ogre::SharedPtr< Skeleton >::reset(), and Ogre::D3D9RenderTexture::~D3D9RenderTexture().
operator==() [2/2]
template<class T > bool Ogre::operator== (const ComPtr< T > & a, const ComPtr< T > & b)
operator!=() [2/2]
template<class T > bool Ogre::operator!= (const ComPtr< T > & a, const ComPtr< T > & b)
operator<() [2/2]
template<class T > bool Ogre::operator< (const ComPtr< T > & a, const ComPtr< T > & b)
operator>()
template<class T > bool Ogre::operator> (const ComPtr< T > & a, const ComPtr< T > & b)
operator<=()
template<class T > bool Ogre::operator<= (const ComPtr< T > & a, const ComPtr< T > & b)
operator>=()
template<class T > bool Ogre::operator>= (const ComPtr< T > & a, const ComPtr< T > & b)
parse() [1/12]
template<> void Ogre::StringConverter::parse (const String & str, ColourValue & v) inline
References Ogre::StringConverter::parseColourValue().
parse() [2/12]
template<> void Ogre::StringConverter::parse (const String & str, Quaternion & v) inline
References Ogre::StringConverter::parseQuaternion().
parse() [3/12]
template<> void Ogre::StringConverter::parse (const String & str, Matrix4 & v) inline
References Ogre::StringConverter::parseMatrix4().
parse() [4/12]
template<> void Ogre::StringConverter::parse (const String & str, Matrix3 & v) inline
References Ogre::StringConverter::parseMatrix3().
parse() [5/12]
template<> void Ogre::StringConverter::parse (const String & str, Vector4 & v) inline
References Ogre::StringConverter::parseVector4().
parse() [6/12]
template<> void Ogre::StringConverter::parse (const String & str, Vector3 & v) inline
References Ogre::StringConverter::parseVector3().
parse() [7/12]
template<> void Ogre::StringConverter::parse (const String & str, Vector2 & v) inline
References Ogre::StringConverter::parseVector2().
parse() [8/12]
template<> void Ogre::StringConverter::parse (const String & str, size_t & v) inline
References Ogre::StringConverter::parseSizeT().
parse() [9/12]
template<> void Ogre::StringConverter::parse (const String & str, long & v) inline
References Ogre::StringConverter::parseLong().
parse() [10/12]
template<> void Ogre::StringConverter::parse (const String & str, bool & v) inline
References Ogre::StringConverter::parseBool().
parse() [11/12]
template<> void Ogre::StringConverter::parse (const String & str, int & v) inline
References Ogre::StringConverter::parseInt().
parse() [12/12]
template<> void Ogre::StringConverter::parse (const String & str, Real & v) inline
References Ogre::StringConverter::parseReal().
Variable Documentation
BLANKSTRING
const String Ogre::BLANKSTRING
Constant blank string, useful for returning by ref where local does not exist.
Referenced by Ogre::Mesh::_getAnimationTypesDirty(), Ogre::Animation::_keyFrameListChanged(), Ogre::Root::createSceneManager(), Ogre::StreamSerialiser::getCurrentChunkDepth(), Ogre::MaterialManager::getDefaultSettings(), Ogre::RenderSystem::getErrorDescription(), Ogre::InstanceManager::getInstancingTechnique(), Ogre::TerrainLayerBlendMap::getLayerIndex(), OgreBites::TrayManager::getListener(), Ogre::PagedWorld::getManager(), Ogre::CompositorInstance::getScheme(), Ogre::ConfigFile::getSettingsBySection(), Ogre::Material::getUnsupportedTechniquesExplanation(), OgreBites::TrayManager::hideBackdrop(), Ogre::CompositionPass::InputTex::InputTex(), Ogre::Image::loadRawData(), Ogre::ResourceGroupManager::openResource(), and Ogre::Log::Stream::operator<<().