//---------------------------------------------------------------------------
//These materials/shaders are part of the NEW InstanceManager implementation
//Written by Matias N. Goldberg ("dark_sylinc")
//---------------------------------------------------------------------------

//---------------------------------------------
//Vertex Shader Input
//---------------------------------------------
struct VS_INPUT
{
	float4 Position	:	POSITION;
	float3x4 mat	:	TEXCOORD1;
};

#include "InstancingVertexInterpolators.cg"

//---------------------------------------------
//Main Vertex Shader
//---------------------------------------------
VS_OUTPUT main_vs( in VS_INPUT input,
				   uniform float4x4 viewProjMatrix
				)
{
	VS_OUTPUT output;

	float3x4 worldMatrix = input.mat;

	float4 worldPos = float4( mul( worldMatrix, input.Position ).xyz, 1.0f );
	//Transform the position
	output.Position		= mul( viewProjMatrix, worldPos );

	output.ps.unused	= float3( output.Position.zw, 0 );
	output.ps.depth		= output.Position.z;

	return output;
}
