//---------------------------------------------------------------------------
//These materials/shaders are part of the NEW InstanceManager implementation
//Written by Matias N. Goldberg ("dark_sylinc")
//---------------------------------------------------------------------------

//---------------------------------------------
//Pixel Shader Input
//---------------------------------------------
struct PS_INPUT
{
	float4 Position	:	POSITION;
#ifndef DEPTH_SHADOWCASTER
	float2 uv0		:	TEXCOORD0;
	float3 Normal	:	TEXCOORD1;
	float3 vPos		:	TEXCOORD2;
	
	#ifdef DEPTH_SHADOWRECEIVER
		float4 lightSpacePos	:	TEXCOORD3;
	#endif
#endif
};

//---------------------------------------------
//Vertex Shader Output
//---------------------------------------------
struct VS_OUTPUT
{
	PS_INPUT	ps;
};
