OGRE: Ogre::Texture Class Reference
Ogre::Texture Class Reference abstract
Core » Resources
Abstract class representing a Texture resource.
#include <OgreTexture.h>
Public Types
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
Public Member Functions
Texture (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual=false, ManualResourceLoader *loader=0)
virtual ~Texture ()
virtual void _autogenerateMipmaps (void)=0
Tells the API to let the HW autogenerate mipmaps.
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
virtual void _loadImages (const ConstImagePtrList &images)
Internal method to load the texture from a set of images.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
virtual void convertToImage (Image &destImage, bool includeMipMaps=false, uint32 mipmapBias=0)
Populate an Image with the contents of this texture.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual void copyToTexture (TexturePtr &target)
Copies (and maybe scales to fit) the contents of this texture to another texture.
virtual void createInternalResources (void)
Creates the internal texture resources for this texture.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
virtual void freeInternalResources (void)
Frees internal texture resources for this texture.
virtual v1::HardwarePixelBufferSharedPtr getBuffer (size_t face=0, size_t mipmap=0)=0
Return hardware pixel buffer for a surface.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual void getCustomAttribute (const String &name, void *pData)
Retrieve a platform or API-specific piece of information from this texture.
uint32 getDepth (void) const
Returns the depth of the texture (only applicable for 3D textures).
virtual ushort getDesiredFloatBitDepth (void) const
gets desired bit depth for float pixel format textures.
PixelFormat getDesiredFormat (void) const
Returns the desired pixel format for the texture surface.
virtual ushort getDesiredIntegerBitDepth (void) const
gets desired bit depth for integer pixel format textures.
PixelFormat getFormat () const
Returns the pixel format for the texture surface.
virtual uint getFSAA () const
Get the level of multisample AA to be used if this texture is a rendertarget.
virtual const String & getFSAAHint () const
Get the multisample AA hint if this texture is a rendertarget.
float getGamma (void) const
Returns the gamma adjustment factor applied to this texture on loading.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
uint32 getHeight (void) const
Returns the height of the texture.
virtual LoadingState getLoadingState () const
Returns the current loading state.
bool getMipmapsHardwareGenerated (void) const
Are mipmaps hardware generated?
virtual const String & getName (void) const
Gets resource name.
virtual size_t getNumFaces () const
Return the number of faces this texture has.
uint8 getNumMipmaps (void) const
Gets the number of mipmaps to be used for this texture.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
uint32 getSrcDepth (void) const
Returns the original depth of the input texture (only applicable for 3D textures).
PixelFormat getSrcFormat (void) const
Returns the pixel format of the original input texture (may differ due to hardware requirements and pixel format conversion).
uint32 getSrcHeight (void) const
Returns the height of the original input texture (may differ due to hardware requirements).
uint32 getSrcWidth (void) const
Returns the width of the original input texture (may differ due to hardware requirements).
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
TextureType getTextureType (void) const
Gets the type of texture.
virtual bool getTreatLuminanceAsAlpha (void) const
Gets whether luminace pixel format will treated as alpha format when load this texture.
virtual int getUsage () const
Returns the TextureUsage identifier for this Texture.
uint32 getWidth (void) const
Returns the width of the texture.
virtual bool hasAlpha (void) const
Returns true if the texture has an alpha layer.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isHardwareGammaEnabled () const
Gets whether this texture will be set up so that on sampling it, hardware gamma correction is applied.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
bool isTextureTypeArray (void) const
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void loadImage (const Image &img)
Loads the data from an image.
virtual void loadRawData (DataStreamPtr &stream, ushort uWidth, ushort uHeight, PixelFormat eFormat)
Loads the data from a raw stream.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (void)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
void setDepth (uint32 d)
Set the depth of the texture (only applicable for 3D textures); can only do this before load();.
virtual void setDesiredBitDepths (ushort integerBits, ushort floatBits)
Sets desired bit depth for integer and float pixel format.
virtual void setDesiredFloatBitDepth (ushort bits)
Sets desired bit depth for float pixel format textures.
virtual void setDesiredIntegerBitDepth (ushort bits)
Sets desired bit depth for integer pixel format textures.
virtual void setFormat (PixelFormat pf)
Sets the pixel format for the texture surface; can only be set before load().
virtual void setFSAA (uint fsaa, const String &fsaaHint, bool explicitResolve)
Set the level of multisample AA to be used if this texture is a rendertarget.
void setGamma (float g)
Sets the gamma adjustment factor applied to this texture on loading the data.
void setHardwareGammaEnabled (bool enabled)
Sets whether this texture will be set up so that on sampling it, hardware gamma correction is applied.
void setHeight (uint32 h)
Set the height of the texture; can only do this before load();.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
void setNumMipmaps (uint8 num)
Sets the number of mipmaps to be used for this texture.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setTextureType (TextureType ttype)
Sets the type of texture; can only be changed before load()
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
virtual void setTreatLuminanceAsAlpha (bool asAlpha)
Sets whether luminace pixel format will treated as alpha format when load this texture.
virtual void setUsage (int u)
Sets the TextureUsage identifier for this Texture; only useful before load()
void setWidth (uint32 w)
Set the width of the texture; can only do this before load();.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
OGRE_AUTO_MUTEX
Detailed Description
Abstract class representing a Texture resource.
Remarks
The actual concrete subclass which will exist for a texture is dependent on the rendering system in use (Direct3D, OpenGL etc). This class represents the commonalities, and is the one 'used' by programmers even though the real implementation could be different in reality. Texture objects are created through the 'create' method of the TextureManager concrete subclass.
Member Enumeration Documentation
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
Constructor & Destructor Documentation
Ogre::Texture::Texture (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual = false, ManualResourceLoader * loader = 0)
virtual Ogre::Texture::~Texture () inline virtual
Member Function Documentation
virtual void Ogre::Texture::_autogenerateMipmaps (void) pure virtual
Tells the API to let the HW autogenerate mipmaps.
Assumes the texture is of usage TU_RENDERTARGET & TU_AUTOMIPMAP
Implemented in Ogre::MetalTexture, Ogre::NULLTexture, Ogre::D3D11DepthTexture, Ogre::D3D11NullTexture, and Ogre::MetalNullTexture.
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
virtual void Ogre::Texture::_loadImages (const ConstImagePtrList & images) virtual
Internal method to load the texture from a set of images.
Note
Do NOT call this method unless you are inside the load() routine already, e.g. a ManualResourceLoader. It is not threadsafe and does not check or update resource loading status.
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
virtual void Ogre::Texture::convertToImage (Image & destImage, bool includeMipMaps = false, uint32 mipmapBias = 0) virtual
Populate an Image with the contents of this texture.
Parameters
destImage The target image (contents will be overwritten)
includeMipMaps Whether to embed mipmaps in the image
mipmapBias From which mipmap we should start from; in range [0; getNumMipmaps()]
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
virtual void Ogre::Texture::copyToTexture (TexturePtr & target) virtual
Copies (and maybe scales to fit) the contents of this texture to another texture.
Reimplemented in Ogre::D3D9Texture, and Ogre::D3D11Texture.
virtual void Ogre::Texture::createInternalResources (void) virtual
Creates the internal texture resources for this texture.
Remarks
This method creates the internal texture resources (pixel buffers, texture surfaces etc) required to begin using this texture. You do not need to call this method directly unless you are manually creating a texture, in which case something must call it, after having set the size and format of the texture (e.g. the ManualResourceLoader might be the best one to call it). If you are not defining a manual texture, or if you use one of the self-contained load...() methods, then it will be called for you.
Reimplemented in Ogre::D3D11DepthTexture, Ogre::D3D11NullTexture, and Ogre::MetalNullTexture.
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Texture::freeInternalResources (void) virtual
Frees internal texture resources for this texture.
Reimplemented in Ogre::D3D11DepthTexture, Ogre::D3D11NullTexture, and Ogre::MetalNullTexture.
virtual v1::HardwarePixelBufferSharedPtr Ogre::Texture::getBuffer (size_t face = 0, size_t mipmap = 0) pure virtual
Return hardware pixel buffer for a surface.
This buffer can then be used to copy data from and to a particular level of the texture.
Parameters
face Face number, in case of a cubemap texture. Must be 0 for other types of textures. For cubemaps, this is one of +X (0), -X (1), +Y (2), -Y (3), +Z (4), -Z (5)
mipmap Mipmap level. This goes from 0 for the first, largest mipmap level to getNumMipmaps()-1 for the smallest.
Returns
A shared pointer to a hardware pixel buffer
Remarks
The buffer is invalidated when the resource is unloaded or destroyed. Do not use it after the lifetime of the containing texture.
Implemented in Ogre::D3D9Texture, Ogre::MetalTexture, Ogre::D3D11Texture, Ogre::NULLTexture, and Ogre::GL3PlusTexture.
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
virtual void Ogre::Texture::getCustomAttribute (const String & name, void * pData) virtual
Retrieve a platform or API-specific piece of information from this texture.
This method of retrieving information should only be used if you know what you're doing.
Parameters
name The name of the attribute to retrieve
pData Pointer to memory matching the type of data you want to retrieve.
Reimplemented in Ogre::GL3PlusTexture.
uint32 Ogre::Texture::getDepth (void) const inline
Returns the depth of the texture (only applicable for 3D textures).
virtual ushort Ogre::Texture::getDesiredFloatBitDepth (void) const virtual
gets desired bit depth for float pixel format textures.
PixelFormat Ogre::Texture::getDesiredFormat (void) const inline
Returns the desired pixel format for the texture surface.
virtual ushort Ogre::Texture::getDesiredIntegerBitDepth (void) const virtual
gets desired bit depth for integer pixel format textures.
PixelFormat Ogre::Texture::getFormat (void) const inline
Returns the pixel format for the texture surface.
virtual uint Ogre::Texture::getFSAA () const inline virtual
Get the level of multisample AA to be used if this texture is a rendertarget.
virtual const String& Ogre::Texture::getFSAAHint () const inline virtual
Get the multisample AA hint if this texture is a rendertarget.
float Ogre::Texture::getGamma (void) const inline
Returns the gamma adjustment factor applied to this texture on loading.
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::v1::OldSkeletonInstance.
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::v1::OldSkeletonInstance.
uint32 Ogre::Texture::getHeight (void) const inline
Returns the height of the texture.
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
bool Ogre::Texture::getMipmapsHardwareGenerated (void) const inline
Are mipmaps hardware generated?
Remarks
Will only be accurate after texture load, or createInternalResources
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::v1::OldSkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName().
virtual size_t Ogre::Texture::getNumFaces () const virtual
Return the number of faces this texture has.
This will be 6 for a cubemap texture and 1 for a 1D, 2D or 3D one.
uint8 Ogre::Texture::getNumMipmaps (void) const inline
Gets the number of mipmaps to be used for this texture.
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
uint32 Ogre::Texture::getSrcDepth (void) const inline
Returns the original depth of the input texture (only applicable for 3D textures).
PixelFormat Ogre::Texture::getSrcFormat (void) const inline
Returns the pixel format of the original input texture (may differ due to hardware requirements and pixel format conversion).
uint32 Ogre::Texture::getSrcHeight (void) const inline
Returns the height of the original input texture (may differ due to hardware requirements).
uint32 Ogre::Texture::getSrcWidth (void) const inline
Returns the width of the original input texture (may differ due to hardware requirements).
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
TextureType Ogre::Texture::getTextureType (void) const inline
Gets the type of texture.
virtual bool Ogre::Texture::getTreatLuminanceAsAlpha (void) const virtual
Gets whether luminace pixel format will treated as alpha format when load this texture.
virtual int Ogre::Texture::getUsage () const inline virtual
Returns the TextureUsage identifier for this Texture.
uint32 Ogre::Texture::getWidth (void) const inline
Returns the width of the texture.
virtual bool Ogre::Texture::hasAlpha (void) const virtual
Returns true if the texture has an alpha layer.
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Texture::isHardwareGammaEnabled () const inline virtual
Gets whether this texture will be set up so that on sampling it, hardware gamma correction is applied.
Referenced by Ogre::NULLTexture::getBuffer().
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
bool Ogre::Texture::isTextureTypeArray (void) const inline
References Ogre::TEX_TYPE_2D_ARRAY.
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Texture::loadImage (const Image & img) virtual
Loads the data from an image.
Note
Important: only call this from outside the load() routine of a Resource. Don't call it within (including ManualResourceLoader) - use _loadImages() instead. This method is designed to be external, performs locking and checks the load status before loading.
Reimplemented in Ogre::D3D11Texture, Ogre::D3D11DepthTexture, Ogre::D3D11NullTexture, and Ogre::MetalNullTexture.
virtual void Ogre::Texture::loadRawData (DataStreamPtr & stream, ushort uWidth, ushort uHeight, PixelFormat eFormat) virtual
Loads the data from a raw stream.
Note
Important: only call this from outside the load() routine of a Resource. Don't call it within (including ManualResourceLoader) - use _loadImages() instead. This method is designed to be external, performs locking and checks the load status before loading.
Parameters
stream Data stream containing the raw pixel data
uWidth Width of the image
uHeight Height of the image
eFormat The format of the pixel data
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
virtual void Ogre::Resource::reload (void) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
Remarks
See also
Resource::isBackgroundLoaded . Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::Texture::setDepth (uint32 d) inline
Set the depth of the texture (only applicable for 3D textures); can only do this before load();.
virtual void Ogre::Texture::setDesiredBitDepths (ushort integerBits, ushort floatBits) virtual
Sets desired bit depth for integer and float pixel format.
virtual void Ogre::Texture::setDesiredFloatBitDepth (ushort bits) virtual
Sets desired bit depth for float pixel format textures.
Note
Available values: 0, 16 and 32, where 0 (the default) means keep original format as it is. This value is number of bits for a channel of the pixel.
virtual void Ogre::Texture::setDesiredIntegerBitDepth (ushort bits) virtual
Sets desired bit depth for integer pixel format textures.
Note
Available values: 0, 16 and 32, where 0 (the default) means keep original format as it is. This value is number of bits for the pixel.
virtual void Ogre::Texture::setFormat (PixelFormat pf) virtual
Sets the pixel format for the texture surface; can only be set before load().
virtual void Ogre::Texture::setFSAA (uint fsaa, const String & fsaaHint, bool explicitResolve) inline virtual
Set the level of multisample AA to be used if this texture is a rendertarget.
Note
This option will be ignored if TU_RENDERTARGET is not part of the usage options on this texture, or if the hardware does not support it.
Parameters
fsaa The number of samples
fsaaHint Any hinting text (
See also
Root::createRenderWindow)
Parameters
explicitResolve TextureDefinitionBase::TextureDefinition::fsaaExplicitResolve
void Ogre::Texture::setGamma (float g) inline
Sets the gamma adjustment factor applied to this texture on loading the data.
Note
Must be called before any 'load' method. This gamma factor will be premultiplied in and may reduce the precision of your textures. You can use setHardwareGamma if supported to apply gamma on sampling the texture instead.
void Ogre::Texture::setHardwareGammaEnabled (bool enabled) inline
Sets whether this texture will be set up so that on sampling it, hardware gamma correction is applied.
Remarks
24-bit textures are often saved in gamma colour space; this preserves precision in the 'darks'. However, if you're performing blending on the sampled colours, you really want to be doing it in linear space. One way is to apply a gamma correction value on loading (see setGamma), but this means you lose precision in those dark colours. An alternative is to get the hardware to do the gamma correction when reading the texture and converting it to a floating point value for the rest of the pipeline. This option allows you to do that; it's only supported in relatively recent hardware (others will ignore it) but can improve the quality of colour reproduction.
Note
Must be called before any 'load' method since it may affect the construction of the underlying hardware resources. Also note this only useful on textures using 8-bit colour channels.
void Ogre::Texture::setHeight (uint32 h) inline
Set the height of the texture; can only do this before load();.
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
void Ogre::Texture::setNumMipmaps (uint8 num) inline
Sets the number of mipmaps to be used for this texture.
Note
Must be set before calling any 'load' method.
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
void Ogre::Texture::setTextureType (TextureType ttype) inline
Sets the type of texture; can only be changed before load()
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
virtual void Ogre::Texture::setTreatLuminanceAsAlpha (bool asAlpha) virtual
Sets whether luminace pixel format will treated as alpha format when load this texture.
virtual void Ogre::Texture::setUsage (int u) inline virtual
Sets the TextureUsage identifier for this Texture; only useful before load()
Parameters
u is a combination of TU_STATIC, TU_DYNAMIC, TU_WRITE_ONLY TU_AUTOMIPMAP and TU_RENDERTARGET (see TextureUsage enum). You are strongly advised to use HBU_STATIC_WRITE_ONLY wherever possible, if you need to update regularly, consider HBU_DYNAMIC_WRITE_ONLY.
void Ogre::Texture::setWidth (uint32 w) inline
Set the width of the texture; can only do this before load();.
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
Member Data Documentation
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreTexture.h