OGRE: Ogre::D3D9GpuProgram Class Reference
Ogre::D3D9GpuProgram Class Reference abstract
Direct3D implementation of a few things common to low-level vertex & fragment programs.
#include <OgreD3D9GpuProgram.h>
Classes
class CmdColumnMajorMatrices
Command object for setting matrix packing in column-major order.
class CmdExternalMicrocode
Command object for getting/setting external micro code (void*)
Public Types
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
Public Member Functions
D3D9GpuProgram (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual, ManualResourceLoader *loader)
~D3D9GpuProgram ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
virtual GpuProgram * _getBindingDelegate (void)
Returns the GpuProgram which should be bound to the pipeline.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
virtual size_t calculateSize (void) const
Calculate the size of a resource; this will only be called after 'load'.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
bool getBuildParametersFromReflection (void) const
bool getColumnMajorMatrices (void) const
Gets whether matrix packed in column-major order.
virtual Vector3 getComputeGroupDimensions (void) const
Returns the number of process groups dispatched by this compute program.
virtual const GpuNamedConstants & getConstantDefinitions () const
Get the full list of named constants.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr getDefaultParameters (void)
Get a reference to the default parameters which are to be used for all uses of this program.
LPD3DXBUFFER getExternalMicrocode (void)
Gets the external microcode buffer, if any.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual const String & getLanguage (void) const
Returns a string that specifies the language of the gpu programs as specified in a material script.
virtual LoadingState getLoadingState () const
Returns the current loading state.
virtual const String & getManualNamedConstantsFile () const
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual const String & getName (void) const
Gets resource name.
virtual ushort getNumberOfPosesIncluded (void) const
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
virtual bool getPassFogStates (void) const
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
virtual bool getPassSurfaceAndLightStates (void) const
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
virtual bool getPassTransformStates (void) const
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
virtual const String & getSource (void) const
Gets the assembler source for this program.
virtual const String & getSourceFile (void) const
Gets the name of the file used as source for this program.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
virtual const String & getSyntaxCode (void) const
Gets the syntax code for this program e.g.
virtual GpuProgramType getType (void) const
Get the program type.
virtual bool hasCompileError (void) const
Did this program encounter a compile error when loading?
virtual bool hasDefaultParameters (void) const
Returns true if default parameters have been set up.
virtual bool isAdjacencyInfoRequired (void) const
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isMorphAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform morph animation.
virtual bool isPoseAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform pose animation.
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
virtual bool isSkeletalAnimationIncluded (void) const
Returns whether a vertex program includes the required instructions to perform skeletal animation.
virtual bool isSupported (void) const
Returns whether this program can be supported on the current renderer and hardware.
virtual bool isVertexTextureFetchRequired (void) const
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
virtual void notifyOnDeviceCreate (IDirect3DDevice9 *d3d9Device)
virtual void notifyOnDeviceDestroy (IDirect3DDevice9 *d3d9Device)
virtual void notifyOnDeviceLost (IDirect3DDevice9 *d3d9Device)
virtual void notifyOnDeviceReset (IDirect3DDevice9 *d3d9Device)
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (void)
Reloads the resource, if it is already loaded.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
virtual void resetCompileError (void)
Reset a compile error if it occurred, allowing the load to be retried.
virtual void setAdjacencyInfoRequired (bool r)
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
void setBuildParametersFromReflection (bool buildParams)
void setColumnMajorMatrices (bool columnMajor)
Sets whether matrix packing in column-major order.
virtual void setComputeGroupDimensions (Vector3 dimensions)
Sets the number of process groups dispatched by this compute program.
void setExternalMicrocode (const void *pMicrocode, size_t size)
Tells the program to load from some externally created microcode instead of a file or source.
void setExternalMicrocode (ID3DXBuffer *pMicrocode)
Tells the program to load from some externally created microcode instead of a file or source.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual void setManualNamedConstants (const GpuNamedConstants &namedConstants)
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
virtual void setManualNamedConstantsFile (const String &paramDefFile)
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual void setMorphAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform morph animation.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPoseAnimationIncluded (ushort poseCount)
Sets whether a vertex program includes the required instructions to perform pose animation.
virtual void setSkeletalAnimationIncluded (bool included)
Sets whether a vertex program includes the required instructions to perform skeletal animation.
virtual void setSource (const String &source)
Sets the source assembly for this program from an in-memory string.
virtual void setSource (const String &source, const String &debugFilename)
Sets the source assembly for this program from an in-memory string, while providing a path to a file, which can be needed/useful for debugging shaders (i.e.
virtual void setSourceFile (const String &filename)
Sets the filename of the source assembly for this program.
virtual void setSyntaxCode (const String &syntax)
Sets the syntax code for this program e.g.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
virtual void setType (GpuProgramType t)
Set the program type (only valid before load)
virtual void setVertexTextureFetchRequired (bool r)
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
static void lockDeviceAccess ()
static void unlockDeviceAccess ()
Public Attributes
OGRE_AUTO_MUTEX
Detailed Description
Direct3D implementation of a few things common to low-level vertex & fragment programs.
Member Enumeration Documentation
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
Constructor & Destructor Documentation
Ogre::D3D9GpuProgram::D3D9GpuProgram (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual, ManualResourceLoader * loader)
Ogre::D3D9GpuProgram::~D3D9GpuProgram ()
Member Function Documentation
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
virtual GpuProgram* Ogre::GpuProgram::_getBindingDelegate (void) inline virtual inherited
Returns the GpuProgram which should be bound to the pipeline.
Remarks
This method is simply to allow some subclasses of GpuProgram to delegate the program which is bound to the pipeline to a delegate, if required.
Reimplemented in Ogre::GLSLShader, Ogre::HighLevelGpuProgram, and Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual size_t Ogre::GpuProgram::calculateSize (void) const virtual inherited
Calculate the size of a resource; this will only be called after 'load'.
Reimplemented from Ogre::Resource.
Reimplemented in Ogre::GLSLShader, Ogre::HighLevelGpuProgram, Ogre::UnifiedHighLevelGpuProgram, Ogre::GL3PlusGpuProgram, and Ogre::GLES2GpuProgram.
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
bool Ogre::GpuProgram::getBuildParametersFromReflection (void) const inline inherited
bool Ogre::D3D9GpuProgram::getColumnMajorMatrices (void) const inline
Gets whether matrix packed in column-major order.
virtual Vector3 Ogre::GpuProgram::getComputeGroupDimensions (void) const inline virtual inherited
Returns the number of process groups dispatched by this compute program.
virtual const GpuNamedConstants& Ogre::GpuProgram::getConstantDefinitions () const inline virtual inherited
Get the full list of named constants.
Note
Only available if this parameters object has named parameters, which means either a high-level program which loads them, or a low-level program which has them specified manually.
Reimplemented in Ogre::HighLevelGpuProgram.
References Ogre::SharedPtr< T >::get().
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
virtual GpuProgramParametersSharedPtr Ogre::GpuProgram::getDefaultParameters (void) virtual inherited
Get a reference to the default parameters which are to be used for all uses of this program.
Remarks
A program can be set up with a list of default parameters, which can save time when using a program many times in a material with roughly the same settings. By retrieving the default parameters and populating it with the most used options, any new parameter objects created from this program afterwards will automatically include the default parameters; thus users of the program need only change the parameters which are unique to their own usage of the program.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
LPD3DXBUFFER Ogre::D3D9GpuProgram::getExternalMicrocode (void)
Gets the external microcode buffer, if any.
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::v1::OldSkeletonInstance.
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::v1::OldSkeletonInstance.
virtual const String& Ogre::GpuProgram::getLanguage (void) const virtual inherited
Returns a string that specifies the language of the gpu programs as specified in a material script.
ie: asm, cg, hlsl, glsl
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, Ogre::GLSLShader, Ogre::GLSLProgram, Ogre::UnifiedHighLevelGpuProgram, and Ogre::MetalProgram.
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual const String& Ogre::GpuProgram::getManualNamedConstantsFile () const inline virtual inherited
Gets the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::v1::OldSkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName().
virtual ushort Ogre::GpuProgram::getNumberOfPosesIncluded (void) const inline virtual inherited
Returns the number of simultaneous poses the vertex program can blend, for use in pose animation.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
virtual bool Ogre::GpuProgram::getPassFogStates (void) const inline virtual inherited
Returns whether a fragment program wants fog state to be passed through fixed pipeline low level API rendering calls (default true, subclasses can override)
Remarks
On DirectX, shader model 2 and earlier continues to have fixed-function fog applied to it, so fog state is still passed (you should disable fog on the pass if you want to perform fog in the shader). In OpenGL it is also common to be able to access the fixed-function fog state inside the shader.
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLProgram, and Ogre::MetalProgram.
virtual bool Ogre::GpuProgram::getPassSurfaceAndLightStates (void) const inline virtual inherited
Returns whether a vertex program wants light and material states to be passed through fixed pipeline low level API rendering calls (default false, subclasses can override)
Remarks
Most vertex programs do not need this material information, however GLSL shaders can refer to this material and lighting state so enable this option
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLProgram, and Ogre::MetalProgram.
virtual bool Ogre::GpuProgram::getPassTransformStates (void) const inline virtual inherited
Returns whether a vertex program wants transform state to be passed through fixed pipeline low level API rendering calls.
Remarks
Most vertex programs do not need fixed-function transform information, however GLSL shaders can refer to this state so enable this option
Reimplemented in Ogre::GLSLShader, Ogre::UnifiedHighLevelGpuProgram, Ogre::GLSLProgram, and Ogre::MetalProgram.
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual const String& Ogre::GpuProgram::getSource (void) const inline virtual inherited
Gets the assembler source for this program.
virtual const String& Ogre::GpuProgram::getSourceFile (void) const inline virtual inherited
Gets the name of the file used as source for this program.
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
virtual const String& Ogre::GpuProgram::getSyntaxCode (void) const inline virtual inherited
Gets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
virtual GpuProgramType Ogre::GpuProgram::getType (void) const inline virtual inherited
Get the program type.
virtual bool Ogre::GpuProgram::hasCompileError (void) const inline virtual inherited
Did this program encounter a compile error when loading?
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::hasDefaultParameters (void) const inline virtual inherited
Returns true if default parameters have been set up.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::SharedPtr< T >::isNull().
virtual bool Ogre::GpuProgram::isAdjacencyInfoRequired (void) const inline virtual inherited
Returns whether this geometry program requires adjacency information from the input primitives.
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
virtual bool Ogre::GpuProgram::isMorphAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this returns true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isPoseAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this returns true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isSkeletalAnimationIncluded (void) const inline virtual inherited
Returns whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this returns true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram, and Ogre::GLSLProgram.
virtual bool Ogre::GpuProgram::isSupported (void) const virtual inherited
Returns whether this program can be supported on the current renderer and hardware.
Reimplemented in Ogre::D3D11HLSLProgram, Ogre::D3D9HLSLProgram, and Ogre::UnifiedHighLevelGpuProgram.
virtual bool Ogre::GpuProgram::isVertexTextureFetchRequired (void) const inline virtual inherited
Returns whether this vertex program requires support for vertex texture fetch from the hardware.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
static void Ogre::D3D9Resource::lockDeviceAccess () static inherited
virtual void Ogre::D3D9Resource::notifyOnDeviceCreate (IDirect3DDevice9 * d3d9Device) inline virtual inherited
Reimplemented in Ogre::D3D9Texture, Ogre::D3D9GpuFragmentProgram, Ogre::D3D9GpuVertexProgram, Ogre::D3D9HardwareOcclusionQuery, Ogre::D3D9VertexDeclaration, Ogre::D3D9HardwareIndexBuffer, and Ogre::D3D9HardwareVertexBuffer.
virtual void Ogre::D3D9Resource::notifyOnDeviceDestroy (IDirect3DDevice9 * d3d9Device) inline virtual inherited
Reimplemented in Ogre::D3D9Texture, Ogre::D3D9GpuFragmentProgram, Ogre::D3D9GpuVertexProgram, Ogre::D3D9HardwareOcclusionQuery, Ogre::D3D9VertexDeclaration, Ogre::D3D9HardwareIndexBuffer, and Ogre::D3D9HardwareVertexBuffer.
virtual void Ogre::D3D9Resource::notifyOnDeviceLost (IDirect3DDevice9 * d3d9Device) inline virtual inherited
Reimplemented in Ogre::D3D9Texture, Ogre::D3D9HardwareOcclusionQuery, Ogre::D3D9HardwareIndexBuffer, and Ogre::D3D9HardwareVertexBuffer.
virtual void Ogre::D3D9Resource::notifyOnDeviceReset (IDirect3DDevice9 * d3d9Device) inline virtual inherited
Reimplemented in Ogre::D3D9Texture, Ogre::D3D9HardwareOcclusionQuery, Ogre::D3D9HardwareIndexBuffer, and Ogre::D3D9HardwareVertexBuffer.
References OGRE_STATIC_MUTEX.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
virtual void Ogre::Resource::reload (void) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::GpuProgram::resetCompileError (void) inline virtual inherited
Reset a compile error if it occurred, allowing the load to be retried.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
virtual void Ogre::GpuProgram::setAdjacencyInfoRequired (bool r) inline virtual inherited
Sets whether this geometry program requires adjacency information from the input primitives.
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
Remarks
See also
Resource::isBackgroundLoaded . Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
void Ogre::GpuProgram::setBuildParametersFromReflection (bool buildParams) inline inherited
void Ogre::D3D9GpuProgram::setColumnMajorMatrices (bool columnMajor) inline
Sets whether matrix packing in column-major order.
virtual void Ogre::GpuProgram::setComputeGroupDimensions (Vector3 dimensions) inline virtual inherited
Sets the number of process groups dispatched by this compute program.
void Ogre::D3D9GpuProgram::setExternalMicrocode (const void * pMicrocode, size_t size)
Tells the program to load from some externally created microcode instead of a file or source.
void Ogre::D3D9GpuProgram::setExternalMicrocode (ID3DXBuffer * pMicrocode)
Tells the program to load from some externally created microcode instead of a file or source.
Remarks
add ref count to pMicrocode when setting
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
virtual void Ogre::GpuProgram::setManualNamedConstants (const GpuNamedConstants & namedConstants) virtual inherited
Allows you to manually provide a set of named parameter mappings to a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source.
See also
setManualNamedConstantsFile
virtual void Ogre::GpuProgram::setManualNamedConstantsFile (const String & paramDefFile) virtual inherited
Specifies the name of a file from which to load named parameters mapping for a program which would not be able to derive named parameters itself.
Remarks
You may wish to use this if you have assembler programs that were compiled from a high-level source, and want the convenience of still being able to use the named parameters from the original high-level source. This method will make a low-level program search in the resource group of the program for the named file from which to load parameter names from. The file must be in the format produced by GpuNamedConstants::save.
virtual void Ogre::GpuProgram::setMorphAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform morph animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to morph animation, it will expect the vertex program to do it.
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
virtual void Ogre::GpuProgram::setPoseAnimationIncluded (ushort poseCount) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform pose animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to pose animation, it will expect the vertex program to do it.
Parameters
poseCount The number of simultaneous poses the program can blend
virtual void Ogre::GpuProgram::setSkeletalAnimationIncluded (bool included) inline virtual inherited
Sets whether a vertex program includes the required instructions to perform skeletal animation.
Remarks
If this is set to true, OGRE will not blend the geometry according to skeletal animation, it will expect the vertex program to do it.
Reimplemented in Ogre::GLSLProgram.
virtual void Ogre::GpuProgram::setSource (const String & source) virtual inherited
Sets the source assembly for this program from an in-memory string.
Remarks
Setting this will have no effect until you (re)load the program.
virtual void Ogre::GpuProgram::setSource (const String & source, const String & debugFilename) virtual inherited
Sets the source assembly for this program from an in-memory string, while providing a path to a file, which can be needed/useful for debugging shaders (i.e.
Visual Studio Graphics Debugger)
Parameters
source Shader source code
debugFilename Optional Path to this file. Can be left blank.
virtual void Ogre::GpuProgram::setSourceFile (const String & filename) virtual inherited
Sets the filename of the source assembly for this program.
Remarks
Setting this will have no effect until you (re)load the program.
virtual void Ogre::GpuProgram::setSyntaxCode (const String & syntax) virtual inherited
Sets the syntax code for this program e.g.
arbvp1, fp20, vs_1_1 etc
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
virtual void Ogre::GpuProgram::setType (GpuProgramType t) virtual inherited
Set the program type (only valid before load)
virtual void Ogre::GpuProgram::setVertexTextureFetchRequired (bool r) inline virtual inherited
Sets whether this vertex program requires support for vertex texture fetch from the hardware.
virtual void Ogre::Resource::touch (void) virtual inherited
'Touches' the resource to indicate it has been used.
Reimplemented in Ogre::Material, and Ogre::UnifiedHighLevelGpuProgram.
Referenced by Ogre::Material::touch().
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
static void Ogre::D3D9Resource::unlockDeviceAccess () static inherited
Member Data Documentation
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreD3D9GpuProgram.h