OGRE: Ogre::v1::GL3PlusHardwareIndexBuffer Class Reference
Ogre::v1::GL3PlusHardwareIndexBuffer Class Reference
#include <OgreGL3PlusHardwareIndexBuffer.h>
Public Types
enum IndexType { IT_16BIT, IT_32BIT }
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum UploadOptions { HBU_DEFAULT = 0x0000, HBU_ON_DEMAND = 0x0001 }
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
GL3PlusHardwareIndexBuffer (HardwareBufferManagerBase *mgr, IndexType idxType, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer)
~GL3PlusHardwareIndexBuffer ()
void _updateFromShadow (void)
See HardwareBuffer.
void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
See HardwareBuffer.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
GLuint getGLBufferId (void) const
size_t getIndexSize (void) const
Get the size in bytes of each index.
HardwareBufferManagerBase * getManager () const
Return the manager of this buffer, if any.
size_t getNumIndexes (void) const
Get the number of indexes in this buffer.
virtual void * getRenderSystemData (void)
An internal function that should be used only by a render system for internal use.
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
IndexType getType (void) const
Get the type of indexes used in this buffer.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
Returns whether or not this buffer is currently locked.
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
virtual void * lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the buffer for (potentially) reading / writing.
void * lock (LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the entire buffer for (potentially) reading / writing.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void readData (size_t offset, size_t length, void *pDest)
See HardwareBuffer.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
virtual void unlock (void)
Releases the lock on this buffer.
void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
See HardwareBuffer.
Member Enumeration Documentation
IndexType
enum Ogre::v1::HardwareIndexBuffer::IndexType inherited
Enumerator
IT_16BIT
IT_32BIT
LockOptions
enum Ogre::v1::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
UploadOptions
enum Ogre::v1::HardwareBuffer::UploadOptions inherited
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
Enumerator
HBU_DEFAULT
HBU_ON_DEMAND
Usage
enum Ogre::v1::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Constructor & Destructor Documentation
GL3PlusHardwareIndexBuffer()
Ogre::v1::GL3PlusHardwareIndexBuffer::GL3PlusHardwareIndexBuffer (HardwareBufferManagerBase * mgr, IndexType idxType, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer)
~GL3PlusHardwareIndexBuffer()
Ogre::v1::GL3PlusHardwareIndexBuffer::~GL3PlusHardwareIndexBuffer ()
Member Function Documentation
_updateFromShadow()
void Ogre::v1::GL3PlusHardwareIndexBuffer::_updateFromShadow (void) virtual
See HardwareBuffer.
Reimplemented from Ogre::v1::HardwareBuffer.
copyData() [1/2]
void Ogre::v1::GL3PlusHardwareIndexBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) virtual
See HardwareBuffer.
Reimplemented from Ogre::v1::HardwareBuffer.
copyData() [2/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References Ogre::v1::HardwareBuffer::getSizeInBytes(), and Ogre::min().
getGLBufferId()
GLuint Ogre::v1::GL3PlusHardwareIndexBuffer::getGLBufferId (void) const inline
getIndexSize()
size_t Ogre::v1::HardwareIndexBuffer::getIndexSize (void) const inline inherited
Get the size in bytes of each index.
getManager()
HardwareBufferManagerBase* Ogre::v1::HardwareIndexBuffer::getManager () const inline inherited
Return the manager of this buffer, if any.
getNumIndexes()
size_t Ogre::v1::HardwareIndexBuffer::getNumIndexes (void) const inline inherited
Get the number of indexes in this buffer.
getRenderSystemData()
virtual void* Ogre::v1::HardwareBuffer::getRenderSystemData (void) inline virtual inherited
An internal function that should be used only by a render system for internal use.
Reimplemented in Ogre::v1::MetalHardwareIndexBuffer, and Ogre::v1::MetalHardwareVertexBuffer.
getSizeInBytes()
size_t Ogre::v1::HardwareBuffer::getSizeInBytes (void) const inline inherited
Returns the size of this buffer in bytes.
Referenced by Ogre::v1::HardwareBuffer::copyData().
getType()
IndexType Ogre::v1::HardwareIndexBuffer::getType (void) const inline inherited
Get the type of indexes used in this buffer.
getUsage()
Usage Ogre::v1::HardwareBuffer::getUsage (void) const inline inherited
Returns the Usage flags with which this buffer was created.
hasShadowBuffer()
bool Ogre::v1::HardwareBuffer::hasShadowBuffer (void) const inline inherited
Returns whether this buffer has a system memory shadow for quicker reading.
isLocked()
bool Ogre::v1::HardwareBuffer::isLocked (void) const inline inherited
Returns whether or not this buffer is currently locked.
References Ogre::v1::HardwareBuffer::isLocked().
Referenced by Ogre::v1::HardwareBuffer::isLocked(), and Ogre::v1::HardwareBuffer::unlock().
isSystemMemory()
bool Ogre::v1::HardwareBuffer::isSystemMemory (void) const inline inherited
Returns whether this buffer is held in system memory.
lock() [1/2]
virtual void* Ogre::v1::HardwareBuffer::lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) inline virtual inherited
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns
Pointer to the locked memory
Reimplemented in Ogre::v1::DefaultHardwareCounterBuffer, Ogre::v1::GL3PlusDefaultHardwareCounterBuffer, Ogre::v1::DefaultHardwareUniformBuffer, Ogre::v1::GL3PlusDefaultHardwareUniformBuffer, Ogre::v1::GLES2DefaultHardwareUniformBuffer, Ogre::v1::HardwarePixelBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::GL3PlusDefaultHardwareIndexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::D3D11HardwareUniformBuffer, Ogre::v1::D3D11HardwareVertexBuffer, and Ogre::v1::D3D11HardwareIndexBuffer.
References Ogre::Exception::ERR_INVALIDPARAMS, Ogre::v1::HardwareBuffer::lock(), and OGRE_EXCEPT.
Referenced by Ogre::v1::HardwareBuffer::copyData(), and Ogre::v1::HardwareBuffer::lock().
lock() [2/2]
void* Ogre::v1::HardwareBuffer::lock (LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) inline inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
readData()
void Ogre::v1::GL3PlusHardwareIndexBuffer::readData (size_t offset, size_t length, void * pDest) virtual
See HardwareBuffer.
Implements Ogre::v1::HardwareBuffer.
suppressHardwareUpdate()
void Ogre::v1::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline inherited
Pass true to suppress hardware upload of shadow buffer changes.
unlock()
virtual void Ogre::v1::HardwareBuffer::unlock (void) inline virtual inherited
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented in Ogre::v1::DefaultHardwareCounterBuffer, Ogre::v1::GL3PlusDefaultHardwareCounterBuffer, Ogre::v1::DefaultHardwareUniformBuffer, Ogre::v1::GL3PlusDefaultHardwareUniformBuffer, Ogre::v1::GLES2DefaultHardwareUniformBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::GL3PlusDefaultHardwareIndexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::D3D11HardwareUniformBuffer, Ogre::v1::D3D11HardwareVertexBuffer, and Ogre::v1::D3D11HardwareIndexBuffer.
References Ogre::v1::HardwareBuffer::isLocked(), and Ogre::v1::HardwareBuffer::unlock().
Referenced by Ogre::v1::HardwareBuffer::copyData(), and Ogre::v1::HardwareBuffer::unlock().
writeData()
void Ogre::v1::GL3PlusHardwareIndexBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual
See HardwareBuffer.
Implements Ogre::v1::HardwareBuffer.
The documentation for this class was generated from the following file:
OgreGL3PlusHardwareIndexBuffer.h