OGRE: Ogre::PropertySet Class Reference
Ogre::PropertySet Class Reference
Components » Property
Defines a complete set of properties for a single object instance.
#include <OgreProperty.h>
Public Types
typedef Ogre::MapIterator< PropertyMap > PropertyIterator
typedef map< String, PropertyBase * >::type PropertyMap
Public Member Functions
PropertySet ()
~PropertySet ()
void addProperty (PropertyBase *prop)
Adds a property to this set.
PropertyBase * getProperty (const String &name) const
Gets the property object for a given property name.
PropertyIterator getPropertyIterator ()
Get an iterator over the available properties.
template<typename T >
void getValue (const String &name, T &value) const
Get a named property value.
PropertyValueMap getValueMap () const
Gets an independently usable collection of property values from the current state.
bool hasProperty (const String &name) const
Reports whether this property set contains a named property.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void removeProperty (const String &name)
Removes the named property from the property set.
template<typename T >
void setValue (const String &name, const T *value)
Set a named property value (via pointer to avoid copy).
template<typename T >
void setValue (const String &name, T value)
Set a named property value.
void setValue (const String &name, const char *pChar)
Special-case char*, convert to String automatically.
void setValueMap (const PropertyValueMap &values)
Sets the current state from a given value map.
Detailed Description
Defines a complete set of properties for a single object instance.
Member Typedef Documentation
PropertyIterator
typedef Ogre::MapIterator<PropertyMap> Ogre::PropertySet::PropertyIterator
PropertyMap
typedef map<String, PropertyBase*>::type Ogre::PropertySet::PropertyMap
Constructor & Destructor Documentation
PropertySet()
Ogre::PropertySet::PropertySet ()
~PropertySet()
Ogre::PropertySet::~PropertySet ()
Member Function Documentation
addProperty()
void Ogre::PropertySet::addProperty (PropertyBase * prop)
Adds a property to this set.
Remarks
The PropertySet is responsible for deleting this object.
getProperty()
PropertyBase* Ogre::PropertySet::getProperty (const String & name) const
Gets the property object for a given property name.
Remarks
Note that this property will need to be cast to a templated property compatible with the type you will be setting. You might find the overloaded set and get<type> methods quicker if you already know the type.
getPropertyIterator()
PropertyIterator Ogre::PropertySet::getPropertyIterator ()
Get an iterator over the available properties.
getValue()
template<typename T > void Ogre::PropertySet::getValue (const String & name, T & value) const inline
Get a named property value.
References Ogre::PropertyDef::getTypeForValue().
getValueMap()
PropertyValueMap Ogre::PropertySet::getValueMap () const
Gets an independently usable collection of property values from the current state.
hasProperty()
bool Ogre::PropertySet::hasProperty (const String & name) const
Reports whether this property set contains a named property.
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
removeProperty()
void Ogre::PropertySet::removeProperty (const String & name)
Removes the named property from the property set.
setValue() [1/3]
template<typename T > void Ogre::PropertySet::setValue (const String & name, const T * value) inline
Set a named property value (via pointer to avoid copy).
References Ogre::PropertyDef::getTypeForValue().
setValue() [2/3]
template<typename T > void Ogre::PropertySet::setValue (const String & name, T value) inline
Set a named property value.
References Ogre::PropertyDef::getTypeForValue().
setValue() [3/3]
void Ogre::PropertySet::setValue (const String & name, const char * pChar) inline
Special-case char*, convert to String automatically.
References Ogre::PROP_STRING.
setValueMap()
void Ogre::PropertySet::setValueMap (const PropertyValueMap & values)
Sets the current state from a given value map.
The documentation for this class was generated from the following file:
OgreProperty.h