OGRE: Ogre::RTShader::FunctionInvocation Class Reference
Ogre::RTShader::FunctionInvocation Class Reference
Core » RTShader
A class that represents function invocation code from shader based program function.
#include <OgreShaderFunctionAtom.h>
Classes
struct FunctionInvocationCompare
Comparator function to be used for comparisons.
struct FunctionInvocationLessThan
Comparator function to be used for sorting.
Public Types
typedef vector< Operand >::type OperandVector
Public Member Functions
FunctionInvocation (const String &functionName, int groupOrder, int internalOrder, String returnType="void")
Class constructor.
FunctionInvocation (const FunctionInvocation &rhs)
Copy constructor.
virtual const String & getFunctionAtomType ()
const String & getFunctionName () const
Return the function name.
int getGroupExecutionOrder () const
Get the group execution order of this function atom.
int getInternalExecutionOrder () const
Get an internal execution order within a group of this function atom.
OperandVector & getOperandList ()
Get a list of parameters this function invocation will use in the function call as arguments.
const String & getReturnType () const
Return the return type.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
bool operator!= (const FunctionInvocation &rhs) const
Determines if the current object is not equal to the compared one.
bool operator< (const FunctionInvocation &rhs) const
Determines if the current object is less than the compared one.
bool operator== (const FunctionInvocation &rhs) const
Determines if the current object is equal to the compared one.
void pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask=Operand::OPM_ALL, int indirectionLevel=0)
Push a new operand (on the end) to the function.
virtual void writeSourceCode (std::ostream &os, const String &targetLanguage) const
Static Public Attributes
static String Type
The type of this class.
Detailed Description
A class that represents function invocation code from shader based program function.
Member Typedef Documentation
typedef vector<Operand>::type Ogre::RTShader::FunctionInvocation::OperandVector
Constructor & Destructor Documentation
Ogre::RTShader::FunctionInvocation::FunctionInvocation (const String & functionName, int groupOrder, int internalOrder, String returnType = "void")
Class constructor.
Parameters
functionName The name of the function to invoke.
groupOrder The group order of this invocation.
internalOrder The internal order of this invocation.
returnType The return type of the used function.
Ogre::RTShader::FunctionInvocation::FunctionInvocation (const FunctionInvocation & rhs)
Copy constructor.
Member Function Documentation
virtual const String& Ogre::RTShader::FunctionInvocation::getFunctionAtomType () inline virtual
See also
FunctionAtom::getFunctionAtomType
Implements Ogre::RTShader::FunctionAtom.
const String& Ogre::RTShader::FunctionInvocation::getFunctionName () const inline
Return the function name.
int Ogre::RTShader::FunctionAtom::getGroupExecutionOrder () const inherited
Get the group execution order of this function atom.
int Ogre::RTShader::FunctionAtom::getInternalExecutionOrder () const inherited
Get an internal execution order within a group of this function atom.
OperandVector& Ogre::RTShader::FunctionInvocation::getOperandList () inline
Get a list of parameters this function invocation will use in the function call as arguments.
References Ogre::RTShader::Operand::OPM_ALL.
const String& Ogre::RTShader::FunctionInvocation::getReturnType () const inline
Return the return type.
References Ogre::operator!=(), Ogre::operator<(), and Ogre::operator==().
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
bool Ogre::RTShader::FunctionInvocation::operator!= (const FunctionInvocation & rhs) const
Determines if the current object is not equal to the compared one.
bool Ogre::RTShader::FunctionInvocation::operator< (const FunctionInvocation & rhs) const
Determines if the current object is less than the compared one.
bool Ogre::RTShader::FunctionInvocation::operator== (const FunctionInvocation & rhs) const
Determines if the current object is equal to the compared one.
void Ogre::RTShader::FunctionInvocation::pushOperand (ParameterPtr parameter, Operand::OpSemantic opSemantic, int opMask = Operand::OPM_ALL, int indirectionLevel = 0)
Push a new operand (on the end) to the function.
Parameters
parameter A function parameter.
opSemantic The in/out semantic of the parameter.
opMask The field mask of the parameter.
indirectionLevel The level of nesting inside brackets
virtual void Ogre::RTShader::FunctionInvocation::writeSourceCode (std::ostream & os, const String & targetLanguage) const virtual
See also
FunctionAtom::writeSourceCode
Implements Ogre::RTShader::FunctionAtom.
Member Data Documentation
String Ogre::RTShader::FunctionInvocation::Type static
The type of this class.
The documentation for this class was generated from the following file:
OgreShaderFunctionAtom.h