OGRE: Ogre::Renderable Class Reference
Ogre::Renderable Class Reference abstract
Core » Scene
Abstract class defining the interface all renderable objects must implement.
#include <OgreRenderable.h>
Public Member Functions
Renderable ()
virtual ~Renderable ()
Virtual destructor needed as class has virtual methods.
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
virtual void _setNullDatablock (void)
Sets the datablock to a null pointer.
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
uint8 getCurrentMaterialLod (void) const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
HlmsDatablock * getDatablock (void) const
uint32 getHlmsCasterHash (void) const
uint32 getHlmsHash (void) const
virtual const LightList & getLights (void) const =0
Gets a list of lights, ordered relative to how close they are to this renderable.
MaterialPtr getMaterial (void) const
Retrieves the material this renderable object uses.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
virtual bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
virtual void getRenderOperation (v1::RenderOperation &op, bool casterPass)=0
Gets the render operation required to send this object to the frame buffer.
uint8 getRenderQueueSubGroup (void) const
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic (void) const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix (void) const
Returns whether the world matrix is an identify matrix.
virtual OGRE_DEPRECATED const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
virtual void getWorldTransforms (Matrix4 *xform) const =0
Gets the world transform matrix / matrices for this renderable object.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation (void) const
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
virtual void setMaterial (const MaterialPtr &material)
Sets the given material. Overrides HLMS materials.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
Public Attributes
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
Friends
void LodStrategy::lodSet (ObjectData &t, Real lodValues[ARRAY_PACKED_REALS])
Detailed Description
Abstract class defining the interface all renderable objects must implement.
Remarks
This interface abstracts renderable discrete objects which will be queued in the render pipeline, grouped by material. Classes implementing this interface must be based on a single material, a single world matrix (or a collection of world matrices which are blended by weights), and must be renderable via a single render operation.
Note that deciding whether to put these objects in the rendering pipeline is done from the more specific classes e.g. entities. Only once it is decided that the specific class is to be rendered is the abstract version created (could be more than one per visible object) and pushed onto the rendering queue.
Constructor & Destructor Documentation
Ogre::Renderable::Renderable ()
virtual Ogre::Renderable::~Renderable () virtual
Virtual destructor needed as class has virtual methods.
Member Function Documentation
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
virtual void Ogre::Renderable::_setNullDatablock (void) virtual
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::v1::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::ManualObject::ManualObjectSection, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::SubItem, and Ogre::WireAabb.
uint8 Ogre::Renderable::getCurrentMaterialLod (void) const inline
References ARRAY_PACKED_REALS, and Ogre::LodStrategy::lodSet().
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
HlmsDatablock* Ogre::Renderable::getDatablock (void) const inline
uint32 Ogre::Renderable::getHlmsCasterHash (void) const inline
uint32 Ogre::Renderable::getHlmsHash (void) const inline
virtual const LightList& Ogre::Renderable::getLights (void) const pure virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implemented in Ogre::v1::BillboardSet, Ogre::Frustum, Ogre::v1::OverlayElement, Ogre::v1::ManualObject::ManualObjectSection, Ogre::v1::InstanceBatch, Ogre::v1::BorderRenderable, Ogre::ManualObject::ManualObjectSection, Ogre::v1::BillboardChain, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::SubItem, Ogre::v1::Rectangle2D, Ogre::v1::SimpleRenderable, and Ogre::WireAabb.
MaterialPtr Ogre::Renderable::getMaterial (void) const
Retrieves the material this renderable object uses.
It may be null if it's using the HLMS. getDatablock
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::v1::BorderRenderable, Ogre::v1::SubEntity, Ogre::v1::BaseInstanceBatchVTF, Ogre::v1::InstanceBatchShader, and Ogre::v1::InstanceBatchHW.
virtual bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline virtual
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
virtual void Ogre::Renderable::getRenderOperation (v1::RenderOperation & op, bool casterPass) pure virtual
Gets the render operation required to send this object to the frame buffer.
Implemented in Ogre::v1::BillboardSet, Ogre::Frustum, Ogre::v1::ManualObject::ManualObjectSection, Ogre::v1::InstanceBatch, Ogre::v1::BorderRenderable, Ogre::ManualObject::ManualObjectSection, Ogre::v1::BillboardChain, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::v1::PanelOverlayElement, Ogre::SubItem, Ogre::v1::Rectangle2D, Ogre::v1::TextAreaOverlayElement, Ogre::v1::SimpleRenderable, and Ogre::WireAabb.
uint8 Ogre::Renderable::getRenderQueueSubGroup (void) const inline
References Ogre::NumVertexPass.
bool Ogre::Renderable::getUseIdentityProjection (void) const inline
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
bool Ogre::Renderable::getUseIdentityView (void) const inline
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic (void) const inline virtual
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix (void) const inline virtual
Returns whether the world matrix is an identify matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
virtual OGRE_DEPRECATED const Any& Ogre::Renderable::getUserAny (void) const inline virtual
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const VertexArrayObjectArray& Ogre::Renderable::getVaos (VertexPass vertexPass) const inline
virtual void Ogre::Renderable::getWorldTransforms (Matrix4 * xform) const pure virtual
Gets the world transform matrix / matrices for this renderable object.
Remarks
If the object has any derived transforms, these are expected to be up to date as long as all the SceneNode structures have been updated before this is called.
This method will populate transform with 1 matrix if it does not use vertex blending. If it does use vertex blending it will fill the passed in pointer with an array of matrices, the length being the value returned from getNumWorldTransforms.
Note
Internal Ogre never supports non-affine matrix for world transform matrix/matrices, the behavior is undefined if returns non-affine matrix here.
See also
Matrix4::isAffine.
Implemented in Ogre::v1::BillboardSet, Ogre::Frustum, Ogre::v1::ManualObject::ManualObjectSection, Ogre::Camera, Ogre::v1::BorderRenderable, Ogre::ManualObject::ManualObjectSection, Ogre::v1::OverlayElement, Ogre::v1::BillboardChain, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::v1::BaseInstanceBatchVTF, Ogre::SubItem, Ogre::v1::InstanceBatchShader, Ogre::v1::InstanceBatchHW, Ogre::v1::Rectangle2D, Ogre::v1::SimpleRenderable, and Ogre::WireAabb.
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
bool Ogre::Renderable::hasSkeletonAnimation (void) const inline
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual
Called immediately after the Renderable has been rendered.
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::v1::BillboardChain.
void Ogre::Renderable::removeCustomParameter (size_t index) inline
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
void Ogre::Renderable::setDatablock (IdString datablockName)
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
virtual void Ogre::Renderable::setDatablock (HlmsDatablock * datablock) virtual
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
virtual void Ogre::Renderable::setMaterial (const MaterialPtr & material) virtual
Sets the given material. Overrides HLMS materials.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits) RenderQueue
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
Friends And Related Function Documentation
void LodStrategy::lodSet (ObjectData & t, Real lodValues[ARRAY_PACKED_REALS]) friend
Member Data Documentation
uint32 Ogre::Renderable::mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
The documentation for this class was generated from the following file:
OgreRenderable.h