OGRE: Ogre::v1::RibbonTrail Class Reference
Ogre::v1::RibbonTrail Class Reference
Core » Effects
Subclass of BillboardChain which automatically leaves a trail behind one or more Node instances.
#include <OgreRibbonTrail.h>
Public Types
typedef vector< Element >::type ElementList
typedef FastArray< MovableObject * > MovableObjectArray
SceneManager::cullFrustum
typedef ConstVectorIterator< NodeList > NodeIterator
typedef vector< Node * >::type NodeList
enum TexCoordDirection { TCD_U, TCD_V }
The direction in which texture coordinates from elements of the chain are used.
Public Member Functions
RibbonTrail (IdType id, ObjectMemoryManager *objectMemoryManager, SceneManager *manager, size_t maxElements=20, size_t numberOfChains=1, bool useTextureCoords=true, bool useVertexColours=true)
Constructor (don't use directly, use factory)
virtual ~RibbonTrail ()
destructor
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager (void) const
Get the manager of this object, if any (internal use only)
ObjectData & _getObjectData ()
Returns a direct access to the ObjectData state.
const Matrix4 & _getParentNodeFullTransform (void) const
Returns the full transformation of the parent sceneNode or the attachingPoint node.
virtual void _notifyAttached (Node *parent)
Internal method called to notify the object that it has been attached to a node.
void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyParentNodeMemoryChanged (void)
Node::_callMemoryChangeListeners
virtual void _notifyStaticDirty (void) const
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
virtual void _setNullDatablock (void)
Sets the datablock to a null pointer.
virtual void _timeUpdate (Real time)
Perform any fading / width delta required; internal method.
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
void _updateRenderQueue (RenderQueue *, Camera *camera, const Camera *lodCamera)
Internal method by which the movable object must add Renderable subclass instances to the rendering queue.
virtual void addChainElement (size_t chainIndex, const Element &billboardChainElement)
Add an element to the 'head' of a chain.
virtual void addNode (Node *n)
Add a node to be tracked.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
virtual void clearAllChains (void)
Remove all elements from all chains (but leave the chains themselves intact).
void clearChain (size_t chainIndex)
Remove all elements of a given chain (but leave the chain intact).
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
void detachFromParent (void)
Detaches an object from a parent SceneNode if attached.
const StringVector & getAnimableValueNames (void) const
Gets a list of animable value names for this object.
const AxisAlignedBox & getBoundingBox (void) const
RealAsUint getCachedDistanceToCamera (void) const
Returns the distance to camera as calculated in .
Real getCachedDistanceToCameraAsReal (void) const
Returns the distance to camera as calculated in .
bool getCastShadows (void) const
Returns whether shadow casting is enabled for this object.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
virtual const Element & getChainElement (size_t chainIndex, size_t elementIndex) const
Get the detail of a chain element.
virtual size_t getChainIndexForNode (const Node *n)
Get the chain index for a given Node being tracked.
virtual const ColourValue & getColourChange (size_t chainIndex) const
Get the per-second fading amount.
uint8 getCurrentMaterialLod (void) const
unsigned char getCurrentMeshLod (void) const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
HlmsDatablock * getDatablock (void) const
virtual bool getDynamic (void) const
Gets whether or not the buffers created for this object are suitable for dynamic alteration.
uint32 getHlmsCasterHash (void) const
uint32 getHlmsHash (void) const
IdType getId () const
Get the unique id of this object.
virtual const ColourValue & getInitialColour (size_t chainIndex) const
Get the starting ribbon colour.
virtual Real getInitialWidth (size_t chainIndex) const
Get the starting ribbon width in world units.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
Listener * getListener (void) const
Gets the current listener for this object.
Aabb getLocalAabb (void) const
Retrieves the local axis-aligned bounding box for this object.
MaterialPtr getMaterial (void) const
Retrieves the material this renderable object uses.
virtual size_t getMaxChainElements (void) const
Get the maximum number of chain elements per chain.
const String & getMovableType (void) const
Overridden from MovableObject.
const String & getName (void) const
Returns the name of this object.
virtual NodeIterator getNodeIterator (void) const
Get an iterator over the nodes which are being tracked.
virtual size_t getNumberOfChains (void) const
Get the number of chain segments (this class can render multiple chains at once using the same material).
virtual size_t getNumChainElements (size_t chainIndex) const
Returns the number of chain elements.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
virtual const Real * getOtherTextureCoordRange (void) const
Get the range of the texture coordinates generated across the width of the chain elements.
Node * getParentNode (void) const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode (void) const
virtual bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
uint32 getQueryFlags (void) const
Returns the query flags relevant for this object.
Real getRenderingDistance (void) const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
void getRenderOperation (RenderOperation &, bool casterPass)
Gets the render operation required to send this object to the frame buffer.
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
uint8 getRenderQueueSubGroup (void) const
SkeletonInstance * getSkeletonInstance (void) const
Real getSquaredViewDepth (const Camera *cam) const
virtual TexCoordDirection getTextureCoordDirection (void)
Gets the direction in which texture coords specified on each element are deemed to run.
virtual Real getTrailLength (void) const
Get the length of the trail.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic (void) const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix (void) const
Returns whether the world matrix is an identify matrix.
virtual OGRE_DEPRECATED const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
virtual bool getUseTextureCoords (void) const
Gets whether texture coordinate information should be included in the final buffers generated.
virtual bool getUseVertexColours (void) const
Gets whether vertex colour information should be included in the final buffers generated.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
uint32 getVisibilityFlags (void) const
Returns the visibility flags relevant for this object.
bool getVisible (void) const
Gets this object whether to be visible or not, if it has a renderable component.
virtual Real getWidthChange (size_t chainIndex) const
Get the change in ribbon width per second.
Aabb getWorldAabb () const
Gets the axis aligned box in world space.
Aabb getWorldAabbUpdated ()
Gets the axis aligned box in world space.
float getWorldRadius () const
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
float getWorldRadiusUpdated ()
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
void getWorldTransforms (Matrix4 *) const
Gets the world transform matrix / matrices for this renderable object.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation (void) const
virtual void instanceBatchCullFrustumThreaded (const Frustum *frustum, const Camera *lodCamera, uint32 combinedVisibilityFlags)
InstancingTheadedCullingMethod,
bool isAttached (void) const
Returns true if this object is attached to a Node.
bool isStatic () const
Checks whether this MovableObject is static. setStatic.
bool isVisible (void) const
Returns whether or not this object is supposed to be visible or not.
virtual void nodeAttached (const Node *)
Node has been attached to a parent.
void nodeDestroyed (const Node *node)
virtual void nodeDetached (const Node *)
Node has been detached from a parent.
void nodeUpdated (const Node *node)
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
bool operator() (const IdObject *left, const IdObject *right)
bool operator() (const IdObject &left, const IdObject &right)
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
const LightList & queryLights (void) const
Gets a list of lights, ordered relative to how close they are to this movable object.
virtual void removeChainElement (size_t chainIndex)
Remove an element from the 'tail' of a chain.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
virtual void removeNode (Node *n)
Remove tracking on a given node.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
virtual void setColourChange (size_t chainIndex, const ColourValue &valuePerSecond)
Enables / disables fading the trail using colour.
virtual void setColourChange (size_t chainIndex, Real r, Real g, Real b, Real a)
Enables / disables fading the trail using colour.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
virtual void setDynamic (bool dyn)
Sets whether or not the buffers created for this object are suitable for dynamic alteration.
void setFaceCamera (bool faceCamera, const Vector3 &normalVector=Vector3::UNIT_X)
Sets whether the billboard should always be facing the camera or a custom direction set by each point element.
virtual void setInitialColour (size_t chainIndex, const ColourValue &col)
Set the starting ribbon colour for a given segment.
virtual void setInitialColour (size_t chainIndex, Real r, Real g, Real b, Real a=1.0)
Set the starting ribbon colour.
virtual void setInitialWidth (size_t chainIndex, Real width)
Set the starting ribbon width in world units.
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
void setLocalAabb (const Aabb box)
Sets the local axis-aligned bounding box for this object.
virtual void setMaterial (const MaterialPtr &material)
Sets the given material. Overrides HLMS materials.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
void setMaxChainElements (size_t maxElements)
Set the maximum number of chain elements per chain.
void setName (const String &name)
Sets a custom name for this node.
void setNumberOfChains (size_t numChains)
Set the number of chain segments (this class can render multiple chains at once using the same material).
virtual void setOtherTextureCoordRange (Real start, Real end)
Set the range of the texture coordinates generated across the width of the chain elements.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
bool setStatic (bool bStatic)
Turns this Node into static or dynamic.
virtual void setTextureCoordDirection (TexCoordDirection dir)
Sets the direction in which texture coords specified on each element are deemed to run along the length of the chain.
virtual void setTrailLength (Real len)
Set the length of the trail.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
virtual void setUseTextureCoords (bool use)
Sets whether texture coordinate information should be included in the final buffers generated.
virtual void setUseVertexColours (bool use)
Sets whether vertex colour information should be included in the final buffers generated.
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
virtual void setWidthChange (size_t chainIndex, Real widthDeltaPerSecond)
Set the change in ribbon width per second.
virtual void updateChainElement (size_t chainIndex, size_t elementIndex, const Element &billboardChainElement)
Update the details of an existing chain element.
Static Public Member Functions
static void buildLightList (const size_t numNodes, ObjectData t, const LightListInfo &globalLightList)
SceneManager::buildLightList
static void calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox *outBox)
static void cullFrustum (const size_t numNodes, ObjectData t, const Camera *frustum, uint32 sceneVisibilityFlags, MovableObjectArray &outCulledObjects, const Camera *lodCamera)
static void cullLights (const size_t numNodes, ObjectData t, LightListInfo &outGlobalLightList, const FrustumVec &frustums, const FrustumVec &cubemapFrustums)
SceneManager::cullLights &
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
static void updateAllBounds (const size_t numNodes, ObjectData t)
SceneManager::updateAllBounds
Public Attributes
size_t mGlobalIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
size_t mParentIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
RenderableArray mRenderables
Static Public Attributes
static const FastArray< Real > c_DefaultLodMesh
Detailed Description
Subclass of BillboardChain which automatically leaves a trail behind one or more Node instances.
Remarks
An instance of this class will watch one or more Node instances, and automatically generate a trail behind them as they move. Because this class can monitor multiple modes, it generates its own geometry in world space and thus, even though it has to be attached to a SceneNode to be visible, changing the position of the scene node it is attached to makes no difference to the geometry rendered.
The 'head' element grows smoothly in size until it reaches the required size, then a new element is added. If the segment is full, the tail element shrinks by the same proportion as the head grows before disappearing.
Elements can be faded out on a time basis, either by altering their colour or altering their alpha. The width can also alter over time.
'v' texture coordinates are fixed at 0.0 if used, meaning that you can use a 1D texture to 'smear' a colour pattern along the ribbon if you wish. The 'u' coordinates are by default (0.0, 1.0), but you can alter this using setOtherTexCoordRange if you wish.
Member Typedef Documentation
typedef vector<Element>::type Ogre::v1::BillboardChain::ElementList inherited
typedef FastArray<MovableObject*> Ogre::MovableObject::MovableObjectArray inherited
SceneManager::cullFrustum
Remarks
We don't pass by reference on purpose (avoid implicit aliasing) We perform frustum culling AND test visibility mask at the same time
Parameters
frustum Frustum to clip against
sceneVisibilityFlags Combined scene's visibility flags (i.e. viewport | scene). Set LAYER_SHADOW_CASTER bit if you want to exclude non-shadow casters.
outCulledObjects Out. List of objects that are (fully or partially) inside the frustum and should be rendered
lodCamera Camera in which lod levels calculations are based (i.e. during shadow pass renders) Note however, we only use this camera to calulate if should be visible according to mUpperDistance
typedef ConstVectorIterator<NodeList> Ogre::v1::RibbonTrail::NodeIterator
typedef vector<Node*>::type Ogre::v1::RibbonTrail::NodeList
Member Enumeration Documentation
enum Ogre::v1::BillboardChain::TexCoordDirection inherited
The direction in which texture coordinates from elements of the chain are used.
Enumerator
TCD_U
Tex coord in elements is treated as the 'u' texture coordinate.
TCD_V
Tex coord in elements is treated as the 'v' texture coordinate.
Constructor & Destructor Documentation
Ogre::v1::RibbonTrail::RibbonTrail (IdType id, ObjectMemoryManager * objectMemoryManager, SceneManager * manager, size_t maxElements = 20, size_t numberOfChains = 1, bool useTextureCoords = true, bool useVertexColours = true)
Constructor (don't use directly, use factory)
Parameters
name The name to give this object
maxElements The maximum number of elements per chain
numberOfChains The number of separate chain segments contained in this object, ie the maximum number of nodes that can have trails attached
useTextureCoords If true, use texture coordinates from the chain elements
useVertexColours If true, use vertex colours from the chain elements (must be true if you intend to use fading)
virtual Ogre::v1::RibbonTrail::~RibbonTrail () virtual
destructor
Member Function Documentation
LightList* Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
SceneManager* Ogre::MovableObject::_getManager (void) const inline inherited
Get the manager of this object, if any (internal use only)
ObjectData& Ogre::MovableObject::_getObjectData () inline inherited
Returns a direct access to the ObjectData state.
const Matrix4& Ogre::MovableObject::_getParentNodeFullTransform (void) const inherited
Returns the full transformation of the parent sceneNode or the attachingPoint node.
virtual void Ogre::MovableObject::_notifyAttached (Node * parent) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::v1::Entity, Ogre::ParticleSystem, and Ogre::v1::InstancedEntity.
void Ogre::MovableObject::_notifyManager (SceneManager * man) inline inherited
Notify the object of it's manager (internal use only)
virtual void Ogre::MovableObject::_notifyParentNodeMemoryChanged (void) inline virtual inherited
Node::_callMemoryChangeListeners
Reimplemented in Ogre::Item, and Ogre::v1::InstancedEntity.
virtual void Ogre::MovableObject::_notifyStaticDirty (void) const inline virtual inherited
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
See also
SceneManager::notifyStaticDirty
Reimplemented in Ogre::v1::InstancedEntity.
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual inherited
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
virtual void Ogre::Renderable::_setNullDatablock (void) virtual inherited
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
virtual void Ogre::v1::RibbonTrail::_timeUpdate (Real time) virtual
Perform any fading / width delta required; internal method.
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::v1::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
void Ogre::v1::BillboardChain::_updateRenderQueue (RenderQueue * queue, Camera * camera, const Camera * lodCamera) virtual inherited
Internal method by which the movable object must add Renderable subclass instances to the rendering queue.
Remarks
The engine will call this method when this object is to be rendered. The object must then create one or more Renderable subclass instances which it places on the passed in Queue for rendering.
Reimplemented from Ogre::MovableObject.
virtual void Ogre::v1::BillboardChain::addChainElement (size_t chainIndex, const Element & billboardChainElement) virtual inherited
Add an element to the 'head' of a chain.
Remarks
If this causes the number of elements to exceed the maximum elements per chain, the last element in the chain (the 'tail') will be removed to allow the additional element to be added.
Parameters
chainIndex The index of the chain
billboardChainElement The details to add
virtual void Ogre::v1::RibbonTrail::addNode (Node * n) virtual
Add a node to be tracked.
Parameters
n The node that will be tracked.
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
static void Ogre::MovableObject::buildLightList (const size_t numNodes, ObjectData t, const LightListInfo & globalLightList) static inherited
SceneManager::buildLightList
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
Parameters
globalLightList List of lights already culled against all possible frustums and reorganized contiguously for SoA
static void Ogre::MovableObject::calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox * outBox) static inherited
virtual void Ogre::v1::BillboardChain::clearAllChains (void) virtual inherited
Remove all elements from all chains (but leave the chains themselves intact).
void Ogre::v1::RibbonTrail::clearChain (size_t chainIndex) virtual
Remove all elements of a given chain (but leave the chain intact).
Reimplemented from Ogre::v1::BillboardChain.
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
static void Ogre::MovableObject::cullFrustum (const size_t numNodes, ObjectData t, const Camera * frustum, uint32 sceneVisibilityFlags, MovableObjectArray & outCulledObjects, const Camera * lodCamera) static inherited
static void Ogre::MovableObject::cullLights (const size_t numNodes, ObjectData t, LightListInfo & outGlobalLightList, const FrustumVec & frustums, const FrustumVec & cubemapFrustums) static inherited
SceneManager::cullLights &
See also
MovableObject::cullFrustum Produces the global list of visible lights that is needed in buildLightList
Remarks
We don't pass ObjectData by reference on purpose (avoid implicit aliasing) It's declared here because all affected elements are from MovableObject IMPORTANT: It is assumed that all objects in ObjectData are Lights.
Parameters
outGlobalLightList Output, a list of lights, contiguously placed
frustums An array of all frustums we need to check against
cubemapFrustums An array of all frustums that are used at least once as cubemaps (SceneManager::createCamera)
void Ogre::MovableObject::detachFromParent (void) inherited
Detaches an object from a parent SceneNode if attached.
const StringVector& Ogre::AnimableObject::getAnimableValueNames (void) const inline inherited
Gets a list of animable value names for this object.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
const AxisAlignedBox& Ogre::v1::BillboardChain::getBoundingBox (void) const inherited
RealAsUint Ogre::MovableObject::getCachedDistanceToCamera (void) const inline inherited
Returns the distance to camera as calculated in .
Real Ogre::MovableObject::getCachedDistanceToCameraAsReal (void) const inline inherited
Returns the distance to camera as calculated in .
bool Ogre::MovableObject::getCastShadows (void) const inline inherited
Returns whether shadow casting is enabled for this object.
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::ManualObject::ManualObjectSection, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::SubItem, and Ogre::WireAabb.
virtual const Element& Ogre::v1::BillboardChain::getChainElement (size_t chainIndex, size_t elementIndex) const virtual inherited
Get the detail of a chain element.
Parameters
chainIndex The index of the chain
elementIndex The element index within the chain, measured from the 'head' of the chain
virtual size_t Ogre::v1::RibbonTrail::getChainIndexForNode (const Node * n) virtual
Get the chain index for a given Node being tracked.
virtual const ColourValue& Ogre::v1::RibbonTrail::getColourChange (size_t chainIndex) const virtual
Get the per-second fading amount.
uint8 Ogre::Renderable::getCurrentMaterialLod (void) const inline inherited
References ARRAY_PACKED_REALS, and Ogre::LodStrategy::lodSet().
unsigned char Ogre::MovableObject::getCurrentMeshLod (void) const inline inherited
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
HlmsDatablock* Ogre::Renderable::getDatablock (void) const inline inherited
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
virtual bool Ogre::v1::BillboardChain::getDynamic (void) const inline virtual inherited
Gets whether or not the buffers created for this object are suitable for dynamic alteration.
References Ogre::Vector3::UNIT_X.
uint32 Ogre::Renderable::getHlmsCasterHash (void) const inline inherited
uint32 Ogre::Renderable::getHlmsHash (void) const inline inherited
IdType Ogre::IdObject::getId () const inline inherited
Get the unique id of this object.
virtual const ColourValue& Ogre::v1::RibbonTrail::getInitialColour (size_t chainIndex) const virtual
Get the starting ribbon colour.
virtual Real Ogre::v1::RibbonTrail::getInitialWidth (size_t chainIndex) const virtual
Get the starting ribbon width in world units.
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
const LightList& Ogre::v1::BillboardChain::getLights (void) const virtual inherited
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
Listener* Ogre::MovableObject::getListener (void) const inline inherited
Gets the current listener for this object.
Aabb Ogre::MovableObject::getLocalAabb (void) const inherited
Retrieves the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
MaterialPtr Ogre::Renderable::getMaterial (void) const inherited
Retrieves the material this renderable object uses.
It may be null if it's using the HLMS. getDatablock
virtual size_t Ogre::v1::BillboardChain::getMaxChainElements (void) const inline virtual inherited
Get the maximum number of chain elements per chain.
const String& Ogre::v1::RibbonTrail::getMovableType (void) const virtual
Overridden from MovableObject.
Reimplemented from Ogre::v1::BillboardChain.
const String& Ogre::MovableObject::getName (void) const inline inherited
Returns the name of this object.
virtual NodeIterator Ogre::v1::RibbonTrail::getNodeIterator (void) const virtual
Get an iterator over the nodes which are being tracked.
virtual size_t Ogre::v1::BillboardChain::getNumberOfChains (void) const inline virtual inherited
Get the number of chain segments (this class can render multiple chains at once using the same material).
virtual size_t Ogre::v1::BillboardChain::getNumChainElements (size_t chainIndex) const virtual inherited
Returns the number of chain elements.
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::v1::BorderRenderable, Ogre::v1::SubEntity, Ogre::v1::BaseInstanceBatchVTF, Ogre::v1::InstanceBatchShader, and Ogre::v1::InstanceBatchHW.
virtual const Real* Ogre::v1::BillboardChain::getOtherTextureCoordRange (void) const inline virtual inherited
Get the range of the texture coordinates generated across the width of the chain elements.
Node* Ogre::MovableObject::getParentNode (void) const inline inherited
Returns the node to which this object is attached.
SceneNode* Ogre::MovableObject::getParentSceneNode (void) const inline inherited
virtual bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline virtual inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
uint32 Ogre::MovableObject::getQueryFlags (void) const inline inherited
Returns the query flags relevant for this object.
Real Ogre::MovableObject::getRenderingDistance (void) const inline inherited
Gets the distance at which batches are no longer rendered.
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
void Ogre::v1::BillboardChain::getRenderOperation (RenderOperation & op, bool casterPass) virtual inherited
Gets the render operation required to send this object to the frame buffer.
Implements Ogre::Renderable.
uint8 Ogre::MovableObject::getRenderQueueGroup (void) const inline inherited
Gets the queue group for this entity, see setRenderQueueGroup for full details.
uint8 Ogre::Renderable::getRenderQueueSubGroup (void) const inline inherited
References Ogre::NumVertexPass.
SkeletonInstance* Ogre::MovableObject::getSkeletonInstance (void) const inline inherited
Real Ogre::v1::BillboardChain::getSquaredViewDepth (const Camera * cam) const inherited
virtual TexCoordDirection Ogre::v1::BillboardChain::getTextureCoordDirection (void) inline virtual inherited
Gets the direction in which texture coords specified on each element are deemed to run.
virtual Real Ogre::v1::RibbonTrail::getTrailLength (void) const inline virtual
Get the length of the trail.
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic (void) const inline virtual inherited
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix (void) const inline virtual inherited
Returns whether the world matrix is an identify matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
virtual OGRE_DEPRECATED const Any& Ogre::Renderable::getUserAny (void) const inline virtual inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
virtual bool Ogre::v1::BillboardChain::getUseTextureCoords (void) const inline virtual inherited
Gets whether texture coordinate information should be included in the final buffers generated.
virtual bool Ogre::v1::BillboardChain::getUseVertexColours (void) const inline virtual inherited
Gets whether vertex colour information should be included in the final buffers generated.
const VertexArrayObjectArray& Ogre::Renderable::getVaos (VertexPass vertexPass) const inline inherited
uint32 Ogre::MovableObject::getVisibilityFlags (void) const inline inherited
Returns the visibility flags relevant for this object.
Reserved visibility flags are not returned.
bool Ogre::MovableObject::getVisible (void) const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
virtual Real Ogre::v1::RibbonTrail::getWidthChange (size_t chainIndex) const virtual
Get the change in ribbon width per second.
Aabb Ogre::MovableObject::getWorldAabb () const inherited
Gets the axis aligned box in world space.
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. getWorldAabbUpdated if you need the update process to be guaranteed
Aabb Ogre::MovableObject::getWorldAabbUpdated () inherited
Gets the axis aligned box in world space.
Remarks
Unlike getWorldAabb, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
float Ogre::MovableObject::getWorldRadius () const inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. getWorldRadiusUpdated if you need the update process to be guaranteed
float Ogre::MovableObject::getWorldRadiusUpdated () inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Unlike getWorldRadius, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
void Ogre::v1::BillboardChain::getWorldTransforms (Matrix4 * xform) const virtual inherited
Gets the world transform matrix / matrices for this renderable object.
Remarks
If the object has any derived transforms, these are expected to be up to date as long as all the SceneNode structures have been updated before this is called.
This method will populate transform with 1 matrix if it does not use vertex blending. If it does use vertex blending it will fill the passed in pointer with an array of matrices, the length being the value returned from getNumWorldTransforms.
Note
Internal Ogre never supports non-affine matrix for world transform matrix/matrices, the behavior is undefined if returns non-affine matrix here.
See also
Matrix4::isAffine.
Implements Ogre::Renderable.
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
bool Ogre::Renderable::hasSkeletonAnimation (void) const inline inherited
virtual void Ogre::MovableObject::instanceBatchCullFrustumThreaded (const Frustum * frustum, const Camera * lodCamera, uint32 combinedVisibilityFlags) inline virtual inherited
InstancingTheadedCullingMethod,
See also
InstanceBatch::instanceBatchCullFrustumThreaded
References ARRAY_PACKED_REALS, Ogre::LodStrategy::lodSet(), and Ogre::LodStrategy::lodUpdateImpl().
bool Ogre::MovableObject::isAttached (void) const inline inherited
Returns true if this object is attached to a Node.
bool Ogre::MovableObject::isStatic () const inherited
Checks whether this MovableObject is static. setStatic.
bool Ogre::MovableObject::isVisible (void) const inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account visibility flags and the setVisible, but not rendering distance.
virtual void Ogre::Node::Listener::nodeAttached (const Node *) inline virtual inherited
Node has been attached to a parent.
void Ogre::v1::RibbonTrail::nodeDestroyed (const Node * node) virtual
See also
Node::Listener::nodeDestroyed
Reimplemented from Ogre::Node::Listener.
virtual void Ogre::Node::Listener::nodeDetached (const Node *) inline virtual inherited
Node has been detached from a parent.
void Ogre::v1::RibbonTrail::nodeUpdated (const Node * node) virtual
See also
Node::Listener::nodeUpdated
Reimplemented from Ogre::Node::Listener.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
bool Ogre::IdObject::operator() (const IdObject * left, const IdObject * right) inline inherited
bool Ogre::IdObject::operator() (const IdObject & left, const IdObject & right) inline inherited
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
virtual bool Ogre::v1::BillboardChain::preRender (SceneManager * sm, RenderSystem * rsys) virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented from Ogre::Renderable.
const LightList& Ogre::MovableObject::queryLights (void) const inline inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
The lights are filled in
See also
buildLightList
Returns
The list of lights use to lighting this object.
virtual void Ogre::v1::BillboardChain::removeChainElement (size_t chainIndex) virtual inherited
Remove an element from the 'tail' of a chain.
Parameters
chainIndex The index of the chain
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
virtual void Ogre::v1::RibbonTrail::removeNode (Node * n) virtual
Remove tracking on a given node.
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
virtual void Ogre::v1::RibbonTrail::setColourChange (size_t chainIndex, const ColourValue & valuePerSecond) virtual
Enables / disables fading the trail using colour.
Parameters
chainIndex The index of the chain
valuePerSecond The amount to subtract from colour each second
virtual void Ogre::v1::RibbonTrail::setColourChange (size_t chainIndex, Real r, Real g, Real b, Real a) virtual
Enables / disables fading the trail using colour.
Parameters
chainIndex The index of the chain
r,g,b,a The amount to subtract from each colour channel per second
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
void Ogre::Renderable::setDatablock (IdString datablockName) inherited
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
virtual void Ogre::Renderable::setDatablock (HlmsDatablock * datablock) virtual inherited
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName) inherited
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
virtual void Ogre::v1::BillboardChain::setDynamic (bool dyn) virtual inherited
Sets whether or not the buffers created for this object are suitable for dynamic alteration.
void Ogre::v1::BillboardChain::setFaceCamera (bool faceCamera, const Vector3 & normalVector = Vector3::UNIT_X) inherited
Sets whether the billboard should always be facing the camera or a custom direction set by each point element.
Remarks
Billboards facing the camera are useful for smoke trails, light beams, etc by simulating a cylinder. However, because of this property, wide trails can cause several artefacts unless the head is properly covered. Therefore, non-camera-facing billboards are much more convenient for leaving big trails of movement from thin objects, for example a sword swing as seen in many fighting games.
Parameters
faceCamera True to be always facing the camera (Default value: True)
normalVector Only used when faceCamera == false. Must be a non-zero vector. This vector is the "point of reference" for each point orientation. For example, if normalVector is Vector3::UNIT_Z, and the point's orientation is an identity matrix, the segment corresponding to that point will be facing towards UNIT_Z This vector is internally normalized.
virtual void Ogre::v1::RibbonTrail::setInitialColour (size_t chainIndex, const ColourValue & col) virtual
Set the starting ribbon colour for a given segment.
Parameters
chainIndex The index of the chain
col The initial colour
Note
Only used if this instance is using vertex colours.
virtual void Ogre::v1::RibbonTrail::setInitialColour (size_t chainIndex, Real r, Real g, Real b, Real a = 1.0) virtual
Set the starting ribbon colour.
Parameters
chainIndex The index of the chain
r,b,g,a The initial colour
Note
Only used if this instance is using vertex colours.
virtual void Ogre::v1::RibbonTrail::setInitialWidth (size_t chainIndex, Real width) virtual
Set the starting ribbon width in world units.
Parameters
chainIndex The index of the chain
width The initial width of the ribbon
void Ogre::MovableObject::setLightMask (uint32 lightMask) inline inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
void Ogre::MovableObject::setLocalAabb (const Aabb box) inherited
Sets the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
virtual void Ogre::Renderable::setMaterial (const MaterialPtr & material) virtual inherited
Sets the given material. Overrides HLMS materials.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName) inherited
Sets the name of the Material to be used. Prefer using HLMS setHlms.
void Ogre::v1::RibbonTrail::setMaxChainElements (size_t maxElements) virtual
Set the maximum number of chain elements per chain.
Reimplemented from Ogre::v1::BillboardChain.
void Ogre::MovableObject::setName (const String & name) inline inherited
Sets a custom name for this node.
Doesn't have to be unique
void Ogre::v1::RibbonTrail::setNumberOfChains (size_t numChains) virtual
Set the number of chain segments (this class can render multiple chains at once using the same material).
Reimplemented from Ogre::v1::BillboardChain.
virtual void Ogre::v1::BillboardChain::setOtherTextureCoordRange (Real start, Real end) virtual inherited
Set the range of the texture coordinates generated across the width of the chain elements.
Parameters
start Start coordinate, default 0.0
end End coordinate, default 1.0
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Parameters
dist Distance beyond which the object will not be rendered (the default is FLT_MAX, which means objects are always rendered). Values equal or below zero will be ignored, and cause an assertion in debug mode.
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Valid render queue ids are between 0 & 254 inclusive
Reimplemented in Ogre::ParticleSystem, Ogre::v1::Entity, and Ogre::Light.
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline inherited
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits) RenderQueue
bool Ogre::MovableObject::setStatic (bool bStatic) inherited
Turns this Node into static or dynamic.
Remarks
Switching between dynamic and static has some overhead and forces to update all static scene when converted to static. So don't do it frequently. Static objects are not updated every frame, only when requested explicitly. Use this feature if you plan to have this object unaltered for a very long times
Note all MovableObjects support switching between static & dynamic after they have been created (eg. InstancedEntity)
Changing this attribute will cause to switch the attribute to our parent node, and as a result, all of its other attached entities. Node::setStatic
Returns
True if setStatic made an actual change. False otherwise. Can fail because the object was already static/dynamic, or because switching is not supported
virtual void Ogre::v1::BillboardChain::setTextureCoordDirection (TexCoordDirection dir) virtual inherited
Sets the direction in which texture coords specified on each element are deemed to run along the length of the chain.
Parameters
dir The direction, default is TCD_U.
virtual void Ogre::v1::RibbonTrail::setTrailLength (Real len) virtual
Set the length of the trail.
Remarks
This sets the length of the trail, in world units. It also sets how far apart each segment will be, ie length / max_elements.
Parameters
len The length of the trail in world units
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
virtual void Ogre::v1::BillboardChain::setUseTextureCoords (bool use) virtual inherited
Sets whether texture coordinate information should be included in the final buffers generated.
Note
You must use either texture coordinates or vertex colour since the vertices have no normals and without one of these there is no source of colour for the vertices.
virtual void Ogre::v1::BillboardChain::setUseVertexColours (bool use) virtual inherited
Sets whether vertex colour information should be included in the final buffers generated.
Note
You must use either texture coordinates or vertex colour since the vertices have no normals and without one of these there is no source of colour for the vertices.
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags that is applied a binary 'and' with the SceneManager's mask and a compositor node pass. To exclude particular objects from rendering. Changes to reserved visibility flags are ignored (won't take effect).
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
virtual void Ogre::v1::RibbonTrail::setWidthChange (size_t chainIndex, Real widthDeltaPerSecond) virtual
Set the change in ribbon width per second.
Parameters
chainIndex The index of the chain
widthDeltaPerSecond The amount the width will reduce by per second
static void Ogre::MovableObject::updateAllBounds (const size_t numNodes, ObjectData t) static inherited
SceneManager::updateAllBounds
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
virtual void Ogre::v1::BillboardChain::updateChainElement (size_t chainIndex, size_t elementIndex, const Element & billboardChainElement) virtual inherited
Update the details of an existing chain element.
Parameters
chainIndex The index of the chain
elementIndex The element index within the chain, measured from the 'head' of the chain
billboardChainElement The details to set
Member Data Documentation
const FastArray<Real> Ogre::MovableObject::c_DefaultLodMesh static inherited
size_t Ogre::MovableObject::mGlobalIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
uint32 Ogre::Renderable::mHlmsGlobalIndex inherited
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
size_t Ogre::MovableObject::mParentIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
RenderableArray Ogre::MovableObject::mRenderables inherited
The documentation for this class was generated from the following file:
OgreRibbonTrail.h