OGRE: Ogre::SmallVectorTemplateCommon< T > Class Template Reference
Ogre::SmallVectorTemplateCommon< T > Class Template Reference
#include <OgreSmallVector.h>
Public Types
typedef const T * const_iterator
typedef const T * const_iterator
typedef const T * const_pointer
typedef const T * const_pointer
typedef const T & const_reference
typedef const T & const_reference
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef ptrdiff_t difference_type
typedef ptrdiff_t difference_type
typedef T * iterator
typedef T * iterator
typedef T * pointer
typedef T * pointer
typedef T & reference
typedef T & reference
typedef std::reverse_iterator< iterator > reverse_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
typedef size_t size_type
typedef size_t size_type
typedef T value_type
typedef T value_type
Public Member Functions
SmallVectorTemplateCommon (size_t Size)
SmallVectorTemplateCommon (size_t Size)
reference back ()
const_reference back () const
reference back ()
const_reference back () const
iterator begin ()
const_iterator begin () const
iterator begin ()
const_iterator begin () const
size_t capacity () const
capacity - Return the total number of elements in the currently allocated buffer.
size_t capacity () const
capacity - Return the total number of elements in the currently allocated buffer.
pointer data ()
data - Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
data - Return a pointer to the vector's buffer, even if empty().
pointer data ()
data - Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
data - Return a pointer to the vector's buffer, even if empty().
bool empty () const
bool empty () const
iterator end ()
const_iterator end () const
iterator end ()
const_iterator end () const
reference front ()
const_reference front () const
reference front ()
const_reference front () const
size_type max_size () const
size_type max_size () const
reference operator[] (unsigned idx)
const_reference operator[] (unsigned idx) const
reference operator[] (unsigned idx)
const_reference operator[] (unsigned idx) const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type size () const
Member Typedef Documentation
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_iterator
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_iterator
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_pointer
template<typename T> typedef const T* Ogre::SmallVectorTemplateCommon< T >::const_pointer
template<typename T> typedef const T& Ogre::SmallVectorTemplateCommon< T >::const_reference
template<typename T> typedef const T& Ogre::SmallVectorTemplateCommon< T >::const_reference
template<typename T> typedef std::reverse_iterator<const_iterator> Ogre::SmallVectorTemplateCommon< T >::const_reverse_iterator
template<typename T> typedef std::reverse_iterator<const_iterator> Ogre::SmallVectorTemplateCommon< T >::const_reverse_iterator
template<typename T> typedef ptrdiff_t Ogre::SmallVectorTemplateCommon< T >::difference_type
template<typename T> typedef ptrdiff_t Ogre::SmallVectorTemplateCommon< T >::difference_type
template<typename T> typedef T* Ogre::SmallVectorTemplateCommon< T >::iterator
template<typename T> typedef T* Ogre::SmallVectorTemplateCommon< T >::iterator
template<typename T> typedef T* Ogre::SmallVectorTemplateCommon< T >::pointer
template<typename T> typedef T* Ogre::SmallVectorTemplateCommon< T >::pointer
template<typename T> typedef T& Ogre::SmallVectorTemplateCommon< T >::reference
template<typename T> typedef T& Ogre::SmallVectorTemplateCommon< T >::reference
template<typename T> typedef std::reverse_iterator<iterator> Ogre::SmallVectorTemplateCommon< T >::reverse_iterator
template<typename T> typedef std::reverse_iterator<iterator> Ogre::SmallVectorTemplateCommon< T >::reverse_iterator
template<typename T> typedef size_t Ogre::SmallVectorTemplateCommon< T >::size_type
template<typename T> typedef size_t Ogre::SmallVectorTemplateCommon< T >::size_type
template<typename T> typedef T Ogre::SmallVectorTemplateCommon< T >::value_type
template<typename T> typedef T Ogre::SmallVectorTemplateCommon< T >::value_type
Constructor & Destructor Documentation
template<typename T> Ogre::SmallVectorTemplateCommon< T >::SmallVectorTemplateCommon (size_t Size) inline
template<typename T> Ogre::SmallVectorTemplateCommon< T >::SmallVectorTemplateCommon (size_t Size) inline
Member Function Documentation
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::back () inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::back () const inline
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::back () inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::back () const inline
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::begin () inline
Referenced by Ogre::SmallVectorImpl< Triangle * >::operator<(), Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< Triangle * >::operator==(), Ogre::SmallVectorImpl< Triangle * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::begin () const inline
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::begin () inline
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::begin () const inline
template<typename T> size_t Ogre::SmallVectorTemplateCommon< T >::capacity () const inline
capacity - Return the total number of elements in the currently allocated buffer.
Referenced by Ogre::SmallVectorImpl< Triangle * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
template<typename T> size_t Ogre::SmallVectorTemplateCommon< T >::capacity () const inline
capacity - Return the total number of elements in the currently allocated buffer.
template<typename T> pointer Ogre::SmallVectorTemplateCommon< T >::data () inline
data - Return a pointer to the vector's buffer, even if empty().
template<typename T> const_pointer Ogre::SmallVectorTemplateCommon< T >::data () const inline
data - Return a pointer to the vector's buffer, even if empty().
template<typename T> pointer Ogre::SmallVectorTemplateCommon< T >::data () inline
data - Return a pointer to the vector's buffer, even if empty().
template<typename T> const_pointer Ogre::SmallVectorTemplateCommon< T >::data () const inline
data - Return a pointer to the vector's buffer, even if empty().
bool Ogre::SmallVectorBase::empty () const inline inherited
Referenced by Ogre::SmallVector< T, S >::SmallVector().
bool Ogre::SmallVectorBase::empty () const inline inherited
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::end (void) inline
Referenced by Ogre::SmallVectorImpl< Triangle * >::operator<(), Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< Triangle * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::end (void) const inline
template<typename T> iterator Ogre::SmallVectorTemplateCommon< T >::end (void) inline
template<typename T> const_iterator Ogre::SmallVectorTemplateCommon< T >::end (void) const inline
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::front () inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::front () const inline
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::front () inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::front () const inline
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::max_size () const inline
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::max_size () const inline
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) const inline
template<typename T> reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) inline
template<typename T> const_reference Ogre::SmallVectorTemplateCommon< T >::operator[] (unsigned idx) const inline
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () inline
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () const inline
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () inline
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rbegin () const inline
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () inline
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () const inline
template<typename T> reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () inline
template<typename T> const_reverse_iterator Ogre::SmallVectorTemplateCommon< T >::rend () const inline
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::size (void) const inline
Referenced by Ogre::SmallVectorImpl< T >::operator=(), Ogre::SmallVectorImpl< Triangle * >::operator==(), Ogre::SmallVectorImpl< Triangle * >::set_size(), and Ogre::SmallVectorImpl< T >::swap().
template<typename T> size_type Ogre::SmallVectorTemplateCommon< T >::size (void) const inline
The documentation for this class was generated from the following file:
OgreMain/include/OgreSmallVector.h