OGRE: Ogre::v1::SubEntity Class Reference
Ogre::v1::SubEntity Class Reference
Core » Scene
Utility class which defines the sub-parts of an Entity.
#include <OgreSubEntity.h>
Public Member Functions
virtual ~SubEntity ()
Destructor.
bool _getBuffersMarkedForAnimation (void) const
Are buffers already marked as vertex animated?
VertexData * _getHardwareVertexAnimVertexData (void)
Advanced method to get the hardware morph vertex information.
TempBlendedBufferInfo * _getSkelAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software skeletal animation.
VertexData * _getSkelAnimVertexData (void)
Advanced method to get the temporarily blended vertex information for entities which are software skinned.
VertexData * _getSoftwareVertexAnimVertexData (void)
Advanced method to get the temporarily blended software morph vertex information.
TempBlendedBufferInfo * _getVertexAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software morph animation.
const TempBlendedBufferInfo * _getVertexAnimTempBufferInfo (void) const
void _markBuffersUnusedForAnimation (void)
Mark all vertex data as so far unanimated.
void _markBuffersUsedForAnimation (void)
Mark all vertex data as animated.
void _restoreBuffersForUnusedAnimation (bool hardwareAnimation)
Internal method to copy original vertex data to the morph structures should there be no active animation in use.
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
virtual void _setNullDatablock (void)
Sets the datablock to a null pointer.
void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Overridden from Renderable to provide some custom behaviour.
bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
uint8 getCurrentMaterialLod (void) const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
HlmsDatablock * getDatablock (void) const
uint32 getHlmsCasterHash (void) const
uint32 getHlmsHash (void) const
size_t getIndexDataEndIndex () const
Returns the current value of the start index used for drawing.
size_t getIndexDataStartIndex () const
Returns the current value of the start index used for drawing.
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
MaterialPtr getMaterial (void) const
Retrieves the material this renderable object uses.
unsigned short getNumWorldTransforms (void) const
Overridden - see Renderable.
Entity * getParent (void) const
Accessor to get parent Entity.
virtual bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void getRenderOperation (RenderOperation &op, bool casterPass)
Overridden - see Renderable.
uint8 getRenderQueueSubGroup (void) const
Real getSquaredViewDepth (const Camera *cam) const
Overridden, see Renderable.
SubMesh * getSubMesh (void) const
Accessor method to read mesh data.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic (void) const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix (void) const
Returns whether the world matrix is an identify matrix.
virtual OGRE_DEPRECATED const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
VertexData * getVertexDataForBinding (bool casterPass)
Retrieve the VertexData which should be used for GPU binding.
void getWorldTransforms (Matrix4 *xform) const
Overridden - see Renderable.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation (void) const
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void resetIndexDataStartEndIndex ()
Reset the custom start/end index to the default values.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
void setIndexDataEndIndex (size_t end_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
void setIndexDataStartIndex (size_t start_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
virtual void setMaterial (const MaterialPtr &material)
Sets a Material to be used.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
Public Attributes
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
Friends
class Entity
class SceneManager
Detailed Description
Utility class which defines the sub-parts of an Entity.
Remarks
Just as meshes are split into submeshes, an Entity is made up of potentially multiple SubMeshes. These are mainly here to provide the link between the Material which the SubEntity uses (which may be the default Material for the SubMesh or may have been changed for this object) and the SubMesh data.
The SubEntity also allows the application some flexibility in the material properties for this section of a particular instance of this Mesh, e.g. tinting the windows on a car model.
SubEntity instances are never created manually. They are created at the same time as their parent Entity by the SceneManager method createEntity.
Constructor & Destructor Documentation
virtual Ogre::v1::SubEntity::~SubEntity () virtual
Destructor.
Member Function Documentation
bool Ogre::v1::SubEntity::_getBuffersMarkedForAnimation (void) const inline
Are buffers already marked as vertex animated?
VertexData* Ogre::v1::SubEntity::_getHardwareVertexAnimVertexData (void)
Advanced method to get the hardware morph vertex information.
Note
The positions/normals of the returned vertex data is in object space.
TempBlendedBufferInfo* Ogre::v1::SubEntity::_getSkelAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software skeletal animation.
VertexData* Ogre::v1::SubEntity::_getSkelAnimVertexData (void)
Advanced method to get the temporarily blended vertex information for entities which are software skinned.
Remarks
Internal engine will eliminate software animation if possible, this information is unreliable unless added request for software animation via Entity::addSoftwareAnimationRequest.
Note
The positions/normals of the returned vertex data is in object space.
VertexData* Ogre::v1::SubEntity::_getSoftwareVertexAnimVertexData (void)
Advanced method to get the temporarily blended software morph vertex information.
Remarks
Internal engine will eliminate software animation if possible, this information is unreliable unless added request for software animation via Entity::addSoftwareAnimationRequest.
Note
The positions/normals of the returned vertex data is in object space.
TempBlendedBufferInfo* Ogre::v1::SubEntity::_getVertexAnimTempBufferInfo (void)
Advanced method to get the temp buffer information for software morph animation.
const TempBlendedBufferInfo* Ogre::v1::SubEntity::_getVertexAnimTempBufferInfo (void) const
void Ogre::v1::SubEntity::_markBuffersUnusedForAnimation (void)
Mark all vertex data as so far unanimated.
void Ogre::v1::SubEntity::_markBuffersUsedForAnimation (void)
Mark all vertex data as animated.
void Ogre::v1::SubEntity::_restoreBuffersForUnusedAnimation (bool hardwareAnimation)
Internal method to copy original vertex data to the morph structures should there be no active animation in use.
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual inherited
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
virtual void Ogre::v1::SubEntity::_setNullDatablock (void) virtual
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented from Ogre::Renderable.
void Ogre::v1::SubEntity::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const virtual
Overridden from Renderable to provide some custom behaviour.
Reimplemented from Ogre::Renderable.
bool Ogre::v1::SubEntity::getCastsShadows (void) const virtual
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented from Ogre::Renderable.
uint8 Ogre::Renderable::getCurrentMaterialLod (void) const inline inherited
References ARRAY_PACKED_REALS, and Ogre::LodStrategy::lodSet().
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
HlmsDatablock* Ogre::Renderable::getDatablock (void) const inline inherited
uint32 Ogre::Renderable::getHlmsCasterHash (void) const inline inherited
uint32 Ogre::Renderable::getHlmsHash (void) const inline inherited
size_t Ogre::v1::SubEntity::getIndexDataEndIndex () const
Returns the current value of the start index used for drawing.
size_t Ogre::v1::SubEntity::getIndexDataStartIndex () const
Returns the current value of the start index used for drawing.
See also
setIndexDataStartIndex
const LightList& Ogre::v1::SubEntity::getLights (void) const virtual
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
MaterialPtr Ogre::Renderable::getMaterial (void) const inherited
Retrieves the material this renderable object uses.
It may be null if it's using the HLMS. getDatablock
unsigned short Ogre::v1::SubEntity::getNumWorldTransforms (void) const virtual
Overridden - see Renderable.
Reimplemented from Ogre::Renderable.
Entity* Ogre::v1::SubEntity::getParent (void) const inline
Accessor to get parent Entity.
virtual bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline virtual inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
void Ogre::v1::SubEntity::getRenderOperation (RenderOperation & op, bool casterPass) virtual
Overridden - see Renderable.
Implements Ogre::Renderable.
uint8 Ogre::Renderable::getRenderQueueSubGroup (void) const inline inherited
References Ogre::NumVertexPass.
Real Ogre::v1::SubEntity::getSquaredViewDepth (const Camera * cam) const
Overridden, see Renderable.
SubMesh* Ogre::v1::SubEntity::getSubMesh (void) const
Accessor method to read mesh data.
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic (void) const inline virtual inherited
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix (void) const inline virtual inherited
Returns whether the world matrix is an identify matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
virtual OGRE_DEPRECATED const Any& Ogre::Renderable::getUserAny (void) const inline virtual inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const VertexArrayObjectArray& Ogre::Renderable::getVaos (VertexPass vertexPass) const inline inherited
VertexData* Ogre::v1::SubEntity::getVertexDataForBinding (bool casterPass)
Retrieve the VertexData which should be used for GPU binding.
void Ogre::v1::SubEntity::getWorldTransforms (Matrix4 * xform) const virtual
Overridden - see Renderable.
Implements Ogre::Renderable.
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
bool Ogre::Renderable::hasSkeletonAnimation (void) const inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::v1::BillboardChain.
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
void Ogre::v1::SubEntity::resetIndexDataStartEndIndex ()
Reset the custom start/end index to the default values.
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
virtual void Ogre::v1::SubEntity::setDatablock (HlmsDatablock * datablock) virtual
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented from Ogre::Renderable.
void Ogre::Renderable::setDatablock (IdString datablockName) inherited
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName) inherited
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
void Ogre::v1::SubEntity::setIndexDataEndIndex (size_t end_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
Default value is SubMesh::indexData::indexCount so that the entire index buffer is used when drawing. Valid values are mStartIndex to SubMesh::indexData::indexCount
void Ogre::v1::SubEntity::setIndexDataStartIndex (size_t start_index)
Tells this SubEntity to draw a subset of the SubMesh by adjusting the index buffer extents.
Default value is zero so that the entire index buffer is used when drawing. Valid values are zero to getIndexDataEndIndex()
virtual void Ogre::v1::SubEntity::setMaterial (const MaterialPtr & material) virtual
Sets a Material to be used.
Remarks
By default a SubEntity uses the default Material that the SubMesh uses. This call can alter that so that the Material is different for this instance.
Reimplemented from Ogre::Renderable.
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName) inherited
Sets the name of the Material to be used. Prefer using HLMS setHlms.
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline inherited
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits) RenderQueue
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
Friends And Related Function Documentation
friend class Entity friend
friend class SceneManager friend
Member Data Documentation
uint32 Ogre::Renderable::mHlmsGlobalIndex inherited
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
The documentation for this class was generated from the following file:
OgreSubEntity.h