OGRE: Ogre::v1::MetalHardwareBufferManagerBase Class Reference
Ogre::v1::MetalHardwareBufferManagerBase Class Reference
Implementation of HardwareBufferManager for Metal.
#include <OgreMetalHardwareBufferManager.h>
Public Types
enum BufferLicenseType { BLT_MANUAL_RELEASE, BLT_AUTOMATIC_RELEASE }
Public Member Functions
MetalHardwareBufferManagerBase (MetalDevice *device, VaoManager *vaoManager)
virtual ~MetalHardwareBufferManagerBase ()
void _addDirtyInputLayout (VertexDeclaration *vertexDecl)
Adds a vertex declaration tagged as dirty for us to process later and assign to it an ID shared by other VertexDeclarations with the same vertex formats.
virtual void _forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr &sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _forceReleaseBufferCopies (HardwareVertexBuffer *sourceBuffer)
Internal method that forces the release of copies of a given buffer.
virtual void _freeUnusedBufferCopies (void)
Free all unused vertex buffer copies.
MetalDiscardBufferManager * _getDiscardBufferManager (void)
void _notifyCounterBufferDestroyed (HardwareCounterBuffer *buf)
Notification that at hardware counter buffer has been destroyed.
void _notifyDeviceStalled (void)
void _notifyIndexBufferDestroyed (HardwareIndexBuffer *buf)
Notification that a hardware index buffer has been destroyed.
void _notifyUniformBufferDestroyed (HardwareUniformBuffer *buf)
Notification that at hardware uniform buffer has been destroyed.
void _notifyVertexBufferDestroyed (HardwareVertexBuffer *buf)
Notification that a hardware vertex buffer has been destroyed.
virtual void _releaseBufferCopies (bool forceFreeUnused=false)
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
void _removeInputLayoutReference (uint8 layoutId)
Gets called when the VertexDeclaration no longer matches the assigned shared layout.
virtual void _updateDirtyInputLayouts (void)
Updates all dirty layouts gathered via _addDirtyInputLayout.
virtual HardwareVertexBufferSharedPtr allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee *licensee, bool copyData=false)
Allocates a copy of a given vertex buffer.
virtual HardwareCounterBufferSharedPtr createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String &name="")
Create a counter buffer.
virtual HardwareIndexBufferSharedPtr createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Create an index buffer.
virtual RenderToVertexBufferSharedPtr createRenderToVertexBuffer (void)
Create a render to vertex buffer.
virtual HardwareUniformBufferSharedPtr createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String &name="")
Create a uniform buffer.
virtual HardwareVertexBufferSharedPtr createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer=false)
Creates a vertex buffer.
virtual VertexBufferBinding * createVertexBufferBinding (void)
Creates a new VertexBufferBinding.
virtual VertexDeclaration * createVertexDeclaration (void)
Creates a new vertex declaration.
virtual void destroyVertexBufferBinding (VertexBufferBinding *binding)
Destroys a VertexBufferBinding.
virtual void destroyVertexDeclaration (VertexDeclaration *decl)
Destroys a vertex declaration.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr &sourceBuffer, const HardwareVertexBufferSharedPtr &copy)
Registers a vertex buffer as a copy of another.
virtual void releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Manually release a vertex buffer copy for others to subsequently use.
virtual void touchVertexBufferCopy (const HardwareVertexBufferSharedPtr &bufferCopy)
Tell engine that the vertex buffer copy intent to reuse.
Detailed Description
Implementation of HardwareBufferManager for Metal.
Member Enumeration Documentation
BufferLicenseType
enum Ogre::v1::HardwareBufferManagerBase::BufferLicenseType inherited
Enumerator
BLT_MANUAL_RELEASE
Licensee will only release buffer when it says so.
BLT_AUTOMATIC_RELEASE
Licensee can have license revoked.
Constructor & Destructor Documentation
MetalHardwareBufferManagerBase()
Ogre::v1::MetalHardwareBufferManagerBase::MetalHardwareBufferManagerBase (MetalDevice * device, VaoManager * vaoManager)
~MetalHardwareBufferManagerBase()
virtual Ogre::v1::MetalHardwareBufferManagerBase::~MetalHardwareBufferManagerBase () virtual
Member Function Documentation
_addDirtyInputLayout()
void Ogre::v1::HardwareBufferManagerBase::_addDirtyInputLayout (VertexDeclaration * vertexDecl) inherited
Adds a vertex declaration tagged as dirty for us to process later and assign to it an ID shared by other VertexDeclarations with the same vertex formats.
For internal use.
Parameters
vertexDecl VertexDeclaration that is dirty. Don't call this twice (i.e. check the value of VertexDeclaration::mInputLayoutDirty before calling).
_forceReleaseBufferCopies() [1/2]
virtual void Ogre::v1::HardwareBufferManagerBase::_forceReleaseBufferCopies (const HardwareVertexBufferSharedPtr & sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a shared pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::_forceReleaseBufferCopies().
_forceReleaseBufferCopies() [2/2]
virtual void Ogre::v1::HardwareBufferManagerBase::_forceReleaseBufferCopies (HardwareVertexBuffer * sourceBuffer) virtual inherited
Internal method that forces the release of copies of a given buffer.
Remarks
This usually means that the buffer which the copies are based on has been changed in some fundamental way, and the owner of the original wishes to make that known so that new copies will reflect the changes.
Parameters
sourceBuffer The source buffer as a pointer. Any buffer copies created from the source buffer are deleted.
Reimplemented in Ogre::v1::HardwareBufferManager.
_freeUnusedBufferCopies()
virtual void Ogre::v1::HardwareBufferManagerBase::_freeUnusedBufferCopies (void) virtual inherited
Free all unused vertex buffer copies.
Remarks
This method free all temporary vertex buffers that not in used. In normally, temporary vertex buffers are subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction. But in some cases you want to free them to save hardware memory (e.g. application was runs in a long time, you might free temporary buffers periodically to avoid memory overload).
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::_freeUnusedBufferCopies().
_getDiscardBufferManager()
MetalDiscardBufferManager* Ogre::v1::MetalHardwareBufferManagerBase::_getDiscardBufferManager (void) inline
_notifyCounterBufferDestroyed()
void Ogre::v1::HardwareBufferManagerBase::_notifyCounterBufferDestroyed (HardwareCounterBuffer * buf) inherited
Notification that at hardware counter buffer has been destroyed.
Referenced by Ogre::v1::HardwareBufferManager::_notifyConterBufferDestroyed().
_notifyDeviceStalled()
void Ogre::v1::MetalHardwareBufferManagerBase::_notifyDeviceStalled (void)
_notifyIndexBufferDestroyed()
void Ogre::v1::HardwareBufferManagerBase::_notifyIndexBufferDestroyed (HardwareIndexBuffer * buf) inherited
Notification that a hardware index buffer has been destroyed.
Referenced by Ogre::v1::HardwareBufferManager::_notifyIndexBufferDestroyed().
_notifyUniformBufferDestroyed()
void Ogre::v1::HardwareBufferManagerBase::_notifyUniformBufferDestroyed (HardwareUniformBuffer * buf) inherited
Notification that at hardware uniform buffer has been destroyed.
Referenced by Ogre::v1::HardwareBufferManager::_notifyUniformBufferDestroyed().
_notifyVertexBufferDestroyed()
void Ogre::v1::HardwareBufferManagerBase::_notifyVertexBufferDestroyed (HardwareVertexBuffer * buf) inherited
Notification that a hardware vertex buffer has been destroyed.
Referenced by Ogre::v1::HardwareBufferManager::_notifyVertexBufferDestroyed().
_releaseBufferCopies()
virtual void Ogre::v1::HardwareBufferManagerBase::_releaseBufferCopies (bool forceFreeUnused = false) virtual inherited
Internal method for releasing all temporary buffers which have been allocated using BLT_AUTOMATIC_RELEASE; is called by OGRE.
Parameters
forceFreeUnused If true, free all unused temporary buffers. If false, auto detect and free all unused temporary buffers based on temporary buffers utilization.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::_releaseBufferCopies().
_removeInputLayoutReference()
void Ogre::v1::HardwareBufferManagerBase::_removeInputLayoutReference (uint8 layoutId) inherited
Gets called when the VertexDeclaration no longer matches the assigned shared layout.
_updateDirtyInputLayouts()
virtual void Ogre::v1::HardwareBufferManagerBase::_updateDirtyInputLayouts (void) virtual inherited
Updates all dirty layouts gathered via _addDirtyInputLayout.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::_updateDirtyInputLayouts().
allocateVertexBufferCopy()
virtual HardwareVertexBufferSharedPtr Ogre::v1::HardwareBufferManagerBase::allocateVertexBufferCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, BufferLicenseType licenseType, HardwareBufferLicensee * licensee, bool copyData = false) virtual inherited
Allocates a copy of a given vertex buffer.
Remarks
This method allocates a temporary copy of an existing vertex buffer. This buffer is subsequently stored and can be made available for other purposes later without incurring the cost of construction / destruction.
Parameters
sourceBuffer The source buffer to use as a copy.
licenseType The type of license required on this buffer - automatic release causes this class to release licenses every frame so that they can be reallocated anew.
licensee Pointer back to the class requesting the copy, which must implement HardwareBufferLicense in order to be notified when the license expires.
copyData If true, the current data is copied as well as the structure of the buffer/
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::allocateVertexBufferCopy().
createCounterBuffer()
virtual HardwareCounterBufferSharedPtr Ogre::v1::MetalHardwareBufferManagerBase::createCounterBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String & name = "") virtual
Create a counter buffer.
Implements Ogre::v1::HardwareBufferManagerBase.
createIndexBuffer()
virtual HardwareIndexBufferSharedPtr Ogre::v1::MetalHardwareBufferManagerBase::createIndexBuffer (HardwareIndexBuffer::IndexType itype, size_t numIndexes, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Create an index buffer.
Implements Ogre::v1::HardwareBufferManagerBase.
createRenderToVertexBuffer()
virtual RenderToVertexBufferSharedPtr Ogre::v1::MetalHardwareBufferManagerBase::createRenderToVertexBuffer (void) virtual
Create a render to vertex buffer.
Implements Ogre::v1::HardwareBufferManagerBase.
createUniformBuffer()
virtual HardwareUniformBufferSharedPtr Ogre::v1::MetalHardwareBufferManagerBase::createUniformBuffer (size_t sizeBytes, HardwareBuffer::Usage usage, bool useShadowBuffer, const String & name = "") virtual
Create a uniform buffer.
Implements Ogre::v1::HardwareBufferManagerBase.
createVertexBuffer()
virtual HardwareVertexBufferSharedPtr Ogre::v1::MetalHardwareBufferManagerBase::createVertexBuffer (size_t vertexSize, size_t numVerts, HardwareBuffer::Usage usage, bool useShadowBuffer = false) virtual
Creates a vertex buffer.
Implements Ogre::v1::HardwareBufferManagerBase.
createVertexBufferBinding()
virtual VertexBufferBinding* Ogre::v1::HardwareBufferManagerBase::createVertexBufferBinding (void) virtual inherited
Creates a new VertexBufferBinding.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::createVertexBufferBinding().
createVertexDeclaration()
virtual VertexDeclaration* Ogre::v1::HardwareBufferManagerBase::createVertexDeclaration (void) virtual inherited
Creates a new vertex declaration.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::createVertexDeclaration().
destroyVertexBufferBinding()
virtual void Ogre::v1::HardwareBufferManagerBase::destroyVertexBufferBinding (VertexBufferBinding * binding) virtual inherited
Destroys a VertexBufferBinding.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::destroyVertexBufferBinding().
destroyVertexDeclaration()
virtual void Ogre::v1::HardwareBufferManagerBase::destroyVertexDeclaration (VertexDeclaration * decl) virtual inherited
Destroys a vertex declaration.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::destroyVertexDeclaration().
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
registerVertexBufferSourceAndCopy()
virtual void Ogre::v1::HardwareBufferManagerBase::registerVertexBufferSourceAndCopy (const HardwareVertexBufferSharedPtr & sourceBuffer, const HardwareVertexBufferSharedPtr & copy) virtual inherited
Registers a vertex buffer as a copy of another.
Remarks
This is useful for registering an existing buffer as a temporary buffer which can be allocated just like a copy.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::registerVertexBufferSourceAndCopy().
releaseVertexBufferCopy()
virtual void Ogre::v1::HardwareBufferManagerBase::releaseVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Manually release a vertex buffer copy for others to subsequently use.
Remarks
Only required if the original call to allocateVertexBufferCopy included a licenseType of BLT_MANUAL_RELEASE.
Parameters
bufferCopy The buffer copy. The caller is expected to delete or at least no longer use this reference, since another user may well begin to modify the contents of the buffer.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::releaseVertexBufferCopy().
touchVertexBufferCopy()
virtual void Ogre::v1::HardwareBufferManagerBase::touchVertexBufferCopy (const HardwareVertexBufferSharedPtr & bufferCopy) virtual inherited
Tell engine that the vertex buffer copy intent to reuse.
Remarks
Ogre internal keep an expired delay counter of BLT_AUTOMATIC_RELEASE buffers, when the counter count down to zero, it'll release for other purposes later. But you can use this function to reset the counter to the internal configured value, keep the buffer not get released for some frames.
Parameters
bufferCopy The buffer copy. The caller is expected to keep this buffer copy for use.
Reimplemented in Ogre::v1::HardwareBufferManager.
Referenced by Ogre::v1::HardwareBufferManager::touchVertexBufferCopy().
The documentation for this class was generated from the following file:
OgreMetalHardwareBufferManager.h