OGRE: Ogre::FactoryObj< T > Class Template Reference
Ogre::FactoryObj< T > Class Template Reference abstract
Core » General
Abstract factory class.
#include <OgreFactoryObj.h>
Public Member Functions
virtual ~FactoryObj ()
virtual T * createInstance (const String &name)=0
Creates a new object.
virtual void destroyInstance (T *ptr)=0
Destroys an object which was created by this factory.
virtual const String & getType () const =0
Returns the factory type.
Detailed Description
template<typename T>
class Ogre::FactoryObj< T >
Abstract factory class.
Does nothing by itself, but derived classes can add functionality.
Constructor & Destructor Documentation
template<typename T> virtual Ogre::FactoryObj< T >::~FactoryObj () inline virtual
Member Function Documentation
template<typename T> virtual T* Ogre::FactoryObj< T >::createInstance (const String & name) pure virtual
Creates a new object.
Parameters
name Name of the object to create
Returns
An object created by the factory. The type of the object depends on the factory.
Implemented in Ogre::v1::BillboardParticleRendererFactory, and Ogre::ArchiveFactory.
Referenced by Ogre::FactoryObj< ParticleSystemRenderer >::~FactoryObj().
template<typename T> virtual void Ogre::FactoryObj< T >::destroyInstance (T * ptr) pure virtual
Destroys an object which was created by this factory.
Parameters
ptr Pointer to the object to destroy
Implemented in Ogre::v1::BillboardParticleRendererFactory, Ogre::FileSystemArchiveFactory, Ogre::ZipArchiveFactory, and Ogre::APKFileSystemArchiveFactory.
Referenced by Ogre::FactoryObj< ParticleSystemRenderer >::~FactoryObj().
template<typename T> virtual const String& Ogre::FactoryObj< T >::getType () const pure virtual
Returns the factory type.
Returns
The factory type.
Implemented in Ogre::v1::BillboardParticleRendererFactory, Ogre::EmbeddedZipArchiveFactory, Ogre::FileSystemArchiveFactory, Ogre::ZipArchiveFactory, Ogre::APKFileSystemArchiveFactory, and Ogre::APKZipArchiveFactory.
Referenced by Ogre::FactoryObj< ParticleSystemRenderer >::~FactoryObj().
The documentation for this class was generated from the following file:
OgreFactoryObj.h