OGRE: Ogre::AnyNumeric Class Reference
Ogre::AnyNumeric Class Reference
Core » General
Specialised Any class which has built in arithmetic operators, but can hold only types which support operator +,-,* and / .
#include <OgreAny.h>
Public Member Functions
AnyNumeric ()
template<typename ValueType >
AnyNumeric (const ValueType &value)
AnyNumeric (const AnyNumeric &other)
void destroy ()
template<typename ValueType >
ValueType get (void) const
const std::type_info & getType () const
bool has_value () const
bool isEmpty () const
template<typename ValueType >
ValueType operator() () const
AnyNumeric operator* (const AnyNumeric &rhs) const
AnyNumeric operator* (Real factor) const
AnyNumeric & operator*= (const AnyNumeric &rhs)
AnyNumeric operator+ (const AnyNumeric &rhs) const
AnyNumeric & operator+= (const AnyNumeric &rhs)
AnyNumeric operator- (const AnyNumeric &rhs) const
AnyNumeric & operator-= (const AnyNumeric &rhs)
AnyNumeric operator/ (const AnyNumeric &rhs) const
AnyNumeric & operator/= (const AnyNumeric &rhs)
AnyNumeric & operator= (const AnyNumeric &rhs)
void reset ()
Any & swap (Any &rhs)
const std::type_info & type () const
Detailed Description
Specialised Any class which has built in arithmetic operators, but can hold only types which support operator +,-,* and / .
Constructor & Destructor Documentation
AnyNumeric() [1/3]
Ogre::AnyNumeric::AnyNumeric () inline
Referenced by operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), and operator=().
AnyNumeric() [2/3]
template<typename ValueType > Ogre::AnyNumeric::AnyNumeric (const ValueType & value) inline
References Ogre::MEMCATEGORY_GENERAL, and OGRE_NEW_T.
AnyNumeric() [3/3]
Ogre::AnyNumeric::AnyNumeric (const AnyNumeric & other) inline
Member Function Documentation
destroy()
void Ogre::Any::destroy () inline inherited
Deprecated:
use reset() instead
References Ogre::Any::reset().
Referenced by Ogre::WorkQueue::Response::abortRequest().
get()
template<typename ValueType > ValueType Ogre::Any::get (void) const inline inherited
Deprecated:
use Ogre::any_cast instead
References Ogre::Any::any_cast.
getType()
const std::type_info& Ogre::Any::getType (void) const inline inherited
Deprecated:
use type() instead
References Ogre::Any::type().
has_value()
bool Ogre::Any::has_value () const inline inherited
Referenced by Ogre::Any::isEmpty().
isEmpty()
bool Ogre::Any::isEmpty () const inline inherited
Deprecated:
use has_value() instead
References Ogre::Any::has_value().
operator()()
template<typename ValueType > ValueType Ogre::Any::operator() () const inline inherited
Deprecated:
use Ogre::any_cast instead
References Ogre::Any::any_cast.
operator*() [1/2]
AnyNumeric Ogre::AnyNumeric::operator* (const AnyNumeric & rhs) const inline
References AnyNumeric().
operator*() [2/2]
AnyNumeric Ogre::AnyNumeric::operator* (Real factor) const inline
References AnyNumeric().
operator*=()
AnyNumeric& Ogre::AnyNumeric::operator*= (const AnyNumeric & rhs) inline
References AnyNumeric().
operator+()
AnyNumeric Ogre::AnyNumeric::operator+ (const AnyNumeric & rhs) const inline
References AnyNumeric().
operator+=()
AnyNumeric& Ogre::AnyNumeric::operator+= (const AnyNumeric & rhs) inline
References AnyNumeric().
operator-()
AnyNumeric Ogre::AnyNumeric::operator- (const AnyNumeric & rhs) const inline
References AnyNumeric().
operator-=()
AnyNumeric& Ogre::AnyNumeric::operator-= (const AnyNumeric & rhs) inline
References AnyNumeric().
operator/()
AnyNumeric Ogre::AnyNumeric::operator/ (const AnyNumeric & rhs) const inline
References AnyNumeric().
operator/=()
AnyNumeric& Ogre::AnyNumeric::operator/= (const AnyNumeric & rhs) inline
References AnyNumeric().
operator=()
AnyNumeric& Ogre::AnyNumeric::operator= (const AnyNumeric & rhs) inline
References AnyNumeric().
reset()
void Ogre::Any::reset () inline inherited
References Ogre::MEMCATEGORY_GENERAL, and OGRE_DELETE_T.
Referenced by Ogre::Any::destroy(), and Ogre::Any::~Any().
swap()
Any& Ogre::Any::swap (Any & rhs) inline inherited
References std::swap().
type()
const std::type_info& Ogre::Any::type () const inline inherited
Referenced by Ogre::any_cast(), and Ogre::Any::getType().
The documentation for this class was generated from the following file:
OgreAny.h