OGRE: Ogre::GLES2StateCacheManagerImp Class Reference
Ogre::GLES2StateCacheManagerImp Class Reference
An in memory cache of the OpenGL ES state.
#include <OgreGLES2StateCacheManagerImp.h>
Public Member Functions
GLES2StateCacheManagerImp (void)
GLES2StateCacheManagerImp (void)
~GLES2StateCacheManagerImp (void)
~GLES2StateCacheManagerImp (void)
bool activateGLTextureUnit (unsigned char unit)
See GLES2StateCacheManager.activateGLTextureUnit.
bool activateGLTextureUnit (size_t unit)
See GLES2StateCacheManager.activateGLTextureUnit.
void bindGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLES2StateCacheManager.bindGLBuffer.
void bindGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLES2StateCacheManager.bindGLBuffer.
void bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void clearCache ()
See GLES2StateCacheManager.clearCache.
void clearCache ()
See GLES2StateCacheManager.clearCache.
void deleteGLBuffer (GLenum target, GLuint buffer, bool force=false)
See GLES2StateCacheManager.deleteGLBuffer.
void deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach=0, bool force=false)
See GLES2StateCacheManager.deleteGLBuffer.
GLenum getBlendEquation (void) const
See GLES2StateCacheManager.getBlendEquation.
GLenum getBlendEquation (void) const
See GLES2StateCacheManager.getBlendEquation.
GLclampf getClearDepth (void) const
See GLES2StateCacheManager.getClearDepth.
GLclampf getClearDepth (void) const
See GLES2StateCacheManager.getClearDepth.
vector< GLboolean >::type & getColourMask (void)
See GLES2StateCacheManager.getColourMask.
vector< GLboolean >::type & getColourMask (void)
See GLES2StateCacheManager.getColourMask.
GLenum getDepthFunc (void) const
See GLES2StateCacheManager.getDepthFunc.
GLenum getDepthFunc (void) const
See GLES2StateCacheManager.getDepthFunc.
GLboolean getDepthMask (void) const
See GLES2StateCacheManager.getDepthMask.
GLboolean getDepthMask (void) const
See GLES2StateCacheManager.getDepthMask.
unsigned int getDiscardBuffers (void) const
See GLES2StateCacheManager.getDiscardBuffers.
unsigned int getDiscardBuffers (void) const
See GLES2StateCacheManager.getDiscardBuffers.
GLuint getStencilMask (void) const
See GLES2StateCacheManager.getStencilMask.
GLuint getStencilMask (void) const
See GLES2StateCacheManager.getStencilMask.
void getTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
See GLES2StateCacheManager.getTexParameterfv.
void getTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
See GLES2StateCacheManager.getTexParameterfv.
void initializeCache ()
See GLES2StateCacheManager.initializeCache.
void initializeCache ()
See GLES2StateCacheManager.initializeCache.
void invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void setDiscardBuffers (unsigned int flags)
See GLES2StateCacheManager.setDiscardBuffers.
void setDiscardBuffers (unsigned int flags)
See GLES2StateCacheManager.setDiscardBuffers.
void setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
void setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
Detailed Description
An in memory cache of the OpenGL ES state.
An in memory cache of the OpenGL ES2 state.
See also
GLES2StateCacheManager
Constructor & Destructor Documentation
Ogre::GLES2StateCacheManagerImp::GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::~GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::GLES2StateCacheManagerImp (void)
Ogre::GLES2StateCacheManagerImp::~GLES2StateCacheManagerImp (void)
Member Function Documentation
bool Ogre::GLES2StateCacheManagerImp::activateGLTextureUnit (unsigned char unit)
See GLES2StateCacheManager.activateGLTextureUnit.
bool Ogre::GLES2StateCacheManagerImp::activateGLTextureUnit (size_t unit)
See GLES2StateCacheManager.activateGLTextureUnit.
void Ogre::GLES2StateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLES2StateCacheManager.bindGLBuffer.
void Ogre::GLES2StateCacheManagerImp::bindGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLES2StateCacheManager.bindGLBuffer.
void Ogre::GLES2StateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void Ogre::GLES2StateCacheManagerImp::bindGLTexture (GLenum target, GLuint texture)
See GLES2StateCacheManager.bindGLTexture.
void Ogre::GLES2StateCacheManagerImp::clearCache ()
See GLES2StateCacheManager.clearCache.
void Ogre::GLES2StateCacheManagerImp::clearCache ()
See GLES2StateCacheManager.clearCache.
void Ogre::GLES2StateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, bool force = false)
See GLES2StateCacheManager.deleteGLBuffer.
void Ogre::GLES2StateCacheManagerImp::deleteGLBuffer (GLenum target, GLuint buffer, GLenum attach = 0, bool force = false)
See GLES2StateCacheManager.deleteGLBuffer.
GLenum Ogre::GLES2StateCacheManagerImp::getBlendEquation (void) const inline
See GLES2StateCacheManager.getBlendEquation.
References setBlendEquation(), and setBlendFunc().
GLenum Ogre::GLES2StateCacheManagerImp::getBlendEquation (void) const inline
See GLES2StateCacheManager.getBlendEquation.
GLclampf Ogre::GLES2StateCacheManagerImp::getClearDepth (void) const inline
See GLES2StateCacheManager.getClearDepth.
References setClearColour(), and setClearDepth().
GLclampf Ogre::GLES2StateCacheManagerImp::getClearDepth (void) const inline
See GLES2StateCacheManager.getClearDepth.
vector<GLboolean>::type& Ogre::GLES2StateCacheManagerImp::getColourMask (void) inline
See GLES2StateCacheManager.getColourMask.
References setColourMask().
vector<GLboolean>::type& Ogre::GLES2StateCacheManagerImp::getColourMask (void) inline
See GLES2StateCacheManager.getColourMask.
GLenum Ogre::GLES2StateCacheManagerImp::getDepthFunc (void) const inline
See GLES2StateCacheManager.getDepthFunc.
References setDepthFunc().
GLenum Ogre::GLES2StateCacheManagerImp::getDepthFunc (void) const inline
See GLES2StateCacheManager.getDepthFunc.
GLboolean Ogre::GLES2StateCacheManagerImp::getDepthMask (void) const inline
See GLES2StateCacheManager.getDepthMask.
References setDepthMask().
GLboolean Ogre::GLES2StateCacheManagerImp::getDepthMask (void) const inline
See GLES2StateCacheManager.getDepthMask.
unsigned int Ogre::GLES2StateCacheManagerImp::getDiscardBuffers (void) const inline
See GLES2StateCacheManager.getDiscardBuffers.
unsigned int Ogre::GLES2StateCacheManagerImp::getDiscardBuffers (void) const inline
See GLES2StateCacheManager.getDiscardBuffers.
GLuint Ogre::GLES2StateCacheManagerImp::getStencilMask (void) const inline
See GLES2StateCacheManager.getStencilMask.
References setDisabled(), setEnabled(), setStencilMask(), setVertexAttribDisabled(), and setVertexAttribEnabled().
GLuint Ogre::GLES2StateCacheManagerImp::getStencilMask (void) const inline
See GLES2StateCacheManager.getStencilMask.
void Ogre::GLES2StateCacheManagerImp::getTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
See GLES2StateCacheManager.getTexParameterfv.
void Ogre::GLES2StateCacheManagerImp::getTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
See GLES2StateCacheManager.getTexParameterfv.
void Ogre::GLES2StateCacheManagerImp::initializeCache ()
See GLES2StateCacheManager.initializeCache.
void Ogre::GLES2StateCacheManagerImp::initializeCache ()
See GLES2StateCacheManager.initializeCache.
void Ogre::GLES2StateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
void Ogre::GLES2StateCacheManagerImp::invalidateStateForTexture (GLuint texture)
See GLES2StateCacheManager.invalidateStateForTexture.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
void Ogre::GLES2StateCacheManagerImp::setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
Referenced by getBlendEquation().
void Ogre::GLES2StateCacheManagerImp::setBlendEquation (GLenum eq)
See GLES2StateCacheManager.setBlendEquation.
void Ogre::GLES2StateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
Referenced by getBlendEquation().
void Ogre::GLES2StateCacheManagerImp::setBlendFunc (GLenum source, GLenum dest)
See GLES2StateCacheManager.setBlendFunc.
void Ogre::GLES2StateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
Referenced by getClearDepth().
void Ogre::GLES2StateCacheManagerImp::setClearColour (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
See GLES2StateCacheManager.setClearColour.
void Ogre::GLES2StateCacheManagerImp::setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
Referenced by getClearDepth().
void Ogre::GLES2StateCacheManagerImp::setClearDepth (GLclampf depth)
See GLES2StateCacheManager.setClearDepth.
void Ogre::GLES2StateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
Referenced by getColourMask().
void Ogre::GLES2StateCacheManagerImp::setColourMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
See GLES2StateCacheManager.setColourMask.
void Ogre::GLES2StateCacheManagerImp::setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
Referenced by getDepthFunc().
void Ogre::GLES2StateCacheManagerImp::setDepthFunc (GLenum func)
See GLES2StateCacheManager.setDepthFunc.
void Ogre::GLES2StateCacheManagerImp::setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
Referenced by getDepthMask().
void Ogre::GLES2StateCacheManagerImp::setDepthMask (GLboolean mask)
See GLES2StateCacheManager.setDepthMask.
void Ogre::GLES2StateCacheManagerImp::setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setDisabled (GLenum flag)
See GLES2StateCacheManager.setDisabled.
void Ogre::GLES2StateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLES2StateCacheManager.setDiscardBuffers.
void Ogre::GLES2StateCacheManagerImp::setDiscardBuffers (unsigned int flags) inline
See GLES2StateCacheManager.setDiscardBuffers.
void Ogre::GLES2StateCacheManagerImp::setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setEnabled (GLenum flag)
See GLES2StateCacheManager.setEnabled.
void Ogre::GLES2StateCacheManagerImp::setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setStencilMask (GLuint mask)
See GLES2StateCacheManager.setStencilMask.
void Ogre::GLES2StateCacheManagerImp::setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void Ogre::GLES2StateCacheManagerImp::setTexParameterf (GLenum target, GLenum pname, GLfloat params)
See GLES2StateCacheManager.setTexParameterf.
void Ogre::GLES2StateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void Ogre::GLES2StateCacheManagerImp::setTexParameteri (GLenum target, GLenum pname, GLint param)
See GLES2StateCacheManager.setTexParameteri.
void Ogre::GLES2StateCacheManagerImp::setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setVertexAttribDisabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribDisabled.
void Ogre::GLES2StateCacheManagerImp::setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
Referenced by getStencilMask().
void Ogre::GLES2StateCacheManagerImp::setVertexAttribEnabled (GLuint attrib)
See GLES2StateCacheManager.setVertexAttribEnabled.
The documentation for this class was generated from the following files:
OgreGLES2NullStateCacheManagerImp.h
OgreGLES2StateCacheManagerImp.h