OGRE: Ogre::Material Class Reference
Ogre::Material Class Reference
Core » Materials
Class encapsulates rendering properties of an object.
#include <OgreMaterial.h>
Public Types
enum LoadingState {
LOADSTATE_UNLOADED, LOADSTATE_LOADING, LOADSTATE_LOADED, LOADSTATE_UNLOADING,
LOADSTATE_PREPARED, LOADSTATE_PREPARING
}
Enum identifying the loading state of the resource.
typedef FastArray< Real > LodValueArray
distance list used to specify LOD
typedef ConstVectorIterator< LodValueArray > LodValueIterator
typedef VectorIterator< Techniques > TechniqueIterator
Public Member Functions
Material (ResourceManager *creator, const String &name, ResourceHandle handle, const String &group, bool isManual=false, ManualResourceLoader *loader=0)
Constructor - use resource manager's create method rather than this.
~Material ()
virtual void _dirtyState ()
Manually mark the state of this resource as having been changed.
virtual void _fireLoadingComplete (bool wasBackgroundLoaded)
Firing of loading complete event.
virtual void _firePreparingComplete (bool wasBackgroundLoaded)
Firing of preparing complete event.
virtual void _fireUnloadingComplete (void)
Firing of unloading complete event.
const LodValueArray * _getLodValues (void) const
void _notifyNeedsRecompile (void)
Tells the material that it needs recompilation.
virtual void _notifyOrigin (const String &origin)
Notify this resource of it's origin.
virtual void addListener (Listener *lis)
Register a listener on this resource.
bool applyTextureAliases (const AliasTextureNamePairList &aliasList, const bool apply=true) const
Applies texture names to Texture Unit State with matching texture name aliases.
virtual void changeGroupOwnership (const String &newGroup)
Change the resource group ownership of a Resource.
MaterialPtr clone (const String &newName, bool changeGroup=false, const String &newGroup=BLANKSTRING) const
Creates a new copy of this material with the same settings but a new name.
void compile (bool autoManageTextureUnits=true)
'Compiles' this Material.
void copyDetailsTo (MaterialPtr &mat) const
Copies the details of this material into another, preserving the target's handle and name (unlike operator=) but copying everything else.
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
Technique * createTechnique (void)
Creates a new Technique for this Material.
virtual void escalateLoading ()
Escalates the loading of a background loaded resource.
Technique * getBestTechnique (unsigned short lodIndex=0, const Renderable *rend=0)
Gets the best supported technique.
bool getCompilationRequired () const
Gets the compilation status of the material.
virtual ResourceManager * getCreator (void)
Gets the manager which created this resource.
virtual const String & getGroup (void) const
Gets the group which this resource is a member of.
virtual ResourceHandle getHandle (void) const
virtual LoadingState getLoadingState () const
Returns the current loading state.
LodValueIterator getLodValueIterator (void) const
Gets an iterator over the list of values transformed by the LodStrategy at which each LOD comes into effect.
virtual const String & getName (void) const
Gets resource name.
unsigned short getNumLodLevels (unsigned short schemeIndex) const
Gets the number of levels-of-detail this material has in the given scheme, based on Technique::setLodIndex.
unsigned short getNumLodLevels (const String &schemeName) const
Gets the number of levels-of-detail this material has in the given scheme, based on Technique::setLodIndex.
unsigned short getNumSupportedTechniques (void) const
Retrieves the number of supported techniques.
unsigned short getNumTechniques (void) const
Retrieves the number of techniques.
virtual const String & getOrigin (void) const
Get the origin of this resource, e.g.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
bool getReceiveShadows (void) const
Returns whether or not objects using this material will receive shadows.
virtual size_t getSize (void) const
Retrieves info about the size of the resource.
virtual size_t getStateCount () const
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Technique * getSupportedTechnique (unsigned short index)
Gets the indexed supported technique.
TechniqueIterator getSupportedTechniqueIterator (void)
Gets an iterator over all the Techniques which are supported by the current card.
Technique * getTechnique (unsigned short index)
Gets the indexed technique.
Technique * getTechnique (const String &name)
searches for the named technique.
TechniqueIterator getTechniqueIterator (void)
Get an iterator over the Techniques in this Material.
bool getTransparencyCastsShadows (void) const
Returns whether or not objects using this material be classified as opaque to the shadow caster system.
const String & getUnsupportedTechniquesExplanation () const
Gets a string explaining why any techniques are not supported.
LodValueIterator getUserLodValueIterator (void) const
Gets an iterator over the user-defined list of values which are internally transfomed by the LodStrategy.
virtual bool isBackgroundLoaded (void) const
Returns whether this Resource has been earmarked for background loading.
virtual bool isLoaded (void) const
Returns true if the Resource has been loaded, false otherwise.
virtual bool isLoading () const
Returns whether the resource is currently in the process of background loading.
virtual bool isManuallyLoaded (void) const
Is this resource manually loaded?
virtual bool isPrepared (void) const
Returns true if the Resource has been prepared, false otherwise.
virtual bool isReloadable (void) const
Returns true if the Resource is reloadable, false otherwise.
bool isTransparent (void) const
Determines if the material has any transparency with the rest of the scene (derived from whether any Techniques say they involve transparency).
virtual void load (bool backgroundThread=false)
Loads the resource, if it is not already.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
Material & operator= (const Material &rhs)
Assignment operator to allow easy copying between materials.
virtual void prepare (bool backgroundThread=false)
Prepares the resource for load, if it is not already.
virtual void reload (void)
Reloads the resource, if it is already loaded.
void removeAllTechniques (void)
Removes all the techniques in this Material.
virtual void removeListener (Listener *lis)
Remove a listener on this resource.
void removeTechnique (unsigned short index)
Removes the technique at the given index.
void setAmbient (Real red, Real green, Real blue)
Sets the ambient colour reflectance properties for every Pass in every Technique.
void setAmbient (const ColourValue &ambient)
Sets the ambient colour reflectance properties for every Pass in every Technique.
virtual void setBackgroundLoaded (bool bl)
Tells the resource whether it is background loaded or not.
void setBlendblock (const HlmsBlendblock &blendblock)
Sets the blendbock to every pass.
void setColourWriteEnabled (bool enabled)
Sets whether or not colour buffer writing is enabled for each Pass.
void setDiffuse (Real red, Real green, Real blue, Real alpha)
Sets the diffuse colour reflectance properties of every Pass in every Technique.
void setDiffuse (const ColourValue &diffuse)
Sets the diffuse colour reflectance properties of every Pass in every Technique.
void setFog (bool overrideScene, FogMode mode=FOG_NONE, const ColourValue &colour=ColourValue::White, Real expDensity=0.001, Real linearStart=0.0, Real linearEnd=1.0)
Sets the fogging mode applied to each pass.
void setLodLevels (const LodValueArray &lodValues)
Sets the distance at which level-of-detail (LOD) levels come into effect.
void setMacroblock (const HlmsMacroblock &macroblock)
Sets the macroblock for all passes.
virtual void setManuallyLoaded (bool isManual)
Set "Is this resource manually loaded?".
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
void setPointSize (Real ps)
Sets the point size properties for every Pass in every Technique.
void setReceiveShadows (bool enabled)
Sets whether objects using this material will receive shadows.
void setSamplerblock (const HlmsSamplerblock &samplerblock)
Set samplerblock for every texture unit in every Technique and Pass.
void setSelfIllumination (Real red, Real green, Real blue)
Sets the amount of self-illumination of every Pass in every Technique.
void setSelfIllumination (const ColourValue &selfIllum)
Sets the amount of self-illumination of every Pass in every Technique.
void setShadingMode (ShadeOptions mode)
Sets the type of light shading required.
void setShininess (Real val)
Sets the shininess properties of every Pass in every Technique.
void setSpecular (Real red, Real green, Real blue, Real alpha)
Sets the specular colour reflectance properties of every Pass in every Technique.
void setSpecular (const ColourValue &specular)
Sets the specular colour reflectance properties of every Pass in every Technique.
virtual void setToLoaded (void)
Change the Resource loading state to loaded.
void setTransparencyCastsShadows (bool enabled)
Sets whether objects using this material be classified as opaque to the shadow caster system.
void touch (void)
'Touches' the resource to indicate it has been used.
virtual void unload (void)
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
OGRE_AUTO_MUTEX
Friends
class MaterialManager
class SceneManager
Detailed Description
Class encapsulates rendering properties of an object.
Remarks
Ogre's material class encapsulates ALL aspects of the visual appearance, of an object. It also includes other flags which might not be traditionally thought of as material properties such as culling modes and depth buffer settings, but these affect the appearance of the rendered object and are convenient to attach to the material since it keeps all the settings in one place. This is different to Direct3D which treats a material as just the colour components (diffuse, specular) and not texture maps etc. An Ogre Material can be thought of as equivalent to a 'Shader'.
A Material can be rendered in multiple different ways depending on the hardware available. You may configure a Material to use high-complexity fragment shaders, but these won't work on every card; therefore a Technique is an approach to creating the visual effect you are looking for. You are advised to create fallback techniques with lower hardware requirements if you decide to use advanced features. In addition, you also might want lower-detail techniques for distant geometry.
Each technique can be made up of multiple passes. A fixed-function pass may combine multiple texture layers using multitexturing, but Ogre can break that into multiple passes automatically if the active card cannot handle that many simultaneous textures. Programmable passes, however, cannot be split down automatically, so if the active graphics card cannot handle the technique which contains these passes, OGRE will try to find another technique which the card can do. If, at the end of the day, the card cannot handle any of the techniques which are listed for the material, the engine will render the geometry plain white, which should alert you to the problem.
Ogre comes configured with a number of default settings for a newly created material. These can be changed if you wish by retrieving the default material settings through SceneManager::getDefaultMaterialSettings. Any changes you make to the Material returned from this method will apply to any materials created from this point onward.
Member Typedef Documentation
LodValueArray
typedef FastArray<Real> Ogre::Material::LodValueArray
distance list used to specify LOD
LodValueIterator
typedef ConstVectorIterator<LodValueArray> Ogre::Material::LodValueIterator
TechniqueIterator
typedef VectorIterator<Techniques> Ogre::Material::TechniqueIterator
Member Enumeration Documentation
LoadingState
enum Ogre::Resource::LoadingState inherited
Enum identifying the loading state of the resource.
Enumerator
LOADSTATE_UNLOADED
Not loaded.
LOADSTATE_LOADING
Loading is in progress.
LOADSTATE_LOADED
Fully loaded.
LOADSTATE_UNLOADING
Currently unloading.
LOADSTATE_PREPARED
Fully prepared.
LOADSTATE_PREPARING
Preparing is in progress.
Constructor & Destructor Documentation
Material()
Ogre::Material::Material (ResourceManager * creator, const String & name, ResourceHandle handle, const String & group, bool isManual = false, ManualResourceLoader * loader = 0)
Constructor - use resource manager's create method rather than this.
~Material()
Ogre::Material::~Material ()
Member Function Documentation
_dirtyState()
virtual void Ogre::Resource::_dirtyState () virtual inherited
Manually mark the state of this resource as having been changed.
Remarks
You only need to call this from outside if you explicitly want derived objects to think this object has changed.
See also
getStateCount.
_fireLoadingComplete()
virtual void Ogre::Resource::_fireLoadingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of loading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_firePreparingComplete()
virtual void Ogre::Resource::_firePreparingComplete (bool wasBackgroundLoaded) virtual inherited
Firing of preparing complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
Parameters
wasBackgroundLoaded Whether this was a background loaded event
_fireUnloadingComplete()
virtual void Ogre::Resource::_fireUnloadingComplete (void) virtual inherited
Firing of unloading complete event.
Remarks
You should call this from the thread that runs the main frame loop to avoid having to make the receivers of this event thread-safe. If you use Ogre's built in frame loop you don't need to call this yourself.
_getLodValues()
const LodValueArray* Ogre::Material::_getLodValues (void) const inline
_notifyNeedsRecompile()
void Ogre::Material::_notifyNeedsRecompile (void)
Tells the material that it needs recompilation.
_notifyOrigin()
virtual void Ogre::Resource::_notifyOrigin (const String & origin) inline virtual inherited
Notify this resource of it's origin.
addListener()
virtual void Ogre::Resource::addListener (Listener * lis) virtual inherited
Register a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
applyTextureAliases()
bool Ogre::Material::applyTextureAliases (const AliasTextureNamePairList & aliasList, const bool apply = true) const
Applies texture names to Texture Unit State with matching texture name aliases.
All techniques, passes, and Texture Unit States within the material are checked. If matching texture aliases are found then true is returned.
Parameters
aliasList is a map container of texture alias, texture name pairs
apply set true to apply the texture aliases else just test to see if texture alias matches are found.
Returns
True if matching texture aliases were found in the material.
changeGroupOwnership()
virtual void Ogre::Resource::changeGroupOwnership (const String & newGroup) virtual inherited
Change the resource group ownership of a Resource.
Remarks
This method is generally reserved for internal use, although if you really know what you're doing you can use it to move this resource from one group to another.
Parameters
newGroup Name of the new group
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
clone()
MaterialPtr Ogre::Material::clone (const String & newName, bool changeGroup = false, const String & newGroup = BLANKSTRING) const
Creates a new copy of this material with the same settings but a new name.
Parameters
newName The name for the cloned material
changeGroup If true, the resource group of the clone is changed
newGroup Only required if changeGroup is true; the new group to assign
compile()
void Ogre::Material::compile (bool autoManageTextureUnits = true)
'Compiles' this Material.
Remarks
Compiling a material involves determining which Techniques are supported on the card on which OGRE is currently running, and for fixed-function Passes within those Techniques, splitting the passes down where they contain more TextureUnitState instances than the current card has texture units.
This process is automatically done when the Material is loaded, but may be repeated if you make some procedural changes.
Parameters
autoManageTextureUnits If true, when a fixed function pass has too many TextureUnitState entries than the card has texture units, the Pass in question will be split into more than one Pass in order to emulate the Pass. If you set this to false and this situation arises, an Exception will be thrown.
copyDetailsTo()
void Ogre::Material::copyDetailsTo (MaterialPtr & mat) const
Copies the details of this material into another, preserving the target's handle and name (unlike operator=) but copying everything else.
Parameters
mat Weak reference to material which will receive this material's settings.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
createTechnique()
Technique* Ogre::Material::createTechnique (void)
Creates a new Technique for this Material.
Remarks
A Technique is a single way of rendering geometry in order to achieve the effect you are intending in a material. There are many reason why you would want more than one - the main one being to handle variable graphics card abilities; you might have one technique which is impressive but only runs on 4th-generation graphics cards, for example. In this case you will want to create at least one fallback Technique. OGRE will work out which Techniques a card can support and pick the best one.
If multiple Techniques are available, the order in which they are created is important - the engine will consider lower-indexed Techniques to be preferable to higher-indexed Techniques, ie when asked for the 'best' technique it will return the first one in the technique list which is supported by the hardware.
escalateLoading()
virtual void Ogre::Resource::escalateLoading () virtual inherited
Escalates the loading of a background loaded resource.
Remarks
If a resource is set to load in the background, but something needs it before it's been loaded, there could be a problem. If the user of this resource really can't wait, they can escalate the loading which basically pulls the loading into the current thread immediately. If the resource is already being loaded but just hasn't quite finished then this method will simply wait until the background load is complete.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getBestTechnique()
Technique* Ogre::Material::getBestTechnique (unsigned short lodIndex = 0, const Renderable * rend = 0)
Gets the best supported technique.
Remarks
This method returns the lowest-index supported Technique in this material (since lower-indexed Techniques are considered to be better than higher-indexed ones).
The best supported technique is only available after this material has been compiled, which typically happens on loading the material. Therefore, if this method returns NULL, try calling Material::load.
Parameters
lodIndex The material LOD index to use
rend Optional parameter specifying the Renderable that is requesting this technique. Only used if no valid technique for the active material scheme is found, at which point it is passed to MaterialManager::Listener::handleSchemeNotFound as information.
getCompilationRequired()
bool Ogre::Material::getCompilationRequired () const inline
Gets the compilation status of the material.
Returns
True if the material needs recompilation.
getCreator()
virtual ResourceManager* Ogre::Resource::getCreator (void) inline virtual inherited
Gets the manager which created this resource.
getGroup()
virtual const String& Ogre::Resource::getGroup (void) const inline virtual inherited
Gets the group which this resource is a member of.
Reimplemented in Ogre::v1::OldSkeletonInstance.
getHandle()
virtual ResourceHandle Ogre::Resource::getHandle (void) const inline virtual inherited
Reimplemented in Ogre::v1::OldSkeletonInstance.
getLoadingState()
virtual LoadingState Ogre::Resource::getLoadingState () const inline virtual inherited
Returns the current loading state.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
getLodValueIterator()
LodValueIterator Ogre::Material::getLodValueIterator (void) const
Gets an iterator over the list of values transformed by the LodStrategy at which each LOD comes into effect.
Remarks
Note that the iterator returned from this method is not totally analogous to the one passed in by calling setLodLevels - the list includes a zero entry at the start (since the highest LOD starts at value 0). Also, the values returned are after being transformed by LodStrategy::transformUserValue.
getName()
virtual const String& Ogre::Resource::getName (void) const inline virtual inherited
Gets resource name.
Reimplemented in Ogre::v1::OldSkeletonInstance.
Referenced by Ogre::GpuProgramUsage::getProgramName().
getNumLodLevels() [1/2]
unsigned short Ogre::Material::getNumLodLevels (unsigned short schemeIndex) const
Gets the number of levels-of-detail this material has in the given scheme, based on Technique::setLodIndex.
Remarks
Note that this will not be up to date until the material has been compiled.
getNumLodLevels() [2/2]
unsigned short Ogre::Material::getNumLodLevels (const String & schemeName) const
Gets the number of levels-of-detail this material has in the given scheme, based on Technique::setLodIndex.
Remarks
Note that this will not be up to date until the material has been compiled.
getNumSupportedTechniques()
unsigned short Ogre::Material::getNumSupportedTechniques (void) const
Retrieves the number of supported techniques.
getNumTechniques()
unsigned short Ogre::Material::getNumTechniques (void) const
Retrieves the number of techniques.
getOrigin()
virtual const String& Ogre::Resource::getOrigin (void) const inline virtual inherited
Get the origin of this resource, e.g.
a script file name.
Remarks
This property will only contain something if the creator of this resource chose to populate it. Script loaders are advised to populate it.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getReceiveShadows()
bool Ogre::Material::getReceiveShadows (void) const inline
Returns whether or not objects using this material will receive shadows.
getSize()
virtual size_t Ogre::Resource::getSize (void) const inline virtual inherited
Retrieves info about the size of the resource.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
getStateCount()
virtual size_t Ogre::Resource::getStateCount () const inline virtual inherited
Returns the number of times this resource has changed state, which generally means the number of times it has been loaded.
Objects that build derived data based on the resource can check this value against a copy they kept last time they built this derived data, in order to know whether it needs rebuilding. This is a nice way of monitoring changes without having a tightly-bound callback.
getSupportedTechnique()
Technique* Ogre::Material::getSupportedTechnique (unsigned short index)
Gets the indexed supported technique.
getSupportedTechniqueIterator()
TechniqueIterator Ogre::Material::getSupportedTechniqueIterator (void)
Gets an iterator over all the Techniques which are supported by the current card.
Remarks
The supported technique list is only available after this material has been compiled, which typically happens on loading the material. Therefore, if this method returns an empty list, try calling Material::load.
getTechnique() [1/2]
Technique* Ogre::Material::getTechnique (unsigned short index)
Gets the indexed technique.
getTechnique() [2/2]
Technique* Ogre::Material::getTechnique (const String & name)
searches for the named technique.
Return 0 if technique with name is not found
getTechniqueIterator()
TechniqueIterator Ogre::Material::getTechniqueIterator (void)
Get an iterator over the Techniques in this Material.
getTransparencyCastsShadows()
bool Ogre::Material::getTransparencyCastsShadows (void) const inline
Returns whether or not objects using this material be classified as opaque to the shadow caster system.
getUnsupportedTechniquesExplanation()
const String& Ogre::Material::getUnsupportedTechniquesExplanation () const inline
Gets a string explaining why any techniques are not supported.
getUserLodValueIterator()
LodValueIterator Ogre::Material::getUserLodValueIterator (void) const
Gets an iterator over the user-defined list of values which are internally transfomed by the LodStrategy.
Remarks
Note that the iterator returned from this method is not totally analogous to the one passed in by calling setLodLevels - the list includes a zero entry at the start (since the highest LOD starts at value 0). Also, the values returned are after being transformed by LodStrategy::transformUserValue.
isBackgroundLoaded()
virtual bool Ogre::Resource::isBackgroundLoaded (void) const inline virtual inherited
Returns whether this Resource has been earmarked for background loading.
Remarks
This option only makes sense when you have built Ogre with thread support (OGRE_THREAD_SUPPORT). If a resource has been marked for background loading, then it won't load on demand like normal when load() is called. Instead, it will ignore request to load() except if the caller indicates it is the background loader. Any other users of this resource should check isLoaded(), and if that returns false, don't use the resource and come back later.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isLoaded()
virtual bool Ogre::Resource::isLoaded (void) const inline virtual inherited
Returns true if the Resource has been loaded, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
isLoading()
virtual bool Ogre::Resource::isLoading () const inline virtual inherited
Returns whether the resource is currently in the process of background loading.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
References Ogre::AtomicScalar< T >::get().
isManuallyLoaded()
virtual bool Ogre::Resource::isManuallyLoaded (void) const inline virtual inherited
Is this resource manually loaded?
isPrepared()
virtual bool Ogre::Resource::isPrepared (void) const inline virtual inherited
Returns true if the Resource has been prepared, false otherwise.
References Ogre::AtomicScalar< T >::get().
isReloadable()
virtual bool Ogre::Resource::isReloadable (void) const inline virtual inherited
Returns true if the Resource is reloadable, false otherwise.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
isTransparent()
bool Ogre::Material::isTransparent (void) const
Determines if the material has any transparency with the rest of the scene (derived from whether any Techniques say they involve transparency).
load()
virtual void Ogre::Resource::load (bool backgroundThread = false) virtual inherited
Loads the resource, if it is not already.
Remarks
If the resource is loaded from a file, loading is automatic. If not, if for example this resource gained it's data from procedural calls rather than loading from a file, then this resource will not reload on it's own.
Parameters
backgroundThread Indicates whether the caller of this method is the background resource loading thread.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
operator=()
Material& Ogre::Material::operator= (const Material & rhs)
Assignment operator to allow easy copying between materials.
prepare()
virtual void Ogre::Resource::prepare (bool backgroundThread = false) virtual inherited
Prepares the resource for load, if it is not already.
One can call prepare() before load(), but this is not required as load() will call prepare() itself, if needed. When OGRE_THREAD_SUPPORT==1 both load() and prepare() are thread-safe. When OGRE_THREAD_SUPPORT==2 however, only prepare() is thread-safe. The reason for this function is to allow a background thread to do some of the loading work, without requiring the whole render system to be thread-safe. The background thread would call prepare() while the main render loop would later call load(). So long as prepare() remains thread-safe, subclasses can arbitrarily split the work of loading a resource between load() and prepare(). It is best to try and do as much work in prepare(), however, since this will leave less work for the main render thread to do and thus increase FPS.
Parameters
backgroundThread Whether this is occurring in a background thread
reload()
virtual void Ogre::Resource::reload (void) virtual inherited
Reloads the resource, if it is already loaded.
Remarks
Calls unload() and then load() again, if the resource is already loaded. If it is not loaded already, then nothing happens.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
removeAllTechniques()
void Ogre::Material::removeAllTechniques (void)
Removes all the techniques in this Material.
removeListener()
virtual void Ogre::Resource::removeListener (Listener * lis) virtual inherited
Remove a listener on this resource.
See also
Resource::Listener
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
removeTechnique()
void Ogre::Material::removeTechnique (unsigned short index)
Removes the technique at the given index.
setAmbient() [1/2]
void Ogre::Material::setAmbient (Real red, Real green, Real blue)
Sets the ambient colour reflectance properties for every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setAmbient
setAmbient() [2/2]
void Ogre::Material::setAmbient (const ColourValue & ambient)
Sets the ambient colour reflectance properties for every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setAmbient
setBackgroundLoaded()
virtual void Ogre::Resource::setBackgroundLoaded (bool bl) inline virtual inherited
Tells the resource whether it is background loaded or not.
Remarks
See also
Resource::isBackgroundLoaded . Note that calling this only defers the normal on-demand loading behaviour of a resource, it does not actually set up a thread to make sure the resource gets loaded in the background. You should use ResourceBackgroundLoadingQueue to manage the actual loading (which will call this method itself).
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
setBlendblock()
void Ogre::Material::setBlendblock (const HlmsBlendblock & blendblock)
Sets the blendbock to every pass.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setBlendblock
setColourWriteEnabled()
void Ogre::Material::setColourWriteEnabled (bool enabled)
Sets whether or not colour buffer writing is enabled for each Pass.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setColourWriteEnabled
setDiffuse() [1/2]
void Ogre::Material::setDiffuse (Real red, Real green, Real blue, Real alpha)
Sets the diffuse colour reflectance properties of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setDiffuse
setDiffuse() [2/2]
void Ogre::Material::setDiffuse (const ColourValue & diffuse)
Sets the diffuse colour reflectance properties of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setDiffuse
setFog()
void Ogre::Material::setFog (bool overrideScene, FogMode mode = FOG_NONE, const ColourValue & colour = ColourValue::White, Real expDensity = 0.001, Real linearStart = 0.0, Real linearEnd = 1.0)
Sets the fogging mode applied to each pass.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setFog
setLodLevels()
void Ogre::Material::setLodLevels (const LodValueArray & lodValues)
Sets the distance at which level-of-detail (LOD) levels come into effect.
Remarks
You should only use this if you have assigned LOD indexes to the Technique instances attached to this Material. If you have done so, you should call this method to determine the distance at which the lowe levels of detail kick in. The decision about what distance is actually used is a combination of this and the LOD bias applied to both the current Camera and the current Entity.
Parameters
lodValues A vector of Reals which indicate the LOD value at which to switch to lower details. They are listed in LOD index order, starting at index 1 (ie the first level down from the highest level 0, which automatically applies from a value of 0). These are 'user values', before being potentially transformed by the strategy, so for the distance strategy this is an unsquared distance for example.
setMacroblock()
void Ogre::Material::setMacroblock (const HlmsMacroblock & macroblock)
Sets the macroblock for all passes.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setMacroblock
setManuallyLoaded()
virtual void Ogre::Resource::setManuallyLoaded (bool isManual) inline virtual inherited
Set "Is this resource manually loaded?".
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setPointSize()
void Ogre::Material::setPointSize (Real ps)
Sets the point size properties for every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setPointSize
setReceiveShadows()
void Ogre::Material::setReceiveShadows (bool enabled) inline
Sets whether objects using this material will receive shadows.
Remarks
This method allows a material to opt out of receiving shadows, if it would otherwise do so. Shadows will not be cast on any objects unless the scene is set up to support shadows (
See also
SceneManager::setShadowTechnique), and not all techniques cast shadows on all objects. In any case, if you have a need to prevent shadows being received by material, this is the method you call to do it.
Note
Transparent materials never receive shadows despite this setting. The default is to receive shadows.
setSamplerblock()
void Ogre::Material::setSamplerblock (const HlmsSamplerblock & samplerblock)
Set samplerblock for every texture unit in every Technique and Pass.
Note
This property has been moved to the TextureUnitState class, which is accessible via the Technique and Pass. For simplicity, this method allows you to set these properties for every current TeextureUnitState, If you need more precision, retrieve the Technique, Pass and TextureUnitState instances and set the property there.
See also
TextureUnitState::setSamplerblock
setSelfIllumination() [1/2]
void Ogre::Material::setSelfIllumination (Real red, Real green, Real blue)
Sets the amount of self-illumination of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setSelfIllumination
setSelfIllumination() [2/2]
void Ogre::Material::setSelfIllumination (const ColourValue & selfIllum)
Sets the amount of self-illumination of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setSelfIllumination
setShadingMode()
void Ogre::Material::setShadingMode (ShadeOptions mode)
Sets the type of light shading required.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setShadingMode
setShininess()
void Ogre::Material::setShininess (Real val)
Sets the shininess properties of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setShininess
setSpecular() [1/2]
void Ogre::Material::setSpecular (Real red, Real green, Real blue, Real alpha)
Sets the specular colour reflectance properties of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setSpecular
setSpecular() [2/2]
void Ogre::Material::setSpecular (const ColourValue & specular)
Sets the specular colour reflectance properties of every Pass in every Technique.
Note
This property has been moved to the Pass class, which is accessible via the Technique. For simplicity, this method allows you to set these properties for every current Technique, and for every current Pass within those Techniques. If you need more precision, retrieve the Technique and Pass instances and set the property there.
See also
Pass::setSpecular
setToLoaded()
virtual void Ogre::Resource::setToLoaded (void) inline virtual inherited
Change the Resource loading state to loaded.
References Ogre::AtomicScalar< T >::set().
setTransparencyCastsShadows()
void Ogre::Material::setTransparencyCastsShadows (bool enabled) inline
Sets whether objects using this material be classified as opaque to the shadow caster system.
Remarks
This method allows a material to cast a shadow, even if it is transparent. By default, transparent materials neither cast nor receive shadows. Shadows will not be cast on any objects unless the scene is set up to support shadows (
See also
SceneManager::setShadowTechnique), and not all techniques cast shadows on all objects.
touch()
void Ogre::Material::touch (void) inline virtual
'Touches' the resource to indicate it has been used.
Reimplemented from Ogre::Resource.
References Ogre::Resource::touch().
unload()
virtual void Ogre::Resource::unload (void) virtual inherited
Unloads the resource; this is not permanent, the resource can be reloaded later if required.
Reimplemented in Ogre::UnifiedHighLevelGpuProgram.
Friends And Related Function Documentation
MaterialManager
friend class MaterialManager friend
SceneManager
friend class SceneManager friend
Member Data Documentation
OGRE_AUTO_MUTEX
Ogre::Resource::OGRE_AUTO_MUTEX inherited
The documentation for this class was generated from the following file:
OgreMaterial.h