OGRE: Ogre::v1::PanelOverlayElement Class Reference
Ogre::v1::PanelOverlayElement Class Reference
Core » Overlays
OverlayElement representing a flat, single-material (or transparent) panel which can contain other elements.
#include <OgrePanelOverlayElement.h>
Classes
class CmdTiling
Command object for specifying tiling (see ParamCommand).
class CmdTransparent
Command object for specifying transparency (see ParamCommand).
class CmdUVCoords
Command object for specifying UV coordinates (see ParamCommand).
Public Types
typedef MapIterator< ChildContainerMap > ChildContainerIterator
typedef map< String, OverlayContainer * >::type ChildContainerMap
typedef MapIterator< ChildMap > ChildIterator
typedef map< String, OverlayElement * >::type ChildMap
typedef map< size_t, Vector4 >::type CustomParameterMap
Public Member Functions
PanelOverlayElement (const String &name)
Constructor.
virtual ~PanelOverlayElement ()
void _addChild (OverlayElement *elem)
virtual void _getClippingRegion (RealRect &clippingRegion)
Gets the clipping region of the element.
virtual Real _getDerivedLeft (void)
Gets the 'left' position as derived from own left and that of parents.
virtual Real _getDerivedTop (void)
Gets the 'top' position as derived from own left and that of parents.
Real _getHeight (void) const
Gets the height of this element in relation to the screen (where 1.0 = screen height)
Real _getLeft (void) const
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
virtual Real _getRelativeHeight (void)
Gets the 'height' as derived from own height and metrics mode.
virtual Real _getRelativeWidth (void)
Gets the 'width' as derived from own width and metrics mode.
Real _getTop (void) const
Gets the top of this element in relation to the screen (where 0 = far left, 1.0 = far right)
Real _getWidth (void) const
Gets the width of this element in relation to the screen (where 1.0 = screen width)
virtual void _notifyParent (OverlayContainer *parent, Overlay *overlay)
Overridden from OverlayElement.
virtual void _notifyViewport ()
Overridden from OverlayElement.
virtual void _positionsOutOfDate (void)
Tell the object and its children to recalculate.
void _removeChild (OverlayElement *elem)
void _removeChild (const String &name)
void _setDimensions (Real width, Real height)
Sets the width and height of this element in relation to the screen (where 1.0 = screen width)
void _setHeight (Real height)
Sets the height of this element in relation to the screen (where 1.0 = screen width)
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
void _setLeft (Real left)
Sets the left of this element in relation to the screen (where 1.0 = screen width)
virtual void _setNullDatablock (void)
Sets the datablock to a null pointer.
void _setParent (OverlayContainer *parent)
void _setPosition (Real left, Real top)
Sets the left and top of this element in relation to the screen (where 1.0 = screen width)
void _setTop (Real top)
Sets the top of this element in relation to the screen (where 1.0 = screen width)
void _setWidth (Real width)
Sets the width of this element in relation to the screen (where 1.0 = screen width)
virtual void _update (void)
Overridden from OverlayElement.
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
virtual void _updateFromParent (void)
Updates this elements transform based on it's parent.
void _updateRenderQueue (RenderQueue *queue, Camera *camera, const Camera *lodCamera)
Overridden from OverlayContainer.
virtual void addChild (OverlayElement *elem)
Adds another OverlayElement to this container.
virtual void addChildImpl (OverlayElement *elem)
Adds another OverlayElement to this container.
virtual void addChildImpl (OverlayContainer *cont)
Add a nested container to this container.
virtual OverlayElement * clone (const String &instanceName)
virtual bool contains (Real x, Real y) const
Returns true if xy is within the constraints of the component.
void copyFromTemplate (OverlayElement *templateOverlay)
virtual void copyParametersTo (StringInterface *dest) const
Method for copying this object's parameters to another object.
virtual OverlayElement * findElementAt (Real x, Real y)
This returns a OverlayElement at position x,y.
virtual const DisplayString & getCaption (void) const
Gets the caption for this element.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
virtual OverlayElement * getChild (const String &name)
Gets the named child of this container.
virtual ChildContainerIterator getChildContainerIterator (void)
Gets an iterator for just the container children of this object.
virtual ChildIterator getChildIterator (void)
Gets an object for iterating over all the children of this object.
virtual const ColourValue & getColour (void) const
Gets the colour for this element.
uint8 getCurrentMaterialLod (void) const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
const CustomParameterMap & getCustomParameters (void) const
HlmsDatablock * getDatablock (void) const
Real getHeight (void) const
Gets the height of this element in relation to the screen (where 1.0 = screen height)
uint32 getHlmsCasterHash (void) const
uint32 getHlmsHash (void) const
virtual GuiHorizontalAlignment getHorizontalAlignment (void) const
Gets the horizontal alignment for this element.
Real getLeft (void) const
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
const LightList & getLights (void) const
Gets a list of lights, ordered relative to how close they are to this renderable.
const MaterialPtr & getMaterial (void) const
See Renderable.
virtual const String & getMaterialName (void) const
Gets the name of the material this element uses.
virtual GuiMetricsMode getMetricsMode (void) const
Retrieves the current settings of how the element metrics are interpreted.
const String & getName (void) const
Gets the name of this overlay.
virtual unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
ParamDictionary * getParamDictionary (void)
Retrieves the parameter dictionary for this class.
const ParamDictionary * getParamDictionary (void) const
virtual String getParameter (const String &name) const
Generic parameter retrieval method.
const ParameterList & getParameters (void) const
Retrieves a list of parameters valid for this object.
OverlayContainer * getParent ()
Returns the parent container.
virtual bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void getRenderOperation (v1::RenderOperation &op, bool casterPass)
See Renderable.
uint8 getRenderQueueSubGroup (void) const
const OverlayElement * getSourceTemplate () const
Returns the SourceTemplate for this element.
Real getTileX (ushort layer=0) const
Real getTileY (ushort layer=0) const
Gets the number of times the texture should repeat vertically.
Real getTop (void) const
Gets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
virtual const String & getTypeName (void) const
See OverlayElement.
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic (void) const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix (void) const
Returns whether the world matrix is an identify matrix.
virtual OGRE_DEPRECATED const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
void getUV (Real &u1, Real &v1, Real &u2, Real &v2) const
Get the uv coordinates for the panel.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
virtual GuiVerticalAlignment getVerticalAlignment (void) const
Gets the vertical alignment for this element.
Real getWidth (void) const
Gets the width of this element in relation to the screen (where 1.0 = screen width)
void getWorldTransforms (Matrix4 *xform) const
See Renderable.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation (void) const
virtual void hide (void)
Hides this element if it was visible.
virtual void initialise (void)
Initialise.
virtual bool isChildrenProcessEvents () const
Should this container pass events to their children.
virtual bool isCloneable () const
bool isContainer () const
Overridden from OverlayElement.
bool isEnabled () const
virtual bool isKeyEnabled () const
bool isTransparent (void) const
Returns whether this panel is transparent.
bool isVisible (void) const
Returns whether or not the element is visible.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
virtual void removeChild (const String &name)
Removes a named element from this container.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
virtual void setCaption (const DisplayString &text)
Sets the caption on elements that support it.
virtual void setChildrenProcessEvents (bool val)
Should this container pass events to their children.
virtual void setCloneable (bool c)
virtual void setColour (const ColourValue &col)
Sets the colour on elements that support it.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
void setDimensions (Real width, Real height)
Sets the dimensions of this element in relation to the screen (1.0 = screen width/height).
virtual void setEnabled (bool b)
void setHeight (Real height)
Sets the height of this element in relation to the screen (where 1.0 = screen height)
virtual void setHorizontalAlignment (GuiHorizontalAlignment gha)
Sets the horizontal origin for this element.
void setLeft (Real left)
Sets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
virtual void setMaterial (const MaterialPtr &material)
Sets the given material. Overrides HLMS materials.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
void setMaterialName (const String &matName)
Overridden from OverlayElement.
virtual void setMetricsMode (GuiMetricsMode gmm)
Tells this element how to interpret the position and dimension values it is given.
virtual bool setParameter (const String &name, const String &value)
Generic parameter setting method.
virtual void setParameterList (const NameValuePairList &paramList)
Generic multiple parameter setting method.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setPosition (Real left, Real top)
Sets the position of the top-left corner of the element, relative to the screen size (1.0 = screen width / height)
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
void setTiling (Real x, Real y, ushort layer=0)
Sets the number of times textures should repeat.
void setTop (Real Top)
Sets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
void setTransparent (bool isTransparent)
Sets whether this panel is transparent (used only as a grouping level), or if it is actually rendered.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
void setUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the panel.
virtual void setVerticalAlignment (GuiVerticalAlignment gva)
Sets the vertical origin for this element.
void setWidth (Real width)
Sets the width of this element in relation to the screen (where 1.0 = screen width)
virtual void show (void)
Shows this element if it was hidden.
Static Public Member Functions
static void cleanupDictionary ()
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
Public Attributes
uint8 mCustomParameter
Only valid when using low level materials.
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
Detailed Description
OverlayElement representing a flat, single-material (or transparent) panel which can contain other elements.
Remarks
This class subclasses OverlayContainer because it can contain other elements. Like other containers, if hidden it's contents are also hidden, if moved it's contents also move etc. The panel itself is a 2D rectangle which is either completely transparent, or is rendered with a single material. The texture(s) on the panel can be tiled depending on your requirements.
This component is suitable for backgrounds and grouping other elements. Note that because it has a single repeating material it cannot have a discrete border (unless the texture has one and the texture is tiled only once). For a bordered panel, see it's subclass BorderPanelOverlayElement.
Note that the material can have all the usual effects applied to it like multiple texture layers, scrolling / animated textures etc. For multiple texture layers, you have to set the tiling level for each layer.
Member Typedef Documentation
ChildContainerIterator
typedef MapIterator<ChildContainerMap> Ogre::v1::OverlayContainer::ChildContainerIterator inherited
ChildContainerMap
typedef map<String, OverlayContainer*>::type Ogre::v1::OverlayContainer::ChildContainerMap inherited
ChildIterator
typedef MapIterator<ChildMap> Ogre::v1::OverlayContainer::ChildIterator inherited
ChildMap
typedef map<String, OverlayElement*>::type Ogre::v1::OverlayContainer::ChildMap inherited
CustomParameterMap
typedef map<size_t, Vector4>::type Ogre::Renderable::CustomParameterMap inherited
Constructor & Destructor Documentation
PanelOverlayElement()
Ogre::v1::PanelOverlayElement::PanelOverlayElement (const String & name)
Constructor.
~PanelOverlayElement()
virtual Ogre::v1::PanelOverlayElement::~PanelOverlayElement () virtual
Member Function Documentation
_addChild()
void Ogre::v1::OverlayContainer::_addChild (OverlayElement * elem) inherited
_getClippingRegion()
virtual void Ogre::v1::OverlayElement::_getClippingRegion (RealRect & clippingRegion) virtual inherited
Gets the clipping region of the element.
_getDerivedLeft()
virtual Real Ogre::v1::OverlayElement::_getDerivedLeft (void) virtual inherited
Gets the 'left' position as derived from own left and that of parents.
_getDerivedTop()
virtual Real Ogre::v1::OverlayElement::_getDerivedTop (void) virtual inherited
Gets the 'top' position as derived from own left and that of parents.
_getHeight()
Real Ogre::v1::OverlayElement::_getHeight (void) const inline inherited
Gets the height of this element in relation to the screen (where 1.0 = screen height)
_getLeft()
Real Ogre::v1::OverlayElement::_getLeft (void) const inline inherited
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
_getRelativeHeight()
virtual Real Ogre::v1::OverlayElement::_getRelativeHeight (void) virtual inherited
Gets the 'height' as derived from own height and metrics mode.
_getRelativeWidth()
virtual Real Ogre::v1::OverlayElement::_getRelativeWidth (void) virtual inherited
Gets the 'width' as derived from own width and metrics mode.
_getTop()
Real Ogre::v1::OverlayElement::_getTop (void) const inline inherited
Gets the top of this element in relation to the screen (where 0 = far left, 1.0 = far right)
_getWidth()
Real Ogre::v1::OverlayElement::_getWidth (void) const inline inherited
Gets the width of this element in relation to the screen (where 1.0 = screen width)
_notifyParent()
virtual void Ogre::v1::OverlayContainer::_notifyParent (OverlayContainer * parent, Overlay * overlay) virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
_notifyViewport()
virtual void Ogre::v1::OverlayContainer::_notifyViewport () virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
_positionsOutOfDate()
virtual void Ogre::v1::OverlayContainer::_positionsOutOfDate (void) virtual inherited
Tell the object and its children to recalculate.
Reimplemented from Ogre::v1::OverlayElement.
_removeChild() [1/2]
void Ogre::v1::OverlayContainer::_removeChild (OverlayElement * elem) inline inherited
References Ogre::v1::OverlayContainer::_removeChild(), and Ogre::v1::OverlayElement::getName().
Referenced by Ogre::v1::OverlayContainer::_removeChild().
_removeChild() [2/2]
void Ogre::v1::OverlayContainer::_removeChild (const String & name) inherited
_setDimensions()
void Ogre::v1::OverlayElement::_setDimensions (Real width, Real height) inherited
Sets the width and height of this element in relation to the screen (where 1.0 = screen width)
_setHeight()
void Ogre::v1::OverlayElement::_setHeight (Real height) inherited
Sets the height of this element in relation to the screen (where 1.0 = screen width)
_setHlmsHashes()
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual inherited
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
_setLeft()
void Ogre::v1::OverlayElement::_setLeft (Real left) inherited
Sets the left of this element in relation to the screen (where 1.0 = screen width)
_setNullDatablock()
virtual void Ogre::Renderable::_setNullDatablock (void) virtual inherited
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
_setParent()
void Ogre::v1::OverlayElement::_setParent (OverlayContainer * parent) inline inherited
_setPosition()
void Ogre::v1::OverlayElement::_setPosition (Real left, Real top) inherited
Sets the left and top of this element in relation to the screen (where 1.0 = screen width)
_setTop()
void Ogre::v1::OverlayElement::_setTop (Real top) inherited
Sets the top of this element in relation to the screen (where 1.0 = screen width)
_setWidth()
void Ogre::v1::OverlayElement::_setWidth (Real width) inherited
Sets the width of this element in relation to the screen (where 1.0 = screen width)
_update()
virtual void Ogre::v1::OverlayContainer::_update (void) virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
Reimplemented in Ogre::v1::BorderPanelOverlayElement.
_updateCustomGpuParameter()
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::v1::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
_updateFromParent()
virtual void Ogre::v1::OverlayElement::_updateFromParent (void) virtual inherited
Updates this elements transform based on it's parent.
_updateRenderQueue()
void Ogre::v1::PanelOverlayElement::_updateRenderQueue (RenderQueue * queue, Camera * camera, const Camera * lodCamera) virtual
Overridden from OverlayContainer.
Reimplemented from Ogre::v1::OverlayContainer.
addChild()
virtual void Ogre::v1::OverlayContainer::addChild (OverlayElement * elem) virtual inherited
Adds another OverlayElement to this container.
addChildImpl() [1/2]
virtual void Ogre::v1::OverlayContainer::addChildImpl (OverlayElement * elem) virtual inherited
Adds another OverlayElement to this container.
addChildImpl() [2/2]
virtual void Ogre::v1::OverlayContainer::addChildImpl (OverlayContainer * cont) virtual inherited
Add a nested container to this container.
cleanupDictionary()
static void Ogre::StringInterface::cleanupDictionary () static inherited
Cleans up the static 'msDictionary' required to reset Ogre, otherwise the containers are left with invalid pointers, which will lead to a crash as soon as one of the ResourceManager implementers (e.g.
MaterialManager) initializes.
clone()
virtual OverlayElement* Ogre::v1::OverlayContainer::clone (const String & instanceName) virtual inherited
Reimplemented from Ogre::v1::OverlayElement.
contains()
virtual bool Ogre::v1::OverlayElement::contains (Real x, Real y) const virtual inherited
Returns true if xy is within the constraints of the component.
copyFromTemplate()
void Ogre::v1::OverlayContainer::copyFromTemplate (OverlayElement * templateOverlay) virtual inherited
Reimplemented from Ogre::v1::OverlayElement.
copyParametersTo()
virtual void Ogre::StringInterface::copyParametersTo (StringInterface * dest) const inline virtual inherited
Method for copying this object's parameters to another object.
Remarks
This method takes the values of all the object's parameters and tries to set the same values on the destination object. This provides a completely type independent way to copy parameters to other objects. Note that because of the String manipulation involved, this should not be regarded as an efficient process and should be saved for times outside of the rendering loop.
Any unrecognised parameters will be ignored as with setParameter method.
Parameters
dest Pointer to object to have it's parameters set the same as this object.
References Ogre::StringInterface::setParameter().
findElementAt()
virtual OverlayElement* Ogre::v1::OverlayContainer::findElementAt (Real x, Real y) virtual inherited
This returns a OverlayElement at position x,y.
Reimplemented from Ogre::v1::OverlayElement.
getCaption()
virtual const DisplayString& Ogre::v1::OverlayElement::getCaption (void) const virtual inherited
Gets the caption for this element.
getCastsShadows()
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::ManualObject::ManualObjectSection, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::SubItem, and Ogre::WireAabb.
getChild()
virtual OverlayElement* Ogre::v1::OverlayContainer::getChild (const String & name) virtual inherited
Gets the named child of this container.
getChildContainerIterator()
virtual ChildContainerIterator Ogre::v1::OverlayContainer::getChildContainerIterator (void) virtual inherited
Gets an iterator for just the container children of this object.
Remarks
Good for cascading updates without having to use RTTI
getChildIterator()
virtual ChildIterator Ogre::v1::OverlayContainer::getChildIterator (void) virtual inherited
Gets an object for iterating over all the children of this object.
getColour()
virtual const ColourValue& Ogre::v1::OverlayElement::getColour (void) const virtual inherited
Gets the colour for this element.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
getCurrentMaterialLod()
uint8 Ogre::Renderable::getCurrentMaterialLod (void) const inline inherited
getCustomParameter()
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
getCustomParameters()
const CustomParameterMap& Ogre::Renderable::getCustomParameters (void) const inline inherited
getDatablock()
HlmsDatablock* Ogre::Renderable::getDatablock (void) const inline inherited
getHeight()
Real Ogre::v1::OverlayElement::getHeight (void) const inherited
Gets the height of this element in relation to the screen (where 1.0 = screen height)
getHlmsCasterHash()
uint32 Ogre::Renderable::getHlmsCasterHash (void) const inline inherited
getHlmsHash()
uint32 Ogre::Renderable::getHlmsHash (void) const inline inherited
getHorizontalAlignment()
virtual GuiHorizontalAlignment Ogre::v1::OverlayElement::getHorizontalAlignment (void) const virtual inherited
Gets the horizontal alignment for this element.
getLeft()
Real Ogre::v1::OverlayElement::getLeft (void) const inherited
Gets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
getLights()
const LightList& Ogre::v1::OverlayElement::getLights (void) const inline virtual inherited
Gets a list of lights, ordered relative to how close they are to this renderable.
Remarks
Directional lights, which have no position, will always be first on this list.
Implements Ogre::Renderable.
getMaterial()
const MaterialPtr& Ogre::v1::OverlayElement::getMaterial (void) const inherited
See Renderable.
getMaterialName()
virtual const String& Ogre::v1::OverlayElement::getMaterialName (void) const virtual inherited
Gets the name of the material this element uses.
getMetricsMode()
virtual GuiMetricsMode Ogre::v1::OverlayElement::getMetricsMode (void) const virtual inherited
Retrieves the current settings of how the element metrics are interpreted.
getName()
const String& Ogre::v1::OverlayElement::getName (void) const inherited
Gets the name of this overlay.
Referenced by Ogre::v1::OverlayContainer::_removeChild().
getNumWorldTransforms()
virtual unsigned short Ogre::Renderable::getNumWorldTransforms (void) const inline virtual inherited
Returns the number of world transform matrices this renderable requires.
Remarks
When a renderable uses vertex blending, it uses multiple world matrices instead of a single one. Each vertex sent to the pipeline can reference one or more matrices in this list with given weights. If a renderable does not use vertex blending this method returns 1, which is the default for simplicity.
Reimplemented in Ogre::v1::BorderRenderable, Ogre::v1::SubEntity, Ogre::v1::BaseInstanceBatchVTF, Ogre::v1::InstanceBatchShader, and Ogre::v1::InstanceBatchHW.
getParamDictionary() [1/2]
ParamDictionary* Ogre::StringInterface::getParamDictionary (void) inline inherited
Retrieves the parameter dictionary for this class.
Remarks
Only valid to call this after createParamDictionary.
Returns
Pointer to ParamDictionary shared by all instances of this class which you can add parameters to, retrieve parameters etc.
getParamDictionary() [2/2]
const ParamDictionary* Ogre::StringInterface::getParamDictionary (void) const inline inherited
getParameter()
virtual String Ogre::StringInterface::getParameter (const String & name) const inline virtual inherited
Generic parameter retrieval method.
Remarks
Call this method with the name of a parameter to retrieve a string-format value of the parameter in question. If in doubt, check the parameter definition in the list returned from getParameters for the type of this parameter. If you like you can use StringConverter to convert this string back into a native type.
Parameters
name The name of the parameter to get
Returns
String value of parameter, blank if not found
References Ogre::ParamCommand::doGet().
getParameters()
const ParameterList& Ogre::StringInterface::getParameters (void) const inherited
Retrieves a list of parameters valid for this object.
Returns
A reference to a static list of ParameterDef objects.
getParent()
OverlayContainer* Ogre::v1::OverlayElement::getParent () inherited
Returns the parent container.
getPolygonModeOverrideable()
virtual bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline virtual inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
getRenderOperation()
void Ogre::v1::PanelOverlayElement::getRenderOperation (v1::RenderOperation & op, bool casterPass) virtual
See Renderable.
Implements Ogre::Renderable.
getRenderQueueSubGroup()
uint8 Ogre::Renderable::getRenderQueueSubGroup (void) const inline inherited
getSourceTemplate()
const OverlayElement* Ogre::v1::OverlayElement::getSourceTemplate () const inline inherited
Returns the SourceTemplate for this element.
getTileX()
Real Ogre::v1::PanelOverlayElement::getTileX (ushort layer = 0) const
getTileY()
Real Ogre::v1::PanelOverlayElement::getTileY (ushort layer = 0) const
Gets the number of times the texture should repeat vertically.
Parameters
layer The texture layer to specify (only needs to be altered if you're using a multi-texture layer material)
getTop()
Real Ogre::v1::OverlayElement::getTop (void) const inherited
Gets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
getTypeName()
virtual const String& Ogre::v1::PanelOverlayElement::getTypeName (void) const virtual
See OverlayElement.
Implements Ogre::v1::OverlayElement.
Reimplemented in Ogre::v1::BorderPanelOverlayElement.
getUseIdentityProjection()
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
getUseIdentityView()
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
getUseIdentityViewProjMatrixIsDynamic()
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic (void) const inline virtual inherited
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
getUseIdentityWorldMatrix()
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix (void) const inline virtual inherited
Returns whether the world matrix is an identify matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
getUserAny()
virtual OGRE_DEPRECATED const Any& Ogre::Renderable::getUserAny (void) const inline virtual inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
getUserObjectBindings() [1/2]
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUserObjectBindings() [2/2]
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
getUV()
void Ogre::v1::PanelOverlayElement::getUV (Real & u1, Real & v1, Real & u2, Real & v2) const
Get the uv coordinates for the panel.
getVaos()
const VertexArrayObjectArray& Ogre::Renderable::getVaos (VertexPass vertexPass) const inline inherited
getVerticalAlignment()
virtual GuiVerticalAlignment Ogre::v1::OverlayElement::getVerticalAlignment (void) const virtual inherited
Gets the vertical alignment for this element.
getWidth()
Real Ogre::v1::OverlayElement::getWidth (void) const inherited
Gets the width of this element in relation to the screen (where 1.0 = screen width)
getWorldTransforms()
void Ogre::v1::OverlayElement::getWorldTransforms (Matrix4 * xform) const virtual inherited
See Renderable.
Implements Ogre::Renderable.
Referenced by Ogre::v1::BorderRenderable::getWorldTransforms().
hasCustomParameter()
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
hasSkeletonAnimation()
bool Ogre::Renderable::hasSkeletonAnimation (void) const inline inherited
hide()
virtual void Ogre::v1::OverlayElement::hide (void) virtual inherited
Hides this element if it was visible.
initialise()
virtual void Ogre::v1::PanelOverlayElement::initialise (void) virtual
Initialise.
Reimplemented from Ogre::v1::OverlayContainer.
Reimplemented in Ogre::v1::BorderPanelOverlayElement.
isChildrenProcessEvents()
virtual bool Ogre::v1::OverlayContainer::isChildrenProcessEvents () const inline virtual inherited
Should this container pass events to their children.
isCloneable()
virtual bool Ogre::v1::OverlayElement::isCloneable () const inline virtual inherited
isContainer()
bool Ogre::v1::OverlayContainer::isContainer () const inline virtual inherited
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
isEnabled()
bool Ogre::v1::OverlayElement::isEnabled () const inherited
isKeyEnabled()
virtual bool Ogre::v1::OverlayElement::isKeyEnabled () const inline virtual inherited
isTransparent()
bool Ogre::v1::PanelOverlayElement::isTransparent (void) const
Returns whether this panel is transparent.
isVisible()
bool Ogre::v1::OverlayElement::isVisible (void) const inherited
Returns whether or not the element is visible.
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
postRender()
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
preRender()
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::v1::BillboardChain.
removeChild()
virtual void Ogre::v1::OverlayContainer::removeChild (const String & name) virtual inherited
Removes a named element from this container.
removeCustomParameter()
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
setCaption()
virtual void Ogre::v1::OverlayElement::setCaption (const DisplayString & text) virtual inherited
Sets the caption on elements that support it.
Remarks
This property doesn't do something on all elements, just those that support it. However, being a common requirement it is in the top-level interface to avoid having to set it via the StringInterface all the time.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
setChildrenProcessEvents()
virtual void Ogre::v1::OverlayContainer::setChildrenProcessEvents (bool val) inline virtual inherited
Should this container pass events to their children.
setCloneable()
virtual void Ogre::v1::OverlayElement::setCloneable (bool c) inline virtual inherited
setColour()
virtual void Ogre::v1::OverlayElement::setColour (const ColourValue & col) virtual inherited
Sets the colour on elements that support it.
Remarks
This property doesn't do something on all elements, just those that support it. However, being a common requirement it is in the top-level interface to avoid having to set it via the StringInterface all the time.
Reimplemented in Ogre::v1::TextAreaOverlayElement.
setCustomParameter()
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
setDatablock() [1/2]
void Ogre::Renderable::setDatablock (IdString datablockName) inherited
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
setDatablock() [2/2]
virtual void Ogre::Renderable::setDatablock (HlmsDatablock * datablock) virtual inherited
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
setDatablockOrMaterialName()
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName) inherited
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
setDimensions()
void Ogre::v1::OverlayElement::setDimensions (Real width, Real height) inherited
Sets the dimensions of this element in relation to the screen (1.0 = screen width/height).
setEnabled()
virtual void Ogre::v1::OverlayElement::setEnabled (bool b) virtual inherited
setHeight()
void Ogre::v1::OverlayElement::setHeight (Real height) inherited
Sets the height of this element in relation to the screen (where 1.0 = screen height)
setHorizontalAlignment()
virtual void Ogre::v1::OverlayElement::setHorizontalAlignment (GuiHorizontalAlignment gha) virtual inherited
Sets the horizontal origin for this element.
Remarks
By default, the horizontal origin for a OverlayElement is the left edge of the parent container (or the screen if this is a root element). You can alter this by calling this method, which is especially useful when you want to use pixel-based metrics (see setMetricsMode) since in this mode you can't use relative positioning.
For example, if you were using GMM_PIXELS metrics mode, and you wanted to place a 30x30 pixel crosshair in the center of the screen, you would use GHA_CENTER with a 'left' property of -15.
Note that neither GHA_CENTER or GHA_RIGHT alter the position of the element based on it's width, you have to alter the 'left' to a negative number to do that; all this does is establish the origin. This is because this way you can align multiple things in the center and right with different 'left' offsets for maximum flexibility.
setLeft()
void Ogre::v1::OverlayElement::setLeft (Real left) inherited
Sets the left of this element in relation to the screen (where 0 = far left, 1.0 = far right)
setMaterial()
virtual void Ogre::Renderable::setMaterial (const MaterialPtr & material) virtual inherited
Sets the given material. Overrides HLMS materials.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
setMaterialName() [1/2]
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName) inherited
Sets the name of the Material to be used. Prefer using HLMS setHlms.
setMaterialName() [2/2]
void Ogre::v1::PanelOverlayElement::setMaterialName (const String & matName) virtual
Overridden from OverlayElement.
Reimplemented from Ogre::v1::OverlayElement.
setMetricsMode()
virtual void Ogre::v1::OverlayElement::setMetricsMode (GuiMetricsMode gmm) virtual inherited
Tells this element how to interpret the position and dimension values it is given.
Remarks
By default, OverlayElements are positioned and sized according to relative dimensions of the screen. This is to ensure portability between different resolutions when you want things to be positioned and sized the same way across all resolutions. However, sometimes you want things to be sized according to fixed pixels. In order to do this, you can call this method with the parameter GMM_PIXELS. Note that if you then want to place your element relative to the center, right or bottom of it's parent, you will need to use the setHorizontalAlignment and setVerticalAlignment methods.
Reimplemented in Ogre::v1::BorderPanelOverlayElement, and Ogre::v1::TextAreaOverlayElement.
setParameter()
virtual bool Ogre::StringInterface::setParameter (const String & name, const String & value) virtual inherited
Generic parameter setting method.
Remarks
Call this method with the name of a parameter and a string version of the value to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
name The name of the parameter to set
value String value. Must be in the right format for the type specified in the parameter definition. See the StringConverter class for more information.
Returns
true if set was successful, false otherwise (NB no exceptions thrown - tolerant method)
Referenced by Ogre::StringInterface::copyParametersTo().
setParameterList()
virtual void Ogre::StringInterface::setParameterList (const NameValuePairList & paramList) virtual inherited
Generic multiple parameter setting method.
Remarks
Call this method with a list of name / value pairs to set. The implementor will convert the string to a native type internally. If in doubt, check the parameter definition in the list returned from StringInterface::getParameters.
Parameters
paramList Name/value pair list
setPolygonModeOverrideable()
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
setPosition()
void Ogre::v1::OverlayElement::setPosition (Real left, Real top) inherited
Sets the position of the top-left corner of the element, relative to the screen size (1.0 = screen width / height)
setRenderQueueSubGroup()
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline inherited
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits) RenderQueue
setTiling()
void Ogre::v1::PanelOverlayElement::setTiling (Real x, Real y, ushort layer = 0)
Sets the number of times textures should repeat.
Parameters
x The number of times the texture should repeat horizontally
y The number of times the texture should repeat vertically
layer The texture layer to specify (only needs to be altered if you're using a multi-texture layer material)
setTop()
void Ogre::v1::OverlayElement::setTop (Real Top) inherited
Sets the top of this element in relation to the screen (where 0 = top, 1.0 = bottom)
setTransparent()
void Ogre::v1::PanelOverlayElement::setTransparent (bool isTransparent)
Sets whether this panel is transparent (used only as a grouping level), or if it is actually rendered.
setUseIdentityProjection()
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
setUseIdentityView()
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
setUserAny()
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
setUV()
void Ogre::v1::PanelOverlayElement::setUV (Real u1, Real v1, Real u2, Real v2)
Sets the texture coordinates for the panel.
setVerticalAlignment()
virtual void Ogre::v1::OverlayElement::setVerticalAlignment (GuiVerticalAlignment gva) virtual inherited
Sets the vertical origin for this element.
Remarks
By default, the vertical origin for a OverlayElement is the top edge of the parent container (or the screen if this is a root element). You can alter this by calling this method, which is especially useful when you want to use pixel-based metrics (see setMetricsMode) since in this mode you can't use relative positioning.
For example, if you were using GMM_PIXELS metrics mode, and you wanted to place a 30x30 pixel crosshair in the center of the screen, you would use GHA_CENTER with a 'top' property of -15.
Note that neither GVA_CENTER or GVA_BOTTOM alter the position of the element based on it's height, you have to alter the 'top' to a negative number to do that; all this does is establish the origin. This is because this way you can align multiple things in the center and bottom with different 'top' offsets for maximum flexibility.
setWidth()
void Ogre::v1::OverlayElement::setWidth (Real width) inherited
Sets the width of this element in relation to the screen (where 1.0 = screen width)
show()
virtual void Ogre::v1::OverlayElement::show (void) virtual inherited
Shows this element if it was hidden.
Member Data Documentation
mCustomParameter
uint8 Ogre::Renderable::mCustomParameter inherited
Only valid when using low level materials.
mHlmsGlobalIndex
uint32 Ogre::Renderable::mHlmsGlobalIndex inherited
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
The documentation for this class was generated from the following file:
OgrePanelOverlayElement.h