OGRE: Ogre::v1::D3D11NullPixelBuffer Class Reference
Ogre::v1::D3D11NullPixelBuffer Class Reference
#include <OgreD3D11NullTexture.h>
Public Types
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum UploadOptions { HBU_DEFAULT = 0x0000, HBU_ON_DEMAND = 0x0001 }
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
D3D11NullPixelBuffer (D3D11NullTexture *parentTexture, const String &baseName, uint32 width, uint32 height, uint32 Null, PixelFormat format)
virtual ~D3D11NullPixelBuffer ()
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
virtual void blit (const HardwarePixelBufferSharedPtr &src, const Image::Box &srcBox, const Image::Box &dstBox)
Copies a box from another PixelBuffer to a region of the this PixelBuffer.
void blit (const HardwarePixelBufferSharedPtr &src)
Convenience function that blits the entire source pixel buffer to this buffer.
virtual void blitFromMemory (const PixelBox &src, const Image::Box &dstBox)
Copies a region from normal memory to a region of this pixelbuffer.
void blitFromMemory (const PixelBox &src)
Convenience function that blits a pixelbox from memory to the entire buffer.
virtual void blitToMemory (const Image::Box &srcBox, const PixelBox &dst)
Copies a region of this pixelbuffer to normal memory.
void blitToMemory (const PixelBox &dst)
Convenience function that blits this entire buffer to a pixelbox.
virtual void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
const PixelBox & getCurrentLock ()
Get the current locked region.
uint32 getDepth () const
Gets the depth of this buffer.
PixelFormat getFormat () const
Gets the native pixel format of this buffer.
uint32 getHeight () const
Gets the height of this buffer.
virtual void * getRenderSystemData (void)
An internal function that should be used only by a render system for internal use.
virtual RenderTexture * getRenderTarget (size_t slice=0)
Get a render target for this PixelBuffer, or a slice of it.
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
uint32 getWidth () const
Gets the width of this buffer.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
Returns whether or not this buffer is currently locked.
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
virtual void * lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Make every lock method from HardwareBuffer available.
void * lock (LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Make every lock method from HardwareBuffer available.
virtual const PixelBox & lock (const Image::Box &lockBox, LockOptions options)
Lock the buffer for (potentially) reading / writing.
virtual void * lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the buffer for (potentially) reading / writing.
void * lock (LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the entire buffer for (potentially) reading / writing.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual void readData (size_t offset, size_t length, void *pDest)
Reads data from the buffer and places it in the memory pointed to by pDest.
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
virtual void unlock (void)
Releases the lock on this buffer.
virtual void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Member Enumeration Documentation
LockOptions
enum Ogre::v1::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
UploadOptions
enum Ogre::v1::HardwareBuffer::UploadOptions inherited
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
Enumerator
HBU_DEFAULT
HBU_ON_DEMAND
Usage
enum Ogre::v1::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Constructor & Destructor Documentation
D3D11NullPixelBuffer()
Ogre::v1::D3D11NullPixelBuffer::D3D11NullPixelBuffer (D3D11NullTexture * parentTexture, const String & baseName, uint32 width, uint32 height, uint32 Null, PixelFormat format)
~D3D11NullPixelBuffer()
virtual Ogre::v1::D3D11NullPixelBuffer::~D3D11NullPixelBuffer () virtual
Member Function Documentation
_updateFromShadow()
virtual void Ogre::v1::HardwareBuffer::_updateFromShadow (void) inline virtual inherited
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::MetalHardwareIndexBuffer, and Ogre::v1::MetalHardwareVertexBuffer.
blit() [1/2]
virtual void Ogre::v1::HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src, const Image::Box & srcBox, const Image::Box & dstBox) virtual inherited
Copies a box from another PixelBuffer to a region of the this PixelBuffer.
Parameters
src Source pixel buffer
srcBox Image::Box describing the source region in src
dstBox Image::Box describing the destination region in this buffer
Remarks
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note
Only call this function when both buffers are unlocked.
Reimplemented in Ogre::v1::MetalTextureBuffer, Ogre::v1::GLES2TextureBuffer, Ogre::v1::D3D11HardwarePixelBuffer, and Ogre::v1::GL3PlusTextureBuffer.
blit() [2/2]
void Ogre::v1::HardwarePixelBuffer::blit (const HardwarePixelBufferSharedPtr & src) inherited
Convenience function that blits the entire source pixel buffer to this buffer.
If source and destination dimensions don't match, scaling is done.
Parameters
src PixelBox containing the source pixels and format in memory
Note
Only call this function when the buffer is unlocked.
blitFromMemory() [1/2]
virtual void Ogre::v1::D3D11NullPixelBuffer::blitFromMemory (const PixelBox & src, const Image::Box & dstBox) virtual
Copies a region from normal memory to a region of this pixelbuffer.
The source image can be in any pixel format supported by OGRE, and in any size.
Parameters
src PixelBox containing the source pixels and format in memory
dstBox Image::Box describing the destination region in this buffer
Remarks
The source and destination regions dimensions don't have to match, in which case scaling is done. This scaling is generally done using a bilinear filter in hardware, but it is faster to pass the source image in the right dimensions.
Note
Only call this function when the buffer is unlocked.
Implements Ogre::v1::HardwarePixelBuffer.
blitFromMemory() [2/2]
void Ogre::v1::HardwarePixelBuffer::blitFromMemory (const PixelBox & src) inline inherited
Convenience function that blits a pixelbox from memory to the entire buffer.
The source image is scaled as needed.
Parameters
src PixelBox containing the source pixels and format in memory
Note
Only call this function when the buffer is unlocked.
blitToMemory() [1/2]
virtual void Ogre::v1::D3D11NullPixelBuffer::blitToMemory (const Image::Box & srcBox, const PixelBox & dst) virtual
Copies a region of this pixelbuffer to normal memory.
Parameters
srcBox Image::Box describing the source region of this buffer
dst PixelBox describing the destination pixels and format in memory
Remarks
The source and destination regions don't have to match, in which case scaling is done.
Note
Only call this function when the buffer is unlocked.
Implements Ogre::v1::HardwarePixelBuffer.
blitToMemory() [2/2]
void Ogre::v1::HardwarePixelBuffer::blitToMemory (const PixelBox & dst) inline inherited
Convenience function that blits this entire buffer to a pixelbox.
The image is scaled as needed.
Parameters
dst PixelBox describing the destination pixels and format in memory
Note
Only call this function when the buffer is unlocked.
copyData() [1/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) inline virtual inherited
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::GL3PlusHardwareUniformBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::GL3PlusHardwareShaderStorageBuffer, Ogre::v1::GL3PlusHardwareCounterBuffer, Ogre::v1::MetalHardwareIndexBuffer, Ogre::v1::MetalHardwareVertexBuffer, Ogre::v1::D3D11HardwareUniformBuffer, Ogre::v1::D3D11HardwareVertexBuffer, and Ogre::v1::D3D11HardwareIndexBuffer.
References Ogre::v1::HardwareBuffer::lock(), and Ogre::v1::HardwareBuffer::unlock().
copyData() [2/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References Ogre::v1::HardwareBuffer::getSizeInBytes(), and Ogre::min().
getCurrentLock()
const PixelBox& Ogre::v1::HardwarePixelBuffer::getCurrentLock () inherited
Get the current locked region.
This is the same value as returned by lock(const Image::Box, LockOptions)
Returns
PixelBox containing the locked region
getDepth()
uint32 Ogre::v1::HardwarePixelBuffer::getDepth () const inline inherited
Gets the depth of this buffer.
getFormat()
PixelFormat Ogre::v1::HardwarePixelBuffer::getFormat (void) const inline inherited
Gets the native pixel format of this buffer.
getHeight()
uint32 Ogre::v1::HardwarePixelBuffer::getHeight (void) const inline inherited
Gets the height of this buffer.
getRenderSystemData()
virtual void* Ogre::v1::HardwareBuffer::getRenderSystemData (void) inline virtual inherited
An internal function that should be used only by a render system for internal use.
Reimplemented in Ogre::v1::MetalHardwareIndexBuffer, and Ogre::v1::MetalHardwareVertexBuffer.
getRenderTarget()
virtual RenderTexture* Ogre::v1::D3D11NullPixelBuffer::getRenderTarget (size_t slice = 0) virtual
Get a render target for this PixelBuffer, or a slice of it.
The texture this was acquired from must have TU_RENDERTARGET set, otherwise it is possible to render to it and this method will throw an ERR_RENDERSYSTEM exception.
Parameters
slice Which slice
Returns
A pointer to the render target. This pointer has the lifespan of this PixelBuffer.
Reimplemented from Ogre::v1::HardwarePixelBuffer.
getSizeInBytes()
size_t Ogre::v1::HardwareBuffer::getSizeInBytes (void) const inline inherited
Returns the size of this buffer in bytes.
Referenced by Ogre::v1::HardwareBuffer::copyData().
getUsage()
Usage Ogre::v1::HardwareBuffer::getUsage (void) const inline inherited
Returns the Usage flags with which this buffer was created.
getWidth()
uint32 Ogre::v1::HardwarePixelBuffer::getWidth (void) const inline inherited
Gets the width of this buffer.
hasShadowBuffer()
bool Ogre::v1::HardwareBuffer::hasShadowBuffer (void) const inline inherited
Returns whether this buffer has a system memory shadow for quicker reading.
isLocked()
bool Ogre::v1::HardwareBuffer::isLocked (void) const inline inherited
Returns whether or not this buffer is currently locked.
References Ogre::v1::HardwareBuffer::isLocked().
Referenced by Ogre::v1::HardwareBuffer::isLocked(), and Ogre::v1::HardwareBuffer::unlock().
isSystemMemory()
bool Ogre::v1::HardwareBuffer::isSystemMemory (void) const inline inherited
Returns whether this buffer is held in system memory.
lock() [1/5]
virtual void* Ogre::v1::HardwareBuffer::lock inline inherited
Make every lock method from HardwareBuffer available.
See http://www.research.att.com/~bs/bs_faq2.html#overloadderived
lock() [2/5]
void* Ogre::v1::HardwareBuffer::lock inline inherited
Make every lock method from HardwareBuffer available.
See http://www.research.att.com/~bs/bs_faq2.html#overloadderived
lock() [3/5]
virtual const PixelBox& Ogre::v1::HardwarePixelBuffer::lock (const Image::Box & lockBox, LockOptions options) virtual inherited
Lock the buffer for (potentially) reading / writing.
Parameters
lockBox Region of the buffer to lock
options Locking options
Returns
PixelBox containing the locked region, the pitches and the pixel format
lock() [4/5]
virtual void* Ogre::v1::HardwarePixelBuffer::lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) virtual inherited
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns
Pointer to the locked memory
Reimplemented from Ogre::v1::HardwareBuffer.
lock() [5/5]
void* Ogre::v1::HardwareBuffer::lock (LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) inline inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
readData()
virtual void Ogre::v1::HardwarePixelBuffer::readData (size_t offset, size_t length, void * pDest) virtual inherited
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implements Ogre::v1::HardwareBuffer.
suppressHardwareUpdate()
void Ogre::v1::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline inherited
Pass true to suppress hardware upload of shadow buffer changes.
unlock()
virtual void Ogre::v1::HardwareBuffer::unlock (void) inline virtual inherited
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented in Ogre::v1::DefaultHardwareCounterBuffer, Ogre::v1::GL3PlusDefaultHardwareCounterBuffer, Ogre::v1::DefaultHardwareUniformBuffer, Ogre::v1::GL3PlusDefaultHardwareUniformBuffer, Ogre::v1::GLES2DefaultHardwareUniformBuffer, Ogre::v1::DefaultHardwareIndexBuffer, Ogre::v1::GL3PlusDefaultHardwareIndexBuffer, Ogre::v1::GLES2DefaultHardwareIndexBuffer, Ogre::v1::DefaultHardwareVertexBuffer, Ogre::v1::GL3PlusDefaultHardwareVertexBuffer, Ogre::v1::GLES2DefaultHardwareVertexBuffer, Ogre::v1::D3D11HardwareUniformBuffer, Ogre::v1::D3D11HardwareVertexBuffer, and Ogre::v1::D3D11HardwareIndexBuffer.
References Ogre::v1::HardwareBuffer::isLocked(), and Ogre::v1::HardwareBuffer::unlock().
Referenced by Ogre::v1::HardwareBuffer::copyData(), and Ogre::v1::HardwareBuffer::unlock().
writeData()
virtual void Ogre::v1::HardwarePixelBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual inherited
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implements Ogre::v1::HardwareBuffer.
The documentation for this class was generated from the following file:
OgreD3D11NullTexture.h