OGRE: Ogre::ImageCodec Class Reference
Ogre::ImageCodec Class Reference abstract
Core » Image
Codec specialized in images.
#include <OgreImageCodec.h>
Classes
class ImageData
Codec return class for images.
Public Types
typedef SharedPtr< CodecData > CodecDataPtr
typedef ConstMapIterator< CodecList > CodecIterator
typedef std::pair< MemoryDataStreamPtr, CodecDataPtr > DecodeResult
Result of a decoding; both a decoded data stream and CodecData metadata.
Public Member Functions
virtual ~ImageCodec ()
virtual DecodeResult decode (DataStreamPtr &input) const =0
Codes the data from the input chunk into the output chunk.
virtual DataStreamPtr encode (MemoryDataStreamPtr &input, CodecDataPtr &pData) const =0
Codes the data in the input stream and saves the result in the output stream.
virtual void encodeToFile (MemoryDataStreamPtr &input, const String &outFileName, CodecDataPtr &pData) const =0
Codes the data in the input chunk and saves the result in the output filename provided.
String getDataType () const
Returns the type of the data that supported by this codec as a String.
virtual String getType () const =0
Returns the type of the codec as a String.
virtual bool magicNumberMatch (const char *magicNumberPtr, size_t maxbytes) const
Returns whether a magic number header matches this codec.
virtual String magicNumberToFileExt (const char *magicNumberPtr, size_t maxbytes) const =0
Maps a magic number header to a file extension, if this codec recognises it.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
Static Public Member Functions
static Codec * getCodec (const String &extension)
Gets the codec registered for the passed in file extension.
static Codec * getCodec (char *magicNumberPtr, size_t maxbytes)
Gets the codec that can handle the given 'magic' identifier.
static CodecIterator getCodecIterator (void)
Gets the iterator for the registered codecs.
static StringVector getExtensions (void)
Gets the file extension list for the registered codecs.
static bool isCodecRegistered (const String &codecType)
Return whether a codec is registered already.
static void registerCodec (Codec *pCodec)
Registers a new codec in the database.
static void unregisterCodec (Codec *pCodec)
Unregisters a codec from the database.
Detailed Description
Codec specialized in images.
Remarks
The users implementing subclasses of ImageCodec are required to return a valid pointer to a ImageData class from the decode(...) function.
Member Typedef Documentation
typedef SharedPtr<CodecData> Ogre::Codec::CodecDataPtr inherited
typedef ConstMapIterator<CodecList> Ogre::Codec::CodecIterator inherited
typedef std::pair<MemoryDataStreamPtr, CodecDataPtr> Ogre::Codec::DecodeResult inherited
Result of a decoding; both a decoded data stream and CodecData metadata.
Constructor & Destructor Documentation
virtual Ogre::ImageCodec::~ImageCodec () virtual
Member Function Documentation
virtual DecodeResult Ogre::Codec::decode (DataStreamPtr & input) const pure virtual inherited
Codes the data from the input chunk into the output chunk.
Parameters
input Stream containing the encoded data
Implemented in Ogre::DDSCodec, Ogre::FreeImageCodec, Ogre::ETCCodec, Ogre::PVRTCCodec, and Ogre::STBIImageCodec.
virtual DataStreamPtr Ogre::Codec::encode (MemoryDataStreamPtr & input, CodecDataPtr & pData) const pure virtual inherited
Codes the data in the input stream and saves the result in the output stream.
Implemented in Ogre::DDSCodec, Ogre::FreeImageCodec, Ogre::ETCCodec, Ogre::PVRTCCodec, and Ogre::STBIImageCodec.
virtual void Ogre::Codec::encodeToFile (MemoryDataStreamPtr & input, const String & outFileName, CodecDataPtr & pData) const pure virtual inherited
Codes the data in the input chunk and saves the result in the output filename provided.
Provided for efficiency since coding to memory is progressive therefore memory required is unknown leading to reallocations.
Parameters
input The input data
outFileName The filename to write to
pData Extra information to be passed to the codec (codec type specific)
Implemented in Ogre::DDSCodec, Ogre::FreeImageCodec, Ogre::ETCCodec, Ogre::PVRTCCodec, and Ogre::STBIImageCodec.
static Codec* Ogre::Codec::getCodec (const String & extension) static inherited
Gets the codec registered for the passed in file extension.
static Codec* Ogre::Codec::getCodec (char * magicNumberPtr, size_t maxbytes) static inherited
Gets the codec that can handle the given 'magic' identifier.
Parameters
magicNumberPtr Pointer to a stream of bytes which should identify the file. Note that this may be more than needed - each codec may be looking for a different size magic number.
maxbytes The number of bytes passed
static CodecIterator Ogre::Codec::getCodecIterator (void) inline static inherited
Gets the iterator for the registered codecs.
String Ogre::ImageCodec::getDataType () const inline virtual
Returns the type of the data that supported by this codec as a String.
Implements Ogre::Codec.
static StringVector Ogre::Codec::getExtensions (void) static inherited
Gets the file extension list for the registered codecs.
virtual String Ogre::Codec::getType () const pure virtual inherited
Returns the type of the codec as a String.
Implemented in Ogre::DDSCodec, Ogre::FreeImageCodec, Ogre::ETCCodec, Ogre::PVRTCCodec, and Ogre::STBIImageCodec.
Referenced by Ogre::Codec::registerCodec(), and Ogre::Codec::unregisterCodec().
static bool Ogre::Codec::isCodecRegistered (const String & codecType) inline static inherited
Return whether a codec is registered already.
virtual bool Ogre::Codec::magicNumberMatch (const char * magicNumberPtr, size_t maxbytes) const inline virtual inherited
Returns whether a magic number header matches this codec.
Parameters
magicNumberPtr Pointer to a stream of bytes which should identify the file. Note that this may be more than needed - each codec may be looking for a different size magic number.
maxbytes The number of bytes passed
virtual String Ogre::Codec::magicNumberToFileExt (const char * magicNumberPtr, size_t maxbytes) const pure virtual inherited
Maps a magic number header to a file extension, if this codec recognises it.
Parameters
magicNumberPtr Pointer to a stream of bytes which should identify the file. Note that this may be more than needed - each codec may be looking for a different size magic number.
maxbytes The number of bytes passed
Returns
A blank string if the magic number was unknown, or a file extension.
Implemented in Ogre::DDSCodec, Ogre::FreeImageCodec, Ogre::ETCCodec, Ogre::STBIImageCodec, and Ogre::PVRTCCodec.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
static void Ogre::Codec::registerCodec (Codec * pCodec) inline static inherited
Registers a new codec in the database.
References Ogre::Exception::ERR_DUPLICATE_ITEM, Ogre::Codec::getType(), and OGRE_EXCEPT.
static void Ogre::Codec::unregisterCodec (Codec * pCodec) inline static inherited
Unregisters a codec from the database.
References Ogre::Codec::getType().
The documentation for this class was generated from the following file:
OgreImageCodec.h