OGRE: Ogre::v1::D3D11HardwareVertexBuffer Class Reference
Ogre::v1::D3D11HardwareVertexBuffer Class Reference
Specialisation of HardwareVertexBuffer for D3D11.
#include <OgreD3D11HardwareVertexBuffer.h>
Public Types
enum LockOptions {
HBL_NORMAL, HBL_DISCARD, HBL_READ_ONLY, HBL_NO_OVERWRITE,
HBL_WRITE_ONLY
}
Locking options.
enum UploadOptions { HBU_DEFAULT = 0x0000, HBU_ON_DEMAND = 0x0001 }
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
enum Usage {
HBU_STATIC = 1, HBU_DYNAMIC = 2, HBU_WRITE_ONLY = 4, HBU_DISCARDABLE = 8,
HBU_STATIC_WRITE_ONLY = 5, HBU_DYNAMIC_WRITE_ONLY = 6, HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE = 14
}
Enums describing buffer usage; not mutually exclusive.
Public Member Functions
D3D11HardwareVertexBuffer (HardwareBufferManagerBase *mgr, size_t vertexSize, size_t numVertices, HardwareBuffer::Usage usage, D3D11Device &device, bool useSystemMem, bool useShadowBuffer, bool streamOut)
~D3D11HardwareVertexBuffer ()
virtual void _updateFromShadow (void)
Updates the real buffer from the shadow buffer, if required.
void copyData (HardwareBuffer &srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer=false)
Copy data from another buffer into this one.
virtual void copyData (HardwareBuffer &srcBuffer)
Copy all data from another buffer into this one.
ID3D11Buffer * getD3DVertexBuffer (void) const
Get the D3D-specific vertex buffer.
size_t getInstanceDataStepRate () const
Get the number of instances to draw using the same per-instance data before advancing in the buffer by one element.
bool getIsInstanceData () const
Get if this vertex buffer is an "instance data" buffer (per instance)
HardwareBufferManagerBase * getManager () const
Return the manager of this buffer, if any.
size_t getNumVertices (void) const
Get the number of vertices in this buffer.
virtual void * getRenderSystemData (void)
An internal function that should be used only by a render system for internal use.
size_t getSizeInBytes (void) const
Returns the size of this buffer in bytes.
Usage getUsage (void) const
Returns the Usage flags with which this buffer was created.
size_t getVertexSize (void) const
Gets the size in bytes of a single vertex in this buffer.
bool hasShadowBuffer (void) const
Returns whether this buffer has a system memory shadow for quicker reading.
bool isLocked (void) const
bool isSystemMemory (void) const
Returns whether this buffer is held in system memory.
void * lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the buffer for (potentially) reading / writing.
void * lock (LockOptions options, UploadOptions uploadOpt=HBU_DEFAULT)
Lock the entire buffer for (potentially) reading / writing.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
void readData (size_t offset, size_t length, void *pDest)
Reads data from the buffer and places it in the memory pointed to by pDest.
void setInstanceDataStepRate (const size_t val)
Set the number of instances to draw using the same per-instance data before advancing in the buffer by one element.
void setIsInstanceData (const bool val)
Set if this vertex buffer is an "instance data" buffer (per instance)
void suppressHardwareUpdate (bool suppress)
Pass true to suppress hardware upload of shadow buffer changes.
void unlock (void)
Releases the lock on this buffer.
void writeData (size_t offset, size_t length, const void *pSource, bool discardWholeBuffer=false)
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Detailed Description
Specialisation of HardwareVertexBuffer for D3D11.
Member Enumeration Documentation
LockOptions
enum Ogre::v1::HardwareBuffer::LockOptions inherited
Locking options.
Enumerator
HBL_NORMAL
Normal mode, ie allows read/write and contents are preserved.
HBL_DISCARD
Discards the entire buffer while locking; this allows optimisation to be performed because synchronisation issues are relaxed.
Only allowed on buffers created with the HBU_DYNAMIC flag.
HBL_READ_ONLY
Lock the buffer for reading only.
Not allowed in buffers which are created with HBU_WRITE_ONLY. Mandatory on static buffers, i.e. those created without the HBU_DYNAMIC flag.
HBL_NO_OVERWRITE
As HBL_DISCARD, except the application guarantees not to overwrite any region of the buffer which has already been used in this frame, can allow some optimisation on some APIs.
HBL_WRITE_ONLY
Lock the buffer for writing only.
UploadOptions
enum Ogre::v1::HardwareBuffer::UploadOptions inherited
Device load options The following enum is used to controls how data is loaded to devices in a multi device environment This enum only works with the Direct3D 9 render system (5/2013).
Enumerator
HBU_DEFAULT
HBU_ON_DEMAND
Usage
enum Ogre::v1::HardwareBuffer::Usage inherited
Enums describing buffer usage; not mutually exclusive.
Enumerator
HBU_STATIC
Static buffer which the application rarely modifies once created.
Modifying the contents of this buffer will involve a performance hit.
HBU_DYNAMIC
Indicates the application would like to modify this buffer with the CPU fairly often.
Buffers created with this flag will typically end up in AGP memory rather than video memory.
HBU_WRITE_ONLY
Indicates the application will never read the contents of the buffer back, it will only ever write data.
Locking a buffer with this flag will ALWAYS return a pointer to new, blank memory rather than the memory associated with the contents of the buffer; this avoids DMA stalls because you can write to a new memory area while the previous one is being used.
HBU_DISCARDABLE
Indicates that the application will be refilling the contents of the buffer regularly (not just updating, but generating the contents from scratch), and therefore does not mind if the contents of the buffer are lost somehow and need to be recreated.
This allows and additional level of optimisation on the buffer. This option only really makes sense when combined with HBU_DYNAMIC_WRITE_ONLY.
HBU_STATIC_WRITE_ONLY
Combination of HBU_STATIC and HBU_WRITE_ONLY.
HBU_DYNAMIC_WRITE_ONLY
Combination of HBU_DYNAMIC and HBU_WRITE_ONLY.
If you use this, strongly consider using HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE instead if you update the entire contents of the buffer very regularly.
HBU_DYNAMIC_WRITE_ONLY_DISCARDABLE
Combination of HBU_DYNAMIC, HBU_WRITE_ONLY and HBU_DISCARDABLE.
Constructor & Destructor Documentation
D3D11HardwareVertexBuffer()
Ogre::v1::D3D11HardwareVertexBuffer::D3D11HardwareVertexBuffer (HardwareBufferManagerBase * mgr, size_t vertexSize, size_t numVertices, HardwareBuffer::Usage usage, D3D11Device & device, bool useSystemMem, bool useShadowBuffer, bool streamOut)
~D3D11HardwareVertexBuffer()
Ogre::v1::D3D11HardwareVertexBuffer::~D3D11HardwareVertexBuffer ()
Member Function Documentation
_updateFromShadow()
virtual void Ogre::v1::HardwareBuffer::_updateFromShadow (void) inline virtual inherited
Updates the real buffer from the shadow buffer, if required.
Reimplemented in Ogre::v1::D3D11HardwareBuffer, Ogre::v1::GL3PlusHardwareVertexBuffer, Ogre::v1::GL3PlusHardwareIndexBuffer, Ogre::v1::MetalHardwareIndexBuffer, and Ogre::v1::MetalHardwareVertexBuffer.
copyData() [1/2]
void Ogre::v1::D3D11HardwareVertexBuffer::copyData (HardwareBuffer & srcBuffer, size_t srcOffset, size_t dstOffset, size_t length, bool discardWholeBuffer = false) virtual
Copy data from another buffer into this one.
Remarks
Note that the source buffer must not be created with the usage HBU_WRITE_ONLY otherwise this will fail.
Parameters
srcBuffer The buffer from which to read the copied data
srcOffset Offset in the source buffer at which to start reading
dstOffset Offset in the destination buffer to start writing
length Length of the data to copy, in bytes.
discardWholeBuffer If true, will discard the entire contents of this buffer before copying
Reimplemented from Ogre::v1::HardwareBuffer.
copyData() [2/2]
virtual void Ogre::v1::HardwareBuffer::copyData (HardwareBuffer & srcBuffer) inline virtual inherited
Copy all data from another buffer into this one.
Remarks
Normally these buffers should be of identical size, but if they're not, the routine will use the smallest of the two sizes.
References Ogre::v1::HardwareBuffer::getSizeInBytes(), and Ogre::min().
getD3DVertexBuffer()
ID3D11Buffer* Ogre::v1::D3D11HardwareVertexBuffer::getD3DVertexBuffer (void) const
Get the D3D-specific vertex buffer.
getRenderSystemData()
virtual void* Ogre::v1::HardwareBuffer::getRenderSystemData (void) inline virtual inherited
An internal function that should be used only by a render system for internal use.
Reimplemented in Ogre::v1::MetalHardwareIndexBuffer, and Ogre::v1::MetalHardwareVertexBuffer.
getSizeInBytes()
size_t Ogre::v1::HardwareBuffer::getSizeInBytes (void) const inline inherited
Returns the size of this buffer in bytes.
Referenced by Ogre::v1::HardwareBuffer::copyData().
getUsage()
Usage Ogre::v1::HardwareBuffer::getUsage (void) const inline inherited
Returns the Usage flags with which this buffer was created.
hasShadowBuffer()
bool Ogre::v1::HardwareBuffer::hasShadowBuffer (void) const inline inherited
Returns whether this buffer has a system memory shadow for quicker reading.
isLocked()
bool Ogre::v1::D3D11HardwareVertexBuffer::isLocked (void) const
isSystemMemory()
bool Ogre::v1::HardwareBuffer::isSystemMemory (void) const inline inherited
Returns whether this buffer is held in system memory.
lock() [1/2]
void* Ogre::v1::D3D11HardwareVertexBuffer::lock (size_t offset, size_t length, LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) virtual
Lock the buffer for (potentially) reading / writing.
Parameters
offset The byte offset from the start of the buffer to lock
length The size of the area to lock, in bytes
options Locking options
Returns
Pointer to the locked memory
Reimplemented from Ogre::v1::HardwareBuffer.
lock() [2/2]
void* Ogre::v1::HardwareBuffer::lock (LockOptions options, UploadOptions uploadOpt = HBU_DEFAULT) inline inherited
Lock the entire buffer for (potentially) reading / writing.
Parameters
options Locking options
Returns
Pointer to the locked memory
operator delete() [1/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
operator delete() [2/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
operator delete() [3/3]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
operator delete[]() [1/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
operator delete[]() [2/2]
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
operator new() [1/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
operator new() [2/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
operator new() [3/3]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
operator new[]() [1/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
operator new[]() [2/2]
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
readData()
void Ogre::v1::D3D11HardwareVertexBuffer::readData (size_t offset, size_t length, void * pDest) virtual
Reads data from the buffer and places it in the memory pointed to by pDest.
Parameters
offset The byte offset from the start of the buffer to read
length The size of the area to read, in bytes
pDest The area of memory in which to place the data, must be large enough to accommodate the data!
Implements Ogre::v1::HardwareBuffer.
suppressHardwareUpdate()
void Ogre::v1::HardwareBuffer::suppressHardwareUpdate (bool suppress) inline inherited
Pass true to suppress hardware upload of shadow buffer changes.
unlock()
void Ogre::v1::D3D11HardwareVertexBuffer::unlock (void) virtual
Releases the lock on this buffer.
Remarks
Locking and unlocking a buffer can, in some rare circumstances such as switching video modes whilst the buffer is locked, corrupt the contents of a buffer. This is pretty rare, but if it occurs, this method will throw an exception, meaning you must re-upload the data.
Note that using the 'read' and 'write' forms of updating the buffer does not suffer from this problem, so if you want to be 100% sure your data will not be lost, use the 'read' and 'write' forms instead.
Reimplemented from Ogre::v1::HardwareBuffer.
writeData()
void Ogre::v1::D3D11HardwareVertexBuffer::writeData (size_t offset, size_t length, const void * pSource, bool discardWholeBuffer = false) virtual
Writes data to the buffer from an area of system memory; note that you must ensure that your buffer is big enough.
Parameters
offset The byte offset from the start of the buffer to start writing
length The size of the data to write to, in bytes
pSource The source of the data to be written
discardWholeBuffer If true, this allows the driver to discard the entire buffer when writing, such that DMA stalls can be avoided; use if you can.
Implements Ogre::v1::HardwareBuffer.
The documentation for this class was generated from the following file:
OgreD3D11HardwareVertexBuffer.h