OGRE: Ogre::LodStrategy Class Reference
Ogre::LodStrategy Class Reference abstract
Core » LOD
Strategy for determining level of detail.
#include <OgreLodStrategy.h>
Public Member Functions
LodStrategy (const String &name)
Constructor accepting name.
virtual ~LodStrategy ()
Virtual destructor.
virtual Real getBaseValue () const =0
Get the value of the first (highest) level of detail.
const String & getName () const
Get the name of this strategy.
Real getValue (const MovableObject *movableObject, const Camera *camera) const
Compute the LOD value for a given movable object relative to a given camera.
virtual void lodUpdateImpl (const size_t numNodes, ObjectData t, const Camera *camera, Real bias) const =0
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
virtual Real transformBias (Real factor) const =0
Transform LOD bias so it only needs to be multiplied by the LOD value.
virtual Real transformUserValue (Real userValue) const
Transform user supplied value to internal value.
Static Public Member Functions
static void assertSorted (const v1::Mesh::LodValueArray &values)
Assert that the LOD values are sorted from greatest detail to least detail.
static ushort getIndex (Real value, const v1::Mesh::MeshLodUsageList &meshLodUsageList)
Get the index of the LOD usage which applies to a given value.
static ushort getIndex (Real value, const Material::LodValueArray &materialLodValueArray)
Get the index of the LOD usage which applies to a given value.
static bool isSorted (const v1::Mesh::LodValueArray &values)
Determine if the LOD values are sorted from greatest detail to least detail.
static void lodSet (ObjectData &t, Real lodValues[ARRAY_PACKED_REALS])
static void sort (v1::Mesh::MeshLodUsageList &meshLodUsageList)
Sort mesh LOD usage list from greatest to least detail.
Detailed Description
Strategy for determining level of detail.
Remarks
Generally, to create a new LOD strategy, all of the following will need to be implemented: getValueImpl, getBaseValue, transformBias, getIndex, sort, and isSorted. In addition, transformUserValue may be overridden.
Constructor & Destructor Documentation
Ogre::LodStrategy::LodStrategy (const String & name)
Constructor accepting name.
virtual Ogre::LodStrategy::~LodStrategy () virtual
Virtual destructor.
Member Function Documentation
static void Ogre::LodStrategy::assertSorted (const v1::Mesh::LodValueArray & values) static
Assert that the LOD values are sorted from greatest detail to least detail.
virtual Real Ogre::LodStrategy::getBaseValue () const pure virtual
Get the value of the first (highest) level of detail.
Implemented in Ogre::DistanceLodStrategyBase, and Ogre::PixelCountLodStrategyBase.
static ushort Ogre::LodStrategy::getIndex (Real value, const v1::Mesh::MeshLodUsageList & meshLodUsageList) static
Get the index of the LOD usage which applies to a given value.
static ushort Ogre::LodStrategy::getIndex (Real value, const Material::LodValueArray & materialLodValueArray) static
Get the index of the LOD usage which applies to a given value.
const String& Ogre::LodStrategy::getName (void) const inline
Get the name of this strategy.
Real Ogre::LodStrategy::getValue (const MovableObject * movableObject, const Camera * camera) const
Compute the LOD value for a given movable object relative to a given camera.
static bool Ogre::LodStrategy::isSorted (const v1::Mesh::LodValueArray & values) static
Determine if the LOD values are sorted from greatest detail to least detail.
static void Ogre::LodStrategy::lodSet (ObjectData & t, Real lodValues[ARRAY_PACKED_REALS]) inline static
Referenced by Ogre::Renderable::getCurrentMaterialLod(), and Ogre::MovableObject::instanceBatchCullFrustumThreaded().
virtual void Ogre::LodStrategy::lodUpdateImpl (const size_t numNodes, ObjectData t, const Camera * camera, Real bias) const pure virtual
Implemented in Ogre::ScreenRatioPixelCountLodStrategy, Ogre::AbsolutePixelCountLodStrategy, and Ogre::DistanceLodStrategyBase.
Referenced by Ogre::MovableObject::instanceBatchCullFrustumThreaded().
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
static void Ogre::LodStrategy::sort (v1::Mesh::MeshLodUsageList & meshLodUsageList) static
Sort mesh LOD usage list from greatest to least detail.
virtual Real Ogre::LodStrategy::transformBias (Real factor) const pure virtual
Transform LOD bias so it only needs to be multiplied by the LOD value.
Implemented in Ogre::DistanceLodStrategyBase, and Ogre::PixelCountLodStrategyBase.
virtual Real Ogre::LodStrategy::transformUserValue (Real userValue) const virtual
Transform user supplied value to internal value.
Remarks
By default, performs no transformation.
Do not throw exceptions for invalid values here, as the LOD strategy may be changed such that the values become valid.
Reimplemented in Ogre::DistanceLodStrategyBase, and Ogre::PixelCountLodStrategyBase.
The documentation for this class was generated from the following file:
OgreLodStrategy.h