OGRE: Ogre::v1::InstanceBatchHW_VTF Class Reference
Ogre::v1::InstanceBatchHW_VTF Class Reference
Core » Scene
Instancing implementation using vertex texture through Vertex Texture Fetch (VTF) and hardware instancing.
#include <OgreInstanceBatchHW_VTF.h>
Public Types
typedef vector< Vector4 >::type CustomParamsVec
typedef FastArray< InstancedEntity * > InstancedEntityArray
typedef vector< InstancedEntity * >::type InstancedEntityVec
typedef FastArray< MovableObject * > MovableObjectArray
SceneManager::cullFrustum
enum SkeletalAnimationMode { SKELETONS_NOT_SUPPORTED, SKELETONS_SUPPORTED, SKELETONS_LUT }
Public Member Functions
InstanceBatchHW_VTF (IdType id, ObjectMemoryManager *objectMemoryManager, InstanceManager *creator, MeshPtr &meshReference, const MaterialPtr &material, size_t instancesPerBatch, const Mesh::IndexMap *indexToBoneMap)
virtual ~InstanceBatchHW_VTF ()
void _boundsDirty (void)
void _defragmentBatch (bool optimizeCulling, InstancedEntityVec &usedEntities, CustomParamsVec &usedParams)
void _defragmentBatchDiscard (void)
const Vector4 & _getCustomParam (InstancedEntity *instancedEntity, unsigned char idx)
const Mesh::IndexMap * _getIndexToBoneMap () const
LightList * _getLightList ()
Returns a pointer to the current list of lights for this object.
SceneManager * _getManager (void) const
Get the manager of this object, if any (internal use only)
MeshPtr & _getMeshRef ()
const Ogre::v1::MeshPtr & _getMeshReference (void) const
ObjectData & _getObjectData ()
Returns a direct access to the ObjectData state.
const Matrix4 & _getParentNodeFullTransform (void) const
Returns the full transformation of the parent sceneNode or the attachingPoint node.
void _markTransformSharingDirty ()
Tells that the list of entity instances with shared transforms has changed.
virtual void _notifyAttached (Node *parent)
Internal method called to notify the object that it has been attached to a node.
void _notifyManager (SceneManager *man)
Notify the object of it's manager (internal use only)
virtual void _notifyParentNodeMemoryChanged (void)
Node::_callMemoryChangeListeners
virtual void _notifyStaticDirty (void) const
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
virtual void _notifyStaticDirty (void)
Called by InstancedEntity(s) or directly to tell us we need to update the bounds Should only useful if this batch is static.
void _setCustomParam (InstancedEntity *instancedEntity, unsigned char idx, const Vector4 &newParam)
virtual void _setHlmsHashes (uint32 hash, uint32 casterHash)
Manually sets the hlms hashes. Don't call this directly.
void _setInstancesPerBatch (size_t instancesPerBatch)
Raises an exception if trying to change it after being built.
virtual void _setNullDatablock (void)
Sets the datablock to a null pointer.
SkeletalAnimationMode _supportsSkeletalAnimation () const
Returns true if this technique supports skeletal animation.
void _updateBounds (void)
virtual void _updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry &constantEntry, GpuProgramParameters *params) const
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
void _updateEntitiesBoundsThread (size_t threadIdx)
Updates the bounds of only our entities from multiple threads.
virtual void _updateRenderQueue (RenderQueue *queue, Camera *camera, const Camera *lodCamera)
Overloaded to visibility on a per unit basis and finally updated the vertex texture.
void addQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void addVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
virtual RenderOperation build (const SubMesh *baseSubMesh)
Constructs all the data needed to use this batch, as well as the InstanceEntities.
void buildFrom (const SubMesh *baseSubMesh, const RenderOperation &renderOperation)
size_t calculateMaxNumInstances (const SubMesh *baseSubMesh, uint16 flags) const
virtual AnimableValuePtr createAnimableValue (const String &valueName)
Create a reference-counted AnimableValuePtr for the named value.
InstancedEntity * createInstancedEntity ()
Returns a pointer to a new InstancedEntity ready to use Note it's actually preallocated, so no memory allocation happens at this point.
void detachFromParent (void)
Detaches an object from a parent SceneNode if attached.
bool forceOneWeight () const
const StringVector & getAnimableValueNames (void) const
Gets a list of animable value names for this object.
RealAsUint getCachedDistanceToCamera (void) const
Returns the distance to camera as calculated in .
Real getCachedDistanceToCameraAsReal (void) const
Returns the distance to camera as calculated in .
bool getCastShadows (void) const
Returns whether shadow casting is enabled for this object.
virtual bool getCastsShadows (void) const
Method which reports whether this renderable would normally cast a shadow.
uint8 getCurrentMaterialLod (void) const
unsigned char getCurrentMeshLod (void) const
const Vector4 & getCustomParameter (size_t index) const
Gets the custom value associated with this Renderable at the given index.
HlmsDatablock * getDatablock (void) const
uint32 getHlmsCasterHash (void) const
uint32 getHlmsHash (void) const
IdType getId () const
Get the unique id of this object.
void getInstancedEntitiesInUse (InstancedEntityVec &outEntities, CustomParamsVec &outParams)
Fills the input vector with the instances that are currently being used or were requested.
uint32 getLightMask () const
Get a bitwise mask which will filter the lights affecting this object.
const LightList & getLights (void) const
Listener * getListener (void) const
Gets the current listener for this object.
Aabb getLocalAabb (void) const
Retrieves the local axis-aligned bounding box for this object.
MaterialPtr getMaterial (void) const
Retrieves the material this renderable object uses.
virtual size_t getMaxLookupTableInstances () const
const String & getMovableType (void) const
const String & getName (void) const
Returns the name of this object.
unsigned short getNumWorldTransforms (void) const
Returns the number of world transform matrices this renderable requires.
Node * getParentNode (void) const
Returns the node to which this object is attached.
SceneNode * getParentSceneNode (void) const
virtual bool getPolygonModeOverrideable (void) const
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
uint32 getQueryFlags (void) const
Returns the query flags relevant for this object.
Real getRenderingDistance (void) const
Gets the distance at which batches are no longer rendered.
Real getRenderingMinPixelSize () const
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
void getRenderOperation (RenderOperation &op, bool casterPass)
uint8 getRenderQueueGroup (void) const
Gets the queue group for this entity, see setRenderQueueGroup for full details.
uint8 getRenderQueueSubGroup (void) const
SkeletonInstance * getSkeletonInstance (void) const
Real getSquaredViewDepth (const Camera *cam) const
bool getUseIdentityProjection (void) const
Returns whether or not to use an 'identity' projection.
bool getUseIdentityView (void) const
Returns whether or not to use an 'identity' view.
virtual bool getUseIdentityViewProjMatrixIsDynamic (void) const
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
virtual bool getUseIdentityWorldMatrix (void) const
Returns whether the world matrix is an identify matrix.
virtual OGRE_DEPRECATED const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
UserObjectBindings & getUserObjectBindings ()
Return an instance of user objects binding associated with this class.
const UserObjectBindings & getUserObjectBindings () const
Return an instance of user objects binding associated with this class.
const VertexArrayObjectArray & getVaos (VertexPass vertexPass) const
uint32 getVisibilityFlags (void) const
Returns the visibility flags relevant for this object.
bool getVisible (void) const
Gets this object whether to be visible or not, if it has a renderable component.
Aabb getWorldAabb () const
Gets the axis aligned box in world space.
Aabb getWorldAabbUpdated ()
Gets the axis aligned box in world space.
float getWorldRadius () const
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
float getWorldRadiusUpdated ()
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
void getWorldTransforms (Matrix4 *xform) const
Gets the world transform matrix / matrices for this renderable object.
bool hasCustomParameter (size_t index) const
Checks whether a custom value is associated with this Renderable at the given index.
bool hasSkeletonAnimation (void) const
virtual void instanceBatchCullFrustumThreaded (const Camera *frustum, const Camera *lodCamera, uint32 combinedVisibilityFlags)
virtual void instanceBatchCullFrustumThreaded (const Frustum *frustum, const Camera *lodCamera, uint32 combinedVisibilityFlags)
InstancingTheadedCullingMethod,
bool isAttached (void) const
Returns true if this object is attached to a Node.
bool isBatchFull (void) const
bool isBatchUnused (void) const
Returns true if it no instanced entity has been requested or all of them have been removed.
bool isStatic () const
Checks whether this MovableObject is static. setStatic.
bool isVisible (void) const
Returns whether or not this object is supposed to be visible or not.
void operator delete (void *ptr)
void operator delete (void *ptr, void *)
void operator delete (void *ptr, const char *, int, const char *)
void operator delete[] (void *ptr)
void operator delete[] (void *ptr, const char *, int, const char *)
void * operator new (size_t sz, const char *file, int line, const char *func)
operator new, with debug line info
void * operator new (size_t sz)
void * operator new (size_t sz, void *ptr)
placement operator new
void * operator new[] (size_t sz, const char *file, int line, const char *func)
array operator new, with debug line info
void * operator new[] (size_t sz)
bool operator() (const IdObject *left, const IdObject *right)
bool operator() (const IdObject &left, const IdObject &right)
virtual void postRender (SceneManager *sm, RenderSystem *rsys)
Called immediately after the Renderable has been rendered.
virtual bool preRender (SceneManager *sm, RenderSystem *rsys)
Called just prior to the Renderable being rendered.
const LightList & queryLights (void) const
Gets a list of lights, ordered relative to how close they are to this movable object.
void removeCustomParameter (size_t index)
Removes a custom value which is associated with this Renderable at the given index.
void removeInstancedEntity (InstancedEntity *instancedEntity)
Removes an InstancedEntity from the scene retrieved with getNewInstancedEntity, putting back into a queue.
void removeQueryFlags (uint32 flags)
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void removeVisibilityFlags (uint32 flags)
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void setBoneDualQuaternions (bool enable)
void setBoneMatrixLookup (bool enable, size_t maxLookupTableInstances)
Sets the state of the usage of bone matrix lookup.
void setCastShadows (bool enabled)
Sets whether or not this object will cast shadows.
void setCustomParameter (size_t index, const Vector4 &value)
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
void setDatablock (IdString datablockName)
Assigns a datablock (i.e.
virtual void setDatablock (HlmsDatablock *datablock)
Assigns a datablock (i.e. HLMS Material) to this renderable.
void setDatablockOrMaterialName (String materialName, String groupName)
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
void setForceOneWeight (bool enable)
void setLightMask (uint32 lightMask)
Set a bitwise mask which will filter the lights affecting this object.
void setListener (Listener *listener)
Sets a listener for this object.
void setLocalAabb (const Aabb box)
Sets the local axis-aligned bounding box for this object.
virtual void setMaterial (const MaterialPtr &material)
Sets the given material. Overrides HLMS materials.
void setMaterialName (const String &name, const String &groupName)
Sets the name of the Material to be used. Prefer using HLMS setHlms.
void setName (const String &name)
Sets a custom name for this node.
virtual void setPolygonModeOverrideable (bool override)
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
void setQueryFlags (uint32 flags)
Sets the query flags for this object.
void setRenderingDistance (Real dist)
Sets the distance at which the object is no longer rendered.
void setRenderingMinPixelSize (Real pixelSize)
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
virtual void setRenderQueueGroup (uint8 queueID)
Sets the render queue group this entity will be rendered through.
void setRenderQueueSubGroup (uint8 subGroup)
Sets the render queue sub group.
bool setStatic (bool bStatic)
Tells this batch to stop updating animations, positions, rotations, and display all it's active instances.
void setUseIdentityProjection (bool useIdentityProjection)
Sets whether or not to use an 'identity' projection.
void setUseIdentityView (bool useIdentityView)
Sets whether or not to use an 'identity' view.
void setUseOneWeight (bool enable)
virtual OGRE_DEPRECATED void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
Sets the visibility flags for this object.
void setVisible (bool visible)
Tells this object whether to be visible or not, if it has a renderable component.
bool useBoneDualQuaternions () const
bool useBoneMatrixLookup () const
Tells whether to use bone matrix lookup.
bool useOneWeight () const
Static Public Member Functions
static void buildLightList (const size_t numNodes, ObjectData t, const LightListInfo &globalLightList)
SceneManager::buildLightList
static void calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox *outBox)
static void cullFrustum (const size_t numNodes, ObjectData t, const Camera *frustum, uint32 sceneVisibilityFlags, MovableObjectArray &outCulledObjects, const Camera *lodCamera)
static void cullLights (const size_t numNodes, ObjectData t, LightListInfo &outGlobalLightList, const FrustumVec &frustums, const FrustumVec &cubemapFrustums)
SceneManager::cullLights &
static uint32 getDefaultQueryFlags ()
Get the default query flags for all future MovableObject instances.
static uint32 getDefaultVisibilityFlags ()
Get the default visibility flags for all future MovableObject instances.
static void setDefaultQueryFlags (uint32 flags)
Set the default query flags for all future MovableObject instances.
static void setDefaultVisibilityFlags (uint32 flags)
Set the default visibility flags for all future MovableObject instances.
static void updateAllBounds (const size_t numNodes, ObjectData t)
SceneManager::updateAllBounds
Public Attributes
size_t mGlobalIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
uint32 mHlmsGlobalIndex
Index in the vector holding this Rendrable reference in the HLMS datablock.
size_t mParentIndex
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
RenderableArray mRenderables
Static Public Attributes
static const FastArray< Real > c_DefaultLodMesh
Detailed Description
Instancing implementation using vertex texture through Vertex Texture Fetch (VTF) and hardware instancing.
See also
BaseInstanceBatchVTF and
InstanceBatchHW
The advantage over TextureVTF technique, is that this implements a basic culling algorithm to avoid useless processing in vertex shader and uses a lot less VRAM and memory bandwidth
Basically it has the benefits of both TextureVTF (skeleton animations) and HWInstancingBasic (lower memory consumption and basic culling) techniques
Remarks
Design discussion webpage: http://www.ogre3d.org/forums/viewtopic.php?f=4&t=59902
Author
Matias N. Goldberg ("dark_sylinc")
Version
1.2
Member Typedef Documentation
typedef FastArray<MovableObject*> Ogre::MovableObject::MovableObjectArray inherited
SceneManager::cullFrustum
Remarks
We don't pass by reference on purpose (avoid implicit aliasing) We perform frustum culling AND test visibility mask at the same time
Parameters
frustum Frustum to clip against
sceneVisibilityFlags Combined scene's visibility flags (i.e. viewport | scene). Set LAYER_SHADOW_CASTER bit if you want to exclude non-shadow casters.
outCulledObjects Out. List of objects that are (fully or partially) inside the frustum and should be rendered
lodCamera Camera in which lod levels calculations are based (i.e. during shadow pass renders) Note however, we only use this camera to calulate if should be visible according to mUpperDistance
Member Function Documentation
LightList* Ogre::MovableObject::_getLightList () inline inherited
Returns a pointer to the current list of lights for this object.
Remarks
You should not modify this list outside of MovableObject::Listener::objectQueryLights (say if you want to use it to implement this method, and use the pointer as a return value) and for reading it's only accurate as at the last frame.
SceneManager* Ogre::MovableObject::_getManager (void) const inline inherited
Get the manager of this object, if any (internal use only)
ObjectData& Ogre::MovableObject::_getObjectData () inline inherited
Returns a direct access to the ObjectData state.
const Matrix4& Ogre::MovableObject::_getParentNodeFullTransform (void) const inherited
Returns the full transformation of the parent sceneNode or the attachingPoint node.
virtual void Ogre::MovableObject::_notifyAttached (Node * parent) virtual inherited
Internal method called to notify the object that it has been attached to a node.
Reimplemented in Ogre::v1::Entity, Ogre::ParticleSystem, and Ogre::v1::InstancedEntity.
void Ogre::MovableObject::_notifyManager (SceneManager * man) inline inherited
Notify the object of it's manager (internal use only)
virtual void Ogre::MovableObject::_notifyParentNodeMemoryChanged (void) inline virtual inherited
Node::_callMemoryChangeListeners
Reimplemented in Ogre::Item, and Ogre::v1::InstancedEntity.
virtual void Ogre::MovableObject::_notifyStaticDirty (void) const inline virtual inherited
Called by SceneManager when it is telling we're a static MovableObject being dirty Don't call this directly.
See also
SceneManager::notifyStaticDirty
Reimplemented in Ogre::v1::InstancedEntity.
virtual void Ogre::Renderable::_setHlmsHashes (uint32 hash, uint32 casterHash) virtual inherited
Manually sets the hlms hashes. Don't call this directly.
Reimplemented in Ogre::SubItem.
virtual void Ogre::Renderable::_setNullDatablock (void) virtual inherited
Sets the datablock to a null pointer.
Use case: If you will be destroying an HlmsDatablock and all Renderables associated by it; it makes no sense to change the Renderable's datablock to a default one, only to be destroyed immediately after (you pay an unnecessary performance price).
Remarks
Do not attempt to render a Renderable whose datablock has been set to null. It will crash. You can call setDatablock afterwards though. Use at your own risk, hence the _underscore. See http://ogre3d.org/forums/viewtopic.php?f=25&t=91791&p=534476#p534476
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
virtual void Ogre::Renderable::_updateCustomGpuParameter (const GpuProgramParameters::AutoConstantEntry & constantEntry, GpuProgramParameters * params) const inline virtual inherited
Update a custom GpuProgramParameters constant which is derived from information only this Renderable knows.
Remarks
This method allows a Renderable to map in a custom GPU program parameter based on it's own data. This is represented by a GPU auto parameter of ACT_CUSTOM, and to allow there to be more than one of these per Renderable, the 'data' field on the auto parameter will identify which parameter is being updated. The implementation of this method must identify the parameter being updated, and call a 'setConstant' method on the passed in GpuProgramParameters object, using the details provided in the incoming auto constant setting to identify the index at which to set the parameter.
You do not need to override this method if you're using the standard sets of data associated with the Renderable as provided by setCustomParameter and getCustomParameter. By default, the implementation will map from the value indexed by the 'constantEntry.data' parameter to a value previously set by setCustomParameter. But custom Renderables are free to override this if they want, in any case.
Parameters
constantEntry The auto constant entry referring to the parameter being updated
params The parameters object which this method should call to set the updated parameters.
Reimplemented in Ogre::v1::SubEntity.
References Ogre::GpuProgramParameters::_writeRawConstant(), Ogre::GpuProgramParameters::AutoConstantEntry::data, Ogre::GpuProgramParameters::AutoConstantEntry::elementCount, and Ogre::GpuProgramParameters::AutoConstantEntry::physicalIndex.
void Ogre::MovableObject::addQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are appended to the existing flags on this object.
void Ogre::MovableObject::addVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are appended to the existing flags on this object.
static void Ogre::MovableObject::buildLightList (const size_t numNodes, ObjectData t, const LightListInfo & globalLightList) static inherited
SceneManager::buildLightList
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
Parameters
globalLightList List of lights already culled against all possible frustums and reorganized contiguously for SoA
static void Ogre::MovableObject::calculateCastersBox (const size_t numNodes, ObjectData t, uint32 sceneVisibilityFlags, AxisAlignedBox * outBox) static inherited
virtual AnimableValuePtr Ogre::AnimableObject::createAnimableValue (const String & valueName) inline virtual inherited
Create a reference-counted AnimableValuePtr for the named value.
Remarks
You can use the returned object to animate a value on this object, using AnimationTrack. Subclasses must override this if they wish to support animation of their values.
Reimplemented in Ogre::Light.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
static void Ogre::MovableObject::cullFrustum (const size_t numNodes, ObjectData t, const Camera * frustum, uint32 sceneVisibilityFlags, MovableObjectArray & outCulledObjects, const Camera * lodCamera) static inherited
static void Ogre::MovableObject::cullLights (const size_t numNodes, ObjectData t, LightListInfo & outGlobalLightList, const FrustumVec & frustums, const FrustumVec & cubemapFrustums) static inherited
SceneManager::cullLights &
See also
MovableObject::cullFrustum Produces the global list of visible lights that is needed in buildLightList
Remarks
We don't pass ObjectData by reference on purpose (avoid implicit aliasing) It's declared here because all affected elements are from MovableObject IMPORTANT: It is assumed that all objects in ObjectData are Lights.
Parameters
outGlobalLightList Output, a list of lights, contiguously placed
frustums An array of all frustums we need to check against
cubemapFrustums An array of all frustums that are used at least once as cubemaps (SceneManager::createCamera)
void Ogre::MovableObject::detachFromParent (void) inherited
Detaches an object from a parent SceneNode if attached.
const StringVector& Ogre::AnimableObject::getAnimableValueNames (void) const inline inherited
Gets a list of animable value names for this object.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
RealAsUint Ogre::MovableObject::getCachedDistanceToCamera (void) const inline inherited
Returns the distance to camera as calculated in .
Real Ogre::MovableObject::getCachedDistanceToCameraAsReal (void) const inline inherited
Returns the distance to camera as calculated in .
bool Ogre::MovableObject::getCastShadows (void) const inline inherited
Returns whether shadow casting is enabled for this object.
virtual bool Ogre::Renderable::getCastsShadows (void) const inline virtual inherited
Method which reports whether this renderable would normally cast a shadow.
Remarks
Subclasses should override this if they could have been used to generate a shadow.
Reimplemented in Ogre::ManualObject::ManualObjectSection, Ogre::v1::StaticGeometry::GeometryBucket, Ogre::v1::SubEntity, Ogre::SubItem, and Ogre::WireAabb.
uint8 Ogre::Renderable::getCurrentMaterialLod (void) const inline inherited
References ARRAY_PACKED_REALS, and Ogre::LodStrategy::lodSet().
unsigned char Ogre::MovableObject::getCurrentMeshLod (void) const inline inherited
const Vector4& Ogre::Renderable::getCustomParameter (size_t index) const inline inherited
Gets the custom value associated with this Renderable at the given index.
Parameters
index Index of the parameter to retrieve.
See also
setCustomParameter for full details.
References Ogre::Exception::ERR_ITEM_NOT_FOUND, and OGRE_EXCEPT.
HlmsDatablock* Ogre::Renderable::getDatablock (void) const inline inherited
static uint32 Ogre::MovableObject::getDefaultQueryFlags () inline static inherited
Get the default query flags for all future MovableObject instances.
static uint32 Ogre::MovableObject::getDefaultVisibilityFlags () inline static inherited
Get the default visibility flags for all future MovableObject instances.
uint32 Ogre::Renderable::getHlmsCasterHash (void) const inline inherited
uint32 Ogre::Renderable::getHlmsHash (void) const inline inherited
IdType Ogre::IdObject::getId () const inline inherited
Get the unique id of this object.
uint32 Ogre::MovableObject::getLightMask () const inline inherited
Get a bitwise mask which will filter the lights affecting this object.
Remarks
By default, this mask is fully set meaning all lights will affect this object
Listener* Ogre::MovableObject::getListener (void) const inline inherited
Gets the current listener for this object.
Aabb Ogre::MovableObject::getLocalAabb (void) const inherited
Retrieves the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
MaterialPtr Ogre::Renderable::getMaterial (void) const inherited
Retrieves the material this renderable object uses.
It may be null if it's using the HLMS. getDatablock
const String& Ogre::MovableObject::getName (void) const inline inherited
Returns the name of this object.
Node* Ogre::MovableObject::getParentNode (void) const inline inherited
Returns the node to which this object is attached.
SceneNode* Ogre::MovableObject::getParentSceneNode (void) const inline inherited
virtual bool Ogre::Renderable::getPolygonModeOverrideable (void) const inline virtual inherited
Gets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Reimplemented in Ogre::v1::BorderRenderable.
Referenced by Ogre::v1::BorderRenderable::getPolygonModeOverrideable().
uint32 Ogre::MovableObject::getQueryFlags (void) const inline inherited
Returns the query flags relevant for this object.
Real Ogre::MovableObject::getRenderingDistance (void) const inline inherited
Gets the distance at which batches are no longer rendered.
Real Ogre::MovableObject::getRenderingMinPixelSize () const inline inherited
Returns the minimum pixel size an object needs to be in both screen axes in order to be rendered.
uint8 Ogre::MovableObject::getRenderQueueGroup (void) const inline inherited
Gets the queue group for this entity, see setRenderQueueGroup for full details.
uint8 Ogre::Renderable::getRenderQueueSubGroup (void) const inline inherited
References Ogre::NumVertexPass.
SkeletonInstance* Ogre::MovableObject::getSkeletonInstance (void) const inline inherited
bool Ogre::Renderable::getUseIdentityProjection (void) const inline inherited
Returns whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityProjection
bool Ogre::Renderable::getUseIdentityView (void) const inline inherited
Returns whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this.
See also
Renderable::setUseIdentityView
virtual bool Ogre::Renderable::getUseIdentityViewProjMatrixIsDynamic (void) const inline virtual inherited
Returns whether the Hlms implementation should evaluate getUseIdentityProjection per object at runtime, or if it can assume the Renderable will remain with the same setting until the datablock is flushed (performance optimization)
Remarks
Hlms implementations may ignore this setting (e.g. assume always true or always false) or even not support identity matrix overrides at all. For example currently Unlit supports them all, but will assume this returns always true if getUseIdentityWorldMatrix returns false.
virtual bool Ogre::Renderable::getUseIdentityWorldMatrix (void) const inline virtual inherited
Returns whether the world matrix is an identify matrix.
Remarks
It is up to the Hlms implementation whether to honour this request. Take in mind changes of this value at runtime may not be seen until the datablock is flushed. It is implemented as a virtual call because this functionality isn't required very often (hence we save per-Renderable space for those that don't use it) and this function will be called at creation time to use a different shader; not during rendering time per Renderable.
Reimplemented in Ogre::v1::BillboardSet.
virtual OGRE_DEPRECATED const Any& Ogre::Renderable::getUserAny (void) const inline virtual inherited
Deprecated:
use UserObjectBindings::getUserAny via getUserObjectBindings() instead.
Retrieves the custom user value associated with this object.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::MovableObject::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
UserObjectBindings& Ogre::Renderable::getUserObjectBindings () inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const UserObjectBindings& Ogre::Renderable::getUserObjectBindings () const inline inherited
Return an instance of user objects binding associated with this class.
You can use it to associate one or more custom objects with this class instance.
See also
UserObjectBindings::setUserAny.
const VertexArrayObjectArray& Ogre::Renderable::getVaos (VertexPass vertexPass) const inline inherited
uint32 Ogre::MovableObject::getVisibilityFlags (void) const inline inherited
Returns the visibility flags relevant for this object.
Reserved visibility flags are not returned.
bool Ogre::MovableObject::getVisible (void) const inline inherited
Gets this object whether to be visible or not, if it has a renderable component.
Remarks
Returns the value set by MovableObject::setVisible only.
Aabb Ogre::MovableObject::getWorldAabb () const inherited
Gets the axis aligned box in world space.
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. getWorldAabbUpdated if you need the update process to be guaranteed
Aabb Ogre::MovableObject::getWorldAabbUpdated () inherited
Gets the axis aligned box in world space.
Remarks
Unlike getWorldAabb, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
float Ogre::MovableObject::getWorldRadius () const inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Assumes the caches are already updated. Will trigger an assert otherwise. getWorldRadiusUpdated if you need the update process to be guaranteed
float Ogre::MovableObject::getWorldRadiusUpdated () inherited
Gets the bounding Radius scaled by max(scale.x, scale.y, scale.z).
Remarks
Unlike getWorldRadius, this function guarantees the cache stays up to date. It is STRONGLY advised against calling this function for a large number of MovableObject. Refactor your queries so that they happen after SceneManager::updateAllBounds() has been called
bool Ogre::Renderable::hasCustomParameter (size_t index) const inline inherited
Checks whether a custom value is associated with this Renderable at the given index.
Parameters
index Index of the parameter to check for existence.
See also
setCustomParameter for full details.
bool Ogre::Renderable::hasSkeletonAnimation (void) const inline inherited
virtual void Ogre::MovableObject::instanceBatchCullFrustumThreaded (const Frustum * frustum, const Camera * lodCamera, uint32 combinedVisibilityFlags) inline virtual inherited
InstancingTheadedCullingMethod,
See also
InstanceBatch::instanceBatchCullFrustumThreaded
References ARRAY_PACKED_REALS, Ogre::LodStrategy::lodSet(), and Ogre::LodStrategy::lodUpdateImpl().
bool Ogre::MovableObject::isAttached (void) const inline inherited
Returns true if this object is attached to a Node.
bool Ogre::MovableObject::isStatic () const inherited
Checks whether this MovableObject is static. setStatic.
bool Ogre::MovableObject::isVisible (void) const inherited
Returns whether or not this object is supposed to be visible or not.
Remarks
Takes into account visibility flags and the setVisible, but not rendering distance.
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, void *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr) inline inherited
template<class Alloc > void Ogre::AllocatedObject< Alloc >::operator delete[] (void * ptr, const char * , int , const char *) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, const char * file, int line, const char * func) inline inherited
operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz) inline inherited
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new (size_t sz, void * ptr) inline inherited
placement operator new
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz, const char * file, int line, const char * func) inline inherited
array operator new, with debug line info
template<class Alloc > void* Ogre::AllocatedObject< Alloc >::operator new[] (size_t sz) inline inherited
bool Ogre::IdObject::operator() (const IdObject * left, const IdObject * right) inline inherited
bool Ogre::IdObject::operator() (const IdObject & left, const IdObject & right) inline inherited
virtual void Ogre::Renderable::postRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called immediately after the Renderable has been rendered.
virtual bool Ogre::Renderable::preRender (SceneManager * sm, RenderSystem * rsys) inline virtual inherited
Called just prior to the Renderable being rendered.
Remarks
OGRE is a queued renderer, so the actual render commands are executed at a later time than the point at which an object is discovered to be visible. This allows ordering & grouping of renders without the discovery process having to be aware of it. It also means OGRE uses declarative render information rather than immediate mode rendering - this is very useful in that certain effects and processes can automatically be applied to a wide range of scenes, but the downside is that special cases are more difficult to handle, because there is not the declared state to cope with it.
This method allows a Renderable to do something special at the actual point of rendering if it wishes to. When this method is called, all the material render state as declared by this Renderable has already been set, all that is left to do is to bind the buffers and perform the render. The Renderable may modify render state itself if it wants to (and restore it in the postRender call) before the automated render happens, or by returning 'false' from this method can actually suppress the automatic render and perform one of its own.
Returns
true if the automatic render should proceed, false to skip it on the assumption that the Renderable has done it manually.
Reimplemented in Ogre::v1::BillboardChain.
const LightList& Ogre::MovableObject::queryLights (void) const inline inherited
Gets a list of lights, ordered relative to how close they are to this movable object.
Remarks
The lights are filled in
See also
buildLightList
Returns
The list of lights use to lighting this object.
void Ogre::Renderable::removeCustomParameter (size_t index) inline inherited
Removes a custom value which is associated with this Renderable at the given index.
Parameters
index Index of the parameter to remove.
See also
setCustomParameter for full details.
void Ogre::MovableObject::removeQueryFlags (uint32 flags) inline inherited
As setQueryFlags, except the flags passed as parameters are removed from the existing flags on this object.
void Ogre::MovableObject::removeVisibilityFlags (uint32 flags) inline inherited
As setVisibilityFlags, except the flags passed as parameters are removed from the existing flags on this object.
void Ogre::MovableObject::setCastShadows (bool enabled) inline inherited
Sets whether or not this object will cast shadows.
Remarks
This setting simply allows you to turn on/off shadows for a given object. An object will not cast shadows unless the scene supports it in any case (see SceneManager::setShadowTechnique), and also the material which is in use must also have shadow casting enabled. By default all entities cast shadows. If, however, for some reason you wish to disable this for a single object then you can do so using this method.
Note
This method normally refers to objects which block the light, but since Light is also a subclass of MovableObject, in that context it means whether the light causes shadows itself.
void Ogre::Renderable::setCustomParameter (size_t index, const Vector4 & value) inline inherited
Sets a custom parameter for this Renderable, which may be used to drive calculations for this specific Renderable, like GPU program parameters.
Remarks
Calling this method simply associates a numeric index with a 4-dimensional value for this specific Renderable. This is most useful if the material which this Renderable uses a vertex or fragment program, and has an ACT_CUSTOM parameter entry. This parameter entry can refer to the index you specify as part of this call, thereby mapping a custom parameter for this renderable to a program parameter.
Parameters
index The index with which to associate the value. Note that this does not have to start at 0, and can include gaps. It also has no direct correlation with a GPU program parameter index - the mapping between the two is performed by the ACT_CUSTOM entry, if that is used.
value The value to associate.
void Ogre::Renderable::setDatablock (IdString datablockName) inherited
Assigns a datablock (i.e.
HLMS material) based on its unique name.
Remarks
An null IdString() is valid, it will use the default material
virtual void Ogre::Renderable::setDatablock (HlmsDatablock * datablock) virtual inherited
Assigns a datablock (i.e. HLMS Material) to this renderable.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setDatablockOrMaterialName (String materialName, String groupName) inherited
First tries to see if an HLMS datablock exist with the given name, if not, tries to search among low level materials.
static void Ogre::MovableObject::setDefaultQueryFlags (uint32 flags) inline static inherited
Set the default query flags for all future MovableObject instances.
static void Ogre::MovableObject::setDefaultVisibilityFlags (uint32 flags) inline static inherited
Set the default visibility flags for all future MovableObject instances.
void Ogre::MovableObject::setLightMask (uint32 lightMask) inline inherited
Set a bitwise mask which will filter the lights affecting this object.
Remarks
This mask will be compared against the mask held against Light to determine if a light should affect a given object. By default, this mask is fully set meaning all lights will affect this object
void Ogre::MovableObject::setListener (Listener * listener) inline inherited
Sets a listener for this object.
Remarks
Note for size and performance reasons only one listener per object is allowed.
void Ogre::MovableObject::setLocalAabb (const Aabb box) inherited
Sets the local axis-aligned bounding box for this object.
Remarks
This bounding box is in local coordinates.
virtual void Ogre::Renderable::setMaterial (const MaterialPtr & material) virtual inherited
Sets the given material. Overrides HLMS materials.
Reimplemented in Ogre::v1::BillboardSet, and Ogre::v1::SubEntity.
void Ogre::Renderable::setMaterialName (const String & name, const String & groupName) inherited
Sets the name of the Material to be used. Prefer using HLMS setHlms.
void Ogre::MovableObject::setName (const String & name) inline inherited
Sets a custom name for this node.
Doesn't have to be unique
virtual void Ogre::Renderable::setPolygonModeOverrideable (bool override) inline virtual inherited
Sets whether this renderable's chosen detail level can be overridden (downgraded) by the camera setting.
Parameters
override true means that a lower camera detail will override this renderables detail level, false means it won't.
void Ogre::MovableObject::setQueryFlags (uint32 flags) inline inherited
Sets the query flags for this object.
Remarks
When performing a scene query, this object will be included or excluded according to flags on the object and flags on the query. This is a bitwise value, so only when a bit on these flags is set, will it be included in a query asking for that flag. The meaning of the bits is application-specific.
void Ogre::MovableObject::setRenderingDistance (Real dist) inline inherited
Sets the distance at which the object is no longer rendered.
Parameters
dist Distance beyond which the object will not be rendered (the default is FLT_MAX, which means objects are always rendered). Values equal or below zero will be ignored, and cause an assertion in debug mode.
void Ogre::MovableObject::setRenderingMinPixelSize (Real pixelSize) inline inherited
Sets the minimum pixel size an object needs to be in both screen axes in order to be rendered.
Note
Camera::setUseMinPixelSize() needs to be called for this parameter to be used.
Parameters
pixelSize Number of minimum pixels (the default is 0, which means objects are always rendered).
virtual void Ogre::MovableObject::setRenderQueueGroup (uint8 queueID) virtual inherited
Sets the render queue group this entity will be rendered through.
Remarks
Render queues are grouped to allow you to more tightly control the ordering of rendered objects. If you do not call this method, all Entity objects default to the default queue (RenderQueue::getDefaultQueueGroup), which is fine for most objects. You may want to alter this if you want this entity to always appear in front of other objects, e.g. for a 3D menu system or such.
See RenderQueue for more details.
Parameters
queueID Enumerated value of the queue group to use. See the enum RenderQueueGroupID for what kind of values can be used here.
Valid render queue ids are between 0 & 254 inclusive
Reimplemented in Ogre::ParticleSystem, Ogre::v1::Entity, and Ogre::Light.
void Ogre::Renderable::setRenderQueueSubGroup (uint8 subGroup) inline inherited
Sets the render queue sub group.
Remarks
Within the same RenderQueue ID, you may want to have the renderables to have a specific order (i.e. have a mesh, but the hair submesh with alpha blending needs to be rendered last).
RenderQueue Subgroups are useful for manually sorting objects, just like RenderQueue IDs. However, RenderQueue IDs can also be useful for skipping large number of objects through clever compositing and thus a performance optimization. Subgroups cannot be used for such optimizations.
Parameters
subGroup The sub group. This value can't exceed OGRE_MAKE_MASK(SubRqIdBits) RenderQueue
void Ogre::Renderable::setUseIdentityProjection (bool useIdentityProjection) inline inherited
Sets whether or not to use an 'identity' projection.
Remarks
Usually Renderable objects will use a projection matrix as determined by the active camera. However, if they want they can cancel this out and use an identity projection, which effectively projects in 2D using a {-1, 1} view space. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityProjection
void Ogre::Renderable::setUseIdentityView (bool useIdentityView) inline inherited
Sets whether or not to use an 'identity' view.
Remarks
Usually Renderable objects will use a view matrix as determined by the active camera. However, if they want they can cancel this out and use an identity matrix, which means all geometry is assumed to be relative to camera space already. Useful for overlay rendering. Normal renderables need not change this. The default is false.
See also
Renderable::getUseIdentityView
virtual OGRE_DEPRECATED void Ogre::Renderable::setUserAny (const Any & anything) inline virtual inherited
Deprecated:
use UserObjectBindings::setUserAny via getUserObjectBindings() instead.
Sets any kind of user value on this object.
Remarks
This method allows you to associate any user value you like with this Renderable. This can be a pointer back to one of your own classes for instance.
Referenced by Ogre::v1::InstanceBatch::getRenderOperation().
void Ogre::MovableObject::setVisibilityFlags (uint32 flags) inline inherited
Sets the visibility flags for this object.
Remarks
As well as a simple true/false value for visibility (as seen in setVisible), you can also set visibility flags that is applied a binary 'and' with the SceneManager's mask and a compositor node pass. To exclude particular objects from rendering. Changes to reserved visibility flags are ignored (won't take effect).
void Ogre::MovableObject::setVisible (bool visible) inline inherited
Tells this object whether to be visible or not, if it has a renderable component.
Note
An alternative approach of making an object invisible is to detach it from it's SceneNode, or to remove the SceneNode entirely. Detaching a node means that structurally the scene graph changes. Once this change has taken place, the objects / nodes that have been removed have less overhead to the visibility detection pass than simply making the object invisible, so if you do this and leave the objects out of the tree for a long time, it's faster. However, the act of detaching / reattaching nodes is in itself more expensive than setting an object visibility flag, since in the latter case structural changes are not made. Therefore, small or frequent visibility changes are best done using this method; large or more longer term changes are best done by detaching.
static void Ogre::MovableObject::updateAllBounds (const size_t numNodes, ObjectData t) static inherited
SceneManager::updateAllBounds
Remarks
We don't pass by reference on purpose (avoid implicit aliasing)
Member Data Documentation
const FastArray<Real> Ogre::MovableObject::c_DefaultLodMesh static inherited
size_t Ogre::MovableObject::mGlobalIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
uint32 Ogre::Renderable::mHlmsGlobalIndex inherited
Index in the vector holding this Rendrable reference in the HLMS datablock.
Used for O(1) removals.
Remarks
Despite being public, Do NOT modify it manually.
size_t Ogre::MovableObject::mParentIndex inherited
Index in the vector holding this MO reference (could be our parent node, or a global array tracking all movable objecst to avoid memory leaks).
Used for O(1) removals.
Remarks
It is the parent (or our creator) the one that sets this value, not ourselves. Do NOT modify it manually.
RenderableArray Ogre::MovableObject::mRenderables inherited
The documentation for this class was generated from the following file:
OgreInstanceBatchHW_VTF.h