OGRE: Ogre::ArrayRay Class Reference
Ogre::ArrayRay Class Reference
#include <OgreArrayRay.h>
Public Member Functions
ArrayRay ()
ArrayRay (const ArrayVector3 &origin, const ArrayVector3 &direction)
ArrayMaskR intersects (const ArrayAabb &aabb) const
SLAB method See https://tavianator.com/fast-branchless-raybounding-box-intersections-part-2-nans/.
Public Attributes
ArrayVector3 mDirection
ArrayVector3 mOrigin
Constructor & Destructor Documentation
ArrayRay() [1/2]
Ogre::ArrayRay::ArrayRay () inline
ArrayRay() [2/2]
Ogre::ArrayRay::ArrayRay (const ArrayVector3 & origin, const ArrayVector3 & direction) inline
Member Function Documentation
intersects()
ArrayMaskR Ogre::ArrayRay::intersects (const ArrayAabb & aabb) const inline
SLAB method See https://tavianator.com/fast-branchless-raybounding-box-intersections-part-2-nans/.
References ARRAY_REAL_ZERO, Ogre::MathlibC::CompareGreaterEqual(), Ogre::ArrayAabb::getMaximum(), Ogre::ArrayAabb::getMinimum(), Ogre::ArrayVector3::makeCeil(), Ogre::ArrayVector3::makeFloor(), Ogre::MathlibC::Max(), Ogre::ArrayVector3::mChunkBase, mDirection, Ogre::MathlibC::Min(), mOrigin, and Ogre::MathlibC::SetAll().
Member Data Documentation
mDirection
ArrayVector3 Ogre::ArrayRay::mDirection
Referenced by intersects().
mOrigin
ArrayVector3 Ogre::ArrayRay::mOrigin
Referenced by intersects().
The documentation for this class was generated from the following file:
OgreArrayRay.h