set(CPACK_PACKAGE_VERSION ${OGRE_VERSION})
set(CPACK_PACKAGE_VERSION_MAJOR ${OGRE_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${OGRE_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${OGRE_VERSION_PATCH})

set(CPACK_INSTALL_CMAKE_PROJECTS "${OGRE3D_BINARY_DIR}" "OGRE" "ALL" "/")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Open Source 3D Graphics Engine")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "OGRE")
set(CPACK_PACKAGE_NAME "OGRE")
set(CPACK_PACKAGE_VENDOR "Torus Knot Software")

set(CPACK_RESOURCE_FILE_LICENSE "${OGRE3D_SOURCE_DIR}/COPYING")
set(CPACK_PACKAGE_ICON "${OGRE3D_SOURCE_DIR}\\\\ogrelogo.gif")

include(CPack)
