set(OGRE_VERSION_MAJOR "1")
set(OGRE_VERSION_MINOR "7")
set(OGRE_VERSION_PATCH "0")
set(OGRE_VERSION "${OGRE_VERSION_MAJOR}.${OGRE_VERSION_MINOR}.${OGRE_VERSION_PATCH}")
set(OGRE_VERSION_SUFFIX "")
set(OGRE_VERSION_NAME "Cthugha")


# Set up pkgconfig description
set(prefix ${CMAKE_INSTALL_PREFIX})
set(libdir ${CMAKE_INSTALL_PREFIX}/lib)
set(includedir ${CMAKE_INSTALL_PREFIX}/include)
set(PACKAGE "OGRE")
set(VERSION ${OGRE_VERSION})
set(OGRE_CFLAGS ) #TODO
set(OGRE_THREAD_LIBS ) #TODO
set(exec_prefix ${CMAKE_INSTALL_PREFIX})
configure_file(${OGRE_SOURCE_DIR}/OGRE.pc.in ${CMAKE_CURRENT_BINARY_DIR}/OGRE.pc @ONLY)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/OGRE.pc DESTINATION lib/pkgconfig)

